### PR TITLE
feat: add tooltip with full path when cli tool is detected

### LINKED ISSUE #5215: CLI Tools should show installation path
### Is your enhancement related to a problem? Please describe

When I see an installed CLI, I often want to know where it is installed. Or if I'm having trouble getting it working in a terminal I want to see where it is to check the path or confirm I'm running the same copy/version.

### Describe the solution you'd like

Either the path directly in the UI, or an obvious tooltip with the path.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

PR adds tooltip with full path when mouse hoover over cli tool name

### Screenshot / video of UI

image

image

### What issues does this PR fix or reference?

Fix #5215

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by jeffmaury — DISMISSED** [review]
UI is crappy:

image

**Comment by deboer-tim** [comment]
Nit: remove the word 'full', it's extraneous and implies we might only have partial path in other cases. Or could replace with something like 'Installation path:' or 'Install location:'.

**Review by lstocchi — APPROVED** [review]
LGTM, maybe we should have a way to copy the path? 🤔

**Comment by dgolovin** [comment]
> LGTM, maybe we should have a way to copy the path? 🤔

That could be useful, but it should be different issue.

**Pull request merged**
