### PR TITLE
fix: Done button in DeployPodToKube

### PR DESCRIPTION
**Pull request by SoniaSandler**
Signed-off-by: Sonia Sandler <ssandler@redhat.com>

### What does this PR do?
Fixes the Done button in the DeployPodToKube page so that it would go back to the previous page

### What issues does this PR fix or reference?

https://github.com/containers/podman-desktop/issues/9295

### How to test this PR?
Go to the DeployPodToKube page, finish the pod deployment process, click the Done button, and check that it goes back to the previous page

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
if you can add a unit test

**Review by deboer-tim — APPROVED** [review]
LGTM, same fix I was about to do. Was tempted to say it should always go to Pods page, but that's a separate issue.

Tested launching from Pods page or Pod Details, worked from both. We should really have a unit test here too, but since a unit test wouldn't have avoided this regression I'm approving anyway.

**Comment by deboer-tim** [comment]
Got to this and #9307 out of order, agree with Florent to merge the other and take more time to write unit test for this (even if unit test might not have caught this, there is value).

**Comment by SoniaSandler** [comment]
@benoitf @deboer-tim added tests

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
thanks

**Pull request merged**
