### PR TITLE
fix: edit Podman machine support for MacOS only

### LINKED ISSUE #5233: Editing podman machine on Windows ended up with an Error (exit code 125)
### Bug description

I have a running podman machine (rootfull) which is working fine. I am trying to edit the Podman Machine via edit option. I got an error.

podman_machine_edit_error125

Log: 
[podman_machine_edit_error.log](https://github.com/containers/podman-desktop/files/13649677/podman_machine_edit_error.log)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.6.0

### Steps to reproduce

1. Create a podman machine
2. Start it up
3. Pull an image
4. Go to Resources and try to edit a machine (I tried to change the CPU)
5. Assert: Machine is restarted and value adjusted.
Actual: An error

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #5233

### What does this PR do?

prevent Podman machine to be editable on Windows

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Fixes #5233

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
I checked on macOS and it works

but it's requiring a test to ensure edit is added only for macOS

**Comment by odockal** [comment]
Looking...

**Comment by odockal** [comment]
On windows Edit option is not visible anymore. LGTM.

**Review by odockal — APPROVED** [review]

**Review by benoitf — APPROVED** [review]
thx

**Pull request merged**
