### PR TITLE
refactor: updated compose onboarding installation

### LINKED ISSUE #4475: Disable Compose onboarding for now on Linux
### Bug description

https://github.com/containers/podman-desktop/issues/4456 is currently blocking system-wide installation on Linux machines. 

we should disable onboarding temporarily
### Operating system

mac m1

### Installation Method

None

### Version

1.4.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### LINKED ISSUE #4476: Compose onboarding: Remove system-install toggle, make it mandatory when pressing Next
### Is your enhancement related to a problem? Please describe

When doing the onboarding process, we should always install Compose system-wide so that `podman compose` is immediately useful.

### Describe the solution you'd like

Remove the toggle and replace the step saying:

- Compose successfully installed
- Explaining why Compose needs to be installed system-wide
- Last note being highlighted saying "Pressing Next will install Compose system-wide and may ask for administrative privileges".

And pressing Next will show administrative prompt / install system wide.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
refactor: updated compose onboarding installation

### What does this PR do?

* Installation is now Download which is more correct and files updated
  (installation.ts now download.ts)
* Onboarding compose process is more flowing and streamlined, the
  system-wide install is now it's own step as it's required for
  onboarding
* Updated documentation on how to use compose within the onboarding
  process

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/6422176/e85fc64f-d133-4d32-b9cb-caf66398212f

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/4475
Closes https://github.com/containers/podman-desktop/issues/4476

### How to test this PR?

Go through the onboarding process on a non-linux machine. If you are on
a linux machine, you should NOT see the setup button anymore.

### CODE REVIEW

**Comment by benoitf** [comment]
I confirm that using next/next/next buttons I was able to use `podman compose` right away after that which is a really nice onboarding

I also tried with just the binary being downloaded, aborting the install and resuming later (and also restart Podman Desktop)

I'm just wondering if we should not kill the compose status bar icon ?


I see a message "compose successfully downloaded" but in the status bar it's telling me that it's not downloaded ?

image

**Review by benoitf — APPROVED** [review]

**Review by lstocchi — COMMENTED** [review]
Works fine on Windows but on linux i'm able to start the workflow and face https://github.com/containers/podman-desktop/issues/4456

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by cdrage** [comment]
> Works fine on Windows but on linux i'm able to start the workflow and face #4456

When rebasing it was removed, I've added back isLinux().

For removing Compose from the status, I've opened up: https://github.com/containers/podman-desktop/pull/4492

**Comment by cdrage** [comment]
EDIT: DO NOT MERGE YET so it does not make it in the 1.5.0 release.

**Comment by cdrage** [comment]
Will have to have a brief discussion with regards to this PR before merging since there are now fixes for linux #4502 and #4501 if we still want it disabled.

We may even need to disable Windows until the upstream issue is fixed with `podman compose`.

**Comment by cdrage** [comment]
Updated the PR to not disable Linux onboarding.

**Pull request merged**
