### PR TITLE
chore: create Container Connection actions component

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR just extract the code related to the container connection actions (start/stop/delete/restart) so it can be reused in the details page without duplicate code

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Needed for the refactoring #1337 

### How to test this PR?

1. check if the buttons work as before

### CODE REVIEW

**Comment by slemeur** [comment]
this is looking great :)

**Review by benoitf — APPROVED** [review]

**Comment by lstocchi** [comment]
> this is looking great :)

the image is the mockup made by Mo 😆

**Review by benoitf — COMMENTED** [review]
I think the screenshot is misleading because there is no such details page for now

**Comment by lstocchi** [comment]
> I think the screenshot is misleading because there is no such details page for now

it was to show where i would use the component. Removed just to avoid confusion.

**Comment by benoitf** [comment]
Allow to reuse the purple boxes somewhere else

image

**Pull request merged**
