### PR TITLE
feat(extension-api): Implements showInputBox & showQuickPick

### LINKED ISSUE #1300: Implements showInputBox for extensions
### Is your enhancement related to a problem? Please describe

Subtask of https://github.com/containers/podman-desktop/issues/184 where we need to ask some input to users

### Describe the solution you'd like

adds + implements `window.showInputBox` API

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #1301: Implements showQuickPick for extensions
### Is your enhancement related to a problem? Please describe

Subtask of https://github.com/containers/podman-desktop/issues/184 where we need to ask some input to users

### Describe the solution you'd like

adds + implements `window.showQuickPick` API

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Adds new methods `showInputBox` and `showQuickPick`

it allows to interact with the user through extensions 

### Screenshot/screencast of this PR

https://user-images.githubusercontent.com/436777/216383150-9920577b-038d-4b0c-81c5-a9f2b4e8298b.mp4

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/1300
fixes https://github.com/containers/podman-desktop/issues/1301

### How to test this PR?

Go to the extensions panel in settings and use as OCI image `quay.io/fbenoit/podman-desktop-quickpick`

you should see items in the status bar, click on it

Change-Id: I769c2491bcd00acc468300a549957b2fd96457c4
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by cdrage** [comment]
@benoitf Can you `podman push quay.io/fbenoit/podman-desktop-quickpick` ? I'm unable to pull:

```sh
▶ podman pull quay.io/fbenoit/podman-desktop-quickpick
Trying to pull quay.io/fbenoit/podman-desktop-quickpick:latest...
Error: initializing source docker://quay.io/fbenoit/podman-desktop-quickpick:latest: reading manifest latest in quay.io/fbenoit/podman-desktop-quickpick: unauthorized: access to the requested resource is not authorized
```

**Comment by benoitf** [comment]
ah probably it's a private image

**Comment by benoitf** [comment]
> @benoitf Can you podman push quay.io/fbenoit/podman-desktop-quickpick ? I'm unable to pull:

should be fixed

**Comment by lstocchi** [comment]
> quay.io/fbenoit/podman-desktop-quickpick

Tried but it's the wrong image. I only see a hello world alert 
wrong_image

**Comment by benoitf** [comment]
@lstocchi should be fixed (thx for reporting the issue)

**Review by lstocchi — COMMENTED** [review]
Only one doubt. When i add an invalid value should it invalid by default to proceed? 
If i insert 123 and click enter, it shows the alert
error_ok_inputbox

**Review by lstocchi — COMMENTED** [review]
On Windows the line selected remains the first. It only works if i go down/up using the keyboard. It would be cool if it worked with the mouse as well
color-selection

**Comment by benoitf** [comment]
@lstocchi for your doubt probably need to check what Vs Code does

**Comment by cdrage** [comment]
> @lstocchi for your doubt probably need to check what Vs Code does

can confirm that it only changes based on up / down keyboard not mouse on VSCode

**Comment by cdrage** [comment]
@benoitf Can you push the arm64 image or provide the code used for your Docker Image?

Unrelated, but looks like I've encountered a user experience issue we should fix:

```sh
▶ podman pull quay.io/fbenoit/podman-desktop-quickpick
Trying to pull quay.io/fbenoit/podman-desktop-quickpick:latest...
Getting image source signatures
Copying blob sha256:e530172ce56f66fe1ce256c82a35089ebd560f7d195275c69ff38c1715623ea1
Copying blob sha256:03288c496ea166f1695219fa402270fa7179992c5a0b03d474adcc092c10de41
Copying blob sha256:48fb7f411f61c9351180fccdbd91b05315a933296aefdf9dd59d8ea11159929d
Copying config sha256:f0bb259bd16080dac3abb5df64b0ed83d58ced7f0e30a729a5b95322f8849ea2
Writing manifest to image destination
Storing signatures
WARNING: image platform ({amd64 linux  [] }) does not match the expected platform ({arm64 linux  [] })
f0bb259bd16080dac3abb5df64b0ed83d58ced7f0e30a729a5b95322f8849ea2
```

We should have better error reporting in terms of alerting the user it's unable to find a container for ARM / different architecture.

Filed issue: https://github.com/containers/podman-desktop/issues/1407

Other than that, out of all 900+ lines, I don't see any major issues (amazing job). Just need to test out more of the functionality then LGTM.

**Comment by benoitf** [comment]
It's a 'scratch' image so you could copy layers to a 'arm' image. I can do that next week

**Comment by benoitf** [comment]
@cdrage the multi-arch image has been pushed

**Comment by benoitf** [comment]
@lstocchi so I checked on VS Code, we shouldn't be able to validate :-)

**Review by cdrage — APPROVED** [review]
Tested intensely on mac M1 and found no issues, nor with the code too. Was able to enter into the input correctly and test the image.

Everything LGTM!

**Comment by lstocchi** [comment]
Unfortunately i cannot test it again as i get "Error: (HTTP code 500) server error - container create: no command or entrypoint provided, and no CMD or ENTRYPOINT from image" when pulling the image.
I wanted to verify one thing because it's something i don't remember. In Vscode there is the filtering active in the quickpick. Is it the same here? It can be quite handy at times.

Then there is also a different row background that makes it clear where the mouse is hovering. 
I was referring to something else here https://github.com/containers/podman-desktop/pull/1366#pullrequestreview-1286840813 but it would be nice to have it imo 
qucikpick_vscode

**Comment by benoitf** [comment]
@lstocchi thanks for your valuable feedback, I'll do the enhancements

**Comment by benoitf** [comment]
@lstocchi I think I addressed all your comments
- invalid input in inputbox : you can't use enter key
- if you click on an item it deselects the row
- there is a hover when highlighting items in quickPick with many option

**Review by lstocchi — APPROVED** [review]
Works perfectly!! Great job 👍 🚀

**Pull request merged**
