### PR TITLE
feat: show warnings on pod creation and two containers use the same port (#2240)

### LINKED ISSUE #2240: Containers created inside pod are exposing ports from all containers
### Bug description

I create 2 containers (docker.io/kennethreitz/httpbin) mapping ports 9000 and 9001 to 80 respectively

Then I created a pod from those 2 pods, the pod gets created but each of the created container is having both ports 9000 and 9001 mapped to 80 

As a consequence one of them can't start

### Operating system

Win11 Pro

### Version

0.14.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR proposes a way to guide users in case they try to create a pod with multiple containers and two or more of them use the same port

### Screenshot/screencast of this PR

same-port-containers

### What issues does this PR fix or reference?

it resolves #2240 

### How to test this PR?

1. select two containers using the same port
2. create a pod from them
3. in the create pod page you should see the warning

### CODE REVIEW

**Comment by deboer-tim** [comment]
+1 on the function. I don't love banner warning UI and it doesn't match anything else (because we don't have a similar issue anywhere else yet), but we could always get design input and change it later.

**Comment by mairin** [comment]
I see where you got the design idea for the Possible Runtime Error alert message... it looks like the Patternfly alert, but it's too bright I think for our theme. I created one of these for the OpenShift Local mockup, looks like this:

Screenshot from 2023-05-30 14-46-15

I think a similar look could work a little better here. (I will mock smtg up, will post later today)

**Comment by mairin** [comment]
Screenshot from 2023-05-30 16-33-00

What do you think about this? Here's the details:

- fill: charcoal-600
- yellow highlight color + header text color: amber-400
- yellow icon color: amber-500
- icon: font awesome triangle-exclamation
- font size: 14pt

**Comment by lstocchi** [comment]
> I see where you got the design idea for the Possible Runtime Error alert message... it looks like the Patternfly alert

I copied the alert notification from the tailwindcss page https://v1.tailwindcss.com/components/alerts#left-accent-border

> What do you think about this? Here's the details:

Much much better, thanks!! I'll update the PR to this 🙏

**Comment by jeffmaury** [comment]
If there are several ports in conflicts, the message is:

image

Can we switch to:

Containers a and b use the same ports c and d ?

**Comment by lstocchi** [comment]
> Containers a and b use the same ports c and d ?

Done. You can see the result in the gif https://user-images.githubusercontent.com/49404737/242282201-241ee8e5-129f-413d-9009-9e1dcfcf78a8.gif

**Comment by mairin** [comment]
That looks fantastic @lstocchi!!!

**Comment by jeffmaury** [comment]
I had 2 containers:

- one was using ports 8080 and 5000
- second one using 8080 and 8443

First was stopped and second running.

Here's what I got:

image

**Comment by lstocchi** [comment]
> image

Ops my bad, i only focussed to see the results with multiple ports and i didn't check in other cases. Added another test for that. Please try again.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by cdrage — APPROVED** [review]
Thanks @lstocchi was able to test this out and it warned correctly when using the same port against a wordpress + another wordpress container + mysql setup.

Code looks good too.

LGTM!

**Pull request merged**
