### PR TITLE
chore: change font of website

### PR DESCRIPTION
**Pull request by cdrage**
chore: change font of website

### What does this PR do?

Changes the font of the website to Manrope

### What issues does this PR fix or reference?

Part of https://github.com/containers/podman-desktop-internal/issues/376

### How to test this PR?

Preview the website

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
tried on https://673e13358a34460bcc36825f--podman-desktop-pr.netlify.app/

**Comment by benoitf** [comment]
I've also approved the argos changes

**Review by Firewall — APPROVED** [review]
Small change but looks amazing!

**Comment by slemeur** [comment]
This is looking promsing.

The alignements are looking off in the main title bar:
Screenshot 2024-11-21 at 13 57 14

Also "podman" should have a bigger weight than "desktop"; The header line should be bolder.

The shadows for the images are showing some glitches:
Screenshot 2024-11-21 at 13 59 59

A couple of adjustments are needed to align this with the mockup.

**Comment by cdrage** [comment]
> This is looking promsing.
> 
> The alignements are looking off in the main title bar: Screenshot 2024-11-21 at 13 57 14
> 
> Also "podman" should have a bigger weight than "desktop"; The header line should be bolder.
> 
> The shadows for the images are showing some glitches: Screenshot 2024-11-21 at 13 59 59
> 
> A couple of adjustments are needed to align this with the mockup.

Thanks for finding those bugs / enhancements! I've opened up two issues as they are outside the scope of the current issue, so it gives chance for others to pick it up:

https://github.com/podman-desktop/podman-desktop/issues/10047
https://github.com/podman-desktop/podman-desktop/issues/10048

**Pull request merged**
