### PR TITLE
feat: enable light mode for buildImageFromContainerfile page

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR enables light mode in the build image from container file page.
It is built over https://github.com/containers/podman-desktop/pull/7768

### Screenshot / video of UI

buildimagefromcont

### What issues does this PR fix or reference?

it is part of #7214 

### How to test this PR?

go to images -> click on build button (top right)

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by deboer-tim — COMMENTED** [review]
Code LGTM and worked well in testing. My only concern is if we should really have --pd-formpage-card*, i.e. whether these should be generic cards (variable names without formpage) or there are existing color variables we should use. @ekidneyrh any preference?

**Review by jeffmaury — APPROVED** [review]
LGTM. Same remarks about reusing variables

**Comment by lstocchi** [comment]
Not sure how to change the variables name. By looking at other cases i see that the cards used for carousel have `content-card-carousel-*`, then we have generic content card `content-card-*`, then card related to `invert-content-` have prefix `invert-content-card-*`. So based on their scope we have different prefixes. As these are related to formpage i thought that using formpage prefix made sense. 
So which are your suggestions? 
By looking at the code, they are actually buttons `<button></button>` styled like cards. Is `content-button-card-*` good enough ?? Anything else?

@deboer-tim @jeffmaury

**Comment by deboer-tim** [comment]
> Not sure how to change the variables name. By looking at other cases i see that the cards used for carousel have `content-card-carousel-*`, then we have generic content card `content-card-*`, then card related to `invert-content-` have prefix `invert-content-card-*`. So based on their scope we have different prefixes. As these are related to formpage i thought that using formpage prefix made sense. So which are your suggestions? By looking at the code, they are actually buttons `<button></button>` styled like cards. Is `content-button-card-*` good enough ?? Anything else?

Our design has most items that always look the same no matter where they are (Buttons, Inputs, Checkboxes, etc), and then some things like content cards that are different depending on context like Dashboard vs Settings. If the design/colors for the platform cards don't match tiles like on the dashboard or elsewhere then I'm fine if they are new vars just for forms, but card-input-bg is definitely 'wrong' because inputs shouldn't change based on where they are. Can you pick up some of the input-field colors instead or switch to use Input instead of defining a new color?

**Comment by lstocchi** [comment]
@deboer-tim updated. TBH i completely missed the form page design made by Emma https://github.com/containers/podman-desktop/wiki/Design-System-Theming#form-page when i started working on the form pages. I was copying what was done in other pages. By following her mockup the job is much easier and i've been removing all formpage styles. 
I will create another PR to remove it from previous updates. Let me know if this looks good now. I edited the gif in the first message

**Review by deboer-tim — APPROVED** [review]
Thanks for the changes, working well. 👍🏼

**Pull request merged**
