### PR TITLE
feat: Kube context on statusbar

### LINKED ISSUE #2309: Show Kube context on the status bar
### Is your enhancement related to a problem? Please describe

I've been caught a couple times where I forgot what my current context was and the pod or action I was expecting wasn't there. I've seen a couple demos recently where people were on one of the pages and then went all the way to the system tray to check the context or switch it.

### Describe the solution you'd like

IMHO we need to have a larger discussion about how we handle the current context vs someone trying to (e.g.) use a local cluster while also deploying to a remote one. One basic fix though would be to start showing the current context on the status bar so that it's easily seen, and ideally making that a menu so that I can easily switch without going back to the system tray.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

This adds the current Kubernetes context to the status bar. When you click on it, a quick pick allows you to switch the context. The name is capped at 20 characters.

This duplicates function already available in the system tray. Some notes:
- The system tray is handy for when you don't have the dashboard open, so should be kept.
- When the dashboard is open you can now see the current context at a glance.
- The system tray is often 'far away' on screen, and viewing/changing is awkward compared to a quick popup.
- Some OS don't have a system tray.

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/19958075/242b02b4-fc3c-415b-be08-24eb1933adc5

### What issues does this PR fix or reference?

Fixes #2309.

### How to test this PR?

Confirm the current context is shown. Change it via the quick pick and system tray to confirm that both are updated.

### CODE REVIEW

**Comment by deboer-tim** [comment]
See issue #2754 for quick fix issues not directly related to this change.

**Comment by benoitf** [comment]
I'm not sure about the gear icon ?

**Comment by deboer-tim** [comment]
Agreed but we don't have custom icon support yet, right? I wanted to use the Kube wheel and tried a few other fa- before I gave up looking, happy to take other suggestions.

**Comment by benoitf** [comment]
yes we can't put kubernetes icon for now as contributing icon is not implemented.
but at the bottom of the left navbar we already have the cog
so it'll display 2 cog icons (one in the navbar and one very close in the status bar so might be disturbing)
I don't have proposal for icon

@mairin do you have one (need to stick for now to a font awesome icon name)

**Comment by mairin** [comment]
@benoitf some ideas, maybe some better than others 😂

- context... a bunch of stuff grouped together in a thing called a context, like the nodes in this triangle https://fontawesome.com/icons/circle-nodes?f=classic&s=solid
- it's *where* you deploy the stuff too? https://fontawesome.com/icons/location-dot?f=classic&s=solid
- it's sort of like a server, because it's a place (sort of), that is kinda of server like in an abstract way? https://fontawesome.com/icons/server?f=classic&s=solid
- a K because Kubernetes starts with K! https://fontawesome.com/icons/k?f=classic&s=solid
- a tag/label bc context is a tag/label in parts of the podman desktop UI? https://fontawesome.com/icons/tag?f=classic&s=solid
- an anchor bc there is no helm icon and anchors are kinda shippy like K8s! https://fontawesome.com/icons/anchor?f=classic&s=solid
- a context is kind of like a layer or view?? https://fontawesome.com/icons/layer-group?f=classic&s=solid

hopefully useful for more than lolz 😄

**Comment by benoitf** [comment]
thanks, I'll let @deboer-tim pick-up one from the list :-)

**Comment by deboer-tim** [comment]
Switched to server icon. If anyone has a stronger preference I'm happy to switch, but also hoping this is semi-temporary until we can get to custom icons.

**Comment by benoitf** [comment]
I'm wondering if there is no kubeconfig file if we should display 'no context'
Might be possible the person is not interested/using kubernetes so might be better to not display it at all ?

**Comment by deboer-tim** [comment]
Yeah, I think that's fair. Will update.

**Comment by slemeur** [comment]
Is there a tooltip displayed on hover on the status bar item?

I like having this in the status bar - but I think we need to be careful as there are some screens where the kubecontext will be used. Does it dispatches an event that is being handle by those screens?

For example: 
- I have kubecontext_1 selected
- I open the "Play Kubernetes YAML" or the "Deploy to Kubernetes"
- I'm using the status bar, switching to kubecontext_2
--> Does the screens show "kubecontext_2" or still "kubecontext_1"
- I do execute the command from the screen
--> Where does it go?

Also, I think we are getting to a stage, where we have too many things in the status bar: Kind, Docker Compatibility, Compose, and this new kubernetes context switcher.

**Comment by deboer-tim** [comment]
> Is there a tooltip displayed on hover on the status bar item?

Yes, currently it says `Current Kubernetes context`. Let me know if you'd prefer something else.

> I like having this in the status bar - but I think we need to be careful as there are some screens where the kubecontext will be used. Does it dispatches an event that is being handle by those screens?

Dispatches an event: yes, same event as if you change the context from the system tray or outside of Podman Desktop.

All screens handling it: the normal places all update based on current context, and are not affected either way by this PR.

> For example:
> 
> * I have kubecontext_1 selected
> * I open the "Play Kubernetes YAML" or the "Deploy to Kubernetes"
> * I'm using the status bar, switching to kubecontext_2
>   --> Does the screens show "kubecontext_2" or still "kubecontext_1"
> * I do execute the command from the screen
>   --> Where does it go?

This screen uses the current context when you open it. You can see it listed and it doesn't update if you change context while it is open. Should it? I'm not 100% sure, but this behaviour already exists if you change from the system tray or externally. This PR would make it marginally easier to change the context while it is open, but I don't think it is fundamentally more likely nor confusing to users.

> Also, I think we are getting to a stage, where we have too many things in the status bar: Kind, Docker Compatibility, Compose, and this new kubernetes context switcher.

Totally agreed. To me seeing the context at a glance is useful when you're doing Kube things the same way seeing the git branch is useful in an IDE. Like Florent's comments above, the goal should be to make sure it is not there/distracting when you don't need it.

I would rather we figure out where items like Docker Compatibility and Compose should move, since they tend to be more onboarding/once-and-done items.

**Comment by deboer-tim** [comment]
Change pushed as per @benoitf's suggestions above. The new status bar won't appear for pure podman/docker users, and will automatically appear when a kubeconfig exists. This behaviour matches the system tray menu.

**Review by benoitf — APPROVED** [review]

**Comment by mairin** [comment]
@slemeur 

> 
> For example:
> 
>     I have kubecontext_1 selected
>     I open the "Play Kubernetes YAML" or the "Deploy to Kubernetes"
>     I'm using the status bar, switching to kubecontext_2
>     --> Does the screens show "kubecontext_2" or still "kubecontext_1"
>     I do execute the command from the screen
>     --> Where does it go?
> 

The way I would handle this is to display the kubecontext selection differently in the "Play Kubernetes YAML" screen. Frame the currently-selected global kubecontext (eg kubecontext_1) as what you're going to get, and if you wanna select a different one (eg kubecontext_2) then you have to "override kubecontext for this deployment" or something like that - framing it this way I think would make it clear that you are not changing the global kubecontext, you are temporarily overriding it.

Something like:

Screenshot from 2023-06-07 15-50-00

The makes the assumption that the user would have a context in which they would occasionally want to deploy to a different kubecontext but have a main one that is their default most of the time.

**Comment by lstocchi** [comment]
> Also, I think we are getting to a stage, where we have too many things in the status bar: Kind, Docker Compatibility, Compose, and this new kubernetes context switcher.

Maybe we should make the status bar customizable by the user as in VScode
vscode-status-bar

**Review by lstocchi — APPROVED** [review]
Works fine and it's super useful. Atleast for me, in Windows i never use the tray as it's hidden. Thanks 🚀 

Some enhancements:

- I would remove/mark the current context entry from the list. Let's say I'm connected to cluster_1, i should not see it in the list when switching context. Or it should be marked in some way.

- If the kubeconfig only contains one entry the click should be disabled

**Comment by deboer-tim** [comment]
Thanks, I will merge. I'm a little hesitant since this thread has diverged from normal PR review into improved design for related things like the 'Play Kubernetes YAML' screen, suggestion to hide status bar items, etc. I don't want to 'lose' these comments, but I don't think they should hold up the merge. All, please feel free to open additional issues to track these ideas & suggestions.

> Some enhancements:
> 
> * I would remove/mark the current context entry from the list. Let's say I'm connected to cluster_1, i should not see it in the list when switching context. Or it should be marked in some way.
> * If the kubeconfig only contains one entry the click should be disabled

My concern with this approach is the first time you see the context on the status bar and try to click it, it does nothing - when you add a second context you may not try again. So, I think it's still better to show a quick pick with one item that doesn't do anything (yet).

I totally agree that the current context should be clear. It should already be selected via this PR, but isn't due to a bug in the quickpick (issue 2754 item 2). In retrospect that's probably still not obvious enough so I will open another PR.

**Comment by mairin** [comment]
@deboer-tim I'll move the design suggestions to another ticket - sorry for that lol sometimes I don't know if im commenting on an issue or a PR 🤦🏻‍♀️

**Pull request merged**
