### PR TITLE
fix: units used for podman machine parameters

### LINKED ISSUE #3062: Size units wrongly processed
### Is your enhancement related to a problem? Please describe

When working on #3047, I noticed that size quantities (memory, disk) are specified in bytes but are not processed and displayed properly.

For example the default of Podman machine is 2GB but is specified as 2048000000 which is not exactly 2GB.
Luckily it is passed to Podman as 2048 as Podman expected MB. So far so good.

But the wizard shows a different value:

image

### Describe the solution you'd like

Convert properly those quantities from bytes to MB (1024 * 1024) and GB (1024 * 1024 * 1024)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by afbjorklund**
The podman parameters uses binary sizes for input, but Podman Desktop was trying to pass decimal sizes resulting in them being slightly off.

Since podman machine init only accepts integer parameters, there will be some round-off errors when converting the actual values from bytes.

### What issues does this PR fix or reference?

Closes #3062

### How to test this PR?

Create a new Podman Machine, compare the resulting values with the input parameters.

There will be some round-off errors due to the unit conversion, but it should be closer...

The round-off errors are worse for the disk (given in GiB), than for the memory (in MiB):

```
NAME                    VM TYPE     CREATED       LAST UP        CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        1 second ago  7 minutes ago  2           3.999GB     9.664GB
```

### CODE REVIEW

**Comment by afbjorklund** [comment]
Related podman documentation fix:
* https://github.com/containers/podman/pull/19146

Might consider changing also Podman Desktop values to use binary sizes, then they would be less awkward...

That is, it could default to 4 GiB and 100 GiB, instead of 4 GB and 100 GB. Then there wouldn't be any roundoff.

**Comment by jeffmaury** [comment]
> Related podman documentation fix:
> 
>     * [Use bytes size consistently instead of human size podman#19146](https://github.com/containers/podman/pull/19146)
> 
> 
> Might consider changing also Podman Desktop values to use binary sizes, then they would be less awkward...
> 
> That is, it could default to 4 GiB and 100 GiB, instead of 4 GB and 100 GB. Then there wouldn't be any roundoff.

Yes I think we should

**Review by lstocchi — APPROVED** [review]

**Review by cdrage — APPROVED** [review]
LGTM! Let's hold off merging until Monday in case this breaks anything.

**Review by benoitf — APPROVED** [review]

**Review by benoitf — APPROVED** [review]
I was on PTO so reviewing some old PRs

thanks @afbjorklund

**Pull request merged**
