### PR TITLE
feat: allow users to pick between WSL and HyperV if both enabled (#8864)

### LINKED ISSUE #8864: Add provider parameter if WSL and HyperV are both enabled

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR allows users to select one between wsl or hyperv when both can be used.
Based on the selected provider, it hides/shows the cpu/memory/disk settings.

### Screenshot / video of UI

hyperv_create_2

### What issues does this PR fix or reference?

it resolves #8864 

### How to test this PR?

1. start desktop as an admin on windows and try to create a hyperv or wsl machine. You should see the dropdown listing both providers

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by gastoner** [comment]
Is this correct? 

https://github.com/user-attachments/assets/21406b90-b645-4741-a623-25d45cbc7d06

**Comment by lstocchi** [comment]
@gastoner fixed. I guess i lost the change during rebasing 🤷‍♂️ 

I also noticed i didn't handle the requirement of Hyper-v to have memory set as a multiple of 2Mb. Fixed it as well

**Review by axel7083 — APPROVED** [review]
LGTM, I do not have the HyperV enabled (not windows pro), so I don't see any change on my side.

**Review by jeffmaury — COMMENTED** [review]
I can't make it to work. The extension does not start (timeout) and if I start it manually it stays forever in ACTIVATING state.

Will look deeper to understand what's happening

May be related to that:

```
11:28:09 [main] [podman]  Can't get machine podman-machine-default resource usage error Error: no engine matching this container
11:28:09 [main] [podman] Podman extension: Failed to read socketPath from machine inspect

11:28:13 [main] Engine does not have an API or a libpod API, returning empty array Podman

```

Update: found out that `updateMachines` called during initialization took 28s on my machine

**Comment by lstocchi** [comment]
> Update: found out that `updateMachines` called during initialization took 28s on my machine

This PR does not change anything on the updateMachines. Have you tried with the main branch to see if you have the same behavior?

**Comment by jeffmaury** [comment]
> > Update: found out that `updateMachines` called during initialization took 28s on my machine
> 
> This PR does not change anything on the updateMachines. Have you tried with the main branch to see if you have the same behavior?

Same issue with main. I think we must update Podman extension activate method to be async

**Review by gastoner — APPROVED** [review]
Great job! Looks like its fixed

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Having hard times to test it (but does not seem related to this PR).

User mode networking should be hidden for Hyper V

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
