### PR TITLE
feat: kube navigation section

### LINKED ISSUE #5660: Kubernetes nav section
### Is your enhancement related to a problem? Please describe

There are already 3 new Kubernetes nav icons (Deployments, Ingress/Routes, Services) that take up a lot of space in the nav bar.

### Describe the solution you'd like

Now that we have nav sections, the Kubernetes nav icons (Deployments, Ingress/Routes, Services) should be in a section. We're just waiting for an appropriate Kubernetes outline icon.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Adds a new Kube icon and moves the three Kubernetes nav items into a new nav section so that they're collapsible.

### Screenshot / video of UI

Screenshot 2024-02-08 at 9 26 31 AM

https://github.com/containers/podman-desktop/assets/19958075/55bccd07-7bc5-4874-98da-413abd19de40

### What issues does this PR fix or reference?

Fixes #5660.

### How to test this PR?

Confirm Kubernetes nav section works as expected.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM.

Just a technical debt question: can't we have the Kubernetes icon in a separate SVG file ?

**Review by cdrage — APPROVED** [review]
This is awesome, LGTM!

**Comment by deboer-tim** [comment]
> Just a technical debt question: can't we have the Kubernetes icon in a separate SVG file ?

I don't mean to hide behind a 'that's what we do everywhere else' :) , but it is in its own .svelte the same way we have done for pod/image/container/etc, and is reusable elsewhere in the UI.

Note that this is an outlined version that fits with our nav style, we'd use the regular blue & white one where we need a Kubernetes logo.

**Comment by slemeur** [comment]
cool!

**Pull request merged**
