### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by Mayureshd-18**
### What does this PR do?
This PR is focused on improving the quality and correctness of the documentation by fixing some of the typos that may confuse users or hinder understanding.

### What issues does this PR fix or reference?
Fixes typos mainly from markdown files. 
One may create a similar pull request after encountering any other typos while going through the documentation.

### CODE REVIEW

**Comment by deboer-tim** [comment]
Thank you @Mayureshd-18! You'll need to add a SignedOff to your commit (so PR DCO check will be ✅).

**Comment by benoitf** [comment]
@Mayureshd-18 you need to sign all the commits (here there is one extra commit)

you can use `git commit --amend` or `git rebase -i HEAD~3` to edit your commits, etc

**Comment by benoitf** [comment]
@Mayureshd-18 FYI I've amended your commit so it's ✅  on DCO check

**Comment by Mayureshd-18** [comment]
Thank you!

**Comment by Mayureshd-18** [comment]
Please review the PR. @benoitf @deboer-tim @gbraad 
Regards

**Review by benoitf — APPROVED** [review]
thanks @Mayureshd-18

**Review by deboer-tim — APPROVED** [review]

**Comment by benoitf** [comment]
@Mayureshd-18 could you file/update the description of the pull request to add that it's about fixing the typos

in the description you might say how you find those, etc.

then, thanks for your valuable contribution @Mayureshd-18 , we should be able to merge

**Comment by Mayureshd-18** [comment]
Done!

**Comment by benoitf** [comment]
thanks @Mayureshd-18

**Pull request merged**
