### PR TITLE
docs(fix): typo that caused page title to appear twice

### PR DESCRIPTION
**Pull request by themr0c**
* Fixed "Installing Podman Desktop with Winget" title appearing twice in https://podman-desktop.io/docs/Installation/windows-install/installing-podman-desktop-with-winget

Signed-off-by: Fabrice Flore-Thébault <ffloreth@redhat.com>

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by benoitf** [comment]
I think you should specify where it's appearing twice, also there is a blank body of the description

**Review by benoitf — COMMENTED** [review]
@themr0c please update the description of this PR
it's blank while it should describe / provide a screenshot where it was displaying twice the page title so any one can review the PR with guidance

**Comment by benoitf** [comment]
thanks @themr0c, sometimes you could just add a screenshot (so people can see where it's appearing and where to check for reviewing the PR)

**Pull request merged**
