### PR TITLE
feat: adding groupContributions logic

### LINKED ISSUE #5313: Images' actions are not scaling
### Is your enhancement related to a problem? Please describe

Screenshot 2023-12-19 at 09 23 15

The icons for the actions are not scaling well.
Here, we are in a situation where we have 3 times the same icon for 3 different actions, and it's very hard for the user to understand what those are about, without waiting for the tooltip.

### Describe the solution you'd like

I think we should try to have a more minimalist way to handle the actions:
- There will be primary actions: run, delete, edit (those are pretty obvious with the 
- There will be secondary actions: "Push to" where we should have a dropdown.

similar to 
Screenshot 2023-12-19 at 09 29 56

This would make the obvious actions self explicit and the other ones, will be clearer with a textual description.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Adding logic to groups contributions with a kebab style when more than one contribution are present in ImageDetails

### Screenshot / video of UI

**only one action contribution**
image

**more than one**
image

### What issues does this PR fix or reference?

Fix #5313

### CODE REVIEW

**Comment by deboer-tim** [comment]
IMHO the kebab still needs the darker box in this context so that it looks like a button.

**Comment by axel7083** [comment]
> IMHO the kebab still needs the darker box in this context so that it looks like a button.

I updated the design and added unit tests!

**Review by lstocchi — COMMENTED** [review]
In my case I see 👇 . I have two contributions `deploy to kind` and `deploy to minikube`.
image

**Comment by axel7083** [comment]
> In my case I see 👇 . I have two contributions `deploy to kind` and `deploy to minikube`. image

I am gonna take a look

**Comment by axel7083** [comment]
@lstocchi I fix it and added a test !

**Review by lstocchi — APPROVED** [review]
LGTM

**Pull request merged**
