### PR TITLE
feat(ui): allow to specify tabs for FormPage element

### LINKED ISSUE #5184: FormPage UI element should let use tabs
### Is your enhancement related to a problem? Please describe

like for DetailsPage where we have a slot for tabs, FormPage should let use tabs as well

### Describe the solution you'd like

add a slot element

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Allow to use tabs in FormPage components

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

fixes #5184 

### How to test this PR?

Component test added

### CODE REVIEW

**Review by deboer-tim — COMMENTED** [review]
Really minor, but can you throw a:
```
  {#if $$slots.tabs}
  {/if}
```
around it? Otherwise it is moving all current forms down slightly by the div's bottom border.

**Comment by benoitf** [comment]
@deboer-tim looks like your comment is valid for existing component
https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/ui/DetailsPage.svelte#L63-L65

**Comment by deboer-tim** [comment]
From a component standpoint I agree it should be there too (and I can add it if you want), but we never added it before because all of our DetailsPages have tabs.

When Philippe added tabs to NavPage (for pod filters) he included it there:
https://github.com/containers/podman-desktop/blob/a1fadba85bf75466c897e6a72f10c412305de8cf/packages/renderer/src/lib/ui/NavPage.svelte#L55C23-L55C23

**Comment by deboer-tim** [comment]
FWIW I tried adding the `if` to DetailsPage and was reminded why it's there as part of #5193 - for DetailsPage there is a color difference between the header and content and that line is an intentional divider. The design for FormPage didn't have a divider (I don't remember why and can't find the design file now).

**Comment by benoitf** [comment]
added the if clause for slots.tabs

**Review by deboer-tim — APPROVED** [review]
LGTM

**Pull request merged**
