### PR TITLE
feat: brings a simple command palette to invoke registered commands

### LINKED ISSUE #4011: Display a command palette
### Is your enhancement related to a problem? Please describe

it would be nice if all commands exposed internally and by extensions could be displayed so we can invoke them from a single place.

### Describe the solution you'd like

Command palette that would display all commands and let's invoke them

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Displays a command palette with registered commands
Lot of improvements can be done later like the shortcuts, the Fuzzy search, last recent command being called, etc

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/436777/5aaa6a1b-6df5-4b66-a811-cdd148d02ad6

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/4011

### How to test this PR?

Invoke F1 key to bring the command palette

### CODE REVIEW

**Review by deboer-tim — COMMENTED** [review]
I honestly thought this was a quickpick until I looked at the code. Any reason we can't use a quickpick and avoid the duplicate code? (and things like fuzzy search could be done once and apply to both paths)

**Comment by benoitf** [comment]
I think maybe they can share some code (like some of the workflow) but I think it'll differ as there will shortcuts and recent commands and I'm unsure we should mix these concepts into one big universal component

**Comment by benoitf** [comment]
I think maybe they can share some code (like some of the workflow) but I think it'll differ as there will shortcuts and recent commands and I'm unsure we should mix these concepts into one big universal component

**Review by lstocchi — COMMENTED** [review]
Works fine.

My doubt is, how can someone know that he must click `F1` to prompt the command palette? In vscode there is an entry in the menu with the shortcut
image

Second, i think we should give the option to not show a command in the palette.
E.g some onboarding command only set a context value, so it doesn't make sense to show them here.

**Comment by deboer-tim** [comment]
> My doubt is, how can someone know that he must click `F1` to prompt the command palette? In vscode there is an entry in the menu with the shortcut

FWIW I thought the exact same thing, but then I thought that's actually ok for a bit - some users will stumble on it b/c of VS Code and F1 key elsewhere, and gives us a chance to clean up menu items and try it out before we fully promote it.

**Comment by benoitf** [comment]
@lstocchi yes it's legitimate questions

For 1. I was hoping that we could have it present as the onboarding, hidden so we can try it out. Then show it within help menu, or through a status icon or with links

2. Yes the idea is to bring enablement property key so it'll allow to hide commands. I was thinking it would be a separate addition ( like short keys or fuzzy etc)

**Review by lstocchi — APPROVED** [review]
Yeah, my comments were not a blocker. We can work on them in following PRs.
As a first implementation LGTM

**Review by dgolovin — APPROVED** [review]
Works for me.

**Comment by benoitf** [comment]
I've created

https://github.com/containers/podman-desktop/issues/4111
https://github.com/containers/podman-desktop/issues/4107
https://github.com/containers/podman-desktop/issues/4112

as follow-up issues

**Pull request merged**
