### PR TITLE
docs: add GPU documentation for linux / mac / windows

### LINKED ISSUE #8361: GPU documentation regarding on macOS / WIndows / Linux
### Is your enhancement related to a problem? Please describe

We should document macOS libkrun support, Windows WSL2 and how LInux handles it natively.

### Describe the solution you'd like

Added documentation.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
docs: add GPU documentation for linux / mac / windows

### What does this PR do?

* Adds documentation for each OS on how to install GPU capabilities
* Adds information how to verify each GPU capability.

### Screenshot / video of UI

N/A, docs.

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/8361

### How to test this PR?

Go through the guide for your respective OS.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
for Windows, maybe something when we're using Hyper-V and not WSL ?

**Comment by cdrage** [comment]
> for Windows, maybe something when we're using Hyper-V and not WSL ?

We have zero documentation on how to use Hyper-V (even I do not know how to set it up :(, I remember it being brought up in the past).

There also appears to be nothing on Google / GitHub search other than: https://github.com/containers/podman/discussions/20855 which points to a licensing issue using GPU pass-through with consumer Hyper-V? So I'm assuming we cannot support it.

**Comment by benoitf** [comment]
@cdrage maybe saying it's not supported and need to use WSL for now ?

**Comment by cdrage** [comment]
> @cdrage maybe saying it's not supported and need to use WSL for now ?

Added a small note regarding WSL2 only one supported

**Review by benoitf — APPROVED** [review]

**Pull request merged**
