### PR TITLE
chore: add main and renderer debug scripts

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This adds scripts to debug Podman Desktop. It can be useful to have them here so if someone wants to contribute can use them without getting crazy. It would be good to add a bit of documentation i guess 🤔 

This has been tested on Windows.

### Screenshot/screencast of this PR

debug

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Build and run the app using `yarn watch`, then execute the `Debug Main Process` script to debug the main. A new window will pop up and you have to use that.
If you want to debug the renderer, you can run the `Debug Renderer Process` after the `Debug Main Process` script has been started.
When running the `Debug Renderer process`, the console in the Podman-Desktop window will be connected to vscode so if you put some breakpoint in the console and some in vscode it will stop in both.
For the renderer maybe it's better to stick with the Podman-Desktop window console. I tried a bit and it was a mess but i think it can be useful to have it in some cases.

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
hello,

what about a launch command really launching the whole stuff, not having to run `yarn watch` as a first step ?

ie: launching the watch script

**Comment by jeffmaury** [comment]
Would be good to add to documentation because I'm using WebStorm

**Comment by lstocchi** [comment]
> hello,
> 
> what about a launch command really launching the whole stuff, not having to run `yarn watch` as a first step ?
> 
> ie: launching the watch script

Added a `preLaunchTask` for the `Debug main Process` as it has to be always started. 
The main issue has been to pick a correct problemMatcher. As the watch script never ends I needed a way to signal the debug to start. By using that pattern it seems working fine for me. Found on https://github.com/microsoft/vscode/issues/6209.

**Comment by lstocchi** [comment]
> Would be good to add to documentation because I'm using WebStorm

Do you mean documentation to describe the scripts in general (e.g. if you want to debug use ....) or something specific to explain how to debug on WebStorm? In the second case I've never used WebStorm so i don't have any idea. I have to look into it and create a new PR

**Comment by benoitf** [comment]
FYI the electron template we're using added VS Code launch script: https://github.com/cawa-93/vite-electron-builder/blob/main/.vscode/launch.json it might be simpler ?

**Comment by lstocchi** [comment]
> FYI the electron template we're using added VS Code launch script: https://github.com/cawa-93/vite-electron-builder/blob/main/.vscode/launch.json it might be simpler ?

Edited the original `Debug Main Process` script with this. Tried to update the renderer aswell but i wasn't able to make it work in other ways.

**Comment by benoitf** [comment]
maybe it's missing the inspect in the watch.js script ?
https://github.com/cawa-93/vite-electron-builder/commit/51236a693761a56fea05655abc0f6f1632074501

**Comment by lstocchi** [comment]
> maybe it's missing the inspect in the watch.js script ? [cawa-93/vite-electron-builder@51236a6](https://github.com/cawa-93/vite-electron-builder/commit/51236a693761a56fea05655abc0f6f1632074501)

No that project doesn't have any renderer script. If you start the `Debug Main Process` and you want to debug the ui, vscode is not attached to the view, so only the breakpoints in the console are used.
I guess the `--inspect` is not mandatory as it works fine without that.
I tried with that flag as well, nothing changed.. atleast on Windows

**Comment by benoitf** [comment]
debugging the main process works fine but I would rather attach the process for the renderer instead of spawning a new electron instance.
https://github.com/lstocchi/podman-desktop/pull/1

**Comment by lstocchi** [comment]
> debugging the main process works fine but I would rather attach the process for the renderer instead of spawning a new electron instance. [lstocchi#1](https://github.com/lstocchi/podman-desktop/pull/1)

Thank you!! It works fine for me.

**Review by benoitf — APPROVED** [review]
tested and it works fine.

For the renderer I need to add breakpoints in Electron DevTools for .svelte files (then it's working from the IDE)

image

**Pull request merged**
