### PR TITLE
feat: registry editing improvements

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
This changes proposal adds a new look and feel to registry editing dialog and provide basic validation for the input fields.
Also adds a switch button to show/hide the password value.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### Screenshot/screencast of this PR

registry

### What issues does this PR fix or reference?

part of #290 #286 #283

### How to test this PR?

Try to add or modify the registry from the preference page.

### CODE REVIEW

**Comment by vzhukovs** [comment]
Autocompletion for the registry url is in progress at this moment. The same for credentials validation. Those features will be provided as separate PRs.

**Comment by slemeur** [comment]
That's nice! good work @vzhukovs

**Review by benoitf — APPROVED** [review]
I'm wondering if the border color of the dialog should not be the same than the color of the navbar item

image

and IMHO the dialog is taking too much space based on the existing window
image
but all these remarks are follow-up discussions

**Comment by benoitf** [comment]
nice improvement 🎉

**Pull request merged**
