### PR TITLE
feat: show no logs view when opening logs tab and waiting for logs to being fetched (#1117)

### LINKED ISSUE #1117: Loading pod container logs lags / appears with a blank terminal and no loading screen
### Bug description

When clicking on a container that is part of a pod, the logs "lag" and don't appear right away. There is also no indicator of any form of loading screen. This makes the user think that the application has frozen.

https://user-images.githubusercontent.com/6422176/210633879-8c50dbf2-fed6-4477-a16d-3a5f8ab12e17.mov

### Operating system

M1

### Version

0.10.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This shows the no logs view when opening the logs tab and waiting for logs to being fetched.

### Screenshot/screencast of this PR

spinner_terminal

### What issues does this PR fix or reference?

it fixes https://github.com/containers/podman-desktop/issues/1117

### How to test this PR?

1. have a container that start printing logs after a while
2. open the logs view, see the no logs view 

I have used this to simulate a similar behavior
```
apiVersion: v1
kind: Pod
metadata:
  name: sleep-print
spec:
  containers:
    - name: sleepy
      image: alpine      
      command: 
        - /bin/sh
        - -c 
        - | 
          sleep 10 && echo "hello"
```

### CODE REVIEW

**Comment by benoitf** [comment]
Should we add a little text like : `Retrieving logs...`

also might be interesting to know why it's taking so long ?

**Comment by lstocchi** [comment]
> Should we add a little text like : `Retrieving logs...`

Sure

> also might be interesting to know why it's taking so long ?

In my case because there is a sleep 10 and then it starts printing stuff.

**Comment by benoitf** [comment]
Ok so maybe it's not about 'Retrieval' it's more about "Waiting for something to be added into the log" ?

**Comment by lstocchi** [comment]
> Ok so maybe it's not about 'Retrieval' it's more about "Waiting for something to be added into the log" ?

Yeah 😆 but it's not a nice message to display.

**Comment by lstocchi** [comment]
@benoitf this is with the message

fetching_log_terminal

**Comment by deboer-tim** [comment]
I really don't like 'Fetching' only being half screen and then the logs jump to full screen. Ideally it looks like the log window is already full screen and this is just a message overlay.

The message makes it seem like it's a delay in getting the logs or in Podman Desktop. Maybe a message more like "Waiting for container output"?

**Comment by benoitf** [comment]
at some points we had a "No logs" screen.

spinner usually means we're doing something that user asked but from I understand it's just that log is empty so I would expect to see an empty state (like if I don't have any containers)

Because let suppose the container is never sending logs I would think I need to wait while it will never end.

**Comment by lstocchi** [comment]
> at some points we had a "No logs" screen.
> 
> spinner usually means we're doing something that user asked but from I understand it's just that log is empty so I would expect to see an empty state (like if I don't have any containers)
> 
> Because let suppose the container is never sending logs I would think I need to wait while it will never end.

The no logs is still there but it's hidden because the callback has never been called so the ui doesn't know yet if there are logs or not.

Once the callback is called the spinner disappear and the view is updated as before (no logs or the actual logs). 
If the container never send logs back it's because it's stuck in some long-running task and it's not creating any logs

**Comment by lstocchi** [comment]
> at some points we had a "No logs" screen.
> 
> spinner usually means we're doing something that user asked but from I understand it's just that log is empty so I would expect to see an empty state (like if I don't have any containers)
> 
> Because let suppose the container is never sending logs I would think I need to wait while it will never end.

The no logs screen is still there but it's hidden because the callback is never called so the ui doesn't know yet if there are logs or not. It only appears if you stop the container before it received any logs.

I wonder if the `no logs` view makes sense during execution.
If you are executing a process that is long running and does not print any logs for some reason, would it be better to see the `no logs` message or a `waiting for container output` spinner?

**Comment by benoitf** [comment]
I would say that `fetching logs` means that we're trying to collect data and if it takes time, I don't understand.


If I run for example a no-log container like
```
podman run --rm -it fedora bash -c 'sleep infinity'
```

image


I don't really understand.

But if I had like 'No logs for now' , 'Container has not written any log' message then I would understand that ok my container is not writing anything for now, it's not that we're not able to grab the logs

**Comment by lstocchi** [comment]
@benoitf @deboer-tim so now when the container logs view is opened the `No logs` message is shown and it disappears when logs start flowing in
logs_visibility_2

@benoitf regarding these lines
https://github.com/containers/podman-desktop/pull/1353/files#diff-15d8dc7ff89f92933651f2fe7083df99cf9019fffd9fecef58fe4d3bd1a637b8R134-R135
I tested some things and it seems this hack makes its job.

As the `no logs` message has to be visible from the beginning, the div containing the actual logs must be hidden. 
By using the `display: none` rule it's like the terminal resizing doesn't work when the first log arrives. The terminal tab only gets half page as height (exactly the same as it is now when you open the logs view the first time). 
Using the `visibility: hidden` rule, the element is in the DOM with real dimension (0px height at start) and by updating its size, the resizing works fine.

**Comment by deboer-tim** [comment]
For the waiting screen maybe you can switch to using ui/EmptyScreen?

I don't know if there's a different/better way to implement this, but thanks for fixing my usability concerns. I think it's much clearer now that there is no output from the container and it's not a client loading delay.

**Comment by lstocchi** [comment]
> For the waiting screen maybe you can switch to using ui/EmptyScreen?

What do you mean by EmptyScreen? Not showing anything? Because this was the original problem to fix. 
"When clicking on a container that is part of a pod, the logs "lag" and don't appear right away. There is also no indicator of any form of loading screen. This makes the user think that the application has frozen"  https://github.com/containers/podman-desktop/issues/1117

> I don't know if there's a different/better way to implement this

me neither. I was trying to propose some solutions 😆

**Comment by deboer-tim** [comment]
Reusable EmptyScreen: https://github.com/containers/podman-desktop/blob/94e1859cac1e50fb42561457c0f82ed5cd5681fe/packages/renderer/src/lib/ui/EmptyScreen.svelte

**Comment by benoitf** [comment]
hello @lstocchi do you will add the usage of <EmptyScreen> component ?

**Comment by lstocchi** [comment]
@benoitf done. 👍  I forgot about it sorry.

**Review by benoitf — APPROVED** [review]
tested with the command `podman run --rm -it fedora bash -c 'sleep 10 && echo "we have a log"'`



https://user-images.githubusercontent.com/436777/218476519-5b93e309-2537-4bcb-85a3-b3393f8da412.mp4

**Comment by benoitf** [comment]
@lstocchi if you could update the PR's description and the screencast with what the PR does now

then I think we're ready to merge

**Comment by lstocchi** [comment]
> @lstocchi if you could update the PR's description and the screencast with what the PR does now
> 
> then I think we're ready to merge

@benoitf done 👍

**Pull request merged**
