### PR TITLE
chore: fix svelte 5 deprecation warning

### LINKED ISSUE #9313: Bug(ui-library) Column typing is not compatible with Svelte 5
### Bug description

In AI-Lab I was trying to use svelte 5 component as renderer and got the following typecheck error

```
The types of info.renderMapping are incompatible between these types.
    Type ((object: ModelInfo) => Type) | undefined is not assignable to type
```

The problem is coming from the following type definition we are using

https://github.com/containers/podman-desktop/blob/fc042fef0214bb6a5e7fb001210c9fba74fb5d4c/packages/ui/src/lib/table/table.ts#L52

As per the svelte documentation `ComponentType` is deprecated _Deprecated: This type is obsolete when working with the new Component type._ [^1]

---

## Solution

From their documentation, the following is the new way of typing components.

```diff
- readonly renderer?: ComponentType<SvelteComponent<{ object: RenderType }>>;
+ readonly renderer?: Component<{ object: RenderType }>;
```

[^1]: https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes-component-typing-changes

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. use svelte 5 components for the renderer
2. assert typecheck error

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Replaces code to remove deprecation warning.

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Fixes #9313.

### How to test this PR?

PR checks.

### CODE REVIEW

**Comment by benoitf** [comment]
there is a typecheck failure then

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Seems other change is required

**Comment by axel7083** [comment]
Weirdly enough we need to remove the following lines

https://github.com/containers/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/ui/src/lib/table/Table.svelte#L316

https://github.com/containers/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/ui/src/lib/table/Table.svelte#L278

Note sure if they are important ? But removing them fix the svelte-check on my machine

**Comment by deboer-tim** [comment]
I haven't tried yet, but I'd expect removing that would break reactivity for actions, e.g. if you click start, the icon button on the left wouldn't change.

**Comment by axel7083** [comment]
> I haven't tried yet, but I'd expect removing that would break reactivity for actions, e.g. if you click start, the icon button on the left wouldn't change.

It does, I've tried it, and it seems to work fine

**Comment by benoitf** [comment]
setting to draft as it's not passing pr checks

**Comment by deboer-tim** [comment]
Sorry for the delay. Rebased and included on:update removal, moving back to review. I wanted a chance to thoroughly test, and I could not break it. I concur with @axel7083, on:update is no longer required, svelte 5 ftw.

**Review by axel7083 — APPROVED** [review]
I tested running, starting, stopping, removing containers, the table is working on my side.
 
Also deleting images works, the table update properly

**Comment by deboer-tim** [comment]
@jeffmaury please re-review

**Review by cdrage — APPROVED** [review]
Checked with Pods and Containers, it all updated fine to me 👍

**Review by benoitf — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
