### PR TITLE
chore: bump to svelte v4

### LINKED ISSUE #3004: Upgrade to svelte 4
### Is your enhancement related to a problem? Please describe

Svelte 4 is out, so we should update to this version
https://svelte.dev/blog/svelte-4

Ensuring all components are working fine

### Describe the solution you'd like

Update to svelte v4

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
bump to svelte v4

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/3004

### How to test this PR?

Should work as before (or faster in UI)

### CODE REVIEW

**Review by cdrage — APPROVED** [review]

**Comment by cdrage** [comment]
```
/home/runner/work/podman-desktop/podman-desktop/packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte
Error:   2:36  error  '/home/runner/work/podman-desktop/podman-desktop/node_modules/svelte/types/index.d.ts' imported multiple times  import/no-duplicates
Error:   3:21  error  '/home/runner/work/podman-desktop/podman-desktop/node_modules/svelte/types/index.d.ts' imported multiple times  import/no-duplicates
```

Linter trying to lint `node_modules`, hah.

**Comment by benoitf** [comment]
@cdrage yes found out that it's related to https://github.com/import-js/eslint-plugin-import/issues/1479 
basically if two different modules have the same .d.ts then plug-in fails...

**Comment by benoitf** [comment]
so there were two svelte checks that fails:

one about a returned object in onMount (moved to onDestroy)
one was about `indeterminate` field not being part of the object (remove it as what we display is a fontAwesome icon)

I think @deboer-tim you were the author of Checkbox, does it work for you ?

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
