### PR TITLE
draft: BinaryRegistry and UpdateProviderRegistry

### PR DESCRIPTION
**Pull request by axel7083**
### Why this PR

I started developing an extension aiming to add the [kompose](https://kompose.io/) project into podman-desktop. While doing so, I discovered that a lot of code/logic is being duplicated in each extension implementation (downloading, updating etc.). 

### What does this PR do?

This PR provide helpers/methods to handle binaries files in a way to ease the updating process without relying on each extensions to handle the job of searching for update, updating the file, and keeping it system wide.

This PR is mainly related to https://github.com/containers/podman-desktop/issues/4059

But extend and offer a better way later to catch other errors such as https://github.com/containers/podman-desktop/issues/4079

### Screenshot/screencast of this PR

Here is a minimal example realised with the code available in the first comment. 

> The extension is not responsible of showing the picker, nor managing the installation.

https://github.com/containers/podman-desktop/assets/42176370/7814d98a-4d2f-4028-baaf-93074e7fcc05

### CODE REVIEW

**Comment by axel7083** [comment]
# Large changes and first working prototype 

@cdrage @benoitf if you have some time at some point, and are interesting, I would appreciate some comment :) ! I did not started writing all the unit tests, so it is more about the main logic ! 

## Workflow explain (extension only)

1. A `BinaryProvider` is created with an `UpdatedProvider` within.
2. The extension api allows to request an installation or update for a `BinaryProvider`
3. When requested, the backend will ask the `Updater` of the targeted `BinaryProvider` to provide a list of assets available
4. It will display the list of candidates to the user
5. when selected, it will ask the `UpdaterProvider` to perform the install by giving it the asset and the path to install the binary

### extension-api added

- [x] binaries namespace accessible using `podmanDesktopAPI.binaries`
- [x] A generic method for adding binary provider `registerBinary(provider: BinaryProvider): BinaryDisposable`
> It is very important for the client to get more than a disposable, getting the providerId is mandatory
- [x] A github oriented binary privider with code provided by the core `registerGithubBinary(...)`
- [x] `getBinariesInstalled(providersIds?: string)` get the list of providers installed
- [x] `requestInstallOrUpdate(providerId: string)` will use the UdateProvider of the BinaryProvider to start installation process
> The process is **not** handle by the extension, it cannot force an installation. The process is to ask the user to validate the installation.

## Changes / features

- [x] Displaying all the versions on the ui to let the user choose.
    - [ ] Allow the extension to put some contraint on the Github Updater provider (minimum tag, etc.)
    - [ ] Do not display a list if only one element is returned by the Updater provider.
- [x] creating `binaries.json` to keep track of installed binaries and version
> This solution is not too bad, trying to keep track of versions is kinda hard without a storage.
- [ ] a logic to install binary system wide
- [ ] a logic to delete an installed binary
- [ ] fix the problem of binary provider unique id
> not sure what to use, name provided by the extension ? It need to be unique and stateful (keep the same after reboot)


<details>
  <summary><h2>Kompose <code>extension.ts</code> example</h2></summary>
  
  ### extension.ts

  ```ts
 import * as podmanDesktopAPI from '@podman-desktop/api';
import * as extensionApi from '@podman-desktop/api';

const KOMPOSE_MENU_COMMAND = 'my.first.command';
const KOMPOSE_WINDOWS = 'kompose-windows-amd64.exe';

export async function activate(extensionContext: podmanDesktopAPI.ExtensionContext): Promise<void> {

  const binaryDisposable = podmanDesktopAPI.binaries.registerGithubBinary(
    'kompose',
    'kubernetes',
    'kompose',
    KOMPOSE_WINDOWS
  );

  extensionContext.subscriptions.push(
    binaryDisposable,
  );

  const binaryInfo: podmanDesktopAPI.BinaryInfo[] = await podmanDesktopAPI.binaries.getBinariesInstalled([binaryDisposable.providerId]);

  if(binaryInfo.length)
  return;

  const statusBarItem = extensionApi.window.createStatusBarItem();
  
  statusBarItem.text = 'Kompose';
  statusBarItem.tooltip = 'Kompose not found on your system, click to download and install it';
  statusBarItem.command = KOMPOSE_MENU_COMMAND;
  statusBarItem.iconClass = 'fa fa-exclamation-triangle';
  statusBarItem.show();
  
  extensionContext.subscriptions.push(
    podmanDesktopAPI.commands.registerCommand(KOMPOSE_MENU_COMMAND, async () => {
      podmanDesktopAPI.binaries.requestInstallOrUpdate(binaryDisposable.providerId).then((value) => {
        if(value)
          statusBarItem.dispose();
      })
      return;
    }),
    statusBarItem,
  );
}
  ```

Here is an example when clicking on the status bar item created by the `kompose` example

image


</details>

**Review by benoitf — COMMENTED** [review]
hello, 

I gave a quick look at the PR.

It's an incredible work. But I would step back about the extensibility pattern.

We need an abstraction between the clients (extensions) and the service provided by Podman Desktop.

so we can't have methods like `registerGithubBinary` 

Why ?

With the extension pattern, the GitHub implementation needs to come from an extension.

So, we can have Github implementation, GitLab, (etc.)

So we register dedicated Providers for handling  (we don't add Octokit in Podman Desktop core)


There is provider part (where we register GitHub handler) and the consumer part (for example Kind extension that can ask for a specific provider like 'GitHub'

to have something more generic, we may ends up providing Uri instead of githubOrganization, githubRepo and assetName
like `github://containers/podman-desktop/...`

We should not have 'BinaryDisposable', it should be Disposable.

For a consumer it would be like `search**(uri)` or `list**(uri)`

For notification we need on*** patterns methods like onUpdate, onSomething

**Comment by axel7083** [comment]
> hello,
> 
> I gave a quick look at the PR.
> 
> It's an incredible work. But I would step back about the extensibility pattern.
> 
> We need an abstraction between the clients (extensions) and the service provided by Podman Desktop.
> 
> so we can't have methods like `registerGithubBinary`
> 
> Why ?
> 
> With the extension pattern, the GitHub implementation needs to come from an extension.
> 
> So, we can have Github implementation, GitLab, (etc.)
> 
> So we register dedicated Providers for handling (we don't add Octokit in Podman Desktop core)
> 
> There is provider part (where we register GitHub handler) and the consumer part (for example Kind extension that can ask for a specific provider like 'GitHub'
> 
> to have something more generic, we may ends up providing Uri instead of githubOrganization, githubRepo and assetName like `github://containers/podman-desktop/...`
> 
> We should not have 'BinaryDisposable', it should be Disposable.
> 
> For a consumer it would be like `search**(uri)` or `list**(uri)`
> 
> For notification we need on*** patterns methods like onUpdate, onSomething

Thanks for the comments and the feedback ! I now understand more the requirements on the extension pattern :) , thanks for clarifications.

I am writing some todos to follow up 

- [x] move the GitHubUpdater from the core to a dedicated extension
- [x] use `uri` identifier instead of providerId in the BinaryRegistry. (I really like this idea it solve so many issues)
- [x] Create an `UpdateProviderRegistry` with unique identifier provided by the client
- [x] When registering a BinaryProvider, client should provide an uri (e.g. `github://`, `gitlab://`, etc.) 
- [x] The `uri` prefix will be used to determined which UpdateProvider will be used.
- [x] Add generic event methods provided by the client (e.g. `postInstall`, `onError`, `onCancel` etc.)
- [x] Update the extension-api.d.ts properly

Feel free to add/changes if you see some scopes missing (this is some big lines)

**Comment by benoitf** [comment]
@axel7083 about changes I think that `extension-api.d.ts` changes are the most important one as once it's there it can't really be changed.

**Comment by axel7083** [comment]
## Extension api
To follow up here are the new api for the extensions provided in the `binaries` namespace.

```ts
export namespace binaries {
    export function registerBinary(provider: BinaryProvider): Disposable;

    export function getBinariesInstalled(providersIds?: string[]): Promise<BinaryInfo[]>;

    export function requestInstallOrUpdate(providerId: string): Promise<boolean>;

    export function registerUpdateProvider(provider: UpdateProvider): Disposable;
  }
```

## Notable changes

- The `providerId` of a BinaryProvider is the uri provided, this allows to keep a unique id even after restart.
- The `UpdateRegistry` use the protocol (E.g. github, gitlab etc.) as a unique identifier. An error is thrown if an extension try to register an existing protocol.

## New extension `update-providers`

As advised by @benoitf I moved out of the core the GithubUpdateProvider, and create an extension, that register it. A new `UpdateProviderRegistry` has been added to allows storing them.

Any extensions can register a new Updater extending the abstract class `UpdateProvider`.

In this PR I am adding the `GithubUpdaterProvider` as an example of implementation. 

## An example of usage with `kompose`

Registering a binary with an existing provider as the GithubupdateProvider is really easy. Here is an example
```ts
export async function activate(extensionContext: podmanDesktopAPI.ExtensionContext): Promise<void> {
podmanDesktopAPI.binaries.registerBinary({
    uri: `github://kubernetes/kompose?assetName=${getAssetName()}`,
    name: 'kompose',
    onInstalled(assetInfo: extensionApi.AssetInfo, destFile: string) {
      // to stuff
    },
    onRemoved() {
      // to stuff
    }
  });
}
```
> Here the `getAssetName` is a function that need to provide the asset name to use (E.g. `kompose-windows-amd64.exe`).

### Full working example

<details>
  <summary><h3>Kompoe <code>extension</code></h3></summary>
  
  ### `extension.ts`
  ```ts
import * as podmanDesktopAPI from '@podman-desktop/api';
import * as extensionApi from '@podman-desktop/api';
import * as os from 'node:os';

const KOMPOSE_MENU_COMMAND = 'my.first.command';

function getAssetName(platform: string, arch: string) {
  switch (platform) {
    case 'win32':
      return 'kompose-windows-amd64.exe';
    case 'linux':
      return `kompose-linux-${arch}`;
    case 'darwin':
      return `kompose-darwin-${arch}`;
  }
}

const URI = `github://kubernetes/kompose?assetName=${getAssetName(os.platform(), os.arch())}`

function showMenu(statusBarItem: podmanDesktopAPI.StatusBarItem) {
  statusBarItem.text = 'Kompose';
  statusBarItem.tooltip = 'Kompose not found on your system, click to download and install it';
  statusBarItem.command = KOMPOSE_MENU_COMMAND;
  statusBarItem.iconClass = 'fa fa-exclamation-triangle';
  statusBarItem.show();
}

function hideMenu(statusBarItem: podmanDesktopAPI.StatusBarItem) {
  statusBarItem.dispose();
}
export async function activate(extensionContext: podmanDesktopAPI.ExtensionContext): Promise<void> {

  let statusBarItem = extensionApi.window.createStatusBarItem();
  podmanDesktopAPI.binaries.registerBinary({
    uri: URI,
    name: 'kompose',
    onInstalled(assetInfo: extensionApi.AssetInfo, destFile: string) {
      hideMenu(statusBarItem);
    },
    onRemoved() {
      showMenu(statusBarItem);
    }
  });

  const binaryInfo: podmanDesktopAPI.BinaryInfo[] = await podmanDesktopAPI.binaries.getBinariesInstalled([URI]);

  if(binaryInfo.length)
    return;
  console.log('kompose binary is not installed.');
  showMenu(statusBarItem);

  extensionContext.subscriptions.push(
    podmanDesktopAPI.commands.registerCommand(KOMPOSE_MENU_COMMAND, async () => {
      podmanDesktopAPI.binaries.requestInstallOrUpdate(URI).then((value) => {
        if(value)
          statusBarItem.dispose();
      })
      return;
    }),
    statusBarItem,
  );
}

  ```
</details>

**Comment by axel7083** [comment]
I included in this PR the update-providers extension with the GitHub provider, but I can remove it and make another PR.

**Comment by axel7083** [comment]
Closing as overlap with existing work

**Pull request closed without merging**
