### PR TITLE
fix: wait until remote side has fully initialized the extensions

### LINKED ISSUE #3196: Pulling of an image does not refresh Images after first podman machine initialization
### Bug description

I do not see the image that was pulled successfully in Images page. This happens on fresh install of podman desktop and podman machine. Workaround is to force refresh (CTRL + R), then it does not happen again.

The same issue was spotted by @xbabalov on her pull image test PR - locally on linux. I have also ecnounter it on Linux, but was not able to reproduce, probably needs proper clean up to reproduce.

### Operating system

Windows 10 Pro, Mac OS 13 Intel, Fedora 37

### Installation Method

Installer from website/GitHub releases

### Version

1.2.0

### Steps to reproduce

0. No previous machine, images, containers are in the test env. 
1. Install of Podman Desktop
2. Installation of podman
3. Initializing of podman machine
4. Starting up the machine (default setup via dashboard)
5. Pull an image -> `quay.io/podman/hello`
6. Press done once it is complete
7. Assert: Image page is shown and there is the `hello` image present
Actual result: No image is present. Cli `podman images` shows the image.

Workaround: CTRL + R.

### Relevant log output

Nothing worth mentioning.
_No response_

### Additional context

This could be duplicate of #2806 or it is related.

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Wait that remote side has finished to init extensions and not at the first run.
Alternative to https://github.com/containers/podman-desktop/pull/3214 that send sometimes twice the events

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/3196

### How to test this PR?

Increase the startup of an extension like podman

in extension.ts of podman, do
```ts
 export async function activate(extensionContext: extensionApi.ExtensionContext): Promise<void> {
+  // delay the activation by 10s
+  await timeout(10000);
```

and check without or with the fix.
Look at the stores (light bulb in status bar) it should contains the right data but it should be fetched only once

Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM. Tested with binary.

Maybe we should have a unit test for the case remote takes several seconds to initialize 😄

**Comment by benoitf** [comment]
@jeffmaury I've added tests

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by lstocchi — APPROVED** [review]
LGTM

**Pull request merged**
