### PR TITLE
chore: settings nav item

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

I tried the same thing for preferences navigation as I did for the main nav bar in PR #3404: a SettingsNavItem component makes PreferencesNavigation far simpler.

Matching the PF styling was relatively straight-forward, but I have changed five things:
- bg-color corrected to match our design: charcoal-700.
- Ditto for selection bg-color: charcoal-300.
- This makes the hover color indistinguishable, so I went with charcoal-500 for now.
- PF sections (e.g. Extensions) are never selected when expanded. IMHO this is a defect and fixed here as per the screen cap.
- PF has an abnormally large right margin on child elements, I reduced this so there is less wrapping (see OpenShift Local in the screen cap).

PF has a nice fa-angle animation when you expand/collapse the section which I haven't tried to replicate, but in my highly-biased opinion that should not hold this PR up.

### Screenshot/screencast of this PR

Before:

Screenshot 2023-08-03 at 2 44 18 PM

After:

Screenshot 2023-08-03 at 2 40 10 PM

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Go to each of the pages in Settings and check for visual regressions.

### CODE REVIEW

**Comment by benoitf** [comment]
Hello, in the previous versions, when we were expanding a tree, it was not becoming highlighted but now it is, I don't know who is the winner ;-)

before:

https://github.com/containers/podman-desktop/assets/436777/924313b6-83cf-43dd-a192-a4b050ccf8b8


after:


https://github.com/containers/podman-desktop/assets/436777/68c99471-45ce-4e71-940c-b427177ebfa7



image


On the hovering, it was picking up a darker colour.
I think I prefer a darker colour than a lighter colour when hovering or when an element is active (also it's already highlighted by the left vertical purple bar) or maybe it's because the difference of colour is too important.

**Comment by deboer-tim** [comment]
As per the first comment, the selection difference when sections are expanded was intentional, this seemed like a bug in PF to me. Either way, the colors match what's in the design now but I plan on leaving this in draft until @mairin returns and is able to confirm or suggest tweaks.

**Comment by mairin** [comment]
I think it depends how closely we want to follow PatternFly. The lighter one with the blue left border is selected, and the one under it with the slightly-lighter-than-the-background-gray background is the hover color.

Screenshot from 2023-08-08 21-30-32

(from https://www.patternfly.org/components/navigation )

I can do a design for an alternative though.

**Comment by mairin** [comment]
Ok, here are some options, you can click through them here (if you log into the upper right, the <> icon will pop up center top and you can inspect for color codes / etc. too.):

https://design.penpot.app/#/view/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=d574d52f-52fe-8081-8002-f3986345fdf5&section=interactions&index=0&share-id=bea72f69-717e-81b4-8002-f39ad32c661b

Let me walk thru them here:

## Option 1

This is the closest to upstream PatternFly, I'm suggesting purple-700 hovers here just for the contrast (but maybe too much.)

Screenshot from 2023-08-10 17-31-55

## Option 2

I think this and all subsequent options use a darker version of the PatternFly active/selected nav styling, which is what Cockpit does as an override to PatternFly's lighter active/selected nav styling.

This option also has inset & rounded charcoal-400 hovers.

Screenshot from 2023-08-10 17-38-20

## Option 3

Same as option 2 with full width / non-rounded hover items in charcoal-500

Screenshot from 2023-08-10 17-39-34

## Option 4

Same as option 3 with purple-700 hover items... I like the full color hover, there's a few apps that do this (including Penpot 😅) and I like the connection it makes between the hover color and the color highlight on the active selection. But again, it may be too much, the charcoal color may suffice fine.

Screenshot from 2023-08-10 17-40-32

## Option 5

This probably draws too much attention on the main nav... but the idea here is the currently active/selected item on the main iconified nav is purple-700, and the secondary settings nav uses the Cockpit-style darkened Patternfly active/selected item style.

Screenshot from 2023-08-10 17-42-37

**Comment by benoitf** [comment]
thanks for the options design @mairin , choice is difficult ! :-)

**Comment by deboer-tim** [comment]
A couple random (and inconsistent :) ) thoughts:
- I usually prefer it when hover is somewhere between the active/selected and default/bg colors, i.e. active > hover > bg. None of these have that... I guess that's ok, but it is throwing me off that active and hover go in opposite directions.
- I like the style of the rounded hover on option 2 - but I also like the purple connection in options 1 and 4 (it's like when you click the purple moves to the left) and I don't think doing both at the same time would work.

**Comment by deboer-tim** [comment]
Rebased on main so that this branch has the new settings on top of the updated main nav.

Added animation when expanding/contracting a section (same look as PF), and updated tests.

I'm moving this from draft to regular PR because IMHO this already has several improvements over what we have today (sections show selection correctly, some colors updated to what's in the design, no PF) and is ready for review; we can still implement one of the options above in another commit, or follow up via a separate PR.

**Review by cdrage — APPROVED** [review]
Awesome work on less PF and there's even tests on this too.

Code change looks good and functionality is there.

LGTM

https://github.com/containers/podman-desktop/assets/6422176/01e4f07d-5f4b-4d43-b804-b0490fd57d24

**Comment by deboer-tim** [comment]
Discussed with Mairin, we'll merge since there already improvements here and can always change hover/selection later.

**Pull request merged**
