### PR TITLE
chore: replace colors by using registry colors in service, task-manager, troubleshooting, and window-control-buttons

### PR DESCRIPTION
**Pull request by SoniaSandler**
Signed-off-by: Sonia Sandler <ssandler@redhat.com>

### What does this PR do?
*Needs to be merged after https://github.com/containers/podman-desktop/pull/9424
Updates any bg- and text- hardcoded colors to use the color registry

Changes to the color registry:
The services have assigned colors in PD, so they also have been added to the registry based on `ServiceColumnType.svelte`:
- ClusterIP - sky[500]
- LoadBalancer - purple[500]
- NodePort - fuschia[600]
- unknown - gray

I have also added `title-hover-bg` so that the circle will be visible when hovering the buttons in the titlebar after changing it to use the color registry

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/9080

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by SoniaSandler** [comment]
@deboer-tim this PR includes new colors in the registry for services, providers, and the titlebar hover bg.
Based on https://github.com/containers/podman-desktop/pull/9420#issuecomment-2423121485, do we want to keep the provider colors hardcoded? and as for the service colors, should I just move them to the badge section?

**Comment by SoniaSandler** [comment]
@deboer-tim I've updated the service colors to have more general names and be in the badge section. lmk if I should keep the providers' colors hardcoded or if having them in the colors registry is ok.

**Comment by deboer-tim** [comment]
I still don't love having three provider colors (podman, docker, Kubernetes) and putting these in the registry; if we did then I think we should at least use the correct colors ourselves vs the palette. This might be a good conversation for the UX call though, maybe I am a minority or someone has a better idea.

IMHO this PR is still too big though, I would recommend to keep splitting out the obvious goodness & cleanup into separate PRs.

**Review by benoitf — APPROVED** [review]

**Review by feloy — APPROVED** [review]

**Comment by SoniaSandler** [comment]
rebased

**Pull request merged**
