### PR TITLE
fix: use ui terminal cols/rows to set container exec instance size

### LINKED ISSUE #3767: terminal's container is reporting a different output
### Bug description

If I execute a local terminal and launch nodejs binary the last line is truncated and it works well

but if I use the embedded terminal of Podman Desktop, the output is becoming broken

### Operating system

macOS Ventura

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Launch a node container in background

1. podman run --rm -it -d node

then, connect with Podman Desktop to the terminal

it should display a root terminal like

```
root@b5e041596fec:/# node
```

Then, type node

```
root@b5e041596fec:/# node
```

You're entering into the node interpreter:

```
Welcome to Node.js v20.5.1.
Type ".help" for more information.
> 
```

and now, enter the work `conso`

you should see output becoming like that

image

then try to end to type the word `console` by adding `l` and `e` keys

and see now the last lines are broken
image

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

Pass terminal size in UI to container exec instance to ensure correct terminal behavior with long lines

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/620330/c12be4ec-bc83-41e6-bed7-8658b32e5348

### What issues does this PR fix or reference?

Fix #3767.

### How to test this PR?

see #3767

### CODE REVIEW

**Comment by cdrage** [comment]
As per call, do we need to update PodsList.svelte as well?

**Comment by dgolovin** [comment]
It seems terminals used to show logs are not affected, it is only an issue for interactive terminals.

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Update err to any

**Review by benoitf — CHANGES_REQUESTED** [review]
It fixes the issue, congrats 🚀  but I noticed that if I increase the height of the window to increase the number of lines and then reduce the height then I no longer see the lines of my terminal


https://github.com/containers/podman-desktop/assets/436777/c8723054-c091-45ca-b5d6-c32da6c84beb

**Comment by dgolovin** [comment]
That is a different issue, not related the fix. I've just pulled latest main and there it is the same problem.

**Comment by benoitf** [comment]
ah ok didn't check with main. I tested changing the size as it was involved here

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
removing my request for changes but the other issue would need to be fixed (can be a separate PR)

**Comment by dgolovin** [comment]
I created new issue https://github.com/containers/podman-desktop/issues/3992 for issue @benoitf discovered during testing

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
