### PR TITLE
Hardcoded colors

### LINKED ISSUE #9080: Hardcoded colors values
### Bug description

There are remaining hard-coded colors values in svelte templates:

```
% grep -rl 'bg-[^[].*[0-9]00' packages/renderer/**/*.svelte      
```
- [x] packages/renderer/src/lib/dialogs/CustomPick.svelte
- [x] packages/renderer/src/lib/task-manager/TaskManager.svelte
- [x] packages/renderer/src/lib/ui/Badge.svelte
- [x] packages/renderer/src/lib/ui/ProviderInfoCircle.svelte
- [x] packages/renderer/src/lib/carousel/CarouselTest.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderInstalled.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderNotInstalled.svelte
- [x] packages/renderer/src/lib/dialogs/CommandPalette.svelte
- [x] packages/renderer/src/lib/dialogs/QuickPickInput.svelte
- [x] packages/renderer/src/lib/extensions/CatalogExtension.svelte
- [x] packages/renderer/src/lib/extensions/ExtensionBadge.svelte
- [x] packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte
- [x] packages/renderer/src/lib/image/PushImageModal.svelte
- [x] packages/renderer/src/lib/pod/KubernetesTerminalBrowser.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesProviderInstallationModal.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/EnumItem.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/FloatNumberItem.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/SliderItem.svelte
- [x] packages/renderer/src/lib/recommendation/ExtensionBanner.svelte
- [x] packages/renderer/src/lib/task-manager/ProgressBar.svelte
- [x] packages/renderer/src/lib/ui/AuditMessageBox.svelte
- [x] packages/renderer/src/lib/ui/ConnectionStatus.svelte
- [x] packages/renderer/src/lib/ui/ExtensionStatus.svelte
- [x] packages/renderer/src/lib/ui/ProviderInfo.svelte
- [x] packages/renderer/src/lib/window-control-buttons/LinuxControlButton.svelte

```
% grep -rl 'text-[^[].*[0-9]00' packages/renderer/**/*.svelte 
```

- [x] packages/renderer/src/lib/dialogs/CustomPick.svelte
- [x] packages/renderer/src/lib/dialogs/QuickPickInput.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesCliTool.svelte
- [x] packages/renderer/src/lib/ui/ProviderResultPage.svelte
- [x] packages/renderer/src/lib/toast/ToastCustomUi.svelte
- [x] packages/renderer/src/lib/configmaps-secrets/ConfigMapDetails.svelte
- [x] packages/renderer/src/lib/configmaps-secrets/ConfigMapDetailsSummary.svelte
- [x] packages/renderer/src/lib/configmaps-secrets/SecretDetails.svelte
- [x] packages/renderer/src/lib/configmaps-secrets/SecretDetailsSummary.svelte
- [x] packages/renderer/src/lib/container/ContainerColumnNameContainer.svelte
- [x] packages/renderer/src/lib/container/ContainerDetails.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderConfigured.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderConfiguring.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderInstalled.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderNotInstalled.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderReady.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderStarting.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderWarnings.svelte
- [x] packages/renderer/src/lib/deployments/DeploymentDetailsSummary.svelte
- [x] packages/renderer/src/lib/dialogs/CommandPalette.svelte
- [x] packages/renderer/src/lib/extensions/CatalogExtension.svelte
- [x] packages/renderer/src/lib/extensions/ExtensionBadge.svelte
- [x] packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte
- [x] packages/renderer/src/lib/featured/FeaturedExtension.svelte
- [x] packages/renderer/src/lib/feedback/SendFeedback.svelte
- [x] packages/renderer/src/lib/image/PullImage.svelte
- [x] packages/renderer/src/lib/image/PushImageModal.svelte
- [x] packages/renderer/src/lib/image/RecommendedRegistry.svelte
- [x] packages/renderer/src/lib/ingresses-routes/IngressDetails.svelte
- [x] packages/renderer/src/lib/ingresses-routes/IngressRouteDetailsSummary.svelte
- [x] packages/renderer/src/lib/ingresses-routes/RouteDetails.svelte
- [x] packages/renderer/src/lib/kube/KubeDetailsSummary.svelte
- [x] packages/renderer/src/lib/kube/KubePodDetailsSummary.svelte
- [x] packages/renderer/src/lib/node/NodeDetailsSummary.svelte
- [x] packages/renderer/src/lib/onboarding/OnboardingComponent.svelte
- [x] packages/renderer/src/lib/pod/KubernetesTerminalBrowser.svelte
- [x] packages/renderer/src/lib/pod/PodDetails.svelte
- [x] packages/renderer/src/lib/pod/PodDetailsSummary.svelte
- [x] packages/renderer/src/lib/pod/PodmanPodDetailsSummary.svelte
- [x] packages/renderer/src/lib/preferences/ExtensionIcon.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesProviderInstallationModal.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesProviderRendering.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesProxiesRendering.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesRenderingItem.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/EditableItem.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/FloatNumberItem.svelte
- [x] packages/renderer/src/lib/pvc/PVCDetails.svelte
- [x] packages/renderer/src/lib/pvc/PVCDetailsSummary.svelte
- [x] packages/renderer/src/lib/service/ServiceColumnType.svelte
- [x] packages/renderer/src/lib/service/ServiceDetails.svelte
- [x] packages/renderer/src/lib/service/ServiceDetailsSummary.svelte
- [x] packages/renderer/src/lib/troubleshooting/TroubleshootingPageStoreDetails.svelte
- [x] packages/renderer/src/lib/ui/AuditMessageBox.svelte
- [x] packages/renderer/src/lib/ui/ConnectionErrorInfoButton.svelte
- [x] packages/renderer/src/lib/ui/ConnectionStatus.svelte
- [x] packages/renderer/src/lib/ui/ExtensionStatus.svelte
- [x] packages/renderer/src/lib/ui/PasswordInput.svelte
- [x] packages/renderer/src/lib/ui/StatusDot.svelte
- [x] packages/renderer/src/lib/window-control-buttons/LinuxControlButton.svelte

### Operating system

mac

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SoniaSandler**
### What does this PR do?
(Will be split into multiple PR, no need to review this one)
Updates any bg- and text- hardcoded colors to use the color registry

### What issues does this PR fix or reference?
Closes https://github.com/containers/podman-desktop/issues/9080

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by deboer-tim** [comment]
This is great work, but I'm really hoping you break this up into several areas/PRs to make review & merging easier. 🙂

**Comment by SoniaSandler** [comment]
@deboer-tim I'll do it, I just followed Philippe's list, so it's a lot :sweat_smile:.
I'm not sure what to do about:
- packages/renderer/src/lib/dialogs/CommandPalette.svelte
- packages/renderer/src/lib/dialogs/CustomPick.svelte
- packages/renderer/src/lib/dialogs/QuickPickInput.svelte
since I can't find how to view the components. Is there a way to do it?

**Comment by benoitf** [comment]
>packages/renderer/src/lib/dialogs/CommandPalette.svelte

press F1 key

**Comment by benoitf** [comment]
>packages/renderer/src/lib/dialogs/QuickPickInput.svelte

click in bottom left on 'the kubernetes context'

**Pull request closed without merging**
