### PR TITLE
chore: cleanup names of commands of Podman extension

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Use Pascal case for title of commands (Podman vs podman)

### What issues does this PR fix or reference?

#4011

### CODE REVIEW

**Review by deboer-tim — APPROVED** [review]
+1 for this fix, but I'm wondering: if we think the prefix is important, should we automatically prefix it in core instead of requiring/assuming that all extensions will do this consistently?

**Comment by benoitf** [comment]
it's just a pattern/best practice but extensions are free to use any title they want

like I don't know extension is named 'k8s' but you want to display 'Kubernetes' instead or you want to display a fully different name

**Comment by deboer-tim** [comment]
> it's just a pattern/best practice but extensions are free to use any title they want
> 
> like I don't know extension is named 'k8s' but you want to display 'Kubernetes' instead or you want to display a fully different name

Yeah, I'm good with this for now. 👍🏼
FWIW I checked VS Code and it prefixes a category, maybe we'll need to do something like this to split it up in the future, e.g.:
```
{
  "title": "Toggle Watch Mode",
  "command": "vitest.toggleWatching",
  "category": "Vitest"
}
```

**Comment by benoitf** [comment]
yes it's like step 2

**Review by lstocchi — APPROVED** [review]

**Review by cdrage — APPROVED** [review]

**Comment by benoitf** [comment]
filed https://github.com/containers/podman-desktop/issues/4106

**Pull request merged**
