### PR TITLE
Fix: Icon

### PR DESCRIPTION
**Pull request by rdwz**
- Trim unnecessary whitespace
- Minify file with [SVGO](https://zkrew.red/svgomfg/)

### CODE REVIEW

**Comment by rdwz** [comment]
[#532](https://github.com/containers/podman-desktop/issues/532)

**Comment by benoitf** [comment]
thanks for the PR @redwerkz

**Comment by benoitf** [comment]
@redwerkz AFAIK the svg file is not used directly, it's the source for .png or .icns file so probably for windows the icon.png should be updated (for macOS it's using icns file)

**Comment by rdwz** [comment]
I somehow messed this up and opened another pr: [#636](https://github.com/containers/podman-desktop/pull/636)

**Pull request closed without merging**
