### PR TITLE
fix: Trim images being pulled

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Minor fixes:
- If extension or image to be pulled (image, extension, or docker extension) contains only whitespace it should still be marked as invalid (button not enabled).
- Trim image pull (to match others) so that extraneous whitespace doesn't cause pull failures.
- Couldn't help myself, fixed Docker extension input field rounding and background to match the other pages.

### Screenshot/screencast of this PR

N/A, only minor change to docker extension input field.

### What issues does this PR fix or reference?

Fixes issue #2227.

### How to test this PR?

Test input fields in all three place, making sure if there is only whitespace the buttons aren't enabled. Try pulling an image like "registry.access.redhat.com/ubi8/ubi-minimal:latest ".

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

Would be good to have a unit test

**Review by cdrage — APPROVED** [review]
LGTM! Was able to use the test scenario and wasn't able to get an error. Code LGTM too.

**Comment by cdrage** [comment]
Rereview: Tests are failing :( but code still LGTM / implementation still works.

**Comment by deboer-tim** [comment]
Tests relied on one change from another branch. Once that was merged they are passing, so merging now.

**Pull request merged**
