### PR TITLE
chore: change font spacing and font weight

### PR DESCRIPTION
**Pull request by cdrage**
chore: change font spacing and font weight

### What does this PR do?

Changes the font spacing and font weight for the index page.

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop-internal/issues/376

### How to test this PR?

Preview the website

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
seeing the update, I feel that now it's too much collapsed to the top but I have the feeling that in the PR it's too far away from the top

I might not see the download button by default

image


even if we remove the text 'Podman Desktop' and reduce the text (from the other PR)

**Comment by benoitf** [comment]
might be another follow-up improvement, to move the download button to be either on the left or right of the text description

**Comment by cdrage** [comment]
> seeing the update, I feel that now it's too much collapsed to the top but I have the feeling that now it's too far away from the top
> 
> I might not see the download button by default
> 
> image
> 
> even if we remove the text 'Podman Desktop' and reduce the text (from the other PR)

I had the same thoughts too but just followed the penpot :( because of the banner it is too "far away" from it.

**Comment by MariaLeonova** [comment]
Couple of thoughts. The AI Lab banner was supposed to go away after the CNCF announcement, so that could potentially free up some space. 

Otherwise, let's think what can be done in this case:
- make text shorter, as proposed, both for the title text and description 
- make the font smaller
- if that doesn't help, adjust the spacing top and bottom, so the button fits on the screen
- also we could swap the description (`Podman Desktop is the best free and open source tool to work with Containers and Kubernetes for developers. Get an intuitive and user-friendly interface to effortlessly bridge the gap between local development and Kubernetes clusters. Build, manage, and deploy everywhere with ease from a single tool`.) with the download button, so that the button comes first
- @cdrage can you please define the screen size that we are addressing here, so I can make the changes to the mock accordingly. What would be the screen height in pixels? 

Here's a quote from google: `In 2024, common screen resolutions for desktops include 1920 x 1080, 1366 x 768, and 1536 x 864. `
So shall we say 768 will be the smallest?

**Comment by cdrage** [comment]
> Couple of thoughts. The AI Lab banner was supposed to go away after the CNCF announcement, so that could potentially free up some space.
> 
> Otherwise, let's think what can be done in this case:
> 
> * make text shorter, as proposed, both for the title text and description
> * make the font smaller
> * if that doesn't help, adjust the spacing top and bottom, so the button fits on the screen
> * also we could swap the description (`Podman Desktop is the best free and open source tool to work with Containers and Kubernetes for developers. Get an intuitive and user-friendly interface to effortlessly bridge the gap between local development and Kubernetes clusters. Build, manage, and deploy everywhere with ease from a single tool`.) with the download button, so that the button comes first
> * @cdrage can you please define the screen size that we are addressing here, so I can make the changes to the mock accordingly. What would be the screen height in pixels?
> 
> Here's a quote from google: `In 2024, common screen resolutions for desktops include 1920 x 1080, 1366 x 768, and 1536 x 864. ` So shall we say 768 will be the smallest?

Text change is in the PR https://github.com/podman-desktop/podman-desktop/pull/10034 I cannot change the text in this PR, so please comment there :)

~I'll reduce the font size slightly and spacing.~

Let's see how it looks after AI banner is removed! I'll put this PR on draft.

**Comment by cdrage** [comment]
Ready for another review (this has been rebased on #10056 )
Screenshot 2024-11-25 at 9 15 29 AM

**Comment by slemeur** [comment]
+1 for the spacing

**Review by jeffmaury — COMMENTED** [review]
The banner has been removed but as a result the title/description is now lower in the page is that on purpose

**Comment by cdrage** [comment]
> The banner has been removed but as a result the title/description is now lower in the page is that on purpose

Yup, it's the same amount of pixels spacing as the mock ups by @MariaLeonova and I talked / reviewed it together too.

**Review by slemeur — APPROVED** [review]
LGTM

**Review by Firewall — APPROVED** [review]

**Comment by benoitf** [comment]
not sure to understand how this PR is approved 

This PR includes a dependency from another PR
(the removal of the banner from another PR)
but this other PR being 'on hold'
https://github.com/podman-desktop/podman-desktop/pull/10056#issuecomment-2506148320

so ?

**Comment by slemeur** [comment]
I don't think this PR should be rebased on #10056. It should be based on the current state, as it was in the first screenshots. 
The screenshot [here](https://github.com/podman-desktop/podman-desktop/pull/10035#issuecomment-2498143951) includes the removal of the AI Lab banner, which should be done in a later time.

To me this PR should be merged without the change with the AI Lab banner.

The challenge with the position of the download button being something which can be improved with the changes on the text: https://github.com/podman-desktop/podman-desktop/pull/10034

**Comment by cdrage** [comment]
> not sure to understand how this PR is approved
> 
> This PR includes a dependency from another PR (the removal of the banner from another PR) but this other PR being 'on hold' [#10056 (comment)](https://github.com/podman-desktop/podman-desktop/pull/10056#issuecomment-2506148320)
> 
> so ?

This was rebased against the banner removed since all the mockups were based on the banner not being there, so that's what I followed. 

I'll put this on draft until I sync up with @MariaLeonova what spacing I should use with the banner still there.

**Comment by MariaLeonova** [comment]
> > not sure to understand how this PR is approved
> > This PR includes a dependency from another PR (the removal of the banner from another PR) but this other PR being 'on hold' [#10056 (comment)](https://github.com/podman-desktop/podman-desktop/pull/10056#issuecomment-2506148320)
> > so ?
> 
> This was rebased against the banner removed since all the mockups were based on the banner not being there, so that's what I followed.
> 
> I'll put this on draft until I sync up with @MariaLeonova what spacing I should use with the banner still there.

@cdrage can you please upload the latest screenshot?

**Comment by cdrage** [comment]
> > > not sure to understand how this PR is approved
> > > This PR includes a dependency from another PR (the removal of the banner from another PR) but this other PR being 'on hold' [#10056 (comment)](https://github.com/podman-desktop/podman-desktop/pull/10056#issuecomment-2506148320)
> > > so ?
> > 
> > 
> > This was rebased against the banner removed since all the mockups were based on the banner not being there, so that's what I followed.
> > I'll put this on draft until I sync up with @MariaLeonova what spacing I should use with the banner still there.
> 
> @cdrage can you please upload the latest screenshot?

Here's the screenshot!
Screenshot 2024-12-02 at 8 48 22 AM

**Comment by MariaLeonova** [comment]
> > > > not sure to understand how this PR is approved
> > > > This PR includes a dependency from another PR (the removal of the banner from another PR) but this other PR being 'on hold' [#10056 (comment)](https://github.com/podman-desktop/podman-desktop/pull/10056#issuecomment-2506148320)
> > > > so ?
> > > 
> > > 
> > > This was rebased against the banner removed since all the mockups were based on the banner not being there, so that's what I followed.
> > > I'll put this on draft until I sync up with @MariaLeonova what spacing I should use with the banner still there.
> > 
> > 
> > @cdrage can you please upload the latest screenshot?
> 
> Here's the screenshot! Screenshot 2024-12-02 at 8 48 22 AM

Thank you! It looks good on my side. In any case, the spacing can be slightly reduced (yellow arrows) - would you need the exact pixel size? 

Screenshot 2024-12-02 at 14 57 38

**Comment by cdrage** [comment]
> > > > > not sure to understand how this PR is approved
> > > > > This PR includes a dependency from another PR (the removal of the banner from another PR) but this other PR being 'on hold' [#10056 (comment)](https://github.com/podman-desktop/podman-desktop/pull/10056#issuecomment-2506148320)
> > > > > so ?
> > > > 
> > > > 
> > > > This was rebased against the banner removed since all the mockups were based on the banner not being there, so that's what I followed.
> > > > I'll put this on draft until I sync up with @MariaLeonova what spacing I should use with the banner still there.
> > > 
> > > 
> > > @cdrage can you please upload the latest screenshot?
> > 
> > 
> > Here's the screenshot! Screenshot 2024-12-02 at 8 48 22 AM
> 
> Thank you! It looks good on my side. In any case, the spacing can be slightly reduced (yellow arrows) - would you need the exact pixel size?
> 
> Screenshot 2024-12-02 at 14 57 38

That'd be awesome! Let me know the pixel size and I can add it to this PR + we can merge this in :)

**Comment by cdrage** [comment]
Changed to 80px as per slack convo

**Comment by slemeur** [comment]
checked on netlify, LGTM

**Pull request merged**
