### PR TITLE
chore(ci): include parallel all e2e tests on PR check

### PR DESCRIPTION
**Pull request by odockal**
### What does this PR do?
Runs all e2e tests on PR check. This workflow should be non-blocking.
### What issues does this PR fix or reference?
#6494 

### How to test this PR?
On your own fork only.

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by odockal** [comment]
I am thinking about adding `needs` keyword into `e2e-tests` to depend on smoke job since it would run only if smoke has passed.

**Comment by cbr7** [comment]
I'm not seeing the step being run in the pr-check on here.

**Review by cbr7 — APPROVED** [review]

**Comment by odockal** [comment]
@benoitf @cbr7 after discussion I am reverting the need for smoke-e2e for e2e tests. This way it will be faster as it can run in parallel and it would also show us possible flakiness of the tests if one passes and other not.

**Comment by benoitf** [comment]
how long does it take ?
also what's the value in running the smoke tests if we run all the tests ?

**Comment by benoitf** [comment]
I see 5mn for smoke and 7mn for all the tests so should we drop smoke tests ?

**Comment by odockal** [comment]
@benoitf Initial idea was to know if there is something broken besides the core functionality. 

In this particular case, e2e tests differ in a way that they also test extensions installation (dev sandbox and openshift local) and some basic registry handling (where we do not have secrets available so no real adding of the registries). 

Now, what is core functionality that needs to be always passing was denoted as smoke tests. The rest is like all-tests. If we want to distinguish or not, is good question.

**Comment by jeffmaury** [comment]
@odockal this PR is almost 2 monthes old. What is the status ?

**Comment by benoitf** [comment]
closing as no activity

**Pull request closed without merging**
