### PR TITLE
docs: changes to writing an extension

### PR DESCRIPTION
**Pull request by timheuer**
### What does this PR do?
In reading the docs on creating an extension for Podman Desktop I found the doc itself not complete. While pointers to the extensions repo helped, the doc should read complete as well.

This PR makes suggestions as a user who approached the doc and found missing items.  I'd also actually recommend the repo contain this sample extension as a complete example so that you can just clone a working example (that is verified).

### How to test this PR?
Docs only.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
thanks @timheuer 🦭

**Comment by benoitf** [comment]
if you could add the SignedOff so I could merge the commit

**Comment by benoitf** [comment]
FYI https://github.com/containers/podman-desktop/pull/6715/checks?check_run_id=23582864386

**Comment by benoitf** [comment]
it looks the files are unformatted (`yarn format:fix` from the root folder) but I could apply it, but I can't SignOff on your behalf :-)

**Comment by timheuer** [comment]
SignedOff

**Pull request merged**
