### PR TITLE
Compose settings card text rewording

### PR DESCRIPTION
**Pull request by mairin**
### What does this PR do?
Adjusts the text on the compose card on Settings > Resources to give more clarity on how to use the tool and point to docs for more info.

### Screenshot/screencast of this PR

Screenshot from 2023-10-26 19-30-52

### What issues does this PR fix or reference?

helps with #4462

### How to test this PR?

Check the settings > resources compose card text. If it doesn't look like screenshot it's the old text.

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Seems messed up with other commits (1.5.0...)

**Comment by mairin** [comment]
> Seems messed up with other commits (1.5.0...)

I based it on the 1.5.x branch bc I wasnt sure what base to use. And it pulled in the other commits. What base should I use?

**Comment by benoitf** [comment]
ok I've changed the target of the PR to be 1.5.x

**Comment by mairin** [comment]
@benoitf oh thanks!!! i went with the default PR settings and i bet it picked the wrong branch, thank you for fixing!!

**Review by jeffmaury — CHANGES_REQUESTED** [review]
LGTM but DCO is missing

**Comment by benoitf** [comment]
@jeffmaury I fixed DCO, should be all ✅

**Review by cdrage — APPROVED** [review]

**Comment by benoitf** [comment]
ping @jeffmaury

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
