### PR TITLE
chore: migrate StatusIcon to ui library

### LINKED ISSUE #7899: Migrate `StatusIcon` to the UI library
### Is your feature request related to a problem? Please describe

AI-Lab still has its own implementation of the StatusIcon component, and should uses the one from podman-desktop as it is just a copy 

### Describe the solution you'd like

Avoid https://github.com/containers/podman-desktop-extension-ai-lab/issues/1271

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Moving the `StatusIcon` ui component to ui package as used by extensions with webview.

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/7899
Required for https://github.com/containers/podman-desktop-extension-ai-lab/issues/1271

### How to test this PR?

- Pipeline should be ✅

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
I thought you brought icons to `/icons` namespace

**Review by benoitf — COMMENTED** [review]
the naming maybe is causing issues

because we do have icons that are just svg file and this one being a component but they do have all the same name pattern

mynameIcon

**Comment by axel7083** [comment]
> I thought you brought icons to `/icons` namespace

It is not an icon, but a component with some logic, therefore I don't think it should go into the /icons namespace

> the naming maybe is causing issues
>because we do have icons that are just svg file and this one being a component but they do have all the same name pattern
> mynameIcon

Locally I added the export in the dist folder instead of packages/ui/src/index.ts...

**Review by benoitf — APPROVED** [review]
I still don't know if we should not pickup another name to not let think it's an 'icon' but anyway it's a move and the component is already named like that

**Review by feloy — APPROVED** [review]

**Pull request merged**
