### PR TITLE
fix: change defaults for Podman machine

### LINKED ISSUE #3047: Default podman-machine creation (rootful, 2CPUs, 4GB RAM)
Rootful required because of Kind on WSL2
2CPUS because 1 seems not enough depending of the workloads
4GB required as 2GB may cause errors if running a Kind cluster

Make sure the same default are also contributed to podman-machine.

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #3047

### What does this PR do?

Changes the defaults when creating a new podman machine

### What issues does this PR fix or reference?

Fixes #3047 

### How to test this PR?

Create a new Podman machine and see the results

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
don't know if documentation is impacted ?

**Comment by afbjorklund** [comment]
You might want to consider having 4.000 GB as the default, instead of 4.096 GB ?

* https://github.com/containers/podman-desktop/issues/3062

Another approach would be to use an even 4 GiB instead, that is: 4294967296 bytes.

`"default": 4096000000,`

**Comment by jeffmaury** [comment]
> You might want to consider having 4.000 GB as the default, instead of 4.096 GB ?
> 
>     * [Size units wrongly processed #3062](https://github.com/containers/podman-desktop/issues/3062)
> 
> 
> Another approach would be to use an even 4 GiB instead, that is: 4294967296 bytes.
> 
> `"default": 4096000000,`

I think as we display quantities as MB or GB, I think the default should be 2000000000 (changed to 4000000000)

**Comment by afbjorklund** [comment]
> I think as we display quantities as MB or GB, I think the default should be 2000000000 (changed to 4000000000)

As long as you have different defaults compared to `podman machine` CLI, that makes sense (simpler GUI sliders)

The scale factor needs to be change accordingly, so that it gets the right number of MiB to use  (1907.3486328125).

The `init` default has 2147483648 bytes (2.000GiB), which is presented to the user by `list` as "2.147GB"

**Review by cdrage — APPROVED** [review]

**Pull request merged**
