### PR TITLE
docs: simplified _Onboarding_ navigation

### LINKED ISSUE #4268: docs: simplify onboarding navigation
### Is your enhancement related to a problem? Please describe

The 3 levels navigation to access "Onboarding for  containers" and "Onboarding for Kubernetes" is too complex.

```
├── onboarding
│   ├── containers
│   └── kubernetes
│       ├── developer-sandbox
│       ├── existing-kubernetes
│       ├── kind
│       ├── lima
│       ├── minikube
│       └── openshift-local
```

### Describe the solution you'd like

Simplify by using a 2 levels navigation:

```
├── onboarding-for-containers
└── onboarding-for-kubernetes
    ├── developer-sandbox
    ├── existing-kubernetes
    ├── kind
    ├── lima
    ├── minikube
    └── openshift-local
```

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by themr0c**
### What does this PR do?

Simplified _Onboarding for containers_ and _Onboarding for Kubernetes_ navigation.

These two section become first level section (rather than onboarding/containers and onboarding/kubernetes).

### Screenshot/screencast of this PR
Screenshot_20231011_165512

### What issues does this PR fix or reference?

fixes #4268

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by themr0c** [comment]
Thank you @benoitf !

**Comment by deboer-tim** [comment]
I see this merged and a deploy of gh-pages branch, but on podman-desktop.io I'm still seeing the previous nav even after clearing the cache and reloading 5h later. I didn't think there was any delay - any idea why I'm not seeing this yet?

**Comment by benoitf** [comment]
@deboer-tim you can check deployments at https://github.com/containers/podman-desktop/actions/runs/6484731641/attempts/1

I've restarted the job and it succeeded

**Comment by deboer-tim** [comment]
👍🏼 thanks

**Pull request merged**
