### PR TITLE
feat(feedback): adding support to get sys info

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Backend part of https://github.com/podman-desktop/podman-desktop/issues/9585.

The goal is to have a `include my system information`

image

That will prefill the GitHub bug issue with the system info.

(not included in this PR, only backend)

image

### Sidenote

Getting a short and usable system information through the node api is very annoying actually, depending on the platform we do not get the same information.

I added documentation above each function to precise how, and why we use certain node:os function for each platform.

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
instead of having the pattern:
```
getDarwinInfo()
   if (!isMac) { error}
   return

getLinuxInfo()
   if (!isInfo) { error}
   return

```

Use the following pattern

``` 
 
 if (isLinux()) {
   this.grabInfo = new LinuxGrabInfo();
 } else if (isDarwin()) {
  this.grabInfo = new DarwinGrabInfo();
  
  
  
 getOsInfo(): string {
    return this.grabInfo.getInfo()
}

**Comment by axel7083** [comment]
> instead of having the pattern:
> ...
> Use the following pattern
> ...

Yes sure! Updated

**Comment by benoitf** [comment]
hmm it's not really what I asked, everything here is in the same file, you can still internally call the other protected methods which is not expected.

you need to instantiate once the specific object/class, then, all callers can call the method, and they'll never be able to call another method that they should not be able to call

Also splitting across multiple chunks: you import only what you need, you have test only for a subpart, etc.

**Comment by axel7083** [comment]
Oh yeah, this is not what I understood sorry, will fix

**Review by benoitf — APPROVED** [review]
thanks, it's much more robust 👍

**Pull request merged**
