### PR TITLE
fix: mark task completed if there's a failure

### LINKED ISSUE #2587: Podman machine start failed but still running
### Bug description

When a Podman machine fails to start the task is left in a running state, which means it stays around forever and can't be cleared.

Screenshot 2023-05-22 at 9 42 00 AM

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

If there's a failure (e.g.) creating a Podman machine, the task is never marked complete and so it stays running forever and can't be removed from the Tasks list. This just marks it as complete in this path.

### Screenshot/screencast of this PR

A task run before (top) and after (bottom) this change. Clicking clear will only remove the bottom one:
Screenshot 2023-06-26 at 3 36 04 PM

### What issues does this PR fix or reference?

Fixes #2587.

### How to test this PR?

Any failure to create a provider instance will do, but the easiest is to create two Podman machines, start one, then try to start the other.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
probably easy to handle in a unit test

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by lstocchi — COMMENTED** [review]
Should this also be applied here https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/image/build-image-task.ts#L161 ?

**Comment by benoitf** [comment]
@deboer-tim wanting to fix in the other file or merge ?

**Comment by deboer-tim** [comment]
Sorry for delay. I confirmed failed build tasks never end either, and the same fix works. Second commit pushed.

**Pull request merged**
