### PR TITLE
chore(ui): navbar issue

### LINKED ISSUE #1313: Toggling settings page is moving UI elements
### Is your enhancement related to a problem? Please describe

When I click on settings/exit settings navbar item height is changing
Also the size of the left sidebar is also changing

https://user-images.githubusercontent.com/436777/215866333-3129974c-c2f0-4cb0-a8ad-0e15c5683047.mp4

### Describe the solution you'd like

Fixes UI glitches with width/height moving

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xbabalov**
### What does this PR do?

Edits the preference navigation bar looks so it corresponds with the main navigation bar.

### Screenshot/screencast of this PR

Peek 2023-03-08 10-01

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/1313

### How to test this PR?

run yarn watch and toggle the bar to see the difference

### CODE REVIEW

**Comment by benoitf** [comment]
@xbabalov could you add sign your commit with SignedOff

**Comment by benoitf** [comment]
@xbabalov so we can have DCO check being ✅

**Comment by xbabalov** [comment]
> @xbabalov could you add sign your commit with SignedOff

I did, thank you for the reminder

**Review by benoitf — APPROVED** [review]

**Review by benoitf — CHANGES_REQUESTED** [review]
it seems it doesn't work when we're reducing the window


https://user-images.githubusercontent.com/436777/223725196-9713e70a-c5a9-42c1-9d55-400074896789.mp4

**Comment by xbabalov** [comment]
> 

So we dont want it to be collapsible like the main navigation bar? Should it stay the same width when we reduce the window?

**Comment by benoitf** [comment]
@xbabalov as there are no icons, probably that it can't hide in the same way than the main navbar.
if we want to have a full hide probably we need to see a kebab menu or another stuff to toggle the navbar width

**Comment by xbabalov** [comment]
@benoitf I fixed it so it's entirely non-collapsible and keeps it's width and style. Maybe it would be desirable to create a separate issue if we want to make it collapsible in a different specific way?

Peek 2023-03-29 21-27

**Comment by deboer-tim** [comment]
I noticed another issue when it collapses (and there are no icons here) so IMHO this works well.

**Review by benoitf — APPROVED** [review]
nice enhancement
thanks @xbabalov

**Pull request merged**
