### PR TITLE
docs: add mermaid diagrams

### LINKED ISSUE #3706: Website: We should have diagrams
### Is your enhancement related to a problem? Please describe

Implement mermaid as requested by @themr0c so we can have diagrams.

### Describe the solution you'd like

Mermaid.js added.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
docs: add mermaid diagrams

### What does this PR do?

Adds mermaid diagrams to be used within the website.

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/6422176/d893c7c8-ae28-4e47-90f6-84547b44b944

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/3706

N/A

### How to test this PR?

Add:

```
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
```

To an example markdown page.

<!-- Please explain steps to reproduce -->

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
As requested by @themr0c

**Review by benoitf — COMMENTED** [review]
I think yarn.lock changes is missing

**Comment by cdrage** [comment]
> I think yarn.lock changes is missing

You're right. It was ignored by mistake! Added.

**Review by benoitf — CHANGES_REQUESTED** [review]
I think there is something wrong in the yarn.lock changes (like trim being updated, etc)

could you revert yarn.lock changes and then run `yarn` command in the root folder and not in the website folder

I think then we should have a better yarn.lock file (most added lines and no replacement lines)

**Review by benoitf — COMMENTED** [review]
request for changes is only for yarn.lock, other changes are 👍

**Comment by cdrage** [comment]
Updated! Reran `yarn` in the main root. It does look like it got messed up.

I did:
1. Added `"@docusaurus/theme-mermaid": "^2.4.1",` to package.json
2. Ran `yarn` in the main folder.

Trim is no longer being updated now. Good catch!

**Review by benoitf — APPROVED** [review]

**Review by themr0c — APPROVED** [review]

**Pull request merged**
