### PR TITLE
feat: Add start on boot and start container engine on launch

### LINKED ISSUE #225: Option to autostart Podman Machine with Windows/macOS Startup
### Is your feature request related to a problem? Please describe

It would be great to have Podman ready to use after Windows startup instead of always having to run `podman machine start` before. Docker Desktop makes Docker ready to use right after system startup.

### Describe the solution you'd like

Autocofigure Windows to run `podman machine start` on Windows startup.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

- Automatically starts Podman Desktop when logging/starting a session on Windows and macOS
- Automatically starts the first podman machine when Podman Desktop is starting. (No machine = no automatic start)

It supports Windows and macOS

note: on macOS, you need to have Podman Desktop in Applications or user Applications folder.
It does not work for development mode as well (macOS or Windows) (when it's started using `yarn start`)

### Screenshot/screencast of this PR

https://user-images.githubusercontent.com/436777/193537580-e453739d-fc89-4803-a1f1-70c91e5c260d.mp4

### What issues does this PR fix or reference?
fixes https://github.com/containers/podman-desktop/issues/225

### How to test this PR?

On Windows: try to see if Podman Desktop is starting automatically on startup (and machine is starting as well)
On macOS: try to see if Podman Desktop is starting automatically on startup (and machine is starting as well)

Turn off/turn on the preferences in the settings page

Change-Id: I6b0f0bc31f3427a41b28dbb87ac620fa1ecbc7b9
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by vzhukovs — APPROVED** [review]

**Comment by kartas39** [comment]
machine is not starting witn Podman desktop in latest version (Windows)

**Comment by slemeur** [comment]
what is your issue @kartas39 ? 
Would you be able to send the logs?
(you'd need to click on the troubleshooting icon, the bulb icon in the bottom right corner)

**Comment by slemeur** [comment]
See this documentation: https://podman-desktop.io/docs/troubleshooting/access-logs

**Comment by kartas39** [comment]
@slemeur the problem is podman machine is not starting with windows boot. Podman desktop does, but not machine. Fresh installed Windows, fresh installed Podman desktop. "podman machine start" works fine
[podman-desktop-20241206101709.zip](https://github.com/user-attachments/files/18035736/podman-desktop-20241206101709.zip)

**Comment by kartas39** [comment]
@slemeur i uninstalled/reinstalled podman and podman desktop - all works now, sorry for false alarm

**Pull request merged**
