### PR TITLE
docs: split troubleshooting page without modifying content

### PR DESCRIPTION
**Pull request by themr0c**
### What does this PR do?

Split the troubleshooting page into smaller sections.

This will enable raising small PR to modify individual sections.

Content unchanged, except for vale errors that block the PR.

### What issues does this PR fix or reference?

refs https://github.com/containers/podman-desktop/issues/3045

### CODE REVIEW

**Comment by themr0c** [comment]
Not touching the content at all was not possible: I had to fix a couple of Vale warnings.

**Review by benoitf — COMMENTED** [review]
I think I already commented in another issue. The problem is that without navigation bar you don't have any pointers to all the troubleshooting page

Like what do do on windows, on Mac on Linux ,etc.

**Comment by themr0c** [comment]
I don't understand. There is a navigation (on the left side).

**Comment by benoitf** [comment]
@themr0c https://github.com/containers/podman-desktop/pull/3091#pullrequestreview-1511700581

As it's an entry page and like the most reached page, I expect to have direct guidance/pointers on what I can find if I'm on Windows or Mac, etc.

**Comment by themr0c** [comment]
Do you mean links to the subpages in the troubleshooting index page?

**Comment by themr0c** [comment]
I believe that's something for a subsequent pull request. I didn't modify anything in the content on purpose. Each piece of content that we have here require consequent rework. Splitting the kilometric page into maintainable chunks is only the first step.

**Review by jeffmaury — APPROVED** [review]
LGTM.

Maybe would be good to have links from the main page to the platform specific pages

**Comment by benoitf** [comment]
> I believe that's something for a subsequent pull request. I didn't modify anything in the content on purpose


You changed the content as people were redirected to a big page and now they're lost as they'll reach a page without having proper indication for what to do. Most of people are coming from Google 

So you removed content from the page that people are seeing before new content is parsed / analyzed by Google

So user experience of all these users is now broken.
They come to a page that doesn't show what they expected to see

**Comment by themr0c** [comment]
We have links already in two places:

1. In the navigation bar (at the left side of the page).
2. **Next** button at the bottom of the content.

Screenshot from 2023-07-13 12-21-57

**Comment by benoitf** [comment]
Did you see my screenshot ?

image


Also on the bottom you only have next section you don't see all items

This page needs to be a landing page if you have problems

So the page itself need to guide you to different pages

It should not be a page saying to use the page of Podman Desktop

**Comment by themr0c** [comment]
Of course, if you intentionally collapse the sidebar, you don't see the navigation. But the sidebar is not collapsed by default. But would it be a sufficient reason to make sidebar not hideable? https://docusaurus.io/docs/sidebar#hideable-sidebar

**Comment by benoitf** [comment]
@themr0c sidebar is also not displayed if your window is not so large

**Pull request merged**
