### PR TITLE
chore(test): refactoring of kubernetes contexts page ARIA labels and unit tests

### PR DESCRIPTION
**Pull request by rostalan**
### What does this PR do?

refactoring of ARIA labels on kubernetes contexts page and its unit tests

### What issues does this PR fix or reference?
run `yarn test:unit`
### How to test this PR?
-

### CODE REVIEW

**Comment by axel7083** [comment]
Linter issues

**Review by odockal — APPROVED** [review]

**Review by cdrage — APPROVED** [review]

**Review by cdrage — DISMISSED** [review]
Looks like tests are failing at the moment due to the aria label change

**Comment by odockal** [comment]
@rostalan -> @cdrage is right, here is the failed unit test: `src/lib/preferences/PreferencesKubernetesContextsRendering.spec.ts > Test that context-name2 is the current context`. I have checked only linux run failure and it was flaky unrelated test, so you need to run unit tests locally and make sure to address changes to the unit tests as well. Also, update description of the PR once it includes changes to the tests. Thanks!

**Comment by rostalan** [comment]
@odockal ok, so I have fixed the file you mentioned, verified the unit tests pass locally, but it still fails on GHA. Could it be the flaky ubuntu test you were talking about?

**Comment by odockal** [comment]
@rostalan Let's see. I have rerun the failed job.

**Review by odockal — APPROVED** [review]

**Pull request merged**
