### PR TITLE
feat: add support for protocol handler 'podman-desktop:'

### LINKED ISSUE #2316: register custom protocol handler for Podman Desktop
### Is your enhancement related to a problem? Please describe

Protocol handler could allow to execute tasks (like installing an extension)

### Describe the solution you'd like

Intercept `podman-desktop:` into Podman Desktop

### Describe alternatives you've considered

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Allow to install extensions with
`open podman-desktop:extension/redhat.openshift-local` For example

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/436777/b11ad1e4-4c2f-455c-957a-01653d2a93c8

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/2316

### How to test this PR?

Open URL like `open podman-desktop:extension/redhat.openshift-local` or `podman-desktop:extension/redhat.redhat-sandbox` or invalid URL like `podman-desktop:extension/my.extension`

Might require to use the binary (not development mode)

### CODE REVIEW

**Comment by jeffmaury** [comment]
On Win11Pro, I did:

- Build the production bits
- Run podman-desktop.exe
- In a Powershell, I ran: `Start-Process podman-desktop:extension/redhat.redhat-sandbox`

Got this error:

image

**Comment by benoitf** [comment]
ok thanks I'll investigate

**Comment by benoitf** [comment]
@jeffmaury could you try again

image

**Comment by jeffmaury** [comment]
> @jeffmaury could you try again
> 
> image

LGTM. Tested on Win11 Pro from Powershell and Firefox. Both are OK

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
