### PR TITLE
fix: don't monitor Docker socket on Windows

### LINKED ISSUE #2559: Plenty of EINVAL errors appearing in the console log on windows
### Bug description

I am seeing a lot of `Unhandled promise rejection warning` errors in the console log. I have podman machine with a rootful connection, kind created. That is all I can say about how to reproduce.

### Operating system

Windows 10

### Version

1.0.0

### Steps to reproduce

1. Podman desktop running (1.3.0-next) and podman installed (4.6)
2. Initialize and start podman machine via dashboard (by default rootless)
3. Watch dev console log for errors.

### Relevant log output

```shell
dex.ts:1327 main ↪️ (node:4620) UnhandledPromiseRejectionWarning: Error: EINVAL: invalid argument, stat '//./pipe/'
(anonymous) @ index.ts:1327
emit @ VM14 sandbox_bundle:2
onMessage @ VM14 sandbox_bundle:2
index.ts:1327 main ↪️ (node:4620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 477)
(anonymous) @ index.ts:1327
emit @ VM14 sandbox_bundle:2
onMessage @ VM14 sandbox_bundle:2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2559

### What does this PR do?

Removes lots of error messages related to Docker socket on Windows

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #2559

### How to test this PR?

Start a Podman machine and check those messages are not here anymore on the console

### CODE REVIEW

**Comment by benoitf** [comment]
@lstocchi if you can check on Windows

if we don't monitor the socket, there is no side issues ?

**Comment by jeffmaury** [comment]
> @lstocchi if you can check on Windows
> 
> if we don't monitor the socket, there is no side issues ?

I don't expect issues as monitoring socket was done through file system watcher which does not work for Windows pipes

**Review by benoitf — APPROVED** [review]

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by odockal** [comment]
LGTM

**Pull request merged**
