### PR TITLE
chore: update to Docusaurus v2.3.0

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Update to v2.3.0

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

dependabot wants to update but is not able to group all component updates in a single update

### How to test this PR?

Check website/documentation

Change-Id: I88af5f26f5a67e4dc984a3f640da08f1a5966427
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by themr0c** [comment]
I receive warnings, is that expected?

```
$ yarn install
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "trim@0.0.3" is incompatible with requested version "trim@0.0.1"
[3/5] Fetching packages...
warning crc@0.0.1: The engine "podman-desktop" appears to be invalid.
warning docker@0.0.1: The engine "podman-desktop" appears to be invalid.
warning kind@0.0.1: The engine "podman-desktop" appears to be invalid.
warning kube-context@0.0.1: The engine "podman-desktop" appears to be invalid.
warning lima@0.0.1: The engine "podman-desktop" appears to be invalid.
warning podman@0.0.1: The engine "podman-desktop" appears to be invalid.
warning registries@0.0.1: The engine "podman-desktop" appears to be invalid.
[4/5] Linking dependencies...
warning " > postcss-import@15.1.0" has unmet peer dependency "postcss@^8.0.0".
warning " > prettier-plugin-svelte@2.9.0" has unmet peer dependency "svelte@^3.2.0".
warning "workspace-aggregator-214b715f-8417-47ef-9b9d-d696b9b014fc > podman > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "workspace-aggregator-214b715f-8417-47ef-9b9d-d696b9b014fc > docs > @docusaurus/core > react-loadable-ssr-addon-v5-slorber@1.0.1" has unmet peer dependency "react-loadable@*".
warning "workspace-aggregator-214b715f-8417-47ef-9b9d-d696b9b014fc > docs > @docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react@3.2.0" has unmet peer dependency "@types/react@>= 16.8.0 < 19.0.0".
warning "workspace-aggregator-214b715f-8417-47ef-9b9d-d696b9b014fc > docs > @docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-preset-algolia@1.7.1" has unmet peer dependency "@algolia/client-search@^4.9.1".
[5/5] Building fresh packages...
Done in 9.64s.

```

**Comment by benoitf** [comment]
yes

**Review by themr0c — APPROVED** [review]
`yarn website:build` and `yarn website:dev` ran fine

**Comment by themr0c** [comment]
Is there a way to make these warnings disappear?

**Comment by benoitf** [comment]
@themr0c all the warnings or a specific category ?

**Pull request merged**
