### PR TITLE
fix: align badges in navigation sidebar (#1327)

### LINKED ISSUE #1327: problem in alignment of badges in the sidebar/navigation bar
### Bug description

the containers badge is not aligned with the other one

image

### Operating system

macOS

### Version

next (development version)

### Steps to reproduce

start enough resources to have all the badges (images, containers, volumes, etc)
then look at the alignment of the containers badge

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR aligns badges in the sidebar

### Screenshot/screencast of this PR

immagine

### What issues does this PR fix or reference?

it fixes #1327 

### How to test this PR?

1. create some resources to have the badges visible
2. look at the badges

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
if possible I would avoid any `!` usage
it often leads to errors

**Comment by lstocchi** [comment]
> if possible I would avoid any `!` usage it often leads to errors

I agree that the !important tag can lead to errors but in this case i guess it would allow to have a cleaner solution. 
Otherwise i need to replicate all rules made by `pf-c-nav__link` class and also some parent (pf-c-nav__item) > child (pf-c-nav__link) rules
immagine


If you still prefer to not use `!` i can move this way though.

**Comment by benoitf** [comment]
@lstocchi 
https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/override.css#L32

you could change to 4px (and then remove all your `!pr-1`

**Comment by lstocchi** [comment]
> @lstocchi https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/override.css#L32
> 
> you could change to 4px (and then remove all your `!pr-1`

This affects everything in the app. Are you sure we don't change some style of some other element that uses the` pf-c-nav` class?

**Comment by benoitf** [comment]
navigation bar is used twice: main page and settings page so it should be easy to check

**Review by benoitf — APPROVED** [review]
image


tested the two navigation bar

**Pull request merged**
