### PR TITLE
feat: display 3rd party contribution to Docker Compatibility page

### LINKED ISSUE #9242: continue the implementation of Docker Compatibility page
### Is your enhancement related to a problem? Please describe

There is an experimental flag to bring this new section

It needs to be completed with the compose part and the podman part (from the mockup it's the sections matching the vertical podman bar in purple)

### Describe the solution you'd like

continue the implementation

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Allow extensions to contribute to the docker compatibility page

### Screenshot / video of UI

https://github.com/user-attachments/assets/844f385e-5489-4768-acbe-d6a4d53fed7b

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/9242

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
LGTM, tested on Windows 11, love the design and implementation, great work conducted 🚀 !

suggestion (non-blocking): could we add a tooltip for the purplish group on the left ? I feel like it would need a bit of info for the user of what it is

image

**Comment by axel7083** [comment]
suggestion (follow-up PR): might be interesting to document the scope/group in https://podman-desktop.io/docs/extensions/developing/config

**Comment by shipsing** [comment]
@benoitf Amazing work! Can i get two screenshots of the Docker Compatibility page? One for macOS and other for Windows.

**Review by gastoner — APPROVED** [review]

**Comment by benoitf** [comment]
rebased as some PR checks were introduced since the review:  smoke e2e tests (production) and  smoke e2e tests (development)

**Pull request merged**
