### PR TITLE
feat: render placeholder text for text and file selection fields

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

Renders placeholder text form configuration property attributes for text and file fields

### Screenshot/screencast of this PR

image

### What issues does this PR fix or reference?

* #2988
* https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/53

### How to test this PR?

NA

### Dependencies

* PR #3391

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
thanks for the smalls PRs

**Review by deboer-tim — APPROVED** [review]
Linter needs a fix, but approving once that's done.

**Comment by dgolovin** [comment]
@deboer-tim it is because I split PR to main/ui parts as @benoitf suggested a while ago.

Restarted the checks after pushing PR for main.

**Comment by benoitf** [comment]
@dgolovin can you trigger the workflow again (force push) (for sonarlint error)

**Pull request merged**
