### PR TITLE
chore: add filtered field to be able to filter tasks

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
allow to filter tasks

depends on 
- [x] https://github.com/podman-desktop/podman-desktop/pull/10194

### What issues does this PR fix or reference?

related to https://github.com/podman-desktop/podman-desktop/issues/9924

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by benoitf** [comment]
pull request rebased as the dependent PR has been merged

**Comment by axel7083** [comment]
src/lib/preferences/PreferencesConnectionDetailsTerminal.spec.ts:202:55 on `pr-check / unit tests / macos-15 (pull_request)` flaky?

**Comment by benoitf** [comment]
yes but not flaky on my computer ^^

**Comment by benoitf** [comment]
I'll try to see if for example, there is a missing waitFor

**Comment by benoitf** [comment]
relaunched the PR check and it's all ✅

**Review by axel7083 — APPROVED** [review]
LGTM

**Pull request merged**
