### PR TITLE
chore(deps-dev): bump svelte-fa from 3.0.4 to 4.0.2

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
we were using as size parameter a pixel value while it was not really planned by the library

now the library enforces specific expected values
converted all px values to default em/x values

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/pull/5555

### How to test this PR?

Ensure that you don't see very big or very small icons in the UI

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
Not sure to have understood the conversion as most seems like custom values so i guess you already checked them.
E.g i see 24px replaced by 1.5x. But shouldn't it be 1.4x?
16 -> 1x
18 -> 1.1
20 -> 1.2
22 -> 1.3
24 -> 1.4

**Comment by benoitf** [comment]
I used a conversion table
https://nekocalc.com/px-to-em-converter

> E.g i see 24px replaced by 1.5x. But shouldn't it be 1.4x?
>16 -> 1x
>18 -> 1.1
>20 -> 1.2
>22 -> 1.3
>24 -> 1.4

1x is 1em = 16px by default

16 * 1.5 = 24

**Review by lstocchi — APPROVED** [review]

**Comment by cdrage** [comment]
FYI this is now causing a white screen on load with the error output:

```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/svelte-fa.js?v=1af1f3ae' does not provide an export named 'Fa' (at LoadingIcon.svelte:3:10)
```

Even after a clean `yarn install` / rm -r node_modules

**Comment by benoitf** [comment]
@cdrage probably an invalid cache, I'm not reproducing on a fresh clone

**Pull request merged**
