### PR TITLE
chore: moving button component to ui package

### LINKED ISSUE #6896: Implement Button UI component

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Moving the `Button` svelte component to the `ui` package. 

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/6896

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

Pipeline should be ✅

### CODE REVIEW

**Comment by benoitf** [comment]
unit tests are failing

**Review by lstocchi — APPROVED** [review]

**Comment by axel7083** [comment]
@benoitf `SonarCloud Code Analysis` is annoyed by the Button.spec.ts file, having too much duplicates, as this is not related to this issue I would like to skip this check

**Review by deboer-tim — APPROVED** [review]
SonarCloud says there is too much duplication in import statements ;-) but I am ok with it.

**Comment by axel7083** [comment]
> SonarCloud says there is too much duplication in import statements ;-) but I am ok with it.

IMO the `*.spec.ts` files should be excluded from the sonardcloud analysis[^1]

[^1]: https://stackoverflow.com/questions/52865737/how-do-i-ignore-duplicated-code-report-in-sonar

**Comment by benoitf** [comment]
sonar cloud is happy now

**Pull request merged**
