### PR TITLE
Use v2 format of insecure registry config

### LINKED ISSUE #3549: Doc: update _Adding an Insecure Registry to Podman Desktop_ to use new configuration file format
Hi,

today I found some time to test this ... and did so on the Podman side (ignoring Podman Desktop for a start).

The new documentation that was added
https://github.com/containers/podman-desktop/commit/b6d1bd77b51d4628bde82037fc78c3a8253c400d#diff-32fcd5d744c9a49f128923566256cc09f1232bf17f3f9e1e114586af2037d21dR46

mentions to add
```
[registries.insecure]
registries = ['example-registry.com']
```

to `/etc/containers/registries.conf`

After I do this, I get an error message:
`Error: loading registries configuration "/etc/containers/registries.conf": mixing sysregistry v1/v2 is not supported`

Reding into this a bit, I think `registries.insecure` is the old way of doing this and 
```
[[registry]]
location = 'foo.bar'
insecure = true`
```
would be better since the rest of the file already uses the new way.

Is this correct or am I missing something here?

_Originally posted by @fschwa in https://github.com/containers/podman-desktop/issues/1653#issuecomment-1660703365_

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

It changes the deprecated config syntax to namespaced config.
Also use example.com domain as it is widely accepted.

### What issues does this PR fix or reference?
This is related to https://github.com/containers/podman-desktop/issues/1653

fixes #3549

### CODE REVIEW

**Comment by ghost** [comment]
Since I was not able to make this work with my registry and do not know what is causing the issue, I do not know, what the correct [[registry]] block would look like. Thus: WIP.

**Comment by cdrage** [comment]
Hi @fschwa we have a weird case of your documentation being correct, but you're also having a different issue in terms of trying to add an insecure registry.

Is it possible for you do any other updates for this PR that may be required and switch it to review status so we can review / merge?

**Comment by ghost** [comment]
> Is it possible for you do any other updates for this PR that may be required and switch it to review status so we can review / merge?

I am not sure what you mean by this. 😅
What do you mean by "required updates"?
How do I switch the PR to review status?

**Review by themr0c — APPROVED** [review]
Nice contribution, thank you!

**Comment by themr0c** [comment]
I currently don't have access to a Windows host to do proper testing, can someone do a proper test? ping @odockal @cdrage.

**Comment by cdrage** [comment]
> > Is it possible for you do any other updates for this PR that may be required and switch it to review status so we can review / merge?
> 
> I am not sure what you mean by this. 😅 What do you mean by "required updates"? How do I switch the PR to review status?

Yup! It was just regarding draft status / switching it to review.


LGTM! I'll approve this.

**Review by cdrage — APPROVED** [review]

**Pull request merged**
