### PR TITLE
chore(tests): add optional param to constructor

### PR DESCRIPTION
**Pull request by cbr7**
### What does this PR do?
Add optional param to Desktop Runner constructor

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/6519

### CODE REVIEW

**Review by odockal — APPROVED** [review]

**Comment by odockal** [comment]
LGTM but we need to refactor this to accept custom settings in the runner as there could be more preferences set, which is not viable to have it done through constructor params but rather settings file itself.

**Review by benoitf — APPROVED** [review]
+1 to @odockal you should probably accept a JSON like object else it won't scale and to avoid to change all calls for each new parameter

**Comment by cbr7** [comment]
@odockal @benoitf created https://github.com/containers/podman-desktop/issues/6524 as a follow up issue to crreate a more general solution

**Comment by odockal** [comment]
@benoitf @cbr7 Yes. That is totally doable. I am also thinking about getting an option to use existing settings.json and merging it with a default/passed configuration.

**Pull request merged**
