### PR TITLE
chore: remove CRC extension from the assembly

### LINKED ISSUE #1685: move CRC extension to its own repository
### Is your feature request related to a problem? Please describe

OpenShift local extension will be provided as a separate extension

it's already in its own repository https://github.com/crc-org/crc-extension

Thus, to avoid to have an old version living in the current podman-desktop repository, we need to remove the embedded one to avoid any conflicts

### Describe the solution you'd like

prune crc code from podman desktop repository

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
it has been moved to a separate repository https://github.com/crc-org/crc-extension

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #1685 

### How to test this PR?

Change-Id: Ib3a0ed0bc81a04cba35575a652e1351270d71793

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
Should we also remove any reference to CRC - extensions/crc from the doc?

**Comment by benoitf** [comment]
the extension is still there (you can install it this is why I kept documentation)

**Review by evidolob — APPROVED** [review]

**Comment by gbraad** [comment]
New location for the extension is: https://github.com/crc-org/crc-extension

**Review by gbraad — APPROVED** [review]

**Review by lstocchi — APPROVED** [review]

**Comment by gbraad** [comment]
> from the doc?

Extensions will have their own documentation. The documentation in this repo would be more generic in how to enable (discover/find) these extensions. In that case, using OpenShift Local (with microshift) as an example, might not be a bad example.

**Pull request merged**
