### PR TITLE
feat(extensions/kind): update projectcontour to v1.30.1

### PR DESCRIPTION
**Pull request by Blaimi**
`pnpm -C extensions/kind install:contour` (requires #9926)

Update the manifestfile for installing projectcontour in the kind-extension to its current version which is [v1.30.1](https://github.com/projectcontour/contour/releases)

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
checked on macOS

cc @podman-desktop/qe-reviewers

**Review by gastoner — APPROVED** [review]
Codewise LGTM

**Review by axel7083 — APPROVED** [review]
> :warning: To be able to use `pnpm -C extensions/kind install:contour` you need to rebase the branch. 

I can confirm on Fedora that this branch use the contour 1.30.1 in new kind cluster created.

> This can be verified by checking the pod in the projectcontour namespace container image

**Comment by Blaimi** [comment]
> > ⚠️ To be able to use `pnpm -C extensions/kind install:contour` you need to rebase the branch.

This was because of #9926 which got merged in the meantime. I rebased this PR.

**Review by odockal — APPROVED** [review]
I have tested the contour upgrade on Windows 10.

**Review by cdrage — APPROVED** [review]

**Pull request merged**
