### PR TITLE
feat: suggest extensions if building or pulling from some registries report errors

### LINKED ISSUE #6389: Implement first recommendation in case of pulling from a registry and we receive authentication error
### Is your enhancement related to a problem? Please describe

This is the workflow described in https://github.com/containers/podman-desktop/issues/5771

As a developer, I’m trying to pull from a registry that requires authentication, but I’m not authenticate and I don’t have corresponding SSO extension.
{use_case}: Pulling from registry
→ Display a notification to point the user to install either the corresponding authentication extension

Ideally, we would like to detect that, even when the user is doing the pull from a CLI command

### Describe the solution you'd like

Implement this workflow

It should be possible with Podman 5 that throw events in case of pulling image errors

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Analyze errors when building and pulling images. If a registry is matching a suggested registry from recommendations, display a message to install the extension (if installed, display a link to the details of the extension)
Then user should be able to authenticate

Introduce a component shared between build and pull

### Screenshot / video of UI

image

image

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/6389

### How to test this PR?

try to pull an image from registry.redhat.io like `registry.redhat.io/rhel9/postgresql-13` without having Red Hat auth extension and without being logged in.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
Love the feature, great work!

Are there plans to also tackle build errors?  I assume that may be a common work flow as well.
Screenshot 2024-04-24 at 10 37 27

**Comment by benoitf** [comment]
@vrothberg I'll check what I can do 👍

**Comment by benoitf** [comment]
One thing that is still bothering me as the user is that we should be able to detect if we're logged-in or not and add the Signed-in button as well but it should be a further improvement

This is because installing the extension is not enough.

**Comment by benoitf** [comment]
@vrothberg I updated the PR to handle build as well

**Comment by vrothberg** [comment]
Works like a charm, great work!

Screenshot 2024-04-24 at 16 02 36

**Review by vrothberg — APPROVED** [review]

**Comment by benoitf** [comment]
had to rebased to fix a conflict

**Review by vrothberg — APPROVED** [review]

**Review by dgolovin — APPROVED** [review]

**Review by deboer-tim — COMMENTED** [review]
This recommends that I install the RH authentication extension, and links me to the page to install it. So I install it, go back and try to pull again. Of course it fails again, and it links me back to the page that confirms I have the extension installed...

So I read a bit of the readme, which tells me to Sign In to use it. I follow the instructions and the only thing that changes is a hat on the status bar. I click that, and it logs me in (again). Ok, not helpful, so I check the readme again: "Once signed in, there is nothing further to be done."

Clearly the auth extension is now failing on my machine :-( , but if it wasn't it feels like there is a gap here where we always direct people to the extension instead of logging in once they have it installed.

**Comment by vrothberg** [comment]
> This recommends that I install the RH authentication extension, and links me to the page to install it. So I install it, go back and try to pull again. Of course it fails again, and it links me back to the page that confirms I have the extension installed...

The text should probably also state to "sign in after installation of the extension".

> Clearly the auth extension is now failing on my machine :-( , but if it wasn't it feels like there is a gap here where we always direct people to the extension instead of logging in once they have it installed.

The build works just fine on my machine once signed in.  Does the build fail for you?

**Review by jeffmaury — APPROVED** [review]
LGTM

Just a remark about the color of the label which is not so different from the error message

**Comment by benoitf** [comment]
Adding a `Sign in...` button to redirect to the auth page if extension is installed

image

**Pull request merged**
