### PR TITLE
feat: port-forward on deployments

### LINKED ISSUE #9661: Support port forwarding for deployments
### Is your enhancement related to a problem? Please describe

Port forwarding support is only supported for pods

### Describe the solution you'd like

Extend to deployments

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Port-forward on deployments (will port forward on the first pod managed by the deployment)

### Screenshot / video of UI

https://github.com/user-attachments/assets/b8db3ac9-9925-4aaa-9dea-637498fd8c27

### What issues does this PR fix or reference?

Fixes #9661 

### How to test this PR?

Start a deployment with one or several pods, go to the Deployment Summary and create the port forward.

If the deployment has several replicas, check that the port forward is done in a specific pod.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — COMMENTED** [review]
If I forward a port from the deployment details page, I do not see the port forward inside the pod summary, which is IMO a problem... :/

**deployment details**
image

**pod details**
image

I don't know if we should remove the `WorkloadKind.DEPLOYMENT` because it does not make any sense, since we forward the managed pod, or we should check for type WorkloadKind.DEPLOYMENT in the pod summary :/

**Comment by feloy** [comment]
> If I forward a port from the deployment details page, I do not see the port forward inside the pod summary, which is IMO a problem... :/
> 
> **deployment details** image
> 
> **pod details** image
> 
> I don't know if we should remove the `WorkloadKind.DEPLOYMENT` because it does not make any sense, since we forward the managed pod, or we should check for type WorkloadKind.DEPLOYMENT in the pod summary :/

I don't understand why it is a problem, compared to how the port forward is currently done for Services.

When a port forward for a service is created, if I understand correctly, we create a port forward on the first pod matching the selector of the service. But the port forward is not displayed in the Pod summary.

**Comment by axel7083** [comment]
> if I understand correctly, we create a port forward on the first pod matching the selector of the service.

Hummm I thought service where something on its own, but after reading the documentation, you are right

**Review by benoitf — APPROVED** [review]
I thought I approved but it was just pending on my side

**Review by axel7083 — APPROVED** [review]

**Pull request merged**
