### PR TITLE
Remove http:// prefix when set proxy variable before exec

### PR DESCRIPTION
**Pull request by mcarbonneaux**
### What does this PR do?

Remove http:// prefix when set proxy variable before exec to try to fix the problem with proxy variable.

cf issue : https://github.com/containers/podman-desktop/issues/4765

### Screenshot / video of UI

in podman machine : 
```
# find /etc -type f | xargs grep https_proxy
/etc/profile.d/default-env.sh:export https_proxy="http://http://localhost:8080"
/etc/systemd/system.conf.d/default-env.conf:DefaultEnvironment=http_proxy="http://http://localhost:8080" https_proxy="http://http://localhost:8080" no_proxy="127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost" HTTP_PROXY="http://http://localhost:8080" HTTPS_PROXY="http://http://localhost:8080" NO_PROXY="127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost"
/etc/environment.d/default-env.conf:https_proxy="http://http://localhost:8080"
```

```
# env | grep -i proxy
no_proxy=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost
https_proxy=http://http://localhost:8080
NO_PROXY=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost
HTTPS_PROXY=http://http://localhost:8080
HTTP_PROXY=http://http://localhost:8080
http_proxy=http://http://localhost:8080
```

299735237-a54ec562-961c-4740-863f-6404ac49f965

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM.

Creation of a Podman machine with proxy is now ok

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Tests should be updated

**Comment by mcarbonneaux** [comment]
> Tests should be updated

i've try to fix it, but in not sure! because i cannot test.

**Comment by benoitf** [comment]
approved the run of the PR check workflows

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
thanks @mcarbonneaux

**Pull request merged**
