### PR TITLE
fix: socket path is not primary key to know which machine it is

### LINKED ISSUE #3401: Can only see one machine in Resources > Podman details
### Bug description

The new screen to show details for a Podman machine is great, but no matter which machine/link I use I only see the details for one machine.

### Operating system

macOS 13.5

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Create multiple podman machines. Use the new link action to open details, the same one opens every time.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
socket path is not primary key to know which machine it is

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/3401

### How to test this PR?

test case of the issue

### CODE REVIEW

**Comment by deboer-tim** [comment]
Tried this while on calls, caused an HMR. I think it needs at least one more change in PreferencesPage.svelte to pass name to PreferencesContainerConnectionRendering?

**Comment by benoitf** [comment]
ah oops I forgot to push some files locally
pushed

**Review by deboer-tim — APPROVED** [review]
Works great 👍🏼

**Comment by benoitf** [comment]
I've added unit test that covers macOS case with socketPath being identical across machines

**Pull request merged**
