### PR TITLE
fix: allow to resume/see task from creation page

### LINKED ISSUE #2079: When I leave a kind cluster creation page I have no way to return to see the logs or outcomes
### Is your enhancement related to a problem? Please describe

I was creating a kind cluster and left the page where the process was shown. I could not get back. I could monitor a task, but once the task was finished, it disappeared. I could assume all went well, but no option to check logs or whatever.

### Describe the solution you'd like

It would be nice to have a way to actually get back to a page where something was happening. 
Ie. I start creating a king cluster, go to Images and then I could return back to the same page of Kind cluster creation.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This allow to resume/see the logs of a running creation task.

### Screenshot/screencast of this PR

resume-task-create

### What issues does this PR fix or reference?

it fixes #2079 

### How to test this PR?

1. create a podman/kind machine/cluster
2. in the middle of the creation process, change page
3. using the task manager go back to the creation page

### CODE REVIEW

**Comment by jeffmaury** [comment]
I noticed a side effect: if a creation of a Kind cluster fails then the next time you try to create another cluster the form is displayed with an error:

task

Check the same on main and cannot reproduce

**Comment by lstocchi** [comment]
> I noticed a side effect: if a creation of a Kind cluster fails then the next time you try to create another cluster the form is displayed with an error:

The problem is deciding how it should behave.
If we have to give users the ability to return to the creation page then we need to decide in which moments. 

What if the user clicks on the task manager and while he/she clicks the task fails/completes, do i show a clear creation page?
or if one reaches the page from one point (e.g the create button) i need to show the clear page otherwise (from the taskmanager) the last state?

**Comment by deboer-tim** [comment]
> The problem is deciding how it should behave. If we have to give users the ability to return to the creation page then we need to decide in which moments.
> 
> What if the user clicks on the task manager and while he/she clicks the task fails/completes, do i show a clear creation page? or if one reaches the page from one point (e.g the create button) i need to show the clear page otherwise (from the taskmanager) the last state?

IMHO this is the reason for using the Task Manager: once you click Create the task is off running in the background in the task manager, and this screen is just holding to show progress/cancel and success/fail at the end. (If you want to see logs or detailed information we should probably even be directing people to the task manager)

If you exit the page while it is still running, it doesn't need to come back because the task is still running. The button should probably even be 'I don't want to wait'. Likewise, if you want to see the previous failure (or success) you look in the task manager.

**Comment by lstocchi** [comment]
> IMHO this is the reason for using the Task Manager: once you click Create the task is off running in the background in the task manager, and this screen is just holding to show progress/cancel and success/fail at the end. (If you want to see logs or detailed information we should probably even be directing people to the task manager)
> 
> If you exit the page while it is still running, it doesn't need to come back because the task is still running. The button should probably even be 'I don't want to wait'. Likewise, if you want to see the previous failure (or success) you look in the task manager.

Ok, so basically what it changes is that instead of storing one single creation task i can store multiple ones (e.g i can create multiple podman machine and find their logs etc..). 
When i click on the `New ...` button from the resources page i see an empty and clean creation page and the user should use the task manager to retrieve the state of one of the old processes.

**Comment by lstocchi** [comment]
@jeffmaury your issue should be solved. Please test it again. Thanks!

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by cdrage — APPROVED** [review]
I encountered no issues, I was able to resume / see the task from the creation page and the code LGTM. Thanks @lstocchi !

**Pull request merged**
