### PR TITLE
fix: calculate machine socket path for linux

### PR DESCRIPTION
**Pull request by afbjorklund**
### What does this PR do?

Preparing for being able to use podman machine also on Linux, by avoiding hardcoding only mac/win

### What issues does this PR fix or reference?

* #3068

### CODE REVIEW

**Comment by cdrage** [comment]
Hey @afbjorklund thanks for the PR. Can you let me know the testing steps?

Got a bit confused when making the remote virtual machine 🤣 if you don't mind, then I can review it further.

**Comment by afbjorklund** [comment]
It is part of an epic, so I don't think you can test it properly without more features

* https://github.com/containers/podman-desktop/issues/3068

But you can run `podman-remote machine start` and see where the local socket ends up ?

Podman Desktop is still hard-coding the local socket location, when running on Linux.

----

Note that podman will use `ssh:` rather than `unix:` by default, so the system connections won't "help".

```
Name                         URI                                                            Identity                                                                              Default
lima-podman                  unix:///home/anders/.lima/podman/sock/podman.sock                                                                                                    false
podman-machine-default       ssh://core@127.0.0.1:45689/run/user/1000/podman/podman.sock    /home/anders/.ssh/podman-machine-default                                              false
podman-machine-default-root  ssh://root@127.0.0.1:45689/run/podman/podman.sock              /home/anders/.ssh/podman-machine-default                                              false
```

But the tunnel is still created, under `/home/anders/.local/share/containers/podman/machine/qemu/podman.sock`

```
anders     56939  0.0  0.1 1387260 16736 pts/1   Sl+  07:56   0:00 /usr/libexec/podman/gvproxy -listen-qemu unix:///run/user/1000/podman/qmp_podman-machine-default.sock -pid-file /run/user/1000/podman/podman-machine-default_proxy.pid -ssh-port 45689 -forward-sock /home/anders/.local/share/containers/podman/machine/qemu/podman.sock -forward-dest /run/user/1000/podman/podman.sock -forward-user core -forward-identity /home/anders/.ssh/podman-machine-default
```

**Comment by afbjorklund** [comment]
> Got a bit confused when making the remote virtual machine 🤣

Podman is supposed to create the (QEMU) virtual machine for you

**Review by benoitf — APPROVED** [review]
for now on Linux we don't monitor the machines, so it's kind of dead code for now

**Comment by afbjorklund** [comment]
It makes the actual enabling smaller, once the feature has been figured out.

i.e. how to toggle between multiple podman sockets, on the same desktop

* rootless vs. rootful

* engine vs. machine

**Comment by benoitf** [comment]
sure, no problem. I prefer small PRs

**Pull request merged**
