### PR TITLE
chore(docs): update API documentation for ImageBuildOptions

### PR DESCRIPTION
**Pull request by jeffmaury**
Relates to #5851

### What does this PR do?

Update the API documentation

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#5851 

### How to test this PR?

N/A

### CODE REVIEW

**Comment by feloy** [comment]
This is redondant with #5891

**Review by axel7083 — APPROVED** [review]
LGTM

**Comment by axel7083** [comment]
> This is redondant with #5891

Yes this overlap

**Comment by jeffmaury** [comment]
Done in #5891

**Pull request closed without merging**
