### PR TITLE
chore(test): add aria labels for rows

### LINKED ISSUE #5639: Add ARIA functionality to image/containers/pods table rows
### Is your enhancement related to a problem? Please describe

It's very difficult to handle image/container/pod table rows in their respective pages because there aren't any rows specific ARIA locators available.

### Describe the solution you'd like

Add ARIA functionality at the table tow level to allow for easy individual row selections.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cbr7**
### What does this PR do?
Add aria-labels for images and container page rows

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/5639

### How to test this PR?
Check image and container rows to have aria-label property with the corresponding values.

### CODE REVIEW

**Review by ScrewTSW — APPROVED** [review]
LGTM

**Review by odockal — COMMENTED** [review]
LGTM, but I would like to have someone from developer to take a look at tests.

**Comment by deboer-tim** [comment]
FWIW the reason I didn't do this before is that name isn't unique, and there's no guarantee that any new item we decide to put in a table will have a name (although most of them appear to have one now). If the tests don't have situations where there are (e.g.) multiple images with the same name, then it'll be fine for now.

**Comment by odockal** [comment]
No problem, I just could see possible ambiguity during testing if there are same names used in labels, but that could be workarounded with adding another role/name check. The unit test relying on multiple tooltips seemed awkward to me, that is all.

**Pull request merged**
