### PR TITLE
feat: display Kubernetes connection status in relevant pages

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

This PR is adding a badge to the Service and Deployment page indicating the status ('connected' | 'error') to the current context (when exist).

### Screenshot / video of UI

**error display**
image

**on hover**
image

**connected**
image

### What issues does this PR fix or reference?

https://github.com/containers/podman-desktop/issues/5401

### How to test this PR?

- Create / delete kind cluster
- Switch between contexts

### CODE REVIEW

**Comment by deboer-tim** [comment]
Out of context the badges look a bit like buttons to me (they've only been used in table columns so far), I'm wondering if we should use a different UI element or just not have the badge background.

The original designs for all these pages (e.g. #4403) is to allow multiple contexts or namespaces, so a 'global' status wouldn't work long term, but until we get there there isn't an obvious other place to put this.

For both reasons I think it's worth a quick design discussion.

**Comment by axel7083** [comment]
> Out of context the badges look a bit like buttons to me (they've only been used in table columns so far), I'm wondering if we should use a different UI element or just not have the badge background.
> 
> The original designs for all these pages (e.g. #4403) is to allow multiple contexts or namespaces, so a 'global' status wouldn't work long term, but until we get there there isn't an obvious other place to put this.
> 
> For both reasons I think it's worth a quick design discussion.

I agree for the button, as you said it is the one used in the column. I read the #4403 original design page, and I have some questions
- Does all contexts will be automatically connected and displayed ?
- Does the page will not have a overload look if we display many contexts in the same page ?
> I worked with some Kubernetes cluster where we had hundreds of pods in a single namespace, I am a bit afraid for the scaling 
- Does the search bar search for all the pods/services in all contexts ?

**Comment by slemeur** [comment]
At the moment, Podman Desktop displays the objects from the selected kubecontext and the objects from Podman - pods and deployments at least.  

As the connectivity information is related to the kubecontext, it would make sense to me to display it along with the kubecontext in the status bar. This way as a user, I have a single place to see the information about my current context: which one is selected, what is that connectivity status.

On the other hand, I think the current empty screen is misleading. Right now, we are saying there are no services to display, while in fact, there is a connectivity issue... That error should be reported to the user in a more obvious way and I would not hide the error behind a tooltip. We could probably, add in the empty screen message, the connectivity error.

**Comment by axel7083** [comment]
> At the moment, Podman Desktop displays the objects from the selected kubecontext and the objects from Podman - pods and deployments at least.
> 
> As the connectivity information is related to the kubecontext, it would make sense to me to display it along with the kubecontext in the status bar. This way as a user, I have a single place to see the information about my current context: which one is selected, what is that connectivity status.

Adding the connection status to the status bar along it could be interesting, but would require some internal changes

> On the other hand, I think the current empty screen is misleading. Right now, we are saying there are no services to display, while in fact, there is a connectivity issue... That error should be reported to the user in a more obvious way and I would not hide the error behind a tooltip. We could probably, add in the empty screen message, the connectivity error.

I agree that the `empty screen is misleading` as we do not see the difference between nothing to display vs an error.

**Pull request closed without merging**
