### PR TITLE
Fix: Icon #533 Patch 2

### PR DESCRIPTION
**Pull request by rdwz**
[#532](https://github.com/containers/podman-desktop/issues/532)

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
Hello @redwerkz it seems you removed some part of the logo, not only the extra whitespace around the icon

**Comment by rdwz** [comment]
> Hello @redwerkz it seems you removed some part of the logo, not only the extra whitespace around the icon

please see my [latest post on the issue](https://github.com/containers/podman-desktop/issues/532#issuecomment-1279734940), I added some screenshots:

**Comment by slemeur** [comment]
hi @redwerkz ! Thanks for submitting the PR. 

I agree that the icon does not look right on Chrome OS Flex as you mentioned in https://github.com/containers/podman-desktop/issues/532#issuecomment-1279734940.

But I think overall removing the dark background also hurts the icon on other platforms which are more used. Was removing the extra white space in the initial icon sufficiently improving the situation for windows from your point of view? 

@mairin What do you think on this?

**Comment by mairin** [comment]
> hi @redwerkz ! Thanks for submitting the PR.
> 
> I agree that the icon does not look right on Chrome OS Flex as you mentioned in [#532 (comment)](https://github.com/containers/podman-desktop/issues/532#issuecomment-1279734940).
> 
> But I think overall removing the dark background also hurts the icon on other platforms which are more used. Was removing the extra white space in the initial icon sufficiently improving the situation for windows from your point of view?
> 
> @mairin What do you think on this?

I'm not familiar with what options Chrome OS Flex provides for app icons... but it seems that would could drop the roudned square rectangle behind the hex logo and instead have the background (the circle?) be colored that same dark color value instead of white? That should look much better and would give more room for the hex mark?

Without changing the logo I'd rather see something like this:
Screenshot from 2022-10-18 13-30-51

If it was feasible to modify the logo, maybe something like this:
Screenshot from 2022-10-18 14-18-14

What do you think @slemeur ?

**Comment by benoitf** [comment]
PTAL @slemeur

**Comment by slemeur** [comment]
@mairin Yeah I completely agree with you. 
I think overall, the icon is looking better with a background.

@redwerkz Do you think there is a way we can achieve that? we are not very familiar with Chrome OS Flex, so we appreciate your help on this!

**Comment by rdwz** [comment]
> I'm not familiar with what options Chrome OS Flex provides for app icons... but it seems that would could drop the roudned square rectangle behind the hex logo and instead have the background (the circle?) be colored that same dark color value instead of white? That should look much better and would give more room for the hex mark?

@mairin right now dev mode supports
- installing .deb packages and this works for podman-desktop
- Chrome Apps from their webstore, but these are already deprecated, afaik no replacment announced yet

the round bg seems to behave according to android: bg gets added on default and despite I like your design update. I doubt if gradients are possible.

**Comment by rdwz** [comment]
> But I think overall removing the dark background also hurts the icon on other platforms which are more used. Was removing the extra white space in the initial icon sufficiently improving the situation for windows from your point of view?

@slemeur
- I have not checked how it looks on linux yet
- Could you provide a Mac screenshot?
- Windows 10/11 are the same, i guess?!

win11-nobg

**Comment by slemeur** [comment]
For mac, it looks like that:
Capture d’écran 2022-11-02 à 11 33 47

So it is fairly consistent with other application's icons

**Comment by benoitf** [comment]
it looks like we would need different icons on mac and Windows / Linux
Closing the PR but issue is still open where we can discuss it.

**Pull request closed without merging**
