### PR TITLE
feat: reduce height of navbar items

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
before having a solution for #6774 with a design, reduce height of each item from navbar

### Screenshot / video of UI

on the left, current state
on the right, PR state

image

### What issues does this PR fix or reference?

related to https://github.com/containers/podman-desktop/issues/6774

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by deboer-tim** [comment]
I tried playing with this PR. IMHO dropping to py-2.5 looks fine and even going to py-2 looks ok in the sections, but going to 1.5 here looks squished and kind of ugly to me.

It helps a bit if we make the entire bar a little narrower at the same time so that the selection isn't so rectangular... then maybe shrink the icons a little too, but those are both bigger changes that we might not want to make for the long term.

FYI to @ekidneyrh

**Comment by benoitf** [comment]
I agree I was finding it was ok with 2 but went further with 1.5 to get feedback :-)

**Comment by deboer-tim** [comment]
😆

**Comment by axel7083** [comment]
I am wondering if we should not reduce a little bit the size of the icons, as I have the feeling there is too much things in a small space with the new spacing...

| size 24 | Size 22 | Size 20 |
| --- | --- | --- |
| image | image | image |

**Comment by jeffmaury** [comment]
Icon resizing would improve

**Comment by benoitf** [comment]
changed from py-3 to py-2 and reduced the icon size from 24 to 22

**Review by deboer-tim — APPROVED** [review]
I think maybe we should shrink the width of the bar too, but that can be a separate discussion.

**Pull request merged**
