### PR TITLE
Add docker context selector

### PR DESCRIPTION
**Pull request by tony-sol**
### What does this PR do?

Allow to select docker socket via `docker context`

### Screenshot / video of UI

statusBar

contextSwitcher

https://github.com/containers/podman-desktop/assets/33671815/74d91f67-238c-428e-8dc2-9a2113548bc8

†

### What issues does this PR fix or reference?

_TBD_

### How to test this PR?

* Create several docker contexts
* Try to switch between them with selector
* ...
* _TDB_

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by benoitf** [comment]
it's looking promising but in draft state since a couple of months, closing

**Comment by tony-sol** [comment]
> it's looking promising but in draft state since a couple of months, closing

Yeah, i really don't have energy right now to finish this, but hope to continue someday

**Comment by tony-sol** [comment]
@benoitf can you re-open this PR? i'm feeling ok to continue my work on it and looks like it needs brief review for the start

**Comment by benoitf** [comment]
the button is disabled on my side to reopen

**Comment by benoitf** [comment]
reopening

**Comment by benoitf** [comment]
It seems that to be able to reopen the branch containing the code needs to be at the same commit than when it has been closed

**Comment by benoitf** [comment]
anyway we will implement the context selector as part of the docker compatibility page

**Pull request closed without merging**
