### PR TITLE
chore: backport fixes to 1.6 branch

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
backport fixes to 1.6.x
- [x] https://github.com/containers/podman-desktop/pull/5231
- [x] https://github.com/containers/podman-desktop/pull/5219
- [x] https://github.com/containers/podman-desktop/pull/5222
- [x] https://github.com/containers/podman-desktop/pull/5229
- [x] https://github.com/containers/podman-desktop/pull/5236

### What issues does this PR fix or reference?

#5051

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by deboer-tim — APPROVED** [review]
I'm not sure if this PR is meant to accumulate other fixes still or just these two, but LGTM.

**Comment by benoitf** [comment]
@deboer-tim it's like a wip I would add more 
I was planning to accumulate others PRs there

**Comment by deboer-tim** [comment]
Thanks for clarifying. I have zero concerns with your choices and ability to cherrypick commits so I am happy to leave my pre-approval. :)

**Comment by benoitf** [comment]
FYI I've cherry-picked 2 additional PRs

**Comment by benoitf** [comment]
added a new one https://github.com/containers/podman-desktop/pull/5236

**Pull request merged**
