### PR TITLE
fix: Kind move image did not move image to Kind cluster

### LINKED ISSUE #1745: kind extension: move image broken
### Bug description

When move image feature is called, the command is wrong and the return code is not check correctly leading to confusion

### Operating system

Win11 Pro

### Version

0.12.0

### Steps to reproduce

1. Create a kind cluster
2. Create an image on podman
3. Move that image to the Kind cluster
4. On the kind container (called kind-cluster_name), open a terminal and issues the command: `crictl images`. You should see an images called xxx/import-date)

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #1745

### What does this PR do?

Fixes move image to Kind cluster which was kind of NOP as the CLI was wrongly called and return code was not checked

### Screenshot/screencast of this PR

kind

### What issues does this PR fix or reference?

Fixes #1745

### How to test this PR?

1. Create a Kind cluster
2. Push an image to that Kind cluster
3. Go to the kind control plane container in the Containers tab
4. Open an terminal and run the `crictl images` command
5. You should see an image called xxx/import-date (original name is going to be fixed by #1746)

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
I think we should improve the feedback we give to the user.
When pushing there is no signal of what it's happening (i only see the final notification) and when there is an error it's only visible when clicking on the three dots action.
error-push-kind

**Comment by jeffmaury** [comment]
> I think we should improve the feedback we give to the user. When pushing there is no signal of what it's happening (i only see the final notification) and when there is an error it's only visible when clicking on the three dots action. error-push-kind [ error-push-kind ](https://user-images.githubusercontent.com/49404737/226830975-52dca668-25bf-4c87-b5e6-b71a77dd63ac.gif) [ ](https://user-images.githubusercontent.com/49404737/226830975-52dca668-25bf-4c87-b5e6-b71a77dd63ac.gif)

Agree but that's unrelated to this PR so should be part of another issues

**Comment by benoitf** [comment]
I was not able to test due to https://github.com/containers/podman-desktop/issues/1782
but it looks my issue is macOS specific so I'll try to fix https://github.com/containers/podman-desktop/issues/1782

**Comment by jeffmaury** [comment]
> I was not able to test due to #1782 but it looks my issue is macOS specific so I'll try to fix #1782

@benoitf can you retest this one as #1782 is now closed ?

**Comment by benoitf** [comment]
I'm stuck by https://github.com/containers/podman-desktop/issues/1818

**Comment by jeffmaury** [comment]
> I'm stuck by #1818

Let's create the Kind cluster using the CLI 😅

**Review by benoitf — APPROVED** [review]
Being able to test with https://github.com/containers/podman-desktop/pull/1843 chery-picked on top of this PR

I was able to import the image but I do not have any feedback that the image is pushed on the cluster (because notification is not working on macOS (different story))

I also thought that the Push Image to Kind cluster icon was not working as it displays the icon of a kebab menu so I don't know if we should change the icon to be still a random image but not being the kebab menu icon

**Comment by benoitf** [comment]
Forgot to attach the screencast:

https://user-images.githubusercontent.com/436777/228168193-966daf7c-3ab5-40b9-ae3b-e82be1a99a22.mp4

**Pull request merged**
