### PR TITLE
feat: Fixed, simple navigation bar

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

I had no clue I'd end up working on this today, but after a long day I thought I'd try one topic that came up earlier and it turned out to be pretty straight-forward.

This changes the main navigation to be a fixed width icon bar that is always visible.

- Removed all titles and counter badges. Added tooltips.
- There were several redundant divs and unused code removed. I tried scanning all other classes to fix inconsistencies.
- Extensions were expandable before - I made the call to remove the Extensions icon and always include them.
- I made the Settings title have slightly less top padding so that it is at the same position as other titles like Images/Container list.
- Removed Exit Settings link.

### Screenshot/screencast of this PR

Screenshot 2023-04-19 at 5 40 56 PM

### What issues does this PR fix or reference?

Fixes issue #2167 and issue #1648.

### How to test this PR?

It's pretty obvious. ;-) Check formatting of main navigation & settings pages.

### CODE REVIEW

**Comment by deboer-tim** [comment]
Also fixes this previous problem with extension icons when the window was narrow - thought I had opened an issue but can't find it now:
Screenshot 2023-03-21 at 11 55 03 AM

**Comment by cdrage** [comment]
https://user-images.githubusercontent.com/6422176/233445664-85c6562e-aba4-4cfa-b8e8-42ac92d5f629.mov

This looks great and the code changes LGTM!

My brain isn't used to the text being removed haha, so I keep imagining that they are there.

I saw that there are a few updates here:

https://github.com/containers/podman-desktop/issues/2167

So I'm assuming we'll wait / update this PR @deboer-tim ?

I'm also curious if we're able to update the delay on the hover (it takes approx 2s for me until it appears). But that's just a small nitpick.

**Comment by cdrage** [comment]
https://user-images.githubusercontent.com/6422176/233448144-f02d1daa-8f7f-4804-a9b3-820b651f74d7.mov

Found 1 issue. When you open settings, clicking on the button again doesn't close it.

**Comment by deboer-tim** [comment]
> I saw that there are a few updates here: #2167
> So I'm assuming we'll wait / update this PR @deboer-tim ?

Yes, just hadn't gotten back here since the design meeting. I was planning to pick up a couple of the easy items (maybe separator, image/etc counts) and update the PR, leaving the rest for another day. Since the second one brings back a chunk of code and there is now a branch conflict I may force push and will ask for a re-review.

> I'm also curious if we're able to update the delay on the hover (it takes approx 2s for me until it appears). But that's just a small nitpick.

IIRC from another issue this is Electron and the only way to fix is to do our own tooltips.

> Found 1 issue. When you open settings, clicking on the button again doesn't close it.

I noticed that, and then thought "well, none of the other tabs close either?". I wasn't sure what behaviour would be better, e.g. should we still return to the previous tab? dashboard?

**Comment by cdrage** [comment]
> > I saw that there are a few updates here: #2167
> > So I'm assuming we'll wait / update this PR @deboer-tim ?
> 
> Yes, just hadn't gotten back here since the design meeting. I was planning to pick up a couple of the easy items (maybe separator, image/etc counts) and update the PR, leaving the rest for another day. Since the second one brings back a chunk of code and there is now a branch conflict I may force push and will ask for a re-review.
> 
> > I'm also curious if we're able to update the delay on the hover (it takes approx 2s for me until it appears). But that's just a small nitpick.
> 
> IIRC from another issue this is Electron and the only way to fix is to do our own tooltips.
> 
> > Found 1 issue. When you open settings, clicking on the button again doesn't close it.
> 
> I noticed that, and then thought "well, none of the other tabs close either?". I wasn't sure what behaviour would be better, e.g. should we still return to the previous tab? dashboard?

Previous tab would be best! For example: I'm working on Pods, realize my Kubeconfig is messed up, so I go to settings. If I click settings again, I expect it to go back to Pods / previous tab.

**Comment by jeffmaury** [comment]
I'm missing the count in the tooltip but I can't see the extension icons (maybe an issue with the OpenShift Local one)

**Comment by deboer-tim** [comment]
Replacement commit pushed to:
- resolve branch conflict
- add separator between regular icons and extensions
- adding pod/image/etc counters to tooltips
- allowing the user to click Settings again to return to previous tab

Now just a partial fix for issue #2167 (two first issues), but I do not think the remaining issues (change bg color, highlight selection color, and handle large # of extensions) should block this PR as they all existed before and can be handled as independent improvements.

@cdrage or @jeffmaury, please review again.

**Comment by cdrage** [comment]
https://user-images.githubusercontent.com/6422176/233674191-e6b7dc49-00cf-4b1e-918f-b463683c875e.mov

Reviewed, was able to check all the changes as well as check to see if it shows zero images/pods/volumes/etc. correctly.

LGTM! Thanks for applying the requested changes.

**Review by cdrage — APPROVED** [review]

**Comment by benoitf** [comment]
From what I see, relying now only on "browser tooltip" to display the description of the icon is too slow.
Newcomers may have hard time to figure out what icon is doing what
IMHO we should add popup that displays instantly on hovering the icons on the left

**Pull request merged**
