### PR TITLE
fix(website): adding recipes details

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Adding a recipes section in the ai-lab website. Moreover adding some css fixes for the video player, css gradient background etc.

### Screenshot / video of UI

image

image

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop-internal/issues/276

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by benoitf** [comment]
IMHO there is too much gradient and different colors for recipes, I don't know if it has been discussed somewhere ?
it doesn't feel matching some of our palette colors.

**Comment by axel7083** [comment]
cc @ekidneyrh 

Using the colors from the `tailwind-color-palette.json` I got the following

image

| x | Chatbot | Text Summarizer | Speech to text | Object Detection |
| --- | --- | --- | --- | --- |
| `colorFrom` | green[200] | purple[200] | red[300] | amber[200] |
| `iconColor` | green[300] | purple[400] | red[400] | amber[400] |

image

**Comment by ekidneyrh** [comment]
Looks good with the different colours! 

A few more changes I'd suggest. For the boxes, it would be nice to have the headings align with each other. 

image

For that I'd either make 'LLM Chatbot' two lines so the body text gets pushed down to match the others:

image

or make the cards be in a 2 x 2 layout like this:
image
(ignore the different icons in the screenshot, I was just making a quick mockup to use as an example) 

As for the spacing, I think bumping it up between the heading 'Experiment with free Open Source recipes' and the cards to even half the spacing thats used from the video card to the heading, if that makes sense. And I'd do that throughout the page.

image

Just to let the content breathe a bit.

**Comment by benoitf** [comment]
On my end I'm still wondering about the colors ( like green, yellow and red as we don't have these colors on big layout)

Mostly we have purple everywhere so wondering if we need this very different colors or be inside purple tones

**Comment by axel7083** [comment]
> On my end I'm still wondering about the colors ( like green, yellow and red as we don't have these colors on big layout)
> 
> Mostly we have purple everywhere so wondering if we need this very different colors or be inside purple tones

I like colors, life is too gray

**Review by cdrage — APPROVED** [review]
The colours look great IMHO and adds some character to the page.

LGTM.

Although unrelated to the PR, I do find two issues though:

- Hard to navigate to page (only accessible from index page from small text on the banner, maybe we should add it to the "top" section of PD too?)
- Zooming videos make it very eye straining / nauseous / I think it was suggested on slack to cut down the zoom to much lower number @feloy

**Comment by axel7083** [comment]
cc @ekidneyrh 

Following your guidelines, here is what I got :) !
image

**Comment by benoitf** [comment]
> I like colors, life is too gray

AFAIK purple is not a gray color :-)

To me it's too many different colors on a large surface that are not largely displayed elsewhere. Also on my end the icon feel to disappear/missing relief with the background color.

as it seems inspiration is coming from the orbstack website for the square with gradient, I notice that here it's not the full box that has gradient but only icon

image

and I feel like on my screen, it is making a stronger relief with the suggestion of 2 columns
image

**Comment by axel7083** [comment]
> > I like colors, life is too gray
> 
> AFAIK purple is not a gray color :-)
> 
> To me it's too many different colors on a large surface that are not largely displayed elsewhere. Also on my end the icon feel to disappear/missing relief with the background color.

Better start somewhere :)

> as it seems inspiration is coming from the orbstack website for the square with gradient, I notice that here it's not the full box that has gradient but only icon

I like the way they are doing some stuff, but keep some preference for colors

> and I feel like on my screen, it is making a stronger relief with the suggestion of 2 columns

Updated with the following 
image

**Comment by ekidneyrh** [comment]
I think it's looking good :) Did you adjust the spacing between the headings and the content or would that be a different PR?

**Comment by axel7083** [comment]
> I think it's looking good :) Did you adjust the spacing between the headings and the content or would that be a different PR?

I did, is it not enough ?

**Comment by ekidneyrh** [comment]
> > I think it's looking good :) Did you adjust the spacing between the headings and the content or would that be a different PR?
> 
> I did, is it not enough ?

I would bump it up some more in these spots and then it should be good to go :) 

Screenshot from 2024-05-27 10-42-13

**Comment by axel7083** [comment]
@ekidneyrh with the new spaces this is the result 

image

**Review by ekidneyrh — APPROVED** [review]

**Pull request merged**
