### PR TITLE
chore(tests): update and stabilize compose e2e tests

### PR DESCRIPTION
**Pull request by odockal**
### What does this PR do?
Improves and stabilize compose-e2e tests.
### What issues does this PR fix or reference?
#7515

### How to test this PR?
On linux set, `export COMPOSE_PARTIAL_INSTALL=true` before running the tests so it passes. `docker-compose` must not be installed on the system
```
yarn test:e2e
```

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]

**Comment by odockal** [comment]
I tried to run the tests on windows and it looks good: https://github.com/containers/podman-desktop-e2e/actions/runs/9418416211:

Screenshot_20240607_172700

**Review by cbr7 — APPROVED** [review]

**Review by benoitf — CHANGES_REQUESTED** [review]
we should not have properties for github actions in the tests

we have settings/toggle that you can add inside the GHA but it's not something that should be detected

**Comment by odockal** [comment]
> we should not have properties for github actions in the tests
> 
> we have settings/toggle that you can add inside the GHA but it's not something that should be detected

Is the latest change enough or we should proceed further and set other env. vars. for the particular tests?

**Review by rostalan — APPROVED** [review]
LGTM

**Review by benoitf — APPROVED** [review]

**Pull request merged**
