### PR TITLE
feat: update to podman v4.9.2

### LINKED ISSUE #5830: Update to podman v4.9.2
### Is your enhancement related to a problem? Please describe

Need to embed podman 4.9.2

### Describe the solution you'd like

use the new version

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Update podman to v4.9.2

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/5830

### How to test this PR?

try this new version on mac & windows

### CODE REVIEW

**Comment by axel7083** [comment]
Have I done something wrong ?

### Reproduces

(1) Checkout your branch
(2) Click on `Upgrade to v4.9.2`

image

image

image

**Comment by benoitf** [comment]
AFAIK @axel7083 the podman assets are updated/downloaded for builds not for dev mode

you could either download one binary build from the PR https://github.com/containers/podman-desktop/actions/runs/7782108835?pr=5831

or build one locally using `yarn compile:current`

(or also probably run the download operation manually in podman extension)

**Comment by axel7083** [comment]
> AFAIK @axel7083 the podman assets are updated/downloaded for builds not for dev mode
> 
> you could either download one binary build from the PR https://github.com/containers/podman-desktop/actions/runs/7782108835?pr=5831
> 
> or build one locally using `yarn compile:current`
> 
> (or also probably run the download operation manually in podman extension)

Alright ! Yes I guess it makes sense, but then we might want display something when we run in dev mode ? (not in the scope of this PR)

**Comment by jeffmaury** [comment]
> > AFAIK @axel7083 the podman assets are updated/downloaded for builds not for dev mode
> > you could either download one binary build from the PR https://github.com/containers/podman-desktop/actions/runs/7782108835?pr=5831
> > or build one locally using `yarn compile:current`
> > (or also probably run the download operation manually in podman extension)
> 
> Alright ! Yes I guess it makes sense, but then we might want display something when we run in dev mode ? (not in the scope of this PR)

Run `yarn build:extensions:podman` before `yarn watch` and you'll be good to test )

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by axel7083 — APPROVED** [review]
LGTM

**Pull request merged**
