### PR TITLE
chore(test): use aria-label for locator

### LINKED ISSUE #9300: Stabilize Podman Machine E2E tests running on CI using HyperV provider
### Is your enhancement related to a problem? Please describe

Right now we do not run podman machine* e2e tests on CI with Hyperv. They are not stable.

### Describe the solution you'd like

Debug and fix the instability issues for hyperv provider when runnig various podman machine e2e tests.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cbr7**
### What does this PR do?
Initial draft for fixes.

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/9300

### CODE REVIEW

**Review by amisskii — COMMENTED** [review]
Hi, we are currently using a button instead of a combo box. I merged a similar pull request yesterday, but we  reverted it: [PR #9520](https://github.com/containers/podman-desktop/pull/9520). Now we need to determine whether we should use a button or an option element, as discussed [there](https://github.com/containers/podman-desktop/pull/9533#issuecomment-2431459445).

**Comment by cbr7** [comment]
@amisskii That conversation can be still had, but this fixes the problem immediately, there is no reason to let the tests fail until a resolution to reached on that other issue.

EDIT: Your PR makes changes to the actual component, this PR is a fix limited to the test framework. To be honest I'm not really sure why you even went with a fix that is much larger in scope, when it wasn't needed.

**Review by benoitf — APPROVED** [review]

**Review by odockal — APPROVED** [review]

**Comment by odockal** [comment]
@cbr7 @amisskii Fix is good in the long run. But it needs to be properly designed.

We need to make the tests pass now. Approving.

**Comment by cbr7** [comment]
@benoitf It seems that the Semantic PR check is failing but I have no idea what the is, and it won't let me merge the PR.

EDIT: It seems to have started failing when I pulled main branch into this one.

**Comment by odockal** [comment]
@cbr7 you could rebase your branch so that you have only your commit and no problem with merge commits.

**Comment by benoitf** [comment]
@cbr7 all commits need to follow conventional commits

merge commits are of course not authorized (prefer rebase over merge)

**Comment by benoitf** [comment]
before there was a file to ensure that but it was in a wrong folder https://github.com/containers/podman-desktop/pull/9546
 
This is to ensure all commits and PR title have valid conventional commits

**Comment by cbr7** [comment]
@benoitf I don't understand, how is a basic function of github not a conventional commit? I literally only used the `Update branch` button from github.

**Comment by benoitf** [comment]
> I literally only used the Update branch button from github.

I think in GitHub UI there is "update with rebase" button

I never use merge, always use rebase to have proper history in the pull requests with only my commits (and fixup commits)

if it causing many trouble, we could try to add the `allowMergeCommits` option

**Pull request merged**
