### PR TITLE
fix: start secondary informers for current context only

### LINKED ISSUE #9702: Error message during Kind cluster deletion
### Bug description

While deleting a Kind cluster through the resources page, a popup error appears. However, after closing the popup, the Kind cluster is successfully deleted.
Image

An error message indicates that there is no active cluster, although the node is in a running state. I can push images and deploy containers to the Kind cluster, and all resources are visible.

UPD: There is a similar error with OpenShift Local (openshift).

### Operating system

Fedora 40

### Installation Method

None

### Version

1.14.0

### Steps to reproduce

_No response_

### Relevant log output

Error

A JavaScript error occurred in the main process

Uncaught Exception:
Error: No active cluster!
at KubeConfig.makeApiClient (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:371:19)
at vc.createServiceInformer (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:18133)
at vc.startResourceInformer (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:9213)
at update (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:11960)
at gve.safeSetState (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:4088)
at gve.setStateAndDispatch (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:3538)
at Object.onReachable (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:11692)
at Timeout._onTimeout (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:23910)
at listOnTimeout (node
/timers:581:17)
at process.processTimers (node
/timers:519:7)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Start secondary informers for current context only

### What issues does this PR fix or reference?

Fixes #9702 

### How to test this PR?

Edit the kubeconfig file to remove the line `current-context: ...`. No error should happen.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
issue: it is missing a unit test (can be a follow-up)

question: needs to backport to the next 1.14 bugfixes release ?

**Comment by feloy** [comment]
> issue: it is missing a unit test (can be a follow-up)
> 

Yes, I'll look at adding a test to cover the change. 

> question: needs to backport to the next 1.14 bugfixes release ?

@odockal WDYT?

**Review by gastoner — APPROVED** [review]
LGTM Thanks!

**Comment by gastoner** [comment]
Merge to 1.14.x branch? @feloy

**Comment by benoitf** [comment]
first, we merge to main, then if approved we can backport to 1.14.x

**Comment by odockal** [comment]
@feloy I have asked @amisskii  to take a look to verify the fix.

**Pull request merged**
