### PR TITLE
feat: enable podman desktop running in electron

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

This fix will let running podman-desktop in
electron as close as possible to production env.

To run podman-desktop locally with electron

`pnpm install && pnpm buld && node_modules/.bin/electron .`

The 'packages/main/src/assets' moved to app.asar file for runtime so it works after installing podman desktop with installer.

`pnpm watch`

is not affected because app.getAppPath() returns root of podman-desktop repository.

### What issues does this PR fix or reference?

Related to #5265 and let to replicate it without building installer

### How to test this PR?

1. Pull the branch
2. `pnpm install`
3. `pnpm build`
4. `node_modules/.bin/electron .`
5. You see podman-desktop dashboard

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by odockal** [comment]
I tried to build it using `yarn compile` and resulted binary did not started up correctly at all. It was in the "Initializing" state and could not get into standard start up event, like loading extension, system, etc.

**Comment by dgolovin** [comment]
Have you tried to do 

```
yarn
yarn build
```

Then try to run it with electron

**Comment by dgolovin** [comment]
I have to rebase this and try if it stiil works after migration to pnpm.

**Comment by dgolovin** [comment]
Verified current version with this pr and it works for me the same way. Podman desktop starts almost instantly and works in close to production env loading podman desktop from filesystem.

See how to test it in PR description.

**Review by benoitf — APPROVED** [review]
good timeframe to merge this PR long time before 1.14.0

**Pull request merged**
