### PR TITLE
fix: avoid electron popups when closing the window with exit on close

### LINKED ISSUE #7756: Error popup displayed after closing PD 1.11 application
### Bug description

When I close the PD application 1.11 on macOS, I'm always getting the popup error from below

image (6)

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Install PD 1.11 version on macOS using universal dmg.
2. Open the app.
3. Close the app (ensure that the `Close on Exit` option is enabled)
4. Notice that the error popup is displayed after PD closes.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
avoid electron popups when closing the window with exit on close
- do not propagate the event
- only send data to the window if it's not destroyed

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/7756

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by benoitf** [comment]
adding @feloy on the review as he was able to reproduce the issue

**Comment by feloy** [comment]
The app still crashes with this patch for me

**Comment by feloy** [comment]
```
Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Electron [4690]

Application Specific Information:
abort() called


Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18c836a60 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18c86ec20 pthread_kill + 288
2   libsystem_c.dylib             	       0x18c77ba30 abort + 180
3   Electron Framework            	       0x10e3a8480 uv_mutex_lock + 28
4   Electron Framework            	       0x1150c5ec8 napi_release_threadsafe_function + 32
5   fsevents.node                 	       0x1050f0bcc fse_instance_destroy + 120
6   Electron Framework            	       0x1150c7788 node_api_get_module_file_name + 6080
7   Electron Framework            	       0x1150c35c4 node::AsyncResource::CallbackScope::CallbackScope(node::AsyncResource*) + 1364
8   Electron Framework            	       0x1150b9030 node::Stop(node::Environment*, node::StopFlags::Flags) + 6440
9   Electron Framework            	       0x1150c3268 node::AsyncResource::CallbackScope::CallbackScope(node::AsyncResource*) + 504
10  Electron Framework            	       0x1150c6cf4 node_api_get_module_file_name + 3372
11  Electron Framework            	       0x1150c6d4c node_api_get_module_file_name + 3460
12  Electron Framework            	       0x1150c7048 node_api_get_module_file_name + 4224
13  Electron Framework            	       0x10e39ca94 uv_run + 804
14  Electron Framework            	       0x1150a0914 node::SetCppgcReference(v8::Isolate*, v8::Local<v8::Object>, void*) + 48148
15  Electron Framework            	       0x1150a0e5c node::SetCppgcReference(v8::Isolate*, v8::Local<v8::Object>, void*) + 49500
16  Electron Framework            	       0x1150698b8 node::FreeEnvironment(node::Environment*) + 156
17  Electron Framework            	       0x10e542088 node::FreeArrayBufferAllocator(node::ArrayBufferAllocator*) + 22124
18  Electron Framework            	       0x10e49971c v8::BackingStore::MaxByteLength() const + 67196
19  Electron Framework            	       0x1108a7e90 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 9260156
20  Electron Framework            	       0x1108a93c0 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 9265580
21  Electron Framework            	       0x1108a5c30 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 9251356
22  Electron Framework            	       0x10e6e02a0 v8::CodeEvent::GetScriptLine() + 396700
23  Electron Framework            	       0x10e6e15a4 v8::CodeEvent::GetScriptLine() + 401568
24  Electron Framework            	       0x10e6e1158 v8::CodeEvent::GetScriptLine() + 400468
25  Electron Framework            	       0x10e6dfaa8 v8::CodeEvent::GetScriptLine() + 394660
26  Electron Framework            	       0x10e6dfd0c v8::CodeEvent::GetScriptLine() + 395272
27  Electron Framework            	       0x10e3ad63c ElectronMain + 180
28  dyld                          	       0x18c4e60e0 start + 2360

[...]
```

**Comment by benoitf** [comment]
ok I also got this error from time to time as well. (I got different crash reports) but I no longer reproduce the issue on my end.

did you tried with the `yarn watch` mode or with the binary/production mode being produced ? 

the `node_api_get_module_file_name` may indicate that there is a problem in a native module.

could you try the command `find . -type f -name "*.node"` 

and then try to remove some .node file one by one like
`rm ./node_modules/cpu-features/build/Release/cpufeatures.node` and try again ?

**Comment by feloy** [comment]
Removing the file `./node_modules/fsevents/fsevents.node` fixes the problem on your branch.

Steps to reproduce:
```
$ rm -rf node_modules
$ yarn
$ yarn watch
# Close window => Crash
```

```
$ rm -rf node_modules
$ yarn
$ rm ./node_modules/fsevents/fsevents.node
$ yarn watch
# Close window => No crash
```

**Comment by feloy** [comment]
A few more tests results:

- with the second commit (use latest fsevents), no changes
- with `yarn compile:current` and running the compiled app, the problem is reproducible every time on main, but I haven't seen it on this branch (with/without latest fsevents), making the test several times

**Comment by benoitf** [comment]
@feloy anyway using latest fsevents using resolution would not work on Linux so I reverted to my original patch.

On my end without this current patch I got error (when clicking quit on the tray icon (fixed by the isDestroyed check)) and then crash error being fixed using the preventDefault.

If it works on production now maybe it'll still be a good improvement to merge this PR then

**Review by feloy — APPROVED** [review]
Fixes the problem for production app

(the problem still exists when using `yarn watch` )

**Pull request merged**
