### PR TITLE
feat: add experimental flag to install podman v5

### LINKED ISSUE #6375: should allow to install podman v5 using an experimental flag
### Is your enhancement related to a problem? Please describe

To make the migration from v4 to v5, it should be possible to have podman v5 embedded so we can do the tests in term of release, fetching artifacts, etc.

### Describe the solution you'd like

add an experimental flag to enable Podman v5 installer

if enabled it should allow to update to v5, do all the save/restore flow, etc.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
if toggling the flag in preferences, it'll register the 'update to v5.0.0'

depends on this PR
- [x] https://github.com/containers/podman-desktop/pull/6475
for better result

### Screenshot / video of UI

image

image

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/6375

### How to test this PR?

you can run Podman Desktop and toggle the flag then you should see "Update to 5.0.0" flag
if you don't see it immediately, refresh the UI of the client or apply https://github.com/containers/podman-desktop/pull/6475 before

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM
I have some other issues like i cannot create a podman machine 😓 but it installed podman 5 correctly

**Review by deboer-tim — APPROVED** [review]
It worked for me, and I was able to install Podman 5 (and create/start a machine).

Only nit: "V5" isn't a great name for the property in the UI. Something like 'experimental' would work better, but then wouldn't be a v5 specific property so may not be a better choice.

**Comment by benoitf** [comment]
ExperimentalV5 would be better as property name displayed in the UI ?

**Comment by vzhukovs** [comment]
Maybe `V5` -> `Experimental Support` and get rid of `(experimental)` in property description? Wdyt?

**Comment by benoitf** [comment]
@vzhukovs it displays only the last 'word' so it'll display either `V5` or `Experimental` if we call it foo.experimental.v5 or foo.experimental.v5

**Comment by deboer-tim** [comment]
This is why I had an issue open a while ago to be able to supply a 'display name' 😆. V5 or ExperimentalV5 are likely the best we can do and I'm fine with either.

**Comment by vzhukovs** [comment]
> @vzhukovs it displays only the last 'word' so it'll display either `V5` or `Experimental` if we call it foo.experimental.v5 or foo.experimental.v5

Then, V5 sounds better

**Comment by cdrage** [comment]
> > @vzhukovs it displays only the last 'word' so it'll display either `V5` or `Experimental` if we call it foo.experimental.v5 or foo.experimental.v5
> 
> Then, V5 sounds better

👍 on just V5

**Comment by benoitf** [comment]
ok so it seems the consensus is that I keep as it is

I'll merge tomorrow unless someone will request changes

**Pull request merged**
