### PR TITLE
feat: adds ability to view pod logs

### PR DESCRIPTION
**Pull request by cdrage**
feat: adds ability to view pod logs

### What does this PR do?
- When viewing a pod, logs will show all containers log outputs with the
  container name appended to the beginning
- By default, when clicking on Pod details, it will now show the pod
  logs

### Screenshot/screencast of this PR

https://user-images.githubusercontent.com/6422176/210870034-d2707403-66a6-48c6-9ff8-b6f0bea8418b.mov

### What issues does this PR fix or reference?

Fixes 1/2 of https://github.com/containers/podman-desktop/issues/391

The other part (filter based on container name) will have to mock up
UX/UI before implementation

### How to test this PR?

1. Run two containers that echo the date: `podman run -d alpine sh -c
"while true; do date +%s; sleep 2; done"`
2. Podify it within Podman Desktop
3. View the Pod details

### CODE REVIEW

**Comment by benoitf** [comment]
should we have different output color for each container ?

**Comment by cdrage** [comment]
Sure, the name in the logs, not the output correct? Similar to Docker Compose?

**Comment by benoitf** [comment]
I was thinking also a different output 
Like all lines of container1 in white, all lines of container 2 in yellow etc.

In addition yes the container name

**Comment by cdrage** [comment]
> I was thinking also a different output Like all lines of container1 in white, all lines of container 2 in yellow etc.
> 
> In addition yes the container name

I've updated the PR to colourize the container name. Made it similar to how Docker Compose does it with colourized names. 

Perhaps we can update the colourized terminal output as well as the "filter by container name" in a separate PR after discussions with the UX/UI team?

**Comment by benoitf** [comment]
for sure it's not blocking the PR, was just thinking 🤔

**Review by benoitf — APPROVED** [review]
works fine

maybe colors should be adapted as it looks hard to read the text and few color difference between the two containers/output

image

**Comment by cdrage** [comment]
> works fine
> 
> maybe colors should be adapted as it looks hard to read the text and few color difference between the two containers/output
> 
> image

You're right, they don't appear great! 

I've updated the code to more readable colours, as well as using the colours based upon the order in the array instead instead of calculating it based upon the container name. This makes the colours more predictable and consistent. I also do not include hard-to-read colours such as red or blue and rather use magenta and cyan.

**Comment by cdrage** [comment]
Here's the updated example output:

Screenshot 2023-01-06 at 8 35 54 AM

**Comment by benoitf** [comment]
the colors are looking way better now 🎉

**Comment by cdrage** [comment]
Awesome! Thanks for the approval. Let's keep this open and merge on Monday, we all know how it's like to merge on a Friday with a new feature 🤣

**Comment by slemeur** [comment]
Really cool !

**Pull request merged**
