### PR TITLE
chore: always show image push button

### LINKED ISSUE #5506: Should be able to push without being authenticated (just show error)
### Is your enhancement related to a problem? Please describe

I thought there was a bug when my "Push Image" button had disappeared.

Screenshot 2024-01-11 at 11 51 27 AM

But in the end, it was because I was not authenticated to the proper registry.

### Describe the solution you'd like

I should be able to see and be able to use the button, but upon clicking, show a warning that you are not logged in / authenticated and to click the registries section / fix it before you try and push.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
chore: always show image push button

### What does this PR do?

* Allows the image push button to always appear
* Instead, we will show an unauthenticated warning in the modal with the
  button disabled, if the image is unauthenticated / unable to push to a
  registry.

### Screenshot / video of UI

https://github.com/containers/podman-desktop/assets/6422176/b9438d2f-0f74-45fd-98c9-8aef3e02c0aa

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/5506

### How to test this PR?

1. Go to push on any image, the push button should be there.
2. If unauthenticated, the warning should appear.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by benoitf** [comment]
need to be reviewed by UX team cc @mairin

**Comment by jeffmaury** [comment]
I had quay.io configured (which I don't know if credentials are ok) but push never finished either positively or negatively

push

Update: CLI rejects so seems the credentials are not valid

image

**Comment by cdrage** [comment]
> I had quay.io configured (which I don't know if credentials are ok) but push never finished either positively or negatively
> 
> push [ push ](https://private-user-images.githubusercontent.com/695993/302551936-83744771-0469-468d-9bbb-63e2cc3b9515.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU3NDEsIm5iZiI6MTcwNzIyNTQ0MSwicGF0aCI6Ii82OTU5OTMvMzAyNTUxOTM2LTgzNzQ0NzcxLTA0NjktNDY4ZC05YmJiLTYzZTJjYzNiOTUxNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMzE3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjljMTMyNTk0OTFjY2Q1NmY5OWRjYThjOWRlMjdhYzQwMWEyMDkzNzQ0NDZmZTYwNGE4ZWY0MTYyYjM0OWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2OAVCN8XUCD-LAkeccOxRgkV0upnlSTKLN_KbwCTrLA) [ ](https://private-user-images.githubusercontent.com/695993/302551936-83744771-0469-468d-9bbb-63e2cc3b9515.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU3NDEsIm5iZiI6MTcwNzIyNTQ0MSwicGF0aCI6Ii82OTU5OTMvMzAyNTUxOTM2LTgzNzQ0NzcxLTA0NjktNDY4ZC05YmJiLTYzZTJjYzNiOTUxNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMzE3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjljMTMyNTk0OTFjY2Q1NmY5OWRjYThjOWRlMjdhYzQwMWEyMDkzNzQ0NDZmZTYwNGE4ZWY0MTYyYjM0OWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2OAVCN8XUCD-LAkeccOxRgkV0upnlSTKLN_KbwCTrLA)
> 
> Update: CLI rejects so seems the credentials are not valid
> 
> image

Looks like you discovered a new bug outside of the PR, I've created this issue: https://github.com/containers/podman-desktop/issues/5876

**Comment by mairin** [comment]
## UX review

### dropdown component padding issue

image

(is this better filed in a separate issue?)

### alignment / design of warning

So this is an example of a dialog with form elements from the style guide that has error messages - it does feel like it should be left aligned:

image

So here would be my suggestion if possible:

image

**Comment by cdrage** [comment]
> ## UX review
> ### dropdown component padding issue
> image
> 
> (is this better filed in a separate issue?)
> 
> ### alignment / design of warning
> So this is an example of a dialog with form elements from the style guide that has error messages - it does feel like it should be left aligned:
> 
> image
> 
> So here would be my suggestion if possible:
> 
> image

That looks much cleaner! I'll start work on implementation later this week.

**Comment by deboer-tim** [comment]
Why is push image a dialog instead of a form like pull or build? Is there a general guideline on the number of controls or other reasons why it's done this way?

**Comment by cdrage** [comment]
> Why is push image a dialog instead of a form like pull or build? Is there a general guideline on the number of controls or other reasons why it's done this way?

Unsure, WDYT about dialog vs form / should we do it in this PR or separate? @mairin

**Comment by mairin** [comment]
@cdrage @deboer-tim heh! For consistency it probably should be a form page! Do you need a design for that @cdrage ?

**Comment by benoitf** [comment]
I'm not sure about 'consistency'

I think I would like to stay in the image list page (or where I am) when I push an image, not go elsewhere
I don't see what a form would bring as advantage. I see only cons there (more clicks)

**Comment by mairin** [comment]
Let's keep the dialog then!

**Comment by deboer-tim** [comment]
A form should be identical # of clicks or we're doing something wrong. FWIW I do find it odd that it's different, but part of that is also down to it being modal-ish and not having a task. It shouldn't be part of this PR anyway so I am fine keeping the dialog.

**Comment by cdrage** [comment]
https://github.com/containers/podman-desktop/assets/6422176/3e1d4db6-79db-4607-91c1-9c5a0ad19e6c

Updated the UI!

@mairin should resemble almost 1-1 to what your mockup is. I wanted to make the changes for the entire modal as well.

**Comment by mairin** [comment]
@cdrage looking great!!!

**Review by benoitf — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM. The only remark is that it tells me No registry found but when I go to Registries I can see quay.io (but not configured)

**Comment by mairin** [comment]
Would it make sense instead to say, "No registry with push permissions
found." ?

**Comment by cdrage** [comment]
> Would it make sense instead to say, "No registry with push permissions found." ?

Updated! 👍

**Comment by cdrage** [comment]
Rebased, have two approvals and tests are passing! Enabling auto-merge 👍

**Pull request merged**
