### PR TITLE
fix: use machine.Name to form engineId to retrieve info

### LINKED ISSUE #9030: podman resource usage is broken
### Bug description

I receive in the devconsole

```
Can't get machine podman-machine-default resource usage error Error: no engine matching this container
```

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

try to see usage of the podman machine for the default machine

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

Fixes #9030. Not sure if that correct fix, but it helps clean up console output for me.

### What issues does this PR fix or reference?

#9030.

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM, maybe updating a test to check if info is called with the expected arg?

**Review by axel7083 — APPROVED** [review]

**Review by jeffmaury — COMMENTED** [review]
Code look good but I am still getting the error (after the machine is created)

**Comment by dgolovin** [comment]
> Code look good but I am still getting the error (after the machine is created)

There are multiple errors created in container-registry.ts. You can try to pull this branch https://github.com/containers/podman-desktop/compare/main...dgolovin:clean-up-error-messages-in-info-container-registry?expand=1 with rebase on top of this one to see more detailed message.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
