### PR TITLE
chore: remove core values

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Removes core values from the website as it doesn't make sense anymore and will free up space in the header.

### Screenshot / video of UI

Before:

Screenshot 2024-09-19 at 11 45 33 AM

After:

Screenshot 2024-09-19 at 11 45 18 AM

### What issues does this PR fix or reference?

Part of #5761.

### How to test this PR?

`pnpm website:dev` and confirm section is gone / no visual issues.

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by benoitf — APPROVED** [review]

**Review by axel7083 — APPROVED** [review]
LGTM !!

**Comment by benoitf** [comment]
I see core values in some search engine, should we add a redirect to other pages when people will reach core value. page that has been removed ?

**Comment by axel7083** [comment]
I think this would be nice to avoid 404

**Comment by deboer-tim** [comment]
Agreed, I'll put up a separate PR and redirect to the homepage.

**Comment by benoitf** [comment]
created https://github.com/containers/podman-desktop/issues/9084

**Pull request merged**
