### PR TITLE
docs: use relative links starting by `/` for internal links

### LINKED ISSUE #4005: docs: use relative URLs starting by `/` for internal links
### Is your enhancement related to a problem? Please describe

Relative might have unpredictable results. For instance all relative internal links would fail if we enable the `trailingSlash` option.

### Describe the solution you'd like

Use absolute URLs for internal links.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by themr0c**
### What does this PR do?

docs: use relative links starting by `/` for internal links, rather than links pointing directly to the file name or links pointing to the FQDN URL.

### What issues does this PR fix or reference?

fixes #4005

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
to me it's using relative links and not absolute links

**Review by benoitf — COMMENTED** [review]
my main question is: how do we ensure that we always use relative links when referencing podman-desktop.io links ?

because new blog post will be written, etc.

**Comment by themr0c** [comment]
> To me it's using relative links and not absolute links

True hat. I mean starting by a slash. How would you say that?

> How do we ensure that we always use relative links when referencing podman-desktop.io links?

We have nothing at the moment.
We could add a project specific Vale rule.

**Comment by themr0c** [comment]
Fixed local build. Dividing all links related changes into multiple pull requests has been a source of errors and mistakes.

**Review by benoitf — APPROVED** [review]

**Comment by deboer-tim** [comment]
> > To me it's using relative links and not absolute links
> 
> True hat. I mean starting by a slash. How would you say that?

I was confused when I saw the original title in my inbox, because why would we ever use absolute links? ;-)

Yes, these are relative links, specifically root-relative (i.e. everything relative to the hostname).

> > How do we ensure that we always use relative links when referencing podman-desktop.io links?
> 
> We have nothing at the moment. We could add a project specific Vale rule.

+1, but not via this PR of course.

**Review by deboer-tim — APPROVED** [review]
Big +1 to replacing the absolute `https://` links. I don't think we really needed to change the relative links to root-relative links, but this does make everything consistent.

**Pull request merged**
