### PR TITLE
chore(UI): migrate spinner to UI package

### LINKED ISSUE #6897: Implement Spinner UI component

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Move the Spinner.svelte component from the renderer to the ui package.

Plus adding the $$props.class and $$props.style for better usage

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/6897

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by benoitf** [comment]
will be post 1.10

**Comment by axel7083** [comment]
1.10 has been released 🚀

**Comment by axel7083** [comment]
Tag [v1.10.0 🥳](https://github.com/containers/podman-desktop/commit/3c29884f932e7bb29ee818dcd9cf7a0d4f110d32) has been released !

**Review by benoitf — COMMENTED** [review]
should we have a minimal unit test for Spinner ?

**Comment by axel7083** [comment]
> should we have a minimal unit test for Spinner ?

Everything is possible 🙈 @benoitf

**Comment by benoitf** [comment]
> Tag [v1.10.0 🥳](https://github.com/containers/podman-desktop/commit/3c29884f932e7bb29ee818dcd9cf7a0d4f110d32) has been released !

sorry, I think I wasn't clear enough when speaking about 1.10 being released. It was not for `1.10.0` but the one that will be promoted (so if we need any backport it's very easy)

**Review by benoitf — APPROVED** [review]

**Pull request merged**
