### PR TITLE
website: updated images with latest screenshots for the Features section

### PR DESCRIPTION
**Pull request by deekay2310**
Signed-off-by: Dev Kumar <devskumar99@gmail.com>

### What does this PR do?
Updated the images for the Features page with the screenshots from the latest build

### Screenshot/screencast of this PR

Screen Shot 2022-10-20 at 12 27 46 PM
Screen Shot 2022-10-20 at 12 27 51 PM
Screen Shot 2022-10-20 at 12 27 54 PM
Screen Shot 2022-10-20 at 12 27 57 PM
Screen Shot 2022-10-20 at 12 28 00 PM

### CODE REVIEW

**Comment by deekay2310** [comment]
Screen Shot 2022-10-20 at 1 01 28 PM

**Comment by cdrage** [comment]
New screenshots look great! My only criticism is the one screenshot that's *really* blue, perhaps we can change that to a more darker format to match all the other screenshots?

image

**Comment by deekay2310** [comment]
Screen Shot 2022-10-21 at 11 05 05 AM
 matched the theme for tray icon image

**Review by cdrage — APPROVED** [review]

**Comment by cdrage** [comment]
Looks great! Thanks for making the change too

**Comment by slemeur** [comment]
LGTM

**Review by slemeur — APPROVED** [review]

**Pull request merged**
