### PR TITLE
fix: avoid to crash if configuration is invalid

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
do not stop if config file is corrupted

### What issues does this PR fix or reference?

could be related to https://github.com/containers/podman-desktop/issues/4649

### How to test this PR?

unit test provided

manual testing:
Edit podman settings file and use invalid values ( ~/.local/share/containers/podman-desktop/configuration/settings.json)

before the patch: unable to start
after the patch: able to start

### CODE REVIEW

**Review by cdrage — APPROVED** [review]
Works and I was able to start PD fine,

Should we warn somewhere within PD we have a corrupted configuration file so we can save / read correctly from it? 

When saving a new configuration, won't it override the "corrupt" one?

For example:

1. Start PD with corrupt
2. PD sets it to `configData = {};`
3. PD "clears" the corrupted one rather than warn.

**Comment by benoitf** [comment]
I think that if you do changes it'll override the file with a valid content

**Review by jeffmaury — APPROVED** [review]
LGTM. The only concer I have is that the old content is lost, maybe we should backup it and inform user but could be a follow up PR

**Comment by benoitf** [comment]
@jeffmaury 

I've added changes to the PR, it will display a notification + do a backup of the corrupted file

**Comment by benoitf** [comment]
@jeffmaury @cdrage you approved but I added stuff so probably good to review it again

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by cdrage** [comment]
Tested and viewed the new changes. LGTM!

**Pull request merged**
