### PR TITLE
fix: container details terminal flaky test on macos

### LINKED ISSUE #10405: flaky test in `ContainerDetailsTerminal.spec.ts:236:55` on macos
### Bug description

I see often the [unit tests / macos-15](https://github.com/podman-desktop/podman-desktop/actions/runs/12375466605/job/34540333141?pr=10403#logs) being flaky, the problematic test seems to be the following

https://github.com/podman-desktop/podman-desktop/blob/455637a329078d773244291d944aa9d566174e2e/packages/renderer/src/lib/container/ContainerDetailsTerminal.spec.ts#L193

### Operating system

MacOS

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

```shell
Error: Error: expect(element).toHaveTextContent()

Expected element to have text content:
  hello world
Received:


Ignored nodes: comments, script, style
<html>
  <head />
  <body>
    <div>
      <div
        class="h-full p-[5px] pr-0 bg-[var(--pd-terminal-background)]"
      >
        <div
          class="terminal xterm xterm-dom-renderer-owner-4"
          dir="ltr"
        >
          <div
            class="xterm-accessibility"
          >
            <div
              class="xterm-accessibility-tree"
              role="list"
            >
              <div
                aria-posinset="1"
                aria-setsize="24"
                role="listitem"
                tabindex="-1"
              />
              <div
                aria-posinset="2"
                aria-setsize="24"
                role="listitem"
                tabindex="-1"
              />
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

So while trying to find the root cause of https://github.com/podman-desktop/podman-desktop/issues/10405 I changed a bit the `ContainerDetailsTerminal.spec.ts`.

After searching... I think I have found the root cause of the flakyness;

We have a dedicated store `containerTerminals` that we use to store the current connection. This work nicely, but we forgot to reset the store between the tests, so we often have duplicate data. 

The previous test write `hello\nworld` the second `hello world`, so at the end the div.textContent is `hello\nworldhello world`, this is flaky for an unknown reason, I was able to reproduce it on windows by mixing some stuff, it also seems that the way the terminal display the text may not be detemrinistic, we may have once `<div>hello world</div>` on a run, and on another `<div>hello</div><div>world</div>`, so I created a function `getBySpreadText` based on https://stackoverflow.com/a/75873171.

While searching I updated the tests to use vi.mocked(windows)

### What issues does this PR fix or reference?

Fixes https://github.com/podman-desktop/podman-desktop/issues/10405

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by axel7083** [comment]
I restarted multiple time the `unit tests / macos-15`

- [x] https://github.com/podman-desktop/podman-desktop/actions/runs/12377260061/job/34547327924?pr=10407 ✅ 
- [x] https://github.com/podman-desktop/podman-desktop/actions/runs/12377260061/job/34547760014?pr=10407 ✅ 
- [x] https://github.com/podman-desktop/podman-desktop/actions/runs/12377260061/job/34548273983?pr=10407 ✅ 
- [x] https://github.com/podman-desktop/podman-desktop/actions/runs/12377956438/job/34548723495?pr=10407 ✅

**Review by gastoner — APPROVED** [review]
Those texts in the terminal :D 
Codewise LGTM

**Comment by benoitf** [comment]
if the fix is

```
  // reset
  containerTerminals.set([]);
```

I would like to keep only this data and separate the refactoring. Because here 90% of the code looks like to be refactoring

**Comment by axel7083** [comment]
> I would like to keep only this data and separate the refactoring. Because here 90% of the code looks like to be refactoring

We can try, but there is a probability the refactoring has a sideeffect to fix the code too.

**Comment by axel7083** [comment]
Let's retry several the `unit tests / macos-15` workflow

- [x] https://github.com/podman-desktop/podman-desktop/actions/runs/12391044770/job/34587341724?pr=10407 ✅
- [x] https://github.com/podman-desktop/podman-desktop/actions/runs/12391044770/job/34588035694?pr=10407 ✅
- [x] https://github.com/podman-desktop/podman-desktop/actions/runs/12391044770/job/34588505472?pr=10407

**Review by benoitf — APPROVED** [review]
oops I forgot to hit approved yesterday

**Comment by benoitf** [comment]
okey one more https://github.com/podman-desktop/podman-desktop/actions/runs/12391044770?pr=10407 but all previous run have passed

**Pull request merged**
