### PR TITLE
chore: navitem component

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Created a new NavItem component to replace duplicated code in AppNavigation. Added basic component tests including selection styling and click handler. While I was at it I implemented with Tailwind instead of PF classes.

### Screenshot/screencast of this PR

Before:

https://github.com/containers/podman-desktop/assets/19958075/53965f55-06a8-4bf2-aa3b-61b5e83a3882

After:

https://github.com/containers/podman-desktop/assets/19958075/30a5e0f1-b988-45d4-874b-6ff88589cd35

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Just use the nav, should not be able to tell any difference from before.

### CODE REVIEW

**Comment by mairin** [comment]
I think the hover is too subtle. What would you think about the hover background coloring going purple-500?

**Comment by benoitf** [comment]
tips: @deboer-tim you should add newlines before your screenshots/video links in PR description so that it's displayed inline in the description of the PR, not having users having to download the file

**Comment by deboer-tim** [comment]
> tips: @deboer-tim you should add newlines before your screenshots/video links in PR description so that it's displayed inline in the description of the PR, not having users having to download the file

Updated. Sorry, I had no idea why GitHub was embedding in some cases and not others! 😆

**Comment by benoitf** [comment]
@deboer-tim I wanted to edit the description but then I decided I'll share the info :-)

**Comment by deboer-tim** [comment]
> I think the hover is too subtle. What would you think about the hover background coloring going purple-500?

purple-500 is pretty bold for me, but I agree one of the motivations for the change was so that it'd be possible/far easier to change things like this! It you like it, I will commit.

Screenshot 2023-08-03 at 11 44 09 AM

**Review by lstocchi — APPROVED** [review]
LGTM

**Review by benoitf — APPROVED** [review]
as a follow-up PR, probably need to extract remaining inlined SVGs to separate components

nice job 🎉

**Review by cdrage — APPROVED** [review]

**Pull request merged**
