### PR TITLE
docs: refreshed introduction page

### LINKED ISSUE #5335: Docs: Improve introduction page
### Is your enhancement related to a problem? Please describe

The intro documentation is not welcoming the user and enticing to user the product: https://podman-desktop.io/docs/intro

### Describe the solution you'd like

The introduction is the documentation should provide a good summary of the project and entice the user to read more. From a quick scan of the page, the user might caught interest on the product. 

For this, it’s important that we provide a short introduction of the Project:
- What it is, what it does 
- why we created it
It’s important to differentiate ourselves from the beginning and we should be reusing the talking points we have on the website.

I would add, that we could eventually show a demo of the product, by attaching a link to the youtube short overview from Aine.

Then, we want to guide the user on how to start

We should also provide another set of links:
- Issue tracker
- Troubleshooting
- Community

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by themr0c**
### What does this PR do?

Added content to the introduction page.

### What issues does this PR fix or reference?

fixes #5335

### CODE REVIEW

**Comment by themr0c** [comment]
@cdrage @slemeur At this point, I only added links to the documentation. No additional sentences. Do you agree with the direction it is taking?

**Comment by cdrage** [comment]
> @cdrage @slemeur At this point, I only added links to the documentation. No additional sentences. Do you agree with the direction it is taking?

Unfortunately no, this looks more of a TOC / index page and IMHO should be more of a convincing "Hey! This is the tool and it's cool features!" page.

More of a marketing / sales type page

**Comment by deboer-tim** [comment]
Agreed, we need a short intro page that has a bit of marketing/visual appeal and links you to a few useful places in the docs. This is just a few pages of coloured links.

**Comment by themr0c** [comment]
That's the URL of the video to add, _I think:_ https://www.youtube.com/watch?v=OeJ_cwdoQm8

**Comment by themr0c** [comment]
Video will need another PR, it requires enabling a plugin.

**Review by deboer-tim — CHANGES_REQUESTED** [review]
This is better than before, but it is a wall of text that would take a full minute to read. As a user it's 20 options - I'm very unlikely to read them all and it's listing everything possible, not guiding or helping them get started in any way.

**Comment by themr0c** [comment]
@deboer-tim Can you be more precise on what lines you like and don't like? What could be removed? What could be more concise?

**Comment by themr0c** [comment]
Current state:

Screenshot_20240215_152651

**Review by cdrage — CHANGES_REQUESTED** [review]
I agree with @deboer-tim this is just bullet points and IMHO we should have a few paragraphs detailing Podman Desktop and a nice "introduction" "meaty / feature part" and "conclusion and next steps" or something like that.

Similar to something like: https://kubernetes.io/docs/setup/

Or https://docusaurus.io/docs

Or even this page for react looks nice introducing the product: https://reactnative.dev/docs/getting-started

**Comment by themr0c** [comment]
Adding sections, would it work for you @deboer-tim ?

Firefox_Screenshot_2024-02-15T14-33-48 958Z

**Review by cdrage — CHANGES_REQUESTED** [review]
Way too list based :( IMHO would be more flowey to have it paragraphs / sentences / etc just doing a quick summary / introduction to the product.

**Comment by themr0c** [comment]
More like that?

image

**Comment by deboer-tim** [comment]
> Adding sections, would it work for you @deboer-tim ?

Sections just breaks up '20 items' into '20 items in different sections'. Visually it looks a little nicer but it's not addressing the core problem. We don't need every option on the front page, we need something welcoming and giving a few suggestions on how to start.

**Comment by themr0c** [comment]
False start, sorry.

**Pull request closed without merging**
