### PR TITLE
feat: change Kubernetes menu to submenu

### LINKED ISSUE #7759: Kubernetes Navigation: Replace nav sections by group nav item + individual items
### Is your enhancement related to a problem? Please describe

As we grow the set of Kubernetes objects, there are too many to keep in the main nav, even with the current collapsable nav section. However, moving to a single item has the drawback of requiring two clicks to get to anything (feels like a second-class citizen). The current form will also conflict with hiding nav items as we plan in #6774. 

### Describe the solution you'd like

Nav sections should be removed/replaced. Each of the Kubernetes pages should be contributed as separate nav items, and the group should be contributed as a special 'group' nav item. Clicking on a group nav item opens a submenu identical to the look of the Settings or the AI Lab extension today, with a list of all the nav items in the group.

It is important to point out that both the group and each individual nav item are 'regular' nav items. In particular, they could each be added or removed from the main navigation individually as per #7758. Kubernetes would initially appear as just the one group nav item with a submenu, but here are some examples of what the user could do:
- Add Deployments and Services to the main nav, while keeping the Kubernetes group also visible (to get to all of the other items).
- Add Nodes to the main nav and hide the Kubernetes group, because they're only using nodes at the moment.
- Hide everything, because they're not using Kubernetes.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Change Kubernetes menu to submenu

### Screenshot / video of UI

https://github.com/user-attachments/assets/f2580b81-746b-4456-9ce3-6c16e14034cd

### What issues does this PR fix or reference?

Fixes #7759 

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — COMMENTED** [review]
I feel like we should have a default view (E.g. Node while we do not have the pods) rather than an empty white page for the default.

Otherwise tested locally and LGTM

**Review by benoitf — COMMENTED** [review]
FYI SubmenuNavigation.svelte has no unit tests

about the default view, yes usually we're defaulting the first click to a given page

(like if you open the container's details you land on a given tab)

I'm fine to have a follow-up PR to handle this default landing page as it seems it might be the pod view and with this PR there is no pod view (as expected for the issue)

**Comment by feloy** [comment]
> FYI SubmenuNavigation.svelte has no unit tests
> 
Added, thanks

> about the default view, yes usually we're defaulting the first click to a given page
> 
> (like if you open the container's details you land on a given tab)
> 
> I'm fine to have a follow-up PR to handle this default landing page as it seems it might be the pod view and with this PR there is no pod view (as expected for the issue)

Or a welcome page (#8825)

**Review by benoitf — APPROVED** [review]

**Review by axel7083 — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
