### PR TITLE
feat: add Play Kubernetes YAML to pod navigation

### LINKED ISSUE #540: Provide "Play YAML" action on the "Pod" view
### Is your enhancement related to a problem? Please describe

As a user, if I know I'm going to run a Pod, I'm most likely going to the "Pod" view and will expect to find actions to use start my Pods from there.

Today, the user has to go into the "Containers" view and then eventually switch back to the "Pods" view.

### Describe the solution you'd like

Add a button "Play YAML" on the "Pods" view

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
feat: add Play Kubernetes YAML to pod navigation

### What does this PR do?

* Refactors the Kubernetes-specific actions, to a new folder named
  `kube`
* Adds a button to Play Kubernetes YAML on the pod navigation screen

### Screenshot/screencast of this PR

Screen Shot 2022-10-31 at 10 53 38 AM

### What issues does this PR fix or reference?

Fixes #540

### How to test this PR?

Run `yarn watch`

### CODE REVIEW

**Comment by benoitf** [comment]
FYI both DCO and linters/formatters are failing

**Comment by mairin** [comment]
Would a play icon work better? At that scale the kube icon is hard to make out. Smtg like

https://fontawesome.com/icons/play?f=classic&s=solid

**Comment by cdrage** [comment]
> FYI both DCO and linters/formatters are failing

Weird! Ran it before pushing. Rebased and pushed again. Thanks!

**Comment by cdrage** [comment]
> 

It would! Although I think that @benoitf has been using the rocket symbol lately? WDYT? Rocket or play symbol?

**Comment by cdrage** [comment]
> Would a play icon work better? At that scale the kube icon is hard to make out. Smtg like
> 
> https://fontawesome.com/icons/play?f=classic&s=solid


It would! Although I think that @benoitf has been using the rocket symbol lately for Kubernetes? WDYT? Rocket or play symbol?

**Comment by benoitf** [comment]
rocket was to 'deploy to kubernetes'

here the play button is to play the pod on the instance of podman.
so it makes sense to use play icon as well.
we also have the play icon used to start an existing pod or a container (that is stopped). Is it OK ?

**Review by benoitf — APPROVED** [review]
Tested

image

Icon change can be a follow-up PR

**Pull request merged**
