### PR TITLE
docs: added license to the core values page

### LINKED ISSUE #4096: website: add License page
### Is your enhancement related to a problem? Please describe

It looks like we would need a License page on the website, people are searching for it (License and Licence words).

### Describe the solution you'd like

Add a License page to the website.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by themr0c**
docs: added license to the core values page

- Added license to the _Core Values_ page.
- Rewritten the _Core Values_ page in markdown for maintainability and readability.

fixes #4096

### CODE REVIEW

**Comment by themr0c** [comment]
Alternate implementation: https://github.com/containers/podman-desktop/pull/4119

**Review by benoitf — CHANGES_REQUESTED** [review]
please don't rewrite in markdown TSX page

**Comment by themr0c** [comment]
Why? What is the added value of TSX over markdown in this case?

**Comment by benoitf** [comment]
b/c the look and feel is broken

original layout:

Screenshot 2023-09-27 at 13 58 51

After your changes
Screenshot 2023-09-27 at 13 58 23

**Comment by benoitf** [comment]
and again, you're mixing changes

we do not change and introduce something new at the same time

one PR would be to switch to MD but it's not the idea, website is having fine grained UI elements
one PR is to contribute the addition (you only added 5 lines about the Apache License)

**Comment by themr0c** [comment]
The TSX file in insanely complex to edit.

The content is the same.
Icons updated to icons that are semantically more correct. 
The new presentation is more readable.

**Pull request closed without merging**
