### PR TITLE
fix: update cli management in kind extension

### LINKED ISSUE #8609: kind should uses the CLI installer instead of the statusbar
### Is your enhancement related to a problem? Please describe

See title

### Describe the solution you'd like

Thanks to https://github.com/containers/podman-desktop/pull/8534 we no longer need the statusbar to indicate a tool is not installed

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

It updates the kind extension to use the new install/update/uninstall features for cli tools

### Screenshot / video of UI

kind_cli_tool

### What issues does this PR fix or reference?

it resolves #8609 

### How to test this PR?

1. try to install/upgrade/uninstall kind
2. if kind has been installed by the user in a different folder, you should not be able to update/uninstall it

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by benoitf** [comment]
it looks like we have changes not related to kind extension

so should we have stuff in core and then another that is doing the stuff for kind

**Comment by lstocchi** [comment]
Gonna rebase when https://github.com/containers/podman-desktop/pull/8682 and https://github.com/containers/podman-desktop/pull/8683 are merged

**Comment by lstocchi** [comment]
I merged the other 2 PRs quickly as i'm going on PTO and didn't want to leave too many things open and they were minor things.
Feel free to merge/update/fix this PR when i'm away. Thanks!!

**Review by gastoner — APPROVED** [review]
LGTM, tested on Windows!

**Review by axel7083 — COMMENTED** [review]
Do we support having kind not installed in system-path ?

I tried to install it, without root privilege and got the following

image

> Might not be related to this PR ?

**Comment by lstocchi** [comment]
> Do we support having kind not installed in system-path ?
> 
> I tried to install it, without root privilege and got the following

You're right. System-wide is not mandatory, the user can also cancel the system-wide installation but if the binary has been installed in the podman extension folder is fine. Updated 👍

**Review by axel7083 — APPROVED** [review]
LGTM, tested locally and works fine for system wide and local.

> We could improve this in the future by having some indicator that the executable is installed system wide. Worth creating an issue ?

**Comment by lstocchi** [comment]
> We could improve this in the future by having some indicator that the executable is installed system wide. Worth creating an issue ?

i opened https://github.com/containers/podman-desktop/issues/8901

**Pull request merged**
