### PR TITLE
feat: nav sections

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Nav sections component. Every section starts collapsed and can be expanded to show a set of child nav items. We didn't have a complete design for this to I've tried a few things and ran them past Mairin briefly. State changes are animated, and selection styling updated to use purple outlines instead of left border.

Switched Docker Desktop extensions to use a section (and so that there is something to easily test here), using a new puzzle icon from Mairin (FA only has a solid puzzle). Kubernetes will be done in another PR.

This doesn't directly solve the problem that you could have so many icons that it doesn't fit onscreen, but as we have more sections they start closed and you can at least close most of them to help make sure the thing you need is visible.

### Screenshot / video of UI

https://github.com/containers/podman-desktop/assets/19958075/df73ef69-5340-41fb-92bb-f7e14455242c

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Install at least one docker desktop extension. Expand/collapse to see how it looks.

### CODE REVIEW

**Comment by deboer-tim** [comment]
Updated and rebased on main, removing draft status as this is now ready for review.

**Comment by deboer-tim** [comment]
Added more space between the icon and control as discussed:

Screenshot 2024-01-18 at 11 27 25 AM

Rebased and force-pushed to fix merge conflict.

**Comment by mairin** [comment]
> Added more space between the icon and control as discussed:
> 
> Screenshot 2024-01-18 at 11 27 25 AM
> 
> Rebased and force-pushed to fix merge conflict.

I might even do a little less padding between the arrow and the bottom of the area?

**Comment by slemeur** [comment]
that's pretty cool!

**Review by cdrage — APPROVED** [review]
I was able to test this out and it dropped down like normal, no issues with the UI.

Re-approving again :)

**Comment by deboer-tim** [comment]
Reduced spacing between arrow and bottom as suggested, and rebased.

**Comment by deboer-tim** [comment]
Current screen caps/video:

Screenshot 2024-01-21 at 10 58 01 AM
Screenshot 2024-01-21 at 10 58 10 AM

https://github.com/containers/podman-desktop/assets/19958075/8fc27574-f9e6-4ec0-806f-f8ee413c25f2

@mairin ok to approve?

**Comment by mairin** [comment]
> @mairin ok to approve?

💯 it's *perfect*!

**Comment by benoitf** [comment]
I believe it should only be applied for Docker Desktop extensions only if we have more than 1 item

If I only have one extension, it's taking the same height, but I need an extra click to see/use my extension so it's not convenient at all

**Comment by benoitf** [comment]
so probably it should be in expanded mode by default in that case

image

**Comment by benoitf** [comment]
it looks like it's moving the overall height when clicking on the chevron


https://github.com/containers/podman-desktop/assets/436777/1f5c9330-d97e-4354-af26-f8bfa194c3b4

**Comment by benoitf** [comment]
moved feedback to https://github.com/containers/podman-desktop/issues/5618

**Pull request merged**
