### PR TITLE
fix: remove PORT label from port value (#712)

### LINKED ISSUE #712: Ports not created after importing Kubernetes YAML
### Bug description

After uploading YAML file Images are pulled and pod with containers are created, but no ports were opened.

### Operating system

Windows 10 Wnterprise

### Version

0.9.0

### Steps to reproduce

Start new clean machine. (optional)

Go to "Containers" tab then
Click on "Play Kubernetes YAML"
Upload file.
[itrix_gh.yaml.txt](https://github.com/containers/podman-desktop/files/9878389/itrix_gh.yaml.txt)

Expected result 1:
- When I go to Containers
- Open one container
- Go to "Details" tab
- "Ports" Should list ports instead of N/A

Expected result 2:
- Pod should have open ports 80 and 443

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

It removes the label PORT from the container port value

### Screenshot/screencast of this PR

Before:
immagine

After:
immagine

### What issues does this PR fix or reference?
it closes #712 

### How to test this PR?

Open the container details page of a container that has atleast a port. Check there is no extra PORT label

### CODE REVIEW

**Comment by benoitf** [comment]
note that it's gonna remove the PORT: in the container list view as well as a side effect
image

**Comment by lstocchi** [comment]
> note that it's gonna remove the PORT: in the container list view as well as a side effect image

my bad, thanks for pointing me to that. Pushed a commit

**Review by benoitf — COMMENTED** [review]
maybe we could have two properties in ContainerInfoUI 

we shouldn't do much processing in the svelte part

Could have like another `displayPort` property or a getPort() method with a flag that includes the prefix or not

**Review by benoitf — APPROVED** [review]
Screenshot 2023-02-19 at 06 25 25

Screenshot 2023-02-19 at 06 25 20

checked it works in details page and in container list page

**Pull request merged**
