### PR TITLE
fix: duplicated_indeterminate_progress_bar

### LINKED ISSUE #8193: Duplicated indeterminate progress bar
### Bug description

When creating kind/ minicube cluster/ podman machine,... there is present duplicated indeterminate progress bar, instead of only one progress bar
 

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Settings -> Resources -> Select almost any extension -> Create new -> Create and scroll up 

### Relevant log output

_No response_

### Additional context

https://github.com/user-attachments/assets/711cc3c2-c682-4943-b8f7-24ebf35177ae

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
Fixes  duplicated indeterminate progress bar
### Screenshot / video of UI
Before:

https://github.com/user-attachments/assets/aa1c12fb-074e-42df-954d-54b28853b7c0

After:

https://github.com/user-attachments/assets/33cb9998-6db3-42f3-bee0-b6ff9ad35ec5

### What issues does this PR fix or reference?
Closes #8193 

### How to test this PR?

Settings -> Resources -> Select almost any extension -> Create new -> Create and scroll up (now there should be visible only one progress bar - the one connected with console)

- Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
LGTM

**Review by benoitf — DISMISSED** [review]
it looks like inProgress= is used at various place like CreateVolume 

and FormPage is exposing the property so I think there will be a problem.

**Comment by deboer-tim** [comment]
> it looks like inProgress= is used at various place like CreateVolume
> 
> and FormPage is exposing the property so I think there will be a problem.

Yes, this would remove the (only) progress bar from several other pages.

**Comment by gastoner** [comment]
Is there some place in PD where is only the terminal with progress going, without the topbar progressbar? 
@deboer-tim @benoitf @axel7083

**Comment by deboer-tim** [comment]
> Is there some place in PD where is only the terminal with progress going, without the topbar progressbar? @deboer-tim @benoitf @axel7083

It looks like the only other place where the component is used in onboarding, and it doesn't look like there is another scrollbar there. You'll need to walk through or get feedback from one of the others to see if it still needs a scrollbar there or there is a more generic place like the header that should have one.

**Review by feloy — APPROVED** [review]
LGTM, thanks

**Pull request merged**
