### PR TITLE
fix: Settings page cleanup

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

It was bugging me that the settings/preferences pages all look completely different based on when they were implemented. Even the Registries page that was done fairly recently didn't match the latest Resources page.

This PR does a really quick pass at:
- Making the title, top-spacing, and background match.
- Using the same colour grey box with rounded corners and padding on each page.
- Two really minor things to start making the rest consistent or closer to current design: removed proxy input fields left margin and evened out the right and left padding on Registries.

This pass does not replace a full design cleanup, it just fixes the most glaring differences.

### Screenshot/screencast of this PR

Screenshot 2023-03-24 at 10 09 04 AM
Screenshot 2023-03-24 at 10 09 12 AM
Screenshot 2023-03-24 at 10 18 35 AM
Screenshot 2023-03-24 at 10 18 46 AM
Screenshot 2023-03-24 at 10 18 54 AM

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Click through all the settings pages to make sure they match.

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
when we're not in the settings we are using 

`<NavPage bind:searchTerm="{searchTerm}" title="containers">`

here it looks you applied everywhere the pattern
```svelte
<div class="flex flex-1 flex-col p-2 bg-zinc-900">
  <div>
    <p class="capitalize text-xl">TITLE</p>
    <p class="text-sm text-gray-400"><br /></p>
  </div>
  ```

so I would opt-in for a component so we're sure all settings page are using the same code

**Review by benoitf — APPROVED** [review]
easier to review using the ignore whitespaces

**Comment by benoitf** [comment]
you'll have to fix the formatting issues

**Comment by deboer-tim** [comment]
Fixed the formatting issue. Also opened issue #1826 - I intentionally didn't touch the Resources page since there is other work going on there at the moment, will switch it over to this component later.

**Comment by mairin** [comment]
Just tried this out locally, it looks so much better!! :) One place where I see it's missing is in the individual pages for extensions under the extensions tab like podman, docker, lima, etc.

**Comment by deboer-tim** [comment]
> Just tried this out locally, it looks so much better!! :) One place where I see it's missing is in the individual pages for extensions under the extensions tab like podman, docker, lima, etc.

Yup. I thought we decided to remove those pages so I left them for now and was going to remove as part of issue #1789.

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
FYI you'll need to rebase the PR against the `main` branch (and apply the formatter (including updated rules))

**Comment by deboer-tim** [comment]
Rebased (twice, since the Github web didn't update the first time :) ) to pick up latest changes and formatting.

**Review by benoitf — APPROVED** [review]
reviewed again

https://user-images.githubusercontent.com/436777/228001841-8df58e50-a3e0-4e2e-90e5-84875ccbc9a8.mp4

**Pull request merged**
