### PR TITLE
chore: improve colors of windows titlebar buttons

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
Improves colors of buttons on titlebar to more reflect native colors on Windows

### Screenshot / video of UI
Top: Windows File Explorer
Bottom: PD
image
Screenshot 2024-08-29 123119
Screenshot 2024-08-29 123430
Screenshot 2024-08-29 123633

### How to test this PR?
Open PD on Windows and try to switch between light/dark theme

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
The color of the X is dark when the bg is red in light mode. Would it be possible to have it white?

**Review by axel7083 — COMMENTED** [review]
Maybe those colors should be added to the `tailwind-color-palette.json` ?

**Comment by gastoner** [comment]
> Maybe those colors should be added to the `tailwind-color-palette.json` ?

We were discussing this in https://github.com/containers/podman-desktop/pull/8615 
> Should I add those colors to tailwind-color-palette.json and from there use them in color-registry?
> I would say no as it's not part of the color palette

But mostly it uses colors that are already in the palette

**Comment by gastoner** [comment]
> The color of the X is dark when the bg is red in light mode. Would it be possible to have it white?

Now the text uses this schema https://github.com/containers/podman-desktop/files/15389545/Titlebar.Theming.pdf
But I can try to change it

**Comment by benoitf** [comment]
edited the PR title to replace _ by spaces

**Comment by gastoner** [comment]
Will be rebased after #8677 will be merged

**Review by benoitf — COMMENTED** [review]
it's missing unit test

**Comment by jeffmaury** [comment]
When using Color Picker, I have:
File explorer: c42b1c
This PR (light mode): c13414

**Review by jeffmaury — COMMENTED** [review]
See https://github.com/containers/podman-desktop/pull/8665#issuecomment-2324335901

**Comment by gastoner** [comment]
@jeffmaury Which color picker did you choose? I've used this one https://imagecolorpicker.com/ and I've updated colors (this might differ on various screens?)

**Review by benoitf — APPROVED** [review]
approving from code review POV but on macOS I don't see the color

**Comment by jeffmaury** [comment]
> @jeffmaury Which color picker did you choose? I've used this one https://imagecolorpicker.com/ and I've updated colors (this might differ on various screens?)

I'm using the one from PowerToys

**Comment by gastoner** [comment]
@jeffmaury Updated using ColorPicker from PowerToys!

**Review by axel7083 — APPROVED** [review]
LGTM

**Comment by axel7083** [comment]
_For another PR_ I noticed that the title is not usually matching the windows style

image

**Comment by gastoner** [comment]
Yes I noticed this too, especially the title size (maybe font?)

**Pull request merged**
