### PR TITLE
feat: update podman 5.0.3 to 5.1.1

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

Updates podman to 5.1.1

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#7373 

### How to test this PR?

* Pull the branch for this PR
* Run podman `yarn watch`
* There should be request for update to 5.1.1 on dashboard

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
code is ok but waiting go from @odockal

**Comment by dgolovin** [comment]
Blocked by missing digests in shasum form macOS packages see https://github.com/containers/podman/issues/22887.

**Comment by odockal** [comment]
I am testing this on windows right now. For Mac OS we could need @cbr7 to check it out.

**Comment by odockal** [comment]
And it would be truly good to make sure we got shasums for mac first as @dgolovin pointed out.

**Comment by odockal** [comment]
When trying on windows, I got an error when pressing install Podman button (which also does a requirements check): 
`Error: [main] [podman] The podman extension has not been successfully initialized`.

**Review by odockal — CHANGES_REQUESTED** [review]
Failing to install podman from locally built PD on Windows 10.

**Comment by benoitf** [comment]
looks like there is https://github.com/containers/podman/releases/tag/v5.1.1 a new release

**Comment by dgolovin** [comment]
Updated to 5.1.1. 
shasums file has .pgk file entries, so we are not blocked to merge anymore.

**Comment by dgolovin** [comment]
Checked on Windows 10 Pro and update worked fine no issues.

**Review by axel7083 — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by odockal** [comment]
Am I missing something? If build the code locally: `yarn compile`, I got `Podman Desktop.exe` which seems to be missing the podman installer. Is this expected? Or I need to run `yarn compile:current` or add some other env. var to have it included?

**Comment by jeffmaury** [comment]
> Am I missing something? If build the code locally: `yarn compile`, I got `Podman Desktop.exe` which seems to be missing the podman installer. Is this expected? Or I need to run `yarn compile:current` or add some other env. var to have it included?

run yarn build:extensions:podman to include the bits

**Comment by odockal** [comment]
> > Am I missing something? If build the code locally: `yarn compile`, I got `Podman Desktop.exe` which seems to be missing the podman installer. Is this expected? Or I need to run `yarn compile:current` or add some other env. var to have it included?
> 
> run yarn build:extensions:podman to include the bits

Tried, then `yarn watch` did not work for me. Also, I can see that podman-setup is added into assets folder under `dist/**`. I also tried to download bits from PR: https://github.com/containers/podman-desktop/actions/runs/9374683444/artifacts/1568783336. Downloaded, extracted, run - still cannot get Podman installer to be opened by Podman Desktop. 
Can you please try it yourself @jeffmaury  or anyone with windows? 

If that works for you, it is my local machine problem and we can move on this PR.
Sorry for complications.

**Comment by odockal** [comment]
I can run `podman-setup.exe` on its own from `dist`. So the problem might be for podman extension.

**Comment by jeffmaury** [comment]
Update worked for me and I was able to restart a 5.0.3 machine. However, when I try to create a podman machine, it never completes and I can see the process being spawned but never finishes

**Review by jeffmaury — APPROVED** [review]
Approving

**Comment by odockal** [comment]
So I tried also another windows machine, result is the same.
1. I have downloaded podman-desktop-exe-x64 on the machine, extracted
2. started podman desktop from the executable
3. On dashboard I press Install button
4. Assert: System requirement check passes
5. Assert: Dialog appears in Podman Desktop informing user about an option to install Podman
Actual result: No dialog, it just hangs.
7. Assert: Podman MSI installer is executed and user can install Podman
Actual result: No installer is opened from Podman Desktop. Error with podman extension in the dev console.
Screenshot_20240606_123223

**Comment by odockal** [comment]
I have not problem with this when trying podman 1.10.2 (it offers podman 5.0.2 to install)

**Comment by xbabalov** [comment]
> So I tried also another windows machine, result is the same.
> 
>     1. I have downloaded podman-desktop-exe-x64 on the machine, extracted
> 
>     2. started podman desktop from the executable
> 
>     3. On dashboard I press Install button
> 
>     4. Assert: System requirement check passes
> 
>     5. Assert: Dialog appears in Podman Desktop informing user about an option to install Podman
>        Actual result: No dialog, it just hangs.
> 
>     6. Assert: Podman MSI installer is executed and user can install Podman
>        Actual result: No installer is opened from Podman Desktop. Error with podman extension in the dev console.
>        Screenshot_20240606_123223

I have tried this as well on my Win 11 and I got the exact same issue.

**Comment by odockal** [comment]
Ok. Let's see how it works after being built as nightly. I would fill a bug then if it still happens.

**Review by odockal — APPROVED** [review]

**Pull request merged**
