### PR TITLE
feat: feedback form stores values

### LINKED ISSUE #9192: clicking outside of the feedback form should not close the form
### Bug description

if we open the feedback form and start to fill it then click elsewhere, everything is lost

it should at least notice the user that it's gonna disappear/be closed

### Operating system

macOS

### Installation Method

None

### Version

1.11.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
The feedback form now stores values even if it is closed.

### What issues does this PR fix or reference?
Closes #9192 

### How to test this PR?
Try to fill out the form and then close it and open it again

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by gastoner** [comment]
There are 2 things that I'm not sure about (discussion needed): 
1. I think that the form should be cleared when user submits/sents the form to us/github
2. Both bug and feature shares one form - video

**Comment by gastoner** [comment]
https://github.com/user-attachments/assets/45a065cc-d3f7-4c19-a682-06528b7d0ec1


When switching between feature/bug should both of them have own store? 
What about if user will fill the bug but it is rather a feature? -> should he just change category OR change category and fill out the form aggain?

**Comment by axel7083** [comment]
The issue is named `clicking outside of the feedback form should not close the form`, the discussion in it (https://github.com/podman-desktop/podman-desktop/issues/9192#issuecomment-2428559176) is not talking about storing the forms values in a store.

I am not much in favour creating a store, it add complexity to the component. I would rather have a warning when the user click outside or something alerting him.

**Comment by gastoner** [comment]
> The issue is named `clicking outside of the feedback form should not close the form`, the discussion in it ([#9192 (comment)](https://github.com/podman-desktop/podman-desktop/issues/9192#issuecomment-2428559176)) is not talking about storing the forms values in a store.
> 
> I am not much in favour creating a store, it add complexity to the component. I would rather have a warning when the user click outside or something alerting him.

What about some messageBox? This would be a few line change... but the modal has a bigger z height than the message box (which would need to update its z-height to be above the modal)

**Comment by benoitf** [comment]
yes the intent was more bringing awareness (a quick fix)

I'm not sure it's a component where we want to open/close for a long period of time. There is also a risk that if you hide it you may never come back also, forgetting you had values

**Comment by gastoner** [comment]
image

-function hideModal(): void {
-  displayModal = false;
-
-  // reset fields
-  category = DEFAULT_CATEGORY;
+async function hideModal(): Promise<void> {
+  const result = await window.showMessageBox({
+    title: 'Close Feedback Form',
+    message: 'Do you want to close the Feedback Form?\nClosing will erase your input.',
+    type: 'warning',
+    buttons: ['Yes', 'No'],
+  });
+
+  if (result && result.response === 0) {
+    displayModal = false;
+
+    // reset fields
+    category = DEFAULT_CATEGORY;
+  }

and adding +<div class='z-40'> around the Modal

**Comment by gastoner** [comment]
Closing this PR in favor of https://github.com/podman-desktop/podman-desktop/pull/9975

**Pull request closed without merging**
