### PR TITLE
feat: update run image screen buttons

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Switches all the buttons in the Run Images form to the Button
component. The normal button type is way too bold and stands out, and
the secondary button type has an outline and also stands out a lot,
so I've gone with 'link' since that matches the original look the most.

The Input component was using w-full where it should have been using
grow, which was causing it to overlap with buttons. Fixed and updated
test.

### Screenshot / video of UI

Before:

Screenshot 2024-03-04 at 2 38 48 PM

After:

Screenshot 2024-03-04 at 2 38 14 PM

### What issues does this PR fix or reference?

Fixes one part of [#6220](https://github.com/deboer-tim/desktop/issues/6220).

### How to test this PR?

Open the Run

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by deboer-tim** [comment]
Was originally a draft on top of #6240, that has merged so moving to review now.

**Comment by axel7083** [comment]
In my opinion it is too much purple for the buttons. They look like they are in an active state or hovering.

**Comment by deboer-tim** [comment]
As per discussion with UX, their recommendation is to merge this (with normal review) and put in another PR to revert some of the input styling.

**Review by axel7083 — APPROVED** [review]
Tested locally, and I do not see visual regression where the Input is used, so LGTM

**Review by benoitf — APPROVED** [review]
I would have prefered a commit for replacing w-full by grow in Input and another one for updating the RunImage component

I think we're missing the removal of the purple line by default

Also I think after using for a long time that the change of background/borders everywhere should only be applied on focus, not on hover
else moving the cursor across the RunImage page there are too many highlights

(not blocking the merge of this PR)

**Comment by deboer-tim** [comment]
> I would have prefered a commit for replacing w-full by grow in Input and another one for updating the RunImage component

Sorry, happened organically and agree that would be better in the future.

> I think we're missing the removal of the purple line by default

Correct, this was just updating the buttons to use the component (which did require the minor w-full fix to Input, which was causing problems but not as visible before) and why this was not a 'fixes' for #6220. Recommendation was for separate PR to do something about the input styling.

> Also I think after using for a long time that the change of background/borders everywhere should only be applied on focus, not on hover else moving the cursor across the RunImage page there are too many highlights

That's a good idea, or at least softening the effect a lot. This is clearly a case where the original design just doesn't work in practice and we're trying multiple things to undo/improve but no design/consensus yet.

**Pull request merged**
