### PR TITLE
fix: Testcontainers name

### PR DESCRIPTION
**Pull request by eddumelendez**
Also, fix Testcontainers' website.

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
@eddumelendez thanks for you contribution

Commit sign off is required (DCO).

Also what is the rational as www.containers.org is functional ?

**Comment by eddumelendez** [comment]
> Commit sign off is required (DCO).

Done

> Also what is the rational as [www.containers.org](http://www.containers.org/) is functional ?

testcontainers.org redirects to testcontainers.com

**Comment by jeffmaury** [comment]
> > Commit sign off is required (DCO).
> 
> Done
> 
> > Also what is the rational as [www.containers.org](http://www.containers.org/) is functional ?
> 
> testcontainers.org redirects to testcontainers.com

Yes but as Podman Desktop is open source and the old link is functional, I'm hesitant to link to a .com directly

**Comment by benoitf** [comment]
yes I don't see the big value of the PR. Is it related to hacktoberfest ?

**Review by benoitf — APPROVED** [review]
LGTM

**Comment by eddumelendez** [comment]
> Is it related to hacktoberfest ?

No, it is not. My initial motivation to submit a PR is to fix the name of the project `Testcontainers` instead of `TestContainers`, see the capital `C`. Then I saw the old website and also made that change. I can revert it if you want to.

**Comment by benoitf** [comment]
on my end I'm fine to fix the name and links

Thanks for the contribution ( and the explanation)

**Review by cbr7 — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by jeffmaury** [comment]
Thanks @eddumelendez for your contribution

**Pull request merged**
