### PR TITLE
fix: higher-res icons for featured extensions list

### PR DESCRIPTION
**Pull request by mairin**
### What does this PR do?

Helps address podman-desktop issue #3493 - the icons for the featured extensions are low-res which looks especially poor on high dpi displays.

I've decided based on other icon systems to set the size of the icon artwork to 512x512 px.

Note that the Developer Sandbox icon is a placeholder; I am waiting on the brand team for an update on what to use, as the logo we had been using makes usage of the now deprecated Red Hat Developer logomark. I have used the new Red Hat Developer logo as a placeholder here.

Source files for icons are available here (note this points to a private repo as it includes trademarked logo sources):
https://github.com/containers/podman-desktop-internal/commit/51376b0401c6f81cb9503b4d60d5680a3a650bc7

#### Before
Screenshot from 2023-08-11 22-44-03

#### After
Screenshot from 2023-08-11 23-38-06

### What issues does this PR fix or reference?

[#3493](https://github.com/containers/podman-desktop/issues/3493)

### How to test this PR?

Check to make sure the icons being displayed are as appears in the "after" above and not the "before" image, and that the icons don't appear pixelated.

### CODE REVIEW

**Comment by afbjorklund** [comment]
Thanks for updating the Lima logo, even if is sad to see the "bean" icon go...

* https://github.com/lima-vm/lima/issues/268

Official logos for the Lima project, after being accepted to the CNCF, are here:

https://github.com/cncf/artwork/blob/master/examples/sandbox.md#lima-logos

**Comment by mairin** [comment]
@afbjorklund I used that SVG but colored the text white so it'd be legible, do you think that's ok? (Also happy to use the bean if it's allowed!)

**Comment by afbjorklund** [comment]
> @afbjorklund I used that SVG but colored the text white so it'd be legible, do you think that's ok?

I think it is OK,  should add it to the repository as the "dark mode" version. Maybe the [PNG](https://github.com/containers/podman-desktop/pull/3248/files) as well...

The designer that made the logo might still be on summer vacation, so it could take a while to check.

> (Also happy to use the bean if it's allowed!)

The GitHub issue is still open, so there might still be an icon in the future. But right now, there is none. :-(

As mentioned previously, I think both the project website and graphic profile are in for an overhaul soon.

**Review by deboer-tim — APPROVED** [review]
I was going to suggest that if the Lima issue was still open we should commit the others and refresh Lima later, but then I saw it has been open for years. :( The new logo with just the name is going to be unfortunate for light/dark UIs or anywhere a label is used next to an icon, but if that's the official one lets go ahead.

**Comment by afbjorklund** [comment]
> The new logo with just the name is going to be unfortunate for light/dark UIs or anywhere a label is used next to an icon, but if that's the official one lets go ahead.

If it becomes a problem, you can do like the other icon-less projects and add a background to it.

Like so: https://github.com/lima-vm

**Review by cdrage — APPROVED** [review]

**Pull request merged**
