### PR TITLE
feat: add statusbar item highlight property

### LINKED ISSUE #5814: Status Bar item should have a highlighted/badged/dotted elements to bring attention to it
### Is your feature request related to a problem? Please describe

Some status bar item should have a visible mark when they requires/want user's attention.

### Describe the solution you'd like

A dotted visual elements on top/right corner of the text, to bring a light, and nice attention to the item

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

This PR is adding an `important` property to the StatusBarItem. This can be useful to bring attention to the user to a specific item. For example here the `Update available` StatusBar item.

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/5814

### How to test this PR?

- [x] Unit tests have been added

### CODE REVIEW

**Comment by axel7083** [comment]
cc @deboer-tim I followed your advise and change the name `dotted` to have something agnostic of the frontend implementation, and I went with `important`.

**Comment by deboer-tim** [comment]
Thanks for changing it, but I'm not sure important makes sense in this context? It kind of says that everything is important until you look at it, and it's not. Could you change it to something more like isNew, or userNotified, or ...?

**Comment by axel7083** [comment]
> Thanks for changing it, but I'm not sure important makes sense in this context? It kind of says that everything is important until you look at it, and it's not. Could you change it to something more like isNew, or userNotified, or ...?

@deboer-tim I am willing to change, but maybe we could discuss which one we should use ? 
- I would argue that `isNew` could be interpret as a new status bar item has been created.
- For `userNotified`, we could think, that it is true when the user has been notified, but in fact it is factually not true, the user has not been notified, the ui has changed to _hightlight_ the status bar item
- To continue, the `hightlight` is also not really something I like, as it would let think that it is hightlight in some manner, than the frontend implementation should follow, which looks like similar to `dotted`.

I choose `important` as it let the frontend choose the way to display it, an update is important, you cannot remove the `dot` of the update by just clicking on it, you need to perform the update.

But I'm not very good at wording, so here is a list of proposition given by our dear friend ChatGPT.

image

cc @benoitf any suggestion ?

**Comment by benoitf** [comment]
I would go with `highlight` if it works for @deboer-tim as well

**Comment by deboer-tim** [comment]
The point of the function is notifying the user that something is new/has changed, and the status goes away once they've acknowledged it, so I still prefer something like `userNotified` or `acknowledged` or whatever 🤷🏻‍♂️, but we're probably already bike shedding here so `highlight` would be fine too! (thank you @axel7083)

**Comment by axel7083** [comment]
> The point of the function is notifying the user that something is new/has changed, and the status goes away once they've acknowledged it, so I still prefer something like `userNotified` or `acknowledged` or whatever 🤷🏻‍♂️, but we're probably already bike shedding here so `highlight` would be fine too! (thank you @axel7083)

@deboer-tim @benoitf I updated to `highlight`

**Review by deboer-tim — APPROVED** [review]
Thanks for all the review on this.

**Pull request merged**
