### PR TITLE
docs: add command package.json explanation

### LINKED ISSUE #7454: Docs: Commands schema in package.json
### Is your enhancement related to a problem? Please describe

See:

https://github.com/containers/podman-desktop/issues/5561#issuecomment-2146142828

Sub-issue for adding commands to docs

### Describe the solution you'd like

Document commands section in package.json

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
docs: add command package.json explanation

### What does this PR do?

Adds explanation on how to use commands in package.json

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/7454

### How to test this PR?

N/A, its docs

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]

**Review by benoitf — APPROVED** [review]
talk about command palette and that you can exclude them from being listed in the command palette ?

**Comment by cdrage** [comment]
> talk about command palette and that you can exclude them from being listed in the command palette ?

I've opened up issue: https://github.com/containers/podman-desktop/issues/7473 to add more information to this page as well as create a separate document as well with pictures / gifs explaining the command palette.

It's an important feature yet we do not have it listed anywhere except vaguely in a blog..

LMK if that's okay and we could merge this PR (i've self assigned the other issue).

**Review by axel7083 — APPROVED** [review]
Great !

**Comment by cdrage** [comment]
Setting to auto-merge and will follow up in https://github.com/containers/podman-desktop/issues/7473 since we should really make a separate doc detailing the feature.

**Pull request merged**
