### PR TITLE
docs: fixed footer links

### LINKED ISSUE #3978: https://podman-desktop.io/ docs page 404
### Bug description

Not sure where this bug belongs, as I don't see source for your main website, unless this is another type of issue like "enhancement". Please forward this along to whomever needs to see it.

Using the podman-desktop webpage (from the core values page), I navigated to the Getting Started link at the bottom of the page and got a 404 page not found error. Looks like the url is incorrect.

Screenshot_20230919_183523

### Operating system

Gentoo Linux amd64

### Installation Method

None

### Version

1.4.0

### Steps to reproduce

From https://podman-desktop.io/core-values, go to bottom of page to the "Getting started" link and click on it.
Resulting page url is https://podman-desktop.io/docs/getting-started/getting-started

### Relevant log output

_No response_

### Additional context

Using Brave browser

### PR DESCRIPTION
**Pull request by themr0c**
### What does this PR do?

Fixed broken links in the website footer.

### What issues does this PR fix or reference?
fixes #3978

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
out of curiosity, why getting started is being replaced by Working with containers ?

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by themr0c** [comment]
That was done with https://github.com/containers/podman-desktop/pull/3951.
The content was an old blog post, and content had been already redispatched to other pages.

**Comment by themr0c** [comment]
And, in broader sense, that's part of the ongoing Onboarding content reorg.

The main outline is:

1. Installing Podman Destkop
1. Onboarding
	1. Onboarding for container workloads
	1. Onboarding for Kubernetes workloads
1. Working with containers
1. Working with Kubernetes

I started to move content around in chunks.

**Pull request merged**
