### PR TITLE
feat: Allow to install in one click featured extensions (if not installed)

### PR DESCRIPTION
**Pull request by benoitf**
Requires: 
 - [x] : https://github.com/containers/podman-desktop/pull/2346

### What does this PR do?
Display a widget in dashboard and extensions list to install featured extension in one click

### Screenshot/screencast of this PR

https://user-images.githubusercontent.com/436777/236219250-babe29aa-b793-47b7-a052-92e8a623aed7.mp4

### What issues does this PR fix or reference?

related to https://github.com/containers/podman-desktop/issues/1901

### How to test this PR?

It requires commits from
- https://github.com/containers/podman-desktop/pull/2346

There are component tests

How to test: Launch Podman Desktop (and check that for example you don't already have SandBox or OpenShift Local being installed)

Then click on the download icon and wait a little, then extension should be there

Change-Id: I495ad06dd7f27a3779195c3fc503dae3dd6e0cc3

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
II see this error when fetching the catalog `Unable to fetch the available extensions: Timeout awaiting 'lookup' for 1000ms` and it results in the N/A status. Not sure what we can do to improve it but if that happens, what's the point of showing the crc/openshift local extension if i cannot do anything?

Other point is that the icon of the extension are not high quality - look at the podman/lima/local icons. We should update them
image

**Comment by benoitf** [comment]
@lstocchi https://github.com/containers/podman-desktop/blob/4e90e5b078e1b73b9634291c25627764192889d7/packages/main/src/plugin/extensions-catalog/extensions-catalog.ts#L95-L102 Here is the default settings maybe it's too short for your internet connection.

**Comment by lstocchi** [comment]
> @lstocchi
> 
> https://github.com/containers/podman-desktop/blob/4e90e5b078e1b73b9634291c25627764192889d7/packages/main/src/plugin/extensions-catalog/extensions-catalog.ts#L95-L102
> 
> Here is the default settings maybe it's too short for your internet connection.

yes, by increasing it it worked fine.

**Review by lstocchi — APPROVED** [review]
Approving it as the code related to my issues is at https://github.com/containers/podman-desktop/pull/2346 and i'll be out for a while. 
If we can enhance the icons and increase the timeout or make it customizable would be great.

**Comment by benoitf** [comment]
need to find the good limit then

**Comment by cdrage** [comment]
https://github.com/containers/podman-desktop/pull/2346 has been merged now, so we will need to rebase

**Comment by benoitf** [comment]
@cdrage rebased

**Comment by benoitf** [comment]
I'll open follow-up PRs for timeouts and icons

**Pull request merged**
