### PR TITLE
chore(ui): migrating container icon to ui package

### LINKED ISSUE #6899: Implement ContainerIcon UI component

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

I created a new export in the ui package `@podman-desktop/ui-svelte/icons` to differentiate from the component. (This is a suggestion, I can put everything in the `@podman-desktop/ui-svelte` export if that prefered, but I personnally like to split

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/6899

### How to test this PR?

- Pipeline should be ✅

### CODE REVIEW

**Review by deboer-tim — APPROVED** [review]
I prefer the /icons too, LGTM.

**Comment by axel7083** [comment]
rebased ✅

**Comment by axel7083** [comment]
cc @benoitf what do you think about the dedicated icons folder ?

**Review by benoitf — APPROVED** [review]
I'm fine with the suggestion

**Pull request merged**
