### PR TITLE
chore: enable prefering nullish operator

### PR DESCRIPTION
**Pull request by cdrage**
chore: enable prefering nullish operator

### What does this PR do?

Bad habit of using || when it should be ??

This enables erroring out for `yarn lint:fix` where it should be ?? instead of
||

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

N/A

### How to test this PR?

N/A

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
Draft just to see how much we have to change to get this to work..

**Comment by benoitf** [comment]
273

**Comment by benoitf** [comment]
@cdrage can you try to have a separate PR just introducing `"strictNullChecks": true,` (it's also missing the part in `website` folder)

**Comment by cdrage** [comment]
Will re-open adding strict and then open this one again with the fixes 👍

**Pull request closed without merging**
