### PR TITLE
feat: fixes the badges alignment in navigation bar

### LINKED ISSUE #500: Align notifications to right side of side-bar
### Is your enhancement related to a problem? Please describe

image (1)

I find the notifications a bit odd that they aren't aligned in a row on the side bar. Perhaps we could improve the UX/UI to align to the right?

### Describe the solution you'd like

Aligned to the right side of the sidebar.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0hmX**
Signed-off-by: cu8code <git8ankanroy@gmail.com>

### What does this PR do?
UI : fixed the item alignment in navigation bar

### Screenshot/screencast of this PR

app

s

### What issues does this PR fix or reference?
fixes #500

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
thanks for the PR @cu8code

**Comment by slemeur** [comment]
Hi @cu8code ! Thanks a lot for your contributions. Have you done this contribution that as part of hacktoberfest ?

**Comment by 0hmX** [comment]
@slemeur yes sir

**Comment by slemeur** [comment]
Excellent!!

**Pull request merged**
