### PR TITLE
fix: initialize podmanInstall when no podman in installed

### LINKED ISSUE #7527: Cannot install Podman via Podman Desktop on main branch on Windows
### Bug description

As discussed in #7433, I am still not able to install Podman on my machine using Podman Desktop nightly bits where Podman 5.1.1 installer is available. When tried locally as part of review of #7433, I was able to run the `podman-setup.exe` on its own, but not via Podman Desktop.

podman511-install-error

### Operating system

Windows 10, x64

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Try to install Podman via Podman Desktop (https://github.com/containers/podman-desktop/releases/tag/v0.0.202406091508-34d0fb2).

### Relevant log output

```shell
VM5:2 main ↪️ [podman] The podman extension has not been successfully initialized
console.<computed>	@	VM5:2

VM5:2 main ↪️ [podman] Error: The podman extension has not been successfully initialized
    at hl.doInstallPodman (C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\extensions\podman\builtin\podman.cdix\dist\extension.cjs:172:1839)
    at C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\extensions\podman\builtin\podman.cdix\dist\extension.cjs:181:3257
    at of.executeCommand (C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\packages\main\dist\index.cjs:95:32852)
    at C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\packages\main\dist\index.cjs:338:9910
    at C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\packages\main\dist\index.cjs:336:20656
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82782)
    at WebContents.emit (node:events:519:28)
console.<computed>	@	VM5:2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

During the refactoring to enable the strict rule i added a check that bypassed the initialization of the component responsible for podman installation if podman was not already installed.

This PR just removes that `if`

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

it fixes #7527 

### How to test this PR?

1. have a machine with podman not installed and try to install it

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by lstocchi** [comment]
cc @odockal

**Comment by odockal** [comment]
@lstocchi I am curious if we need to add/update podman-install unit tests?

**Review by odockal — CHANGES_REQUESTED** [review]
Tried to run the bits with changes from this PR. Still does not work. If I do not have podman installed, the installer is not offered. Maybe update of the podman works, but not the new/first installation into "fresh" machine.

**Comment by lstocchi** [comment]
> Tried to run the bits with changes from this PR. Still does not work. If I do not have podman installed, the installer is not offered. Maybe update of the podman works, but not the new/first installation into "fresh" machine.

Just tried again and it works for me. Are you sure you built the podman extension again? 
What i did:
1. uninstall podman
2. build + yarn watch
3. click on setup - install
Do you do anything different?

**Comment by lstocchi** [comment]
> @lstocchi I am curious if we need to add/update podman-install unit tests?

yes, i'll add a new test as soon as we find the solution

**Comment by odockal** [comment]
> > @lstocchi I am curious if we need to add/update podman-install unit tests?
> 
> yes, i'll add a new test as soon as we find the solution

Great!

> Just tried again and it works for me. Are you sure you built the podman extension again?
What i did:

    uninstall podman
    build + yarn watch
    click on setup - install
    Do you do anything different?

I have used the bits produced by the PR checks: https://github.com/containers/podman-desktop/actions/runs/9451914651

**Comment by lstocchi** [comment]
> I have used the bits produced by the PR checks: https://github.com/containers/podman-desktop/actions/runs/9451914651

Just tried both `windows-exe-x64` and `windows-installer-x64` and they work fine on my machine.
@cbr7 i saw you also faced this issue. Could you give this PR a try when you have some free time? Thanks

**Comment by cbr7** [comment]
@lstocchi just tried it and it's still not working for me either, but the error it different from the one I was getting yesterday

image

**Comment by odockal** [comment]
@lstocchi Can you please check that you have no podman installed. no podman binary on the path and also that `.local/share/containers/podman-desktop` is deleted prior the running the pd executable? Also please make sure that no PD instance is running in the background.

**Comment by lstocchi** [comment]
> @lstocchi Can you please check that you have no podman installed. no podman binary on the path and also that `.local/share/containers/podman-desktop` is deleted prior the running the pd executable? Also please make sure that no PD instance is running in the background.

Ok, i was able to replicate by removing everything. Pushed a new fix that seems working. I'll keep testing

**Comment by cbr7** [comment]
@lstocchi I just retried with the latest commit and the fix worked, I was able to install podman from PD now.

**Comment by odockal** [comment]
@lstocchi I can confirm that now I can install podman via podman desktop.

**Comment by lstocchi** [comment]
@cbr7 @odockal great!! Thanks both for checking!!

**Review by odockal — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
