### PR TITLE
chore: added an icon for all docs referencing to the **Settings** menu

### PR DESCRIPTION
**Pull request by themr0c**
chore: added an icon for all docs referencing to the **Settings** menu
chore: additionally, reformatted the files with prettier

### CODE REVIEW

**Comment by benoitf** [comment]
Prettier should check also the files in the website ?
Here it looks you formatted the files but I guess a configuration file should be updated to be sure prettier is always applied

**Comment by themr0c** [comment]
I started asking my IDE to always reformat the files with the default prettier behavior. It's a big relief for my brain. 

I believe enforcement is not desirable (at least now).

**Comment by benoitf** [comment]
we're already enforcing prettier check, so if some files are missing, it should be added, to prevent such PR that are only applying prettier changes.
Then it ensures all people use the same formatter (else you may apply one and another developer another one, etc)

**Comment by themr0c** [comment]
Okay, that was not the purpose of the pull request. I was just trying to explain why the pull request contains more than just added icons.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
