### PR TITLE
fix: add style to link (#4880)

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

it adds style to links as it was before

### Screenshot/screencast of this PR

purple_links_2

### What issues does this PR fix or reference?

it closes 4880

### How to test this PR?

1. open the resources page or any other page with a link

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
I don't see the cursor being updated when the link is in a onboading view

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by lstocchi** [comment]
I have to remove the underline :/
underline

**Comment by deboer-tim** [comment]
If we're fixing this, any chance we could make the links purple too? I always thought they were supposed to be like buttons, i.e. purple-600 with a -500 hover.

FYI to @mairin

**Review by benoitf — COMMENTED** [review]
should we not add the style in the Markdown component ?

https://github.com/containers/podman-desktop/blob/417fc4bb2b29946c095a30e5b2cffc1258dc6ee9/packages/renderer/src/lib/markdown/Markdown.svelte#L4-LL36

**Comment by lstocchi** [comment]
Updated based on your suggestions. Not sure if purple-600 is too dark or it's ok. Do we use it somewhere else?
@mairin

**Comment by deboer-tim** [comment]
> Updated based on your suggestions.

Thank you, that's already looking more consistent to me, and code change is better too.

> Not sure if purple-600 is too dark or it's ok. Do we use it somewhere else?

I pulled those colors from the Button for consistency (which is on the left in the video), but I agree it's too dark when it's not a full box. From the video it looks like maybe bumping it up one level to -500 and -400 would work? I would +1 this after a minor tweak.

**Comment by lstocchi** [comment]
@deboer-tim updated. Idk why the gif i record is always a bit darker of what i actually see on my screen

**Review by deboer-tim — APPROVED** [review]
LGTM, thanks for the changes.

**Review by cdrage — APPROVED** [review]

**Review by benoitf — APPROVED** [review]
my approval was not required, so many approvals already but here is mine

thanks @lstocchi

**Pull request merged**
