### PR TITLE
chore: remove double scrollbar from push image dialog

### LINKED ISSUE #8078: Odd right spacing on terminal for push image
### Bug description

Screenshot 2024-07-15 at 10 45 32 AM

There's a weird misalignment / white spacing on the right with "Push Image"

### Operating system

mac M1

### Installation Method

None

### Version

1.11.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SoniaSandler**
Signed-off-by: Sonia Sandler <ssandler@redhat.com>

### What does this PR do?
Removes double scrollbar from the push image dialog window. In https://github.com/containers/podman-desktop/issues/8078, there is a double scrollbar in the dialog window, and due to the style of the scrollbar and theme of the terminal vs background, the terminal's scrollbar looks like empty space/misaligned terminal (at least in mac OS). However, since the terminal is Xterm terminal, the only way to remove the terminal's scrollbar is to directly modify the css file of Xterm in `node_modules`. This PR solve the issue of the double scrollbars, but the problem of the empty space might still arise with certain background and terminal colors, unless we want to directly modify Xterm's css file.

### Screenshot / video of UI
Screenshot from 2024-08-08 16-44-29

### What issues does this PR fix or reference?
Closes https://github.com/containers/podman-desktop/issues/8078

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by gastoner — COMMENTED** [review]
Tested on Windows:

image

But I might be doing something wrong :D

**Comment by SoniaSandler** [comment]
@gastoner I tried using the max height for the terminal that still removes the outer scrollbar, so it might differ a bit between OS. I'll try changing it to a smaller value

**Review by gastoner — APPROVED** [review]
Looks good! 
Current windows: 
image

**Review by benoitf — APPROVED** [review]

**Review by dgolovin — APPROVED** [review]
LGTM.
The only problem I noticed, if I start doing zoom in/out everything gets distorted and scroll bar can pop up again. But that is a different issue.

**Pull request merged**
