### PR TITLE
chore(deps-dev): update to @tsconfig/svelte v5.0.1

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
update to @tsconfig/svelte v5.0.1

fix a lot of TypeScript errors and ignore only few

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/pull/3624

### How to test this PR?

Everything should work as before

### CODE REVIEW

**Review by dgolovin — CHANGES_REQUESTED** [review]
I have an error in renderer/tsconfig.json

```Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.```

Some modules are not resolved in vscode,

image

**Comment by dgolovin** [comment]
But if I run `yarn test:renderer` everything runs just fine.

**Comment by benoitf** [comment]
I did a fresh checkout of my branch

`git clone https://github.com/benoitf/desktop --branch tsconfig-svelte`

did `yarn` in the desktop folder

Opened it in VS Code

but no errors are reported on my side and it's working just fine

no error when opening the tsconfig.json file
image

and no error when opening `packages/renderer/src/lib/context/contextKey.spec.ts`

image



@lstocchi could you check on your end to see if you're reproducing @dgolovin error or no error like on my side

**Comment by benoitf** [comment]
I used VS Code version: 1.81.1 (Universal) when testing

**Comment by lstocchi** [comment]
@benoitf works fine on my side
@dgolovin try to reinstall the dependencies, maybe something is dirty

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by dgolovin** [comment]
same VSCode, but Typescript configured for workspace was wrong. I switched to 

image

and that fixed package resolution problems and tsconfig.json problems.

But now I have svelte test compilation problems like this one below

image

**Comment by benoitf** [comment]
@dgolovin I suppose it's the test that is incorrect.

If I open the current codebase (not from my pull request) I have the same exact error

**Comment by dgolovin** [comment]
@benoitf it seems so. There are others like this one.

**Review by dgolovin — APPROVED** [review]

**Comment by benoitf** [comment]
Need to investigate why it's not reported in PR checks

**Pull request merged**
