### PR TITLE
chore: keep only one playwright dependency

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
there are two dependencies playwright and @playwright/test, keep only one to avoid mismatch
keep 1.37.1 as 1.39 is failing there https://github.com/containers/podman-desktop/pull/4305

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/pull/4721#issuecomment-1803646498

### How to test this PR?

Tests should work as expected and be ✅

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by jeffmaury** [comment]
Was able to run twice without error on an HyperV Ubuntu VM

**Comment by benoitf** [comment]
ok found the issue after debugging

it's because now we should not forget to do the `playwright install` step

**Comment by benoitf** [comment]
@lstocchi I added one extra commit to install playwright dependencies, still approving ?

**Review by lstocchi — APPROVED** [review]

**Comment by benoitf** [comment]
I will merge this morning if nobody objects

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
