### PR TITLE
Type clean-up on Dashboard

### LINKED ISSUE #6547: Consistent fonts on Dashboard screen
### Is your enhancement related to a problem? Please describe

At the moment, the text on the dashboard screen is not following a consistent set of rules. The visual hierarchy needs to be stronger. 

This relates to https://github.com/containers/podman-desktop/issues/6405 

### Describe the solution you'd like

Go through the page and set the font to the appropriate size, setting them up to be edited later.

### Describe alternatives you've considered

_No response_

### Additional context

From this we can go through the other pages and make them follow this format also.

### PR DESCRIPTION
**Pull request by ekidneyrh**
### What does this PR do?

Sized the text to improve the visual hierarchy of information on the Dashboard page. Also gets things in order to define type sizes in the tailwind config file in the future. 

### Screenshot / video of UI
This is what it looks like now:
Screenshot from 2024-03-28 11-14-41

And this is with the changes:
image

### What issues does this PR fix or reference?

Would close https://github.com/containers/podman-desktop/issues/6547

Changes are only slight until changes are made to the type styles. This is done to avoid disruption to the ui of the rest of the app.

### CODE REVIEW

**Comment by slemeur** [comment]
This is very good work @ekidneyrh !

**Comment by deboer-tim** [comment]
These font sizes appear to be the same as the tailwind default so I'm not concerned about that, but:
- We use text-xs in ~10 places, I think this would revert those to the default size since they wouldn't be found? These need to be fixed or text-xs added.
- The defaults have line-heights, and no fontWeights. Changing the weight globally likely doesn't have a big impact, but changing the height could have one. When we removed PatternFly it changed the line height and caused _lots_ of minor regressions, so we should check lots of screens here.
- Tests would have to be fixed.

**Comment by ekidneyrh** [comment]
> We use text-xs in ~10 places, I think this would revert those to the default size since they wouldn't be found? These need to be fixed or text-xs added.

I can amend the config file and add in the xs size 

> The defaults have line-heights, and no fontWeights. Changing the weight globally likely doesn't have a big impact, but changing the height could have one. When we removed PatternFly it changed the line height and caused _lots_ of minor regressions, so we should check lots of screens here.
> 
Do you mean that the line heights have been changed here, or are you pointing out that they can be defined also? 

I was focusing just on the Dashboard for the time being, but I know this has effects throughout. What way do you think would be best to do this? My original plan was to go screen by screen, but if it has major impacts throughout, then could we do everything in one PR?

**Comment by benoitf** [comment]
>, then could we do everything in one PR?

I would opt for small PRs

(like doing it screen by screen or by component)

like : only buttons, only dashboard, etc

it's easier to see regressions/revert when it's done step by step

**Comment by deboer-tim** [comment]
> Do you mean that the line heights have been changed here, or are you pointing out that they can be defined also?

It looks like the Tailwind defaults have line heights, so not defining them in our own would presumably remove them. It might not be the case or might not be an issue, it's just that this is a 'global' change.

**Comment by ekidneyrh** [comment]
Do you think it would be better if I define the type sizes last? That way it doesn't mess up the other screens in the meantime.

**Review by benoitf — COMMENTED** [review]
AFAIK `text-bt` does not exist in tailwind but I see several usage in this PR

**Comment by ekidneyrh** [comment]
I have text-bt used for button text, which will be defined in the tailwind config file once the type on the rest of the pages are cleaned-up like this.  It seems to just be defaulting to 16px atm.

**Pull request closed without merging**
