### PR TITLE
feat: refactor preferences layout (#1779)

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR refactors the existing layout of the preferences page as shown in #183  

It doesn't include the search bar and the treeview as they will be handled in separate PRs.

It includes a new layout, the reset button and the autosave mechanism.

### Screenshot/screencast of this PR

new-preferences-layout-2

### What issues does this PR fix or reference?

it is part of #1779 

### How to test this PR?

1. go to settings -> preferences
2. update your setting and check that they are correctly saved

### CODE REVIEW

**Comment by benoitf** [comment]
hello, AFAIK the reset to default was an icon close to the title of the property

Like exit on close

227013701-8e080686-046d-4ccb-9a00-643acd9edff7

And it's only displayed if value is not the default one.
But I see in mockup also the 'reset label' below the min/max

so maybe @mairin could you clarify location and behavior of reset ?
Is it a subtle icon close to the title or a label. I thought we started with label and moved to the icon but mockup has both

**Comment by mairin** [comment]
> so maybe @mairin could you clarify location and behavior of reset ? Is it a subtle icon close to the title or a label. I thought we started with label and moved to the icon but mockup has both

Ooh sorry, I thought I'd cleaned that up. You are right, we talked about this and moved it to the icon next to the title. I must have missed removing the links. Sorry about that!

**Comment by benoitf** [comment]
@lstocchi if it's possible to have icon version ( I'm fine with with a follow up PR as well)

**Comment by lstocchi** [comment]
@benoitf added an icon to reset the values. You can check the gif in the first message

**Comment by benoitf** [comment]
ok, trying..

**Comment by benoitf** [comment]
looks reset to default arrow icon is not aligned vertically
image

**Comment by benoitf** [comment]
If I reach the minimum (or maximum) it looks a little bit too dark ? (I'm not sure to understand I reached the limit)
image

**Comment by benoitf** [comment]
the toggle does not look like the mockup (circle not touching the border on mockup while on my screen it's close to the border)

my screen
image

mockup 
image

**Review by benoitf — APPROVED** [review]
I commented somewhere else but maybe for file widget/component we should have a way to remove the file (not only by clicking on reset if default is blank)

I noticed few glitches but it doesn't prevent the approval if we track/follow up

**Comment by lstocchi** [comment]
> If I reach the minimum (or maximum) it looks a little bit too dark ? (I'm not sure to understand I reached the limit) image

@mairin any idea how to make it more clear?

**Comment by lstocchi** [comment]
> If I reach the minimum (or maximum) it looks a little bit too dark ? (I'm not sure to understand I reached the limit)

@benoitf i didn't notice or maybe i did notice and i don't remember i followed this mockup (damn memory 🤯 ) but it looks similar to what Mo did here
image

**Comment by benoitf** [comment]
ok so it looks like I'm not 100% convinced of the disabled state of  min/max mockup of @mairin 🤦

**Comment by mairin** [comment]
yikes my bad! @lstocchi can you try charcoal-600 for the background and charcoal-100 for the +/- symbol?

**Comment by lstocchi** [comment]
> yikes my bad! @lstocchi can you try charcoal-600 for the background and charcoal-100 for the +/- symbol?

Sure 👍 

This is how it looks
image

By adding some border
image

**Comment by lstocchi** [comment]
It looks great for me.

image

**Review by cdrage — APPROVED** [review]
Great job on the refactor, everything LGTM. Tested it out / checked out all the preferences as well as saving settings / exiting and seeing any changes. 

Resizing it to a smaller window / larger worked fine too.

Tested on M1. LGTM!

**Review by benoitf — APPROVED** [review]
thanks @mairin and @lstocchi for the updated component 

works for me now

**Pull request merged**
