### PR TITLE
feat: Final colors and lock down palette

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

In a previous PR #1363 we replaced 6 colors in the default Tailwind palette with our own palette [1]. There are 2 other colors that we didn't override at the time (gray and purple) because we use them a lot and the color values at each level have changed slightly.

This PR:
- Updates the palette to include the last of our official colors, gray and purple.
- Maps all existing use of these two colors to the 'closest color' variant from the new set to minimize color shift in the UI. I wrote a small script to confirm which variants should change - see mapping below. e.g. the old and new purple-200 are close so didn't need to change, but the old purple-300 is closest to the new purple-200.
- Adds all 7 additional colors/variants like slate that we're currently using into tailwind.config.cfg. Over time these will need to be moved 'up' into our official palette, or we stop using them and clean up the palette.
- Moves this palette from extending Tailwind's palette to replacing it. This will force us to stick with the defined palette and can't accidentally use other colors.

Purple
300 -> 200
600 -> 500
700 -> 600
800 -> 700
900 -> 800
950 -> 900

Gray
200 -> 300
300 -> 400
400 -> 700
500 -> 900
600 -> 900
700 -> 900
800 -> 900

[1] https://gist.githubusercontent.com/mairin/c7c1c36e3ecea99a4eb933f7fc7f124c/raw/66ae813487156de2f384c280cf298a4ce1666935/gistfile1.txt

### Screenshot/screencast of this PR

N/A. You shouldn't be able to visually tell the difference.

### What issues does this PR fix or reference?

Major step towards issue #1384.

### How to test this PR?

Start both Podman Desktop and the website (yarn website:dev) and page through as much as you can. There should be no visual differences in color or missing colors.

### CODE REVIEW

**Comment by mairin** [comment]
I updated the zinc background color to a charcoal one, as well as the nav, although I couldn't get tailwind to override patternfly so I updated the color codes in the patternfly overrides css and commented to note which tailwind colors the hexes were, see 

https://github.com/mairin/podman-desktop/tree/mo-palette

**Comment by deboer-tim** [comment]
> I updated the zinc background color ...

Looks good. To avoid this PR snowballing or taking longer to merge I'd prefer to get this in and then follow up with those changes or any further cleanup in another PR.

**Comment by mairin** [comment]
@deboer-tim makes sense, I can rebase once this is in and submit as a separate pr

**Comment by cdrage** [comment]
Screenshot 2023-04-25 at 9 21 54 AM

Looks like this section has changed?

**Comment by deboer-tim** [comment]
I'm not sure how the empty screen got messed up in the find/replace, but I pinged mairin to confirm the correct color (now charcoal-800) and pushed a commit to fix it.

**Review by cdrage — APPROVED** [review]
LGTM! I see no visible changes anymore going through all the screens.

**Pull request merged**
