### PR TITLE
docs: Shorter sidebar category names

### LINKED ISSUE #5884: Documentation: Shorter sidebar category names
### Is your enhancement related to a problem? Please describe

Titles are way too long in the sidebar and words often repeat.

Example:

Screenshot 2024-02-06 at 10 23 49 AM

Remove "Troubleshooting ..."

Another example:

Screenshot 2024-02-06 at 10 23 54 AM

Can be summarized as: "Restarting your minikube cluster" -> "Restarting the cluster"

"Installing the minikube cli" -> Installing the cli

etc.

### Describe the solution you'd like

Smaller titles

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by trmendes**
### What does this PR do?

This PR is shortening some side menu items title

### Screenshot / video of UI

> Cluster sidebar before

cluster_before

> Cluster sidebar now

cluster_now

> Troubleshooting sidebar before

troubleshooting_before

> Troubleshooting sidebar now

troubleshooting_now

### What issues does this PR fix or reference?

Fixes #5884 

### How to test this PR?

1) cd website
2) npx docusaurus start
3) check the side menu bar on docs

### CODE REVIEW

**Review by deboer-tim — APPROVED** [review]
I know it's not directly part of this PR, but could you change `Push` to `Pushing` for Kind and Minikube? It stands out more to me that it's inconsistent after the PR.

**Comment by slemeur** [comment]
Nice contribution @trmendes ! Thank you very much

**Review by slemeur — APPROVED** [review]

**Review by cdrage — APPROVED** [review]
Big 🎉 thanks for the awesome contribution!

**Comment by benoitf** [comment]
@cdrage before merging, please check argos and validate it manually to 'reviewed/approved'

**Pull request merged**
