### PR TITLE
docs: update the troubleshooting guide

### PR DESCRIPTION
**Pull request by themr0c**
### What does this PR do?

- split single-page.
- review, test, and update content.

### What issues does this PR fix or reference?

refs: #3045

### CODE REVIEW

**Comment by afbjorklund** [comment]
The Linux docs seems to be "reversed" ? Podman Desktop only handles Podman Engine currently, and does **not** handle Podman Machine (yet)

**Review by benoitf — COMMENTED** [review]
on usability issue, if I don't see links in navbar or navbar is hidden like

image

the page is only speaking about the Troubleshooting page inside Podman Desktop

I would expect links to the different OS, etc from this page

**Review by jeffmaury — COMMENTED** [review]
Add links from index.md to platform specific page

**Comment by themr0c** [comment]
Will raise smaller pull requests

**Pull request closed without merging**
