### PR TITLE
Fix Delete command for connection do delete correct one

### LINKED ISSUE #2289: Podman machine delete button deletes wrong machine
### Bug description

When creating machines in specific order:
* one named `test3`
* second named `test`

They appear in order of creation `test3` and then `test`.

When Delete button pushed for `test` machine, machine `test3' deleted instead.

### Operating system

macOS M1

### Version

next (development version)

### Steps to reproduce

https://user-images.githubusercontent.com/620330/235589961-3a6e9852-1c4c-43f0-8322-c9814933c97c.mov

### Relevant log output

_No response_

### Additional context

There is also an issues with progress indication, but I guess it caused by this issue.

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

It fixes search for connection targeted by lifecycle command. Instead of using url or socket only it also adds name into find function predicate. 

It also updates delete command inProgress status after it is finished or failed with error.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #2289.

### How to test this PR?

* add two podman machines
* delete last one
* last one should be deleted

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by benoitf** [comment]
~~I'm not sure to understand the patch~~
~~AFAIK socketPath is different for each podman machine  ? Or it provides a symlink ?~~

ok it seems that it's a change in podman 4.5 that is not using anymore a different path for the socket


Podman 4.4
```json
               "PodmanSocket": {
                    "Path": "/Users/benoitf/.local/share/containers/podman/machine/podman-machine-default/podman.sock"
               }
```

Podman 4.5
```json
               "PodmanSocket": {
                    "Path": "/Users/benoitf/.local/share/containers/podman/machine/qemu/podman.sock"
               },
```

**Comment by benoitf** [comment]
Could you please provide unit tests ?

**Comment by benoitf** [comment]
merging as it should be included in the upcoming release but please provide a unit test

**Pull request merged**
