### PR TITLE
chore: simplify pod actions & callbacks

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

It has been bugging me for a while that PodActions has a callback when an action affects a pod, and both PodList and PodDetails have essentially the same response of updating the pod UI object, and then PodList needs to trigger the UI to update. PodActions also passes a podInfoUI to functions when it already has the pod as a property.

When trying to extract columns to use the Table component this gets uglier because there is an intermediate component that needs to pass the callbacks through as well, so I figure it's a good time to simplify this a bit first.

This change just makes the PodAction update the pod UI object itself, and then uses a standard dispatch event to notify parents that something changed. Both PodList and PodDetails just need an on:update to trigger a Svelte update. Simpler/less code all around and less chance of PodList and PodDetails having different behaviour.

Note that there's one thing that still bothers me but is not fixed in this change: PodList and PodDetails use their own copies of PodInfoUI objects, so if you click Start in one view and then switch quickly, the pod is still stopped for a couple seconds in the other view. That is a separate problem but at least this change might make it marginally easier to fix in the future.

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Cleanup prior to #4842.

### How to test this PR?

`yarn test:renderer` or use PodList/PodDetails. As a code simplification chore, there should be no change to behaviour or tests.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
LGTM but should be merged after 1.6

**Review by benoitf — CHANGES_REQUESTED** [review]
it is missing tests to cover the update

**Comment by deboer-tim** [comment]
Added tests (and noticed/fix a bug, which new tests cover).

**Review by benoitf — APPROVED** [review]
main branch is open for new changes and tests have been added 👍

**Comment by deboer-tim** [comment]
@jeffmaury @feloy could I please get a review?

**Comment by deboer-tim** [comment]
(forgot I had a merge conflict, rebased and pushed now)

**Review by feloy — APPROVED** [review]

**Pull request merged**
