### PR TITLE
fix: compose installation via onboarding and cli tools

### LINKED ISSUE #9763: Manipulation of Compose CLI tool installed by Podman Desktop via CLI tools Page has errors
### Bug description

There is multiple problems with compose after its installation. I can install it via CLI tools, and Compose onboarding, but then I cannot really upgrade, downgrade or uninstall it depending on how ti was installed. Check the recording.

https://github.com/user-attachments/assets/7d79fa8b-8e9c-4083-b8f1-6acf0a00b84d

### Operating system

Mac OS 14 M2

### Installation Method

Installer from website/GitHub releases

### Version

1.14.0

### Steps to reproduce

Compose installed by CLI tool:
1. Install compose via CLI tools (one version older than latest - 2.30.1)
2. Assert: Compose is installed correctly system wide
3. Try to upgrade
4. assert: upgrade is successful
Actual result: Unable to update Compose to version 2.30.2 -> In the Task: `error: cannot updat undefined version 2.30.1 to 2.30.2 as it was not installed by podman-desktop`
5. Uninstall compose via Cli  tools
6. Assert: compose uninstalled

Compose Installed by Compose onboarding (2.30.2):
1. Install compose via onboarding
2. Assert: compose is installed correctly
3. Open Cli tools
4. Assert: Compose 2.30.2 is identified correctly
5. assert: there is option to upgrade/downgrade
Actual result: there is only option to update
6. try to update compose
7. assert: you can update (?! downgrade I suppose) compose
Actual result: Unable to update Compose to version 2.30.2 -> in the task: `error: cannot update docker-compose: No cli tool installed`
8. Uninstall compose via CLI tools
9. Assert: compose is uninstalled
Actual result: `error: cannot uninstall docker-compose: No version detected`

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

Fix compose onboarding install and CLI Tools preferences page install to work together.

### Screenshot / video of UI

https://github.com/user-attachments/assets/94cbe680-ee64-42e9-9cae-192f9e7c0ae5

Onboarding status updates after installing and removing compose on CLI Pref Page

https://github.com/user-attachments/assets/7ae56a6c-d435-487a-b321-ee9fa496378a

### What issues does this PR fix or reference?

Fix #9763.

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by gastoner — APPROVED** [review]
LGTM, tested on Windows

**Review by axel7083 — COMMENTED** [review]
Amazing ! This really improve the user experience to understand how it is installed etc.

I just have an issue with the uninstall part of the cli tool.

### Reproduce

1. assert compose not installed
2. assert `Setup...` in Resources page visible
image
3. Do setup (install binary)
4. assert compose executable visible in CliTool page
image
5. uninstall compose from the cli tool page
6. assert compose uninstalled from system
image
7. go to resources page
8. assert no `Setup...` visible
image

Restarting podman desktop or just the compose extension restore the `Setup...` button

**Comment by dgolovin** [comment]
@axel7083 never noticed that one. It seems to be the same origin - disconnection between onboarding and cli implementation. I will try to fix it.

**Comment by dgolovin** [comment]
@axel7083 fixed onboarding status update which hides 'Setup ...' button on resources page after compose installation and shows it after removal.

**Review by axel7083 — APPROVED** [review]

**Comment by gastoner** [comment]
@mergifyio backport 1.14.x

**Pull request merged**
