### PR TITLE
feat: allow to deploy yaml to a kubernetes cluster if any

### LINKED ISSUE #1261: Kind: Provide ability to "Play Kubernetes YAML" with different providers
### Is your feature request related to a problem? Please describe

From Podman Desktop, a user has the ability to generate kubernetes manifests for containers and pods. There are also capabilities that enables a developer to run kubernetes manifests directly with Podman. 

It would be nice to have the ability to run kubernetes manifests to a local cluster setup with Kind from Podman Desktop.

### Describe the solution you'd like

Providers should be able to register for certain capabilities they are able to accomplish (or not). For example, a provider could register that it can run kubernetes manifests. 

When a user selects a kubernetes manifest file, Podman Desktop should be able to determine if there is one or more provider that can run the manifest. If there is, Podman Desktop should be providing the choice on where to run the kubernetes manifests. 

Capture d’écran 2023-04-13 à 14 12 20

(note this is different from deploying the manifest to a cluster, which is a different feature request, here we are in the context of doing a `kubectl apply -f <manifest>`)

Maybe, it would be nice that the user can get the option to define the default provider for certain actions.

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Allow to select if we deploy yaml to podman engine or to a kube cluster

depends on
- https://github.com/containers/podman-desktop/pull/2077

### Screenshot/screencast of this PR

https://user-images.githubusercontent.com/436777/231812563-ece0a56a-b347-48f8-a3a7-400eb9449037.mp4

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/1261

### How to test this PR?

Deploy a kind cluster and try to deploy a yaml

I tried with a Deployment and with a yaml generated by podman (so with a Pod)

Change-Id: I193e9c750f630c166666ad0916558c7ac7aff238

### CODE REVIEW

**Comment by cdrage** [comment]
Initially deploys a Pod or Deployment perfectly fine. 

However, re-running the yaml produces this error:

https://user-images.githubusercontent.com/6422176/231816217-a76f2ebb-2918-4ff2-adb7-c6169af80f34.mov


I also "redeployed" another yaml I have which is more complicated (contains ingress, services, PVC, deployment, pods, etc.)

And I get the same error:

https://user-images.githubusercontent.com/6422176/231816492-6db33ae8-7ff6-454d-881d-18c780dd11f0.mov

Could it be that we're trying to create / not apply? If we are applying then it'll simply check for any changes and applying them rather than trying to recreate. 

Obviously this is an improvement and something not *entirely* critical and we can push a fix next release, but this would be an issue / error reporting when trying to rerun and may be frustrating.

**Review by lstocchi — APPROVED** [review]
LGTM
I guess we need to improve the experience at the end. It was so quick that i didn't notice the button `done` was there lol. Maybe we should add a message or close the upper part or something else...  but as a super quick release it's awesome. GJ 🚀

**Comment by lstocchi** [comment]
> Initially deploys a Pod or Deployment perfectly fine.
> 
> However, re-running the yaml produces this error:
> 
> I also "redeployed" another yaml I have which is more complicated (contains ingress, services, PVC, deployment, pods, etc.)
> 
> And I get the same error:
> 
> Could it be that we're trying to create / not apply? If we are applying then it'll simply check for any changes and applying them rather than trying to recreate.
> 
> Obviously this is an improvement and something not _entirely_ critical and we can push a fix next release, but this would be an issue / error reporting when trying to rerun and may be frustrating.

Isn't the same behavior we have with podman? If you try to build a pod that already exists locally it is not created. You see the error message. Here it will be the same. I wonder if the action should be renamed in another way. For me `play` it's just a friendly action to test what you have. Nothing to do with a professional thing for deploying stuff. If the env is dirty, it's up to you to clean it or change name. BTW i agree that the error message is not so clear

**Comment by cdrage** [comment]
> > Initially deploys a Pod or Deployment perfectly fine.
> > However, re-running the yaml produces this error:
> > I also "redeployed" another yaml I have which is more complicated (contains ingress, services, PVC, deployment, pods, etc.)
> > And I get the same error:
> > Could it be that we're trying to create / not apply? If we are applying then it'll simply check for any changes and applying them rather than trying to recreate.
> > Obviously this is an improvement and something not _entirely_ critical and we can push a fix next release, but this would be an issue / error reporting when trying to rerun and may be frustrating.
> 
> Isn't the same behavior we have with podman? If you try to build a pod that already exists locally it is not created. You see the error message. Here it will be the same. I wonder if the action should be renamed in another way. For me `play` it's just a friendly action to test what you have. Nothing to do with a professional thing for deploying stuff. If the env is dirty, it's up to you to clean it or change name. BTW i agree that the error messago is not so clear

Yeah, unfortunately if I were to deploy a YAML with this method that contains a Pod and a Service or Ingress, I can delete the Pod within Podman Desktop, but in order to redeploy the YAML I'll have to dig through k8s and find the service / ingress and then delete it, then run Play again. Which isn't a very good UI experience.

I do agree, it should be changed / renamed / redone, but obviously outside the scope of the PR.

**Comment by slemeur** [comment]
This is really good, awesome work. 🚀 🥳

**Comment by benoitf** [comment]
@cdrage now it'll correctly display the error:
image

**Review by cdrage — APPROVED** [review]

**Pull request merged**
