### PR TITLE
fix: update Podman extension init procedure to async

### LINKED ISSUE #9124: Podman extension should be initialized async
### Bug description

While testing a PR on my machine, I noticed the Podman extension does not start anymore because it now takes more than 20s.
It should be made async

### Operating system

Win11Pro

### Installation Method

None

### Version

1.11.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #9124

### What does this PR do?

Switch the Podman extension to be async

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#9124 

### How to test this PR?

Run unit test

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
code LGTM but i wonder why now it gets 20+ secs when it worked before. Bc on my machine it takes <=7secs

**Comment by jeffmaury** [comment]
> code LGTM but i wonder why now it gets 20+ secs when it worked before. Bc on my machine it takes <=7secs

Maybe I should reboot because this PR is broken for me in admin mode (no way to create Podman machine need to refresh the provider store)

**Review by lstocchi — CHANGES_REQUESTED** [review]
@jeffmaury just run it and i have your same issue

**Comment by jeffmaury** [comment]
> code LGTM but i wonder why now it gets 20+ secs when it worked before. Bc on my machine it takes <=7secs



> code LGTM but i wonder why now it gets 20+ secs when it worked before. Bc on my machine it takes <=7secs

Maybe I should reboot because this PR is broken for me in admin mode (no way to create Podman machine need to refresh the provider store)

**Review by benoitf — COMMENTED** [review]
Why is it taking more than 20s ?

**Comment by jeffmaury** [comment]
> Why is it taking more than 20s ?

Don't know yet, checking

**Pull request closed without merging**
