### PR TITLE
chore: improve task names

### LINKED ISSUE #9536: Improve titles of some tasks
### Is your enhancement related to a problem? Please describe

With the tasks now showing on the statusbar we are exposing the titles of tasks more often. A few of these can be improved.

A couple of examples are:
1. `Create Container provider` when you are creating a new Podman Machine.  Should `Creating Podman Machine` 
3. `Stop podman-machine-default` -> `Stopping podman-machine-default`
4. `Start podman-libkrun` -> `Starting podman-machine-default`
5. `Create Kubernetes provider` (no difference between creating `kind` cluster or `minikube` cluster). Ideally this would be `Creating Kind provider` `Creating MiniKube provider`
6. When building an image the name is just `Build`. Can we make it `Building image <image-name>`?
We are also missing some:
1. When you pull an image, there is no message

### Describe the solution you'd like

Update the texts

### PR DESCRIPTION
**Pull request by SoniaSandler**
Signed-off-by: Sonia Sandler <ssandler@redhat.com>

### What does this PR do?
Improves the existing task titles in PD

### Screenshot / video of UI
Screenshot from 2024-12-05 12-18-20
Screenshot from 2024-12-05 12-24-28

### What issues does this PR fix or reference?
Fixes https://github.com/podman-desktop/podman-desktop/issues/9536

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by slemeur** [comment]
thank you @SoniaSandler

**Review by slemeur — APPROVED** [review]
Tested, works for me

**Review by benoitf — APPROVED** [review]

**Comment by SoniaSandler** [comment]
@Firewall for exporting container, there is no container name, just its id. As seen in the screenshot above, the task name will include the long id of the container. Is this okay, or do we want to change that to `Exporting container`?

**Comment by Firewall** [comment]
Great catch! What about the short-id? Only 12 characters. Is that something we can use? 

On the other hand, with the new task manager we will have a lot more space then the old one.

**Comment by SoniaSandler** [comment]
We can do the short id for now (it's a really small change), and then undo it with the new task manager if needed

**Comment by SoniaSandler** [comment]
@Firewall updated
before:
Screenshot from 2024-12-06 10-57-48

after:
Screenshot from 2024-12-06 10-56-50

**Comment by Firewall** [comment]
Awesome 🎉

**Review by Firewall — APPROVED** [review]

**Pull request merged**
