### PR TITLE
fix: catch error when failing at installing kind

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

it handle a possible error when installing kind

### Screenshot/screencast of this PR

image

### What issues does this PR fix or reference?

#1584 

### How to test this PR?

1. Not sure honestly. I just launched Podman on fedora and i could see the error message on the console.
2. By debugging i can see that Oktokit is not able to fetch releases -> HttpError status 500 fetch failed

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by benoitf** [comment]
side note:
it seems that the loading on github API should not be done eagerly
I mean, until I don't click on "install" button we shouldn't fetch from github maybe ?

it looks like we're delaying the activation of the extension to fetch these data while activate method should be the fastest

**Comment by benoitf** [comment]
in short: activate method of an extension that takes time = UI of Podman Desktop being displayed later

**Comment by jeffmaury** [comment]
> side note: it seems that the loading on github API should not be done eagerly I mean, until I don't click on "install" button we shouldn't fetch from github maybe ?
> 
> it looks like we're delaying the activation of the extension to fetch these data while activate method should be the fastest

Agree as Github release info is just pulled to check if installation is available/possible, could easily be delayed

**Comment by lstocchi** [comment]
It makes sense but i think it's another gh issue. Do i open it?

**Comment by benoitf** [comment]
it's not blocking the merge of this pr

**Pull request merged**
