### PR TITLE
fix: fail extension load when manifest is incomplete

### LINKED ISSUE #2871: When installing an extension that has an undefined displayName the extensions section gets broken
### Bug description

If an extension does not have a display name the extensions section is broken.
 
extension-tree-broken

It fails at 

```
export async function fetchExtensions() {
  const result = await window.listExtensions();
  result.sort((a, b) => a.displayName.localeCompare(b.displayName));
  extensionInfos.set(result);
}
```

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. install quay.io/lstocchi/sample-podman-extension:v1
2. check that your extensions section is broken

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

This changes analyzeExtension() to reject the Promise if there is an error loading an extension (no manifest or missing required attributes), instead of returning undefined. The main reason for the change is to allow error messages to be propagated back to the client (e.g. UI).

The remaining changes are handling this in all the places that call analyzeExtension(). IMHO most are more readable and handle error cases cleaner after this change, but for lines 267/272/286 I tried several options and couldn't find anything better than adding '.catch(() => undefined))).'

There is also a related issue: if an extension is corrupt or fails to install, the extension installer doesn't clean it up. This doesn't cause any direct issues (on each startup it would quietly be ignored before; now it will log) but I was going to defer this to another PR.

### Screenshot/screencast of this PR

Screenshot 2023-06-23 at 2 17 03 PM

### What issues does this PR fix or reference?

Fixes #2871.

### How to test this PR?

See issue #2871 - try installing this extension: quay.io/lstocchi/sample-podman-extension:v1

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
Hi, I would say that try catch is a pattern but catch => undefined is not a pattern to use

**Comment by deboer-tim** [comment]
Agreed, that was only to get back to the .filter() and ignore anything that didn't load as an extension. It feels like there should be some slick way to use .then() or Promise.allSettled(), but so far all I've come up with is changing:
```
await Promise.all(folders.map(folder => this.analyzeExtension(folder, false).catch(() => undefined)))
   ).filter(extension => extension !== undefined) as AnalyzedExtension[];
```
to something like:
```
await Promise.allSettled(
   externalExtensions.map(folder => this.analyzeExtension(folder, false)),
).then(values =>
   values.filter((x): x is PromiseFulfilledResult<AnalyzedExtension> => x.status === 'fulfilled').map(o => o.value),
) as AnalyzedExtension[];
```
which doesn't feel like much of a win.

**Comment by jeffmaury** [comment]
> Agreed, that was only to get back to the .filter() and ignore anything that didn't load as an extension. It feels like there should be some slick way to use .then() or Promise.allSettled(), but so far all I've come up with is changing:
> 
> ```
> await Promise.all(folders.map(folder => this.analyzeExtension(folder, false).catch(() => undefined)))
>    ).filter(extension => extension !== undefined) as AnalyzedExtension[];
> ```
> 
> to something like:
> 
> ```
> await Promise.allSettled(
>    externalExtensions.map(folder => this.analyzeExtension(folder, false)),
> ).then(values =>
>    values.filter((x): x is PromiseFulfilledResult<AnalyzedExtension> => x.status === 'fulfilled').map(o => o.value),
> ) as AnalyzedExtension[];
> ```
> 
> which doesn't feel like much of a win.

What about:

```
await Promise.allSettled(
   externalExtensions.map(folder => this.analyzeExtension(folder, false)),
).then(values =>
   values.filter(x => x.status === 'fulfilled').map(o => o.value),
) as AnalyzedExtension[];
```

**Review by jeffmaury — COMMENTED** [review]
See comment

**Comment by deboer-tim** [comment]
I had tried that, but it gives an error b/c value doesn't exist on rejected results:
```
Property 'value' does not exist on type 'PromiseSettledResult<AnalyzedExtension>'.
  Property 'value' does not exist on type 'PromiseRejectedResult'.ts(2339)
```
hence the extra `x is PromiseFulfilledResult<AnalyzedExtension>`.

**Comment by benoitf** [comment]
Maybe analyzeExtension method should not send errors but return complete/incomplete objects.
so we don't need to catch here

**Review by benoitf — CHANGES_REQUESTED** [review]
my last comment was about a request for changes

**Comment by deboer-tim** [comment]
Sorry for the super long delay @benoitf. I've been taking a look at this again, and maybe I still don't understand the suggestion: analyzeExtension() is used by 7-8 places (install, start, reload, etc) to check if a folder is a valid extension, and if it returns an extension they load it. If analyzeExtension() returns an incomplete or Partial<> object, it would fall to each of these callers to decide if the extension is good enough to proceed.

I'm worried this could lead toward duplicated, and potentially inconsistent code (e.g. extension was 'good enough' to install, but then fails on restart). Am I misunderstanding, or is there another way to return 'this is not a valid extension' besides a rejected Promise?

**Comment by benoitf** [comment]
> Sorry for the super long delay @benoitf. I've been taking a look at this again, and maybe I still don't understand the suggestion: analyzeExtension() is used by 7-8 places (install, start, reload, etc) to check if a folder is a valid extension, and if it returns an extension they load it. If analyzeExtension() returns an incomplete or Partial<> object, it would fall to each of these callers to decide if the extension is good enough to proceed.

I'm worried this could lead toward duplicated, and potentially inconsistent code (e.g. extension was 'good enough' to install, but then fails on restart). Am I misunderstanding, or is there another way to return 'this is not a valid extension' besides a rejected Promise?


Today, we already have a condition in all the places where we check if we return an object or not.
so if it returns an object with an optional error it'll just change the check by if we don't have errors by `if (!result.error)`

In the code, you're silently catching errors so I would say it's not better rather than if we're able to store errors in the objects so callers can filter more easily. 

Handling errors in asynchronous calls is much of the time leading to worse patterns

> it would fall to each of these callers to decide if the extension is good enough to proceed.

if an error is thrown it's still their responsibility. Also if caller is not doing the right check it can fail later if you provide an invalid object to the next step as well.

But if error is stored within the object, then we can list all extensions with their associated errors, etc.

**Comment by deboer-tim** [comment]
Thanks @benoitf, I understand and concur now. This is so old that I have a new fork and am having trouble getting GitHub to pick up changes in the branch, so I've opened up new PR #4380 to continue and will close this one.

**Pull request closed without merging**
