### PR TITLE
docs: Correct windows instructions for migrating from docker

### PR DESCRIPTION
**Pull request by foxydevloper**
### What does this PR do?

On windows, `DOCKER_HOST` is set to a named pipe instead of a socket, and podman has a seperate field for it, "PodmanPipe", the docs accidentally put "PodmanSocket" on windows. This also notes that you don't actually need to set `DOCKER_HOST` on windows, since podman already uses the default `docker_engine` named pipe.

### How to test this PR?

Run command on windows

### CODE REVIEW

**Review by cdrage — APPROVED** [review]
You're completely correct, this should of been `npipe://` I even see it's the same in the docker documentation as well: https://docs.docker.com/desktop/faqs/general/

Thanks for this contribution!

**Comment by foxydevloper** [comment]
firefox_2023-09-29_16-22-58

**Comment by foxydevloper** [comment]
Fixed the build. Here's how the built docs look:
image

**Review by cdrage — APPROVED** [review]

**Comment by sandial1** [comment]
Well, first of all, @foxydevloper thank you. I ran into this issue yesterday while installing podman for the first time in my Windows machine and finally solved it today with your aid.

On the other hand, I also suggest adding a note about command line emulators:

__The export command to set environment variables only works io Git Bash in windows.__

Mostly to clean it up for clarity/newbies (like me):

# Windows socket manual configuration:
Command to get socket path config:
```shell-session
podman machine inspect --format '{{.ConnectionInfo.PodmanPipe.Path}}'
```

Changing all the backwards slashes for forward slashes.
Itshould look like:
```shell-session
//./pipe/podman-machine-default
```

To this path you must then add the prefix:
```shell-session
npipe://
```

The final path should look like
```shell-session
npipe:////./pipe/podman-machine-default
```

## Commands to set the environment variable:
### cmd:
```cmd
set DOCKER_HOST=npipe://<inspect_command_output>
```
#### example:
```cmd
set DOCKER_HOST=npipe:////./pipe/podman-machine-default
```
### Git Bash:
```bash
export DOCKER_HOST=npipe://<inspect_command_output>
```
#### example:
```bash
export DOCKER_HOST=npipe:////./pipe/podman-machine-default
```

### powershell:
```powershell
$env:DOCKER_HOST="npipe://<inspect_command_output>"
```
note: Don't miss the quotes on the value or powershell will try to interpret it as a command.
#### example:
```powershell
$env:DOCKER_HOST="npipe:////./pipe/podman-machine-default"
```

**Comment by foxydevloper** [comment]
On windows you can also set the environment variable in the windows environment variables program. But yeah, I kind of missed that part. If you're able to make a PR with those changes you could definitely go for it!

**Comment by sandial1** [comment]
> On windows you can also set the environment variable in the windows environment variables program. But yeah, I kind of missed that part. If you're able to make a PR with those changes you could definitely go for it!

Hmm sure,  why not? IT is Hacktoberfest and a good chance as any to make a contribution.

**Pull request merged**
