### PR TITLE
docs: improve navigation by avoiding third level pages for images

### LINKED ISSUE #5338: Doc: Improve left-sidebar navigation
### Is your enhancement related to a problem? Please describe

When you arrive on the documentation, we have a lot of sections but it's hard to know what's in each of the section. It forces the reader to "unflod" each of the section to have an idea of what's into it. 

Screenshot 2023-12-20 at 10 18 44

### Describe the solution you'd like

We would like to have 2 levels of sections unfolded by default.
Also, we would like to visually differentiate the levels of navigation.

Example:
Screenshot 2023-12-20 at 10 21 16
(link: https://ionicframework.com/docs)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by themr0c**
### What does this PR do?

docs: improve navigation by avoiding third level pages for containers/images.

- Moved the content in one single page.
- No changes in the content itself.
- Added redirections.

### What issues does this PR fix or reference?

references #5338 

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by themr0c** [comment]
Can you merge it, please?

**Comment by themr0c** [comment]
The Argos test requires a file that does not exist. I believe the Argos test itself is broken, not this pull request.

**Comment by themr0c** [comment]
I will continue rebasing and fixing the increasing number of conflicts and errors once I receive an agreement on the content. It makes no sense investing time in this activity if the team has no plan to accept the pull request.

**Comment by cdrage** [comment]
Closing this as per discussion the plan is to not have this in one singular page, but expand the sections on pulling / pushing / creating images as those parts become more complex with registry and other extension further making them complex.

**Pull request closed without merging**
