### PR TITLE
feat: add alias for registry entries

### LINKED ISSUE #6298: allow to add aliases/display name when authenticating users in registries
### Is your enhancement related to a problem? Please describe

some providers are generating very ugly username to log-in to registries

For example, with some SSO, username could be "my-very-long-username-generated-for-podman-desktop"
but as it has been generated using SSO access, I think it would be better to display the account name used for example
`john.doe@company.com`

Of course, hovering or clicking will reveal the real username but by default it would display the alias

### Describe the solution you'd like

- Add option to register alias/display name in addition to the login name in the API
- Render display name instead of the username by default

### Describe alternatives you've considered

_No response_

### Additional context

need to store the alias in auth.json file, can add extra field with podman-desktop name on it.

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #6298

### What does this PR do?

Extend Podman Desktop API to allow to register a registry user with an alias and display that alias in the registries page. Field is serialized in auth.json as an additional `podman_desktop.alias` field 

### Screenshot / video of UI

registries

### What issues does this PR fix or reference?

#6298

### How to test this PR?

- Edit your $HOME/.config/containers/auth.json -> add podman_desktop.alias field next to the auth field
- Start Podman Desktop and go the registries field

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
is that toml is fine using dotted keys ?

**Comment by jeffmaury** [comment]
> is that toml is fine using dotted keys ?

That's a JSON file ?

**Review by benoitf — COMMENTED** [review]
maybe use recommended camelCase approach https://jsonapi.org/recommendations/#naming

`podmanDesktopAlias`

**Comment by benoitf** [comment]
@jeffmaury did you forget to push some changes ? You re-requested a review but I don't see any changes from my last review ?

**Comment by jeffmaury** [comment]
> @jeffmaury did you forget to push some changes ? You re-requested a review but I don't see any changes from my last review ?

Click Push while the commit hook was still running :)

**Review by benoitf — APPROVED** [review]

**Review by axel7083 — APPROVED** [review]
LGTM

**Pull request merged**
