### PR TITLE
fix: handle ignoreFocusOut on Modal and dialog visibility

### LINKED ISSUE #7686: Link navigation in QuickInput panel description shows confirmation dialog as grayed out
### Bug description

image

### Operating system

macOS M1 Sonoma 14.5

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

* Install OpenShift Local extension,
* Install OpenShift Local and press 'Initialize and start' on dashboard
* Wait until QuickInput for pull-secret appears with link in deskription
* Click on link to get to screen show abowe

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR fixes a couple of issues that were preventing to open a confirmation dialog from an inputbox (like done in CRC).
The main problem was that we have the `ignoreFocusOut` property but it is not handled at all in the UI, so the inputBox was closed everytime a user clicked out of it.

### Screenshot / video of UI

ignorefocusout

### What issues does this PR fix or reference?

it resolves #7686 

### How to test this PR?

1. Install OpenShift Local and press 'Initialize and start' on dashboard
2. Wait until inputbox for pull-secret appears with link in description
3. Click on the link. You should be able to go to the browser and get back to desktop and add the pull secret value into the inputbox

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — COMMENTED** [review]
I am wondering if we should not simply move the z-order to have the Messagebox ahead ?

**Comment by lstocchi** [comment]
> I am wondering if we should not simply move the z-order to have the Messagebox ahead ?

I opted to just switching their order so to not messing with other items. Not sure if increasing the z-index for Messagebox would cause some other misbehavior. Switching the order seemed quicker.

The main problem was that Desktop offers the `ignoreFocusOut` property https://github.com/containers/podman-desktop/blob/12077341a37b27f8749912e1353ec611e750891a/packages/extension-api/src/extension-api.d.ts#L1159 but we do not actually have any code to make the UI behave based on its value.

**Comment by lstocchi** [comment]
rebased

**Review by axel7083 — APPROVED** [review]

**Review by cdrage — APPROVED** [review]
LGTM and no issues doing it, and code looks good.  I do see however that there is a GitHub warning regarding one of the tests which may need changing, otherwise LGTM.

**Comment by lstocchi** [comment]
> LGTM and no issues doing it, and code looks good. I do see however that there is a GitHub warning regarding one of the tests which may need changing, otherwise LGTM.

Seems it was a flacky test not related to this PR

**Pull request merged**
