### PR TITLE
feat: register docker-compose cli tool through podman-desktop/cli API

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

Uses cli API to register docker-compose CLI tool in podman-desktop

### Screenshot/screencast of this PR

Screenshot 2023-10-18 at 12 29 29 AM

### What issues does this PR fix or reference?

related to https://github.com/containers/podman-desktop/issues/3781
depends on https://github.com/containers/podman-desktop/pull/4197

### CODE REVIEW

**Comment by deboer-tim** [comment]
That description will be way too long by the time we get multiple tools. Can we have the UI control crop long descriptions to 2-3 lines, with some way to show the full text (e.g. twisty or "more" link)?

**Comment by benoitf** [comment]
what is looking odd to me is that we somehow want to promote `podman compose` and not directly `docker-compose` so maybe it should be highlighted somehow that's an enabler for 'podman cli tool' or that we display 'podman compose' instead of 'docker-compose' I don't know

**Comment by benoitf** [comment]
the icon is not the one from the compose extension also ? https://github.com/containers/podman-desktop/blob/main/extensions/compose/icon.png

**Review by cdrage — CHANGES_REQUESTED** [review]
Some of my review comments may have been lost, I see a few things that we should do:

- Use the description and icon added from: https://github.com/containers/podman-desktop/pull/4179
- Defining the createCliTool should be done within`extension.ts` not `compose-extension.ts` as we are removing the `compose-extension.ts` file in the future / not having Compose on the status bar anymore.

**Comment by cdrage** [comment]
> what is looking odd to me is that we somehow want to promote `podman compose` and not directly `docker-compose` so maybe it should be highlighted somehow that's an enabler for 'podman cli tool' or that we display 'podman compose' instead of 'docker-compose' I don't know

We should use the description that is being added via https://github.com/containers/podman-desktop/pull/4179

**Comment by dgolovin** [comment]
> @deboer-tim: That description will be way too long by the time we get multiple tools. Can we have the UI control crop long descriptions to 2-3 lines, with some way to show the full text (e.g. twisty or "more" link)?

This should be implemented in #3781.

**Comment by dgolovin** [comment]
> @benoitf: what is looking odd to me is that we somehow want to promote podman compose and not directly docker-compose so maybe it should be highlighted somehow that's an enabler for 'podman cli tool' or that we display 'podman compose' instead of 'docker-compose' I don't know

Description should be definitely updated to be about 'podman compose'. On the left side it should still say 'docker-compose' because users should know exactly what is going to be installed.

**Comment by cdrage** [comment]
Hi @dgolovin I've opened up https://github.com/containers/podman-desktop/pull/4437 to replace this PR with some changes.

**Comment by dgolovin** [comment]
@cdrage Do you want to replace #4387 and #4388 with this PR?

**Comment by mairin** [comment]
I don't think we can use that icon. We have permission to use the Docker icon for referring to Docker but only the one we were given (we use it for the Docker provider on the Dashboard and in Settings > Resources.) I would use the Compose icon because that's affiliated with the tool.

I agree with @deboer-tim that the text is too long. Where is it coming from? Is it pulling from a file included with docker-compose? This is what I came up with for the mockup:

"The Compose extension provides optional command line support for compose files with Podman. More details, including usage info, are available in Compose Settings."

**Comment by cdrage** [comment]
> I don't think we can use that icon. We have permission to use the Docker icon for referring to Docker but only the one we were given (we use it for the Docker provider on the Dashboard and in Settings > Resources.) I would use the Compose icon because that's affiliated with the tool.
> 
> I agree with @deboer-tim that the text is too long. Where is it coming from? Is it pulling from a file included with docker-compose? This is what I came up with for the mockup:
> 
> "The Compose extension provides optional command line support for compose files with Podman. More details, including usage info, are available in Compose Settings."

Im going to close this PR as https://github.com/containers/podman-desktop/pull/4437 replaces it.

Let's continue the discussion in https://github.com/containers/podman-desktop/pull/4437 but can we use the already existing compose logo. I believe this icon.png was added just for testing by @dgolovin

**Pull request closed without merging**
