### PR TITLE
chore: add Settings title on left sidebar and remove navbar on right panel

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This extracts a part from https://github.com/containers/podman-desktop/pull/1582
It removes the navbar from all internal pages and adds the title in the left sidebar as planned by https://github.com/containers/podman-desktop/issues/1338

### Screenshot/screencast of this PR

immagine

### What issues does this PR fix or reference?

https://github.com/containers/podman-desktop/issues/1337

### How to test this PR?

1. start it and go to the settings

### CODE REVIEW

**Comment by benoitf** [comment]
it doesn't work for resources item in my case

And extensions are not displayed in extension list (tree is never being able to expand)

Also, how do you see preferences ? they are displayed by default but I can't get them back

https://user-images.githubusercontent.com/436777/224744945-4c188212-e584-4d4d-b492-c13f2aff409f.mp4

**Comment by lstocchi** [comment]
> it doesn't work for resources item in my case
> 
> And extensions are not displayed in extension list (tree is never being able to expand)
> 
> Also, how do you see preferences ? they are displayed by default but I can't get them back

I didn't notice before, maybe i tested it before rebasing. 
I confirm i have the same broken behavior as yours, also in the main branch. Investigating.

**Comment by benoitf** [comment]
it was broken after svelte update
https://github.com/containers/podman-desktop/pull/1684

**Comment by benoitf** [comment]
@lstocchi if you can rebase your PR on top of main branch as regression is fixed

**Comment by lstocchi** [comment]
> @lstocchi if you can rebase your PR on top of main branch as regression is fixed

done 👍

**Review by benoitf — APPROVED** [review]
checked settings page and they're all working fine 👍 

https://user-images.githubusercontent.com/436777/224944986-ca0508cc-fa97-4e5d-af1f-9f3eacb2f851.mp4

**Pull request merged**
