### PR TITLE
Light mode for installed extensions buttons

### LINKED ISSUE #7185: Light mode for actions/dropdown menus/bars
### Is your enhancement related to a problem? Please describe

We have actions buttons that don't support light mode.

At a minimum this includes actions, drop-down menus, and the bars they're on in the following places:
1. Actions in Containers/Images/Pods/Volumes views. 
  -> #7480
  -> #7519  
2. Extensions > Installed actions 
  -> #7520 
3. Settings > Resources actions on Podman machines.
  -> https://github.com/containers/podman-desktop/pull/7529

### Describe the solution you'd like

Extract colors for each of these to the registry and add light mode colors.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Light mode for actions buttons on Installed Extensions list

The icon color of the button changes from white to gray-400 and hover button from gray-700 to purple-600, to reuse the same colors as for the actions buttons in the Containers/Pods/Images lists.
 
### Screenshot / video of UI

https://github.com/containers/podman-desktop/assets/9973512/e944e7ce-6c7e-483c-bc41-69feffbb090f

### What issues does this PR fix or reference?

Fixes #7185 

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by deboer-tim — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
hello, why do we need 'action buttons' there ?

I think that buttons are buttons not action buttons

Why do we have introduced a new section/different type of things ? rather than using 'buttons'

**Comment by deboer-tim** [comment]
> hello, why do we need 'action buttons' there ?
> 
> I think that buttons are buttons not action buttons
> 
> Why do we have introduced a new section/different type of things ? rather than using 'buttons'

My bad for thinking the same thing on #7480 (which defined these colors) but waffling and not saying it. Either here or another PR I think we should merge initActionButton() into initButtons() and treat these as if they were another style of button in Button.svelte, i.e. we have primary, secondary, danger, and 'action' (although maybe with another name).

**Comment by feloy** [comment]
> > hello, why do we need 'action buttons' there ?
> > I think that buttons are buttons not action buttons
> > Why do we have introduced a new section/different type of things ? rather than using 'buttons'
> 
> My bad for thinking the same thing on #7480 (which defined these colors) but waffling and not saying it. Either here or another PR I think we should merge initActionButton() into initButtons() and treat these as if they were another style of button in Button.svelte, i.e. we have primary, secondary, danger, and 'action' (although maybe with another name).

I have sticked to the current colors of the actions buttons, which are not the same as the button ones. And because it is not the same component, I thought it was better to use a new category (action-button).

@deboer-tim I'm not sure to understand, do you want to merge LoadingIconButton with Button, or only the colors functions initActionButton and initButtons?

**Comment by jeffmaury** [comment]
The stop button seems a little dark to me

**Review by benoitf — APPROVED** [review]

**Pull request merged**
