### PR TITLE
feat: Updating palette colors for nav + main

### LINKED ISSUE #2287: Update UI palette colors
Corresponding with https://github.com/containers/podman-desktop/issues/2156 - updating palette colors for main screens + settings screens + adding some aesthetic visual tweaks (namely drop shadows / shading)

### PR DESCRIPTION
**Pull request by mairin**
### What does this PR do?

Building on color palette cleanup in https://github.com/containers/podman-desktop/pull/2199 - this removes some of the upstream tailwind zinc colors and replaces with charcoal colors from the podman desktop palette. This also adds a drop shadow to the main nav bar right-side, and a highlight to the bottom of the titlebar.

### Screenshot/screencast of this PR

Note the differences are super-slight... this is cleaning up usage of zinc-* color palette items to instead use the charcoal-* color palette items so we can eventually drop the zinc-* colors. The main visible difference is that the titlebar is darker. 

#### Dashboard

<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>

Screenshot from 2023-05-01 20-22-50

</td><td>

Screenshot from 2023-05-01 20-21-28

</td>
</tr>
</table>

#### Containers

<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>

Screenshot from 2023-05-01 20-22-55

</td><td>

Screenshot from 2023-05-01 20-21-33

</td>
</tr>
</table>

#### Settings > Resources

<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>

Screenshot from 2023-05-01 20-22-59

</td><td>

Screenshot from 2023-05-01 20-21-37

</td>
</tr>
</table>

### What issues does this PR fix or reference?

This helps address:
https://github.com/containers/podman-desktop/issues/1384

### How to test this PR?

Build and run and page around making sure there's good contrast between nav and main screen areas and that there's no bugginess in base colors vs hover colors in the nav or any other weird visual oddities.

### CODE REVIEW

**Comment by benoitf** [comment]
FYI contrast ratio is failing on titles of the table of container list

image

**Comment by mairin** [comment]
@benoitf I ended up darkening the base color of the background the column headers appear on, but I also brightened them a bit so the contrast hsold be a lot better now.

**Comment by mairin** [comment]
Found an issue on long pages with scroll, looking into it

Screenshot from 2023-05-01 10-08-06

**Comment by mairin** [comment]
Dropped all the drop shadows for another PR (https://github.com/containers/podman-desktop/pull/2288/)

**Comment by cdrage** [comment]
Verified that the palette has changed and I don't see any majorly contrasting changes, so this LGTM. I'll let someone else also have a look at it before we merge before our release 💯

**Review by cdrage — APPROVED** [review]

**Pull request merged**
