### PR TITLE
fix: detect virtual machine platform instead of hyper-v

### LINKED ISSUE #480: Pre-flight check should catch hyper-v name on Windows Home (Virtual Machine Platform)
### Bug description

Podman Desktop requires hyper-v being enabled in order to install podman. This is not a prerequisite for podman installation on windows:
* https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md

### Operating system

windows 11 home

### Version

0.0.7

### Steps to reproduce

1. Ensure you dont have hyper-v enabled on your windows machine
2. Ensure you dont have podman installed on your windows machine 
3. download Podman Dekstop
4. Visit Podman Dekstop home page and validate that Podman Desktop shows the message about installing hyper-v before installing podman
5. Follow instructions on installing podman for windows https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md
6. After finishing the installation, open Podman Desktop and validate your are able to use podman and Podman Desktop.

### Relevant log output

_No response_

### Additional context

A solution would be to remove the "enable hyper-v" step on Podman Desktop as we are able to use podman and Podman Desktop without hyper-v being enabled.

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
It use Virtual Machine Platform detection, instead of hyper-v.
As Virtual Machine Platform is subset of Hyper-V, and required to use WSL2, this PR changes detection, which allow installation if podman on windows home edition.

### Screenshot/screencast of this PR
Screenshot 2023-01-26 145320

### What issues does this PR fix or reference?
fix #480

### How to test this PR?

Run it on Windows 10 home, with Virtual Machine Platform feature enabled, and try to install podman.

### CODE REVIEW

**Comment by benoitf** [comment]
@lstocchi @jeffmaury if one of you can check this PR ?

**Comment by lstocchi** [comment]
@jeffmaury do you have any home edition? I'm on the enterprise version, not sure if this can influence the results.

**Comment by jeffmaury** [comment]
> @jeffmaury do you have any home edition? I'm on the enterprise version, not sure if this can influence the results.

I am about installing it on my old machine so far PR runs fin on my W11Pro laptop

**Comment by benoitf** [comment]
ok let me check then, I have a VM with home edition

**Review by benoitf — APPROVED** [review]
checked on a Windows Home edition and check is working fine
image

**Pull request merged**
