### PR TITLE
fix: handle path with spaces on Windows when installing Podman (#1208)

### LINKED ISSUE #1208: Podman desktop automatic installation of Podman with space on user path fails
### Bug description

When user path has a space e.g. `C:\Users\John Doe`, when trying to install Podman on fresh Windows 10 installation, Podman installation fails raising error about path `C:\users\John` (note missing `Doe`). This is presumably space handling issue.

Downloading Podman installer manually and running it works fine.

### Operating system

Windows 10

### Version

0.10.0

### Steps to reproduce

1. Fresh Windows 10 Pro VM install, defining user name with a space e.g. `John Doe`
2. Download Podman desktop and start
3. Follow steps to enable Hyper V and WSL on fresh Windows install (2x restart)
4. Once no Podman system is identified by Podman Desktop, click on automatic install.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

It makes sure to install Podman even on paths having spaces
Found a discussion on node repo about it https://github.com/nodejs/node/issues/38490#issuecomment-830544134
By wrapping the path with double quotes everything should work fine.

This also impacts MacOs users so please give it a try. It should work though.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #1208 

### How to test this PR?

1. make sure you don't have podman installed and you have a username with a space in it
2. start podman-desktop and install podman from it

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
tested on macOS and it works fine

**Comment by jeffmaury** [comment]
Out of curiosity, why do we require shell: true on Windows only where we have a lot of other calls of spawn that don't deal with this specific ?

**Review by cdrage — APPROVED** [review]

**Comment by benoitf** [comment]
@jeffmaury https://github.com/containers/podman-desktop/pull/160/files#r884494437

**Comment by jeffmaury** [comment]
> @jeffmaury https://github.com/containers/podman-desktop/pull/160/files#r884494437

Yes but the case covered there is about yarn which is a script and the ones covered by Luca are about kind and podman which are executables.

**Comment by benoitf** [comment]
If it works fine for you on Windows we can remove the shell options ( in another PR)

**Pull request merged**
