### PR TITLE
Fix 'an pod' typo

### PR DESCRIPTION
**Pull request by cfergeau**
### What does this PR do?

This fixes a typo in the "pods" view

### CODE REVIEW

**Comment by deboer-tim** [comment]
I was going to fix this last week, but then I noticed the entire message - and on every other page - is out of date and doesn't match our current UI. I would like to just decide on a new phrase and fix them all.

**Comment by cfergeau** [comment]
Ah ok, it's my very first time running podman-desktop, so I did not even realize it's out of date :) This can be closed then!

**Comment by benoitf** [comment]
@cfergeau could you amend your commit to have SignedOff then dco check will be  ✅

**Comment by benoitf** [comment]
fix is OK before sentence could be reworked

**Review by benoitf — APPROVED** [review]

**Pull request merged**
