### PR TITLE
fix: horizontal docker logo

### PR DESCRIPTION
**Pull request by afbjorklund**
### What does this PR do?

* use the horizontal version of the docker logo
* remove the text from the icon version of the logo

https://www.docker.com/company/newsroom/media-resources/ + gimp

### Screenshot/screencast of this PR

dashboard-docker-logo

resources-docker-logo

### CODE REVIEW

**Comment by benoitf** [comment]
cc @mairin

**Comment by mairin** [comment]
@afbjorklund This is a great idea! My only hesitation is that when we're working with mulitple logos, it's a good idea to scale them so the sizing is consistent. I wonder, could a max-width / max-height be placed on both so they don't appear disproportionate?

**Comment by afbjorklund** [comment]
> could a max-width / max-height be placed on both so they don't appear disproportionate?

currently it sets max **height**, which is why it looks a bit odd when the originals have different width

maybe something like:

```diff
--- a/packages/renderer/src/lib/dashboard/ProviderLogo.svelte
+++ b/packages/renderer/src/lib/dashboard/ProviderLogo.svelte
@@ -19,6 +19,6 @@ $: {
 {#if logo}
   <div class="flex">
     <!--w-3/4 lg:w-2/3 xl:w-1/2 -->
-    <img src="{logo}" alt="{provider.name}" class="mx-auto max-h-24 xl:max-h-36" />
+    <img src="{logo}" alt="{provider.name}" class="mx-auto max-w-[300px]" />
   </div>
 {/if}

```

The [Lima logo](https://github.com/lima-vm/lima/blob/master/docs/images/lima-logo-01.svg) is of a much lower resolution (150 x 52), so it doesn't really need to scale down.

It _should_ also be a bigger size:

logo-width


EDIT: #3248

**Comment by benoitf** [comment]
> remove the text from the icon version of the logo

I am wondering if we have the right to edit the logo and remove the text of the whale as it seems all logo include the text ?
cc @mairin do you know if it's OK ?

**Comment by afbjorklund** [comment]
It is quite possible that it should use the other version, with the ® sign:

**Comment by mairin** [comment]
@benoitf I checked the approved logo pack we received from Docker with permission to use and it includes versions of the logo separated from the text. I will forward to you via email if that's ok.

**Comment by benoitf** [comment]
@mairin ok but there should be the ® sign as @afbjorklund pointed out ? because here we don't have it

**Comment by mairin** [comment]
> @mairin ok but there should be the ® sign as @afbjorklund pointed out ? because here we don't have it

Nope, we don't need it as its not included in the official logos we were sent to use. (We also dont use the ® / TM marks for other brands I work with so it seems ok.)

**Comment by benoitf** [comment]
@afbjorklund so it looks the file to use is

symbol_blue-docker-logo

**Comment by benoitf** [comment]
and
primary-blue-docker-logo

**Comment by afbjorklund** [comment]
~~Ok, will gimp those (to the right size)~~

**Comment by benoitf** [comment]
@afbjorklund do we need to gimp them ? because these are the one that we are allowed to use

**Comment by deboer-tim** [comment]
Agreed, we should use exactly what they approved and use styling/layout sizing to make things consistent in the UI.

**Comment by afbjorklund** [comment]
Some of the icon sizes are quite enormous.

extensions/docker/icon.png:       PNG image data, 1316 x 1126, 8-bit/color RGBA, non-interlaced
extensions/kind/icon.png:         PNG image data, 985 x 594, 8-bit/color RGBA, interlaced
extensions/kube-context/icon.png: PNG image data, 3600 x 3493, 8-bit/color RGBA, non-interlaced
extensions/lima/icon.png:         PNG image data, 150 x 52, 8-bit/color RGBA, non-interlaced
extensions/podman/icon.png:       PNG image data, 204 x 204, 8-bit/color RGBA, non-interlaced

They are also not square, so align strangely.

**Comment by afbjorklund** [comment]
But, you do you. Left the originals.

**Review by benoitf — APPROVED** [review]

**Comment by afbjorklund** [comment]
I liked Moby Dock the best, anyway. :-)

**Comment by benoitf** [comment]
@afbjorklund unfortunately it seems this one is not in the logos they gave us.

**Comment by afbjorklund** [comment]
I know, everything is ugly these days. Like the Circle of Friends, or even Shadowman.

I think it started with the Apple logo ? Or when did the world go back to monochrome ?

**Pull request merged**
