### PR TITLE
chore(ui): add ARIA functionality into Authentication Providers Page

### PR DESCRIPTION
**Pull request by odockal**
### What does this PR do?
It introduces ARIA functionality in Authentication Page.
### What issues does this PR fix or reference?
#6712

### How to test this PR?
N/A

- [x] - Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
would be nice to add some unit tests to cover these new roles

**Comment by odockal** [comment]
@benoitf Will do! thx.

**Review by axel7083 — APPROVED** [review]

**Review by cbr7 — APPROVED** [review]

**Comment by odockal** [comment]
@benoitf I have added a couple of component tests to check the new roles/labels.

**Review by benoitf — APPROVED** [review]
thx @odockal

**Review by dgolovin — APPROVED** [review]

**Pull request merged**
