### PR TITLE
fix: error text on podman commands

### LINKED ISSUE #809: Podman installation error not readable on windows
### Is your enhancement related to a problem? Please describe

podman refuses to install but hard to guess why

### Describe the solution you'd like

Better log view

### Describe alternatives you've considered

_No response_

### Additional context

image

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
It uses xterm.js to render podman CLI errpors

### Screenshot/screencast of this PR
Screenshot 2022-11-29 at 16 43 04

### What issues does this PR fix or reference?
Fix https://github.com/containers/podman-desktop/issues/809

### How to test this PR?
Try to initialise podman from UI, in case if podman cannot create machine, you should see a readable error message.

### CODE REVIEW

**Comment by benoitf** [comment]
Hi @evidolob could you apply formatter on your PR ?

**Comment by benoitf** [comment]
Hello, trying the PR I have the following output if I kill podman machine init process for example:
image


but output is a progress bar:
```
Downloading VM image: fedora-coreos-37.20221106.2.1-qemu.x86_64.qcow2.xz [=========>------------------------------------------------] 110.3MiB / 643.2MiB
```

so in the log I see tons of time a truncated output `Downloading VM image: fedora-coreos-37.20221106.2.1-qemu.x8…`

So I'm not sure it's more readable. I'm wondering why we don't display terminal output as xterm can render properly it.

so people would see only the current status.
something like:
```
Downloading VM image: fedora-coreos-37.20221106.2.1-qemu.x86_64.qcow2.xz [=========>------------------------------------------------] 110.3MiB / 643.2MiB
killed
```

**Comment by slemeur** [comment]
+1
I think the case described by @benoitf and illustrated also show that the proposed solution does not suit well.
Ideally, we would also want the user to be able to copy the outputs so they could more easily investigate a potential issue.

**Comment by evidolob** [comment]
@benoitf @slemeur 
Now it looks like this:
Screenshot 2022-11-29 at 16 43 04

**Comment by benoitf** [comment]
do you know why it's cutting the line at x8. (? )

**Comment by benoitf** [comment]
`Downloading VM image: fedora-coreos-37.20221106.2.1-qemu.x8`

vs

`Downloading VM image: fedora-coreos-37.20221106.2.1-qemu.x86_64.qcow2.xz [=========>------------------------------------------------] 110.3MiB / 643.2MiB`

**Comment by benoitf** [comment]
I guess it's the default columns of spawn

**Review by benoitf — APPROVED** [review]
I tested, it's far better now with xtermjs 🎉  

but it does not say that there was an error
image

I guess that in case of error or if exit code is not good one we should display it in the output

**Pull request merged**
