### PR TITLE
chore: change the order of elements on the dashboard page

### LINKED ISSUE #8339: Change the order of elements on the dashboard page
### Is your enhancement related to a problem? Please describe

When a user start podman desktop, the dashboard is always showing the same information at the top of the page. The section that are highlighting what's new are at the end of the page and the users might be missing them. If the user has a small window for the application, the sections with the guides and the recommended extensions are even not visible.

Screenshot 2024-08-02 at 14 57 44

### Describe the solution you'd like

In this issue, we would like to change the order of the section on the dashboard.
Today, we have the following order:
1. Onboarding and error messages
2. Providers (podman and others)
3. Learning Center
4. Recommended extensions (dismissed if installed)

We would like to change the order with the following one:
1. Onboarding and error messages
2. Release Note (#8521)
3. Recommended extensions (will be dismissed if installed)
4. Learning Center
5. Providers (podman and others)

Note: Providers will be moving to the status bar.

### Describe alternatives you've considered

_No response_

### Additional context

_Note:_ This is a temporary change, until we are revamping the dashboard.

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
Temporary changes the order of elements on the dashboard page

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

Closes #8339 

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by slemeur** [comment]
Looking great !!

**Comment by cdrage** [comment]
Please see https://github.com/containers/podman-desktop/issues/8339#issuecomment-2275568670

I don't think this is a good change at the moment. 

The on-boarding / learning center / recommended is so large I now have to scroll to the bottom to find what I immediately want to see when first starting podman desktop, and that's seeing if any of my providers need setup / have problems / etc.

**Comment by slemeur** [comment]
@cdrage : We'll proceed with little steps, but the intent is to move the providers into the status bar. 
Please keep in mind that we have 3 ways at the moment to access the providers: Settings, Dashboard, Tray Menu. 

While this PR might make the experience for interacting with the provider a bit harder - there are still other places where the users are interacting with providers.

Unfortunately, this place is also the only place where we can drive more awareness on the featured extension and expose AI Lab a bit more.

**Comment by slemeur** [comment]
@gastoner : you might want to recheck this PR with https://github.com/containers/podman-desktop/issues/8339 (where the requirements changed a bit) and also check with the work here: https://github.com/containers/podman-desktop/pull/8753

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by SoniaSandler — APPROVED** [review]

**Review by axel7083 — DISMISSED** [review]
This is a very impactful change, not sure if it should be merged before 1.13 like this cc @benoitf @deboer-tim

**Review by cdrage — APPROVED** [review]
Code LGTM. 

However I disagree with the design choice and I feel like this may be better changed in a future PR with regards to the complete dashboard revamp.

Approving based solely on code changed!

I also agree with @axel7083 that maybe change should be done post 1.13

**Review by benoitf — APPROVED** [review]
let's merge, we have other enhancements that will come (ability to hide, remove ext-pack) so we can try it anyway and still revert before cutting the release if the order is still not a good thing

**Pull request merged**
