### PR TITLE
chore: adding navigation paths

### LINKED ISSUE #7396: Merge all tasks management in main package
### Is your enhancement related to a problem? Please describe

Currently, tasks can be created or updated both at the API/main level and within the renderer (see tasks store). This means that things in the main package (e.g. the status bar) can't tell if there are tasks / state doesn't match up with what's shown in the UI. e.g. if the status bar changed when there was a running task, it would only work for certain tasks.

### Describe the solution you'd like

All tasks should be created/managed from main, and renderer only handles the UI. Any function related to creating/managing tasks or updating status should either be removed or delegate to API in main.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Add some navigation path required for https://github.com/containers/podman-desktop/pull/8144

The paths are took from following:

https://github.com/containers/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/renderer/src/lib/preferences/PreferencesCliTool.svelte#L25-L29

https://github.com/containers/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte#L369-L373

https://github.com/containers/podman-desktop/blob/e39dc597577a58238c374387feb028d165656dd1/packages/renderer/src/lib/image/build-image-task.ts#L71-L74

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Related to https://github.com/containers/podman-desktop/issues/7396#issuecomment-2236420289

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
there is no test ?

**Comment by axel7083** [comment]
> there is no test ?

Added :heavy_check_mark:

**Comment by benoitf** [comment]
thanks, tests of `navigation.spec.ts` were not committed ?

**Review by lstocchi — APPROVED** [review]

**Comment by axel7083** [comment]
> thanks, tests of `navigation.spec.ts` were not committed ?

I rewrote them all for consistency

**Review by benoitf — APPROVED** [review]
thanks

**Pull request merged**
