### PR TITLE
chore(tests): adding dev sandbox installation verification

### PR DESCRIPTION
**Pull request by xbabalov**
### What does this PR do?
Implements e2e tests for Developer Sandbox extension installation and verification in Podman Desktop

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/3339

### How to test this PR?
yarn test:e2e:smoke

### CODE REVIEW

**Comment by odockal** [comment]
Interesting test failure, looking at the screenshot of failed container details check, there is missing Kube tab. 
containers-container-details

**Comment by benoitf** [comment]
I think that it's because it's using docker engine and not podman engine to run the container/pull the image

**Comment by odockal** [comment]
@benoitf This seems very strange to me, as the tests (container) are passing elsewhere and we do not change anything else but a time that this new dev sandbox extension takes and that is runs first.

**Comment by benoitf** [comment]
@odockal elsewhere using Github action ?

**Comment by odockal** [comment]
> @odockal elsewhere using Github action ?

I mean they pass on different PR checks. So the test itself is not a problem.

**Comment by xbabalov** [comment]
Can I please get a review so I can finalize/merge the PR? @benoitf @jeffmaury @cdrage thank you!

**Comment by cdrage** [comment]
@xbabalov Could you rebase / rerun the tests? For some reason e2e tests are failing on the GitHub action at the moment.

I'm also unable to run this locally.

**Comment by xbabalov** [comment]
@cdrage I rebased and fixed the locators for the new version. Locally everything runs fine. The e2e tests were failing previously because of another test and shouldn't block this one.

**Review by odockal — APPROVED** [review]

**Comment by odockal** [comment]
LGTM.
How about @cdrage @benoitf  ?

**Review by benoitf — APPROVED** [review]

**Comment by odockal** [comment]
@xbabalov @benoitf @cdrage Thanks for your work!

**Pull request merged**
