### PR TITLE
docs: Added the environment variable set commands of the common windows terminal emulators

### PR DESCRIPTION
**Pull request by sandial1**
### What does this PR do?
Added aclaratory notes regarding different terminal emulator commands that are common on a Windows machine.

### What issues does this PR fix or reference?
While I can't be sure about the reproducibility of this error due to only trying on my machine, the fact is that while podman standalone worked perfectly after I installed it with elevated privileges, podman compose ran into some issues:
podman compose command fail
I did manage to figure out a workaround based on this [PR:4157](https://github.com/containers/podman-desktop/pull/4157)
podman compose works after setting up DOCKER_HOST environment variable

Whether this issue will crop up on other users or not, I decided to update the docs with a bit of the Windows CLI landscape.
### How to test this PR?

Run the commands on the emulator terminals.

### CODE REVIEW

**Review by themr0c — APPROVED** [review]

**Comment by themr0c** [comment]
Can you run `yarn format:fix` to address the linter errors?

**Comment by sandial1** [comment]
> Can you run `yarn format:fix` to address the linter errors?

Sure give me an hour that I'm battling with Windows Update day woes...

**Comment by themr0c** [comment]
Now it seems the pull request contains some unexpected changes (7 files rather than 1). Can you have a look?

**Comment by sandial1** [comment]
> Now it seems the pull request contains some unexpected changes (7 files rather than 1). Can you have a look?

7 files were changed:
- 2: were created by a mistake:  I reinstalled node recently and when setting yarn I forgot to set the version to classic so when it executed the install command it created a .yarnrc.yml to set linked as node_modules and a .yarn/install-state.gz binary
- Aditionally it changed the yarn.lock file why installing dependencies (maybe because of some yarn_v2 configuration?)
- The other four files (including the documentation I added) where actually changed by the yarn format:fix command.

I think i'm going to revert the branch to my initial commit and re run yarn install, git merge and yarn format:fix once more to see if it cleans up this issue.

edit: Yeah all the issues started because I did the noob thing and forgot to use yarn classic with yarn install --frozen-lockfile. Originally I intended to bypass everything by only modifying the documentation file in the web browser through github but the linter check complicated things for me... thank you for your patience and time.

**Comment by themr0c** [comment]
I apologize for the delay. I have been sick.

**Comment by sandial1** [comment]
> I apologize for the delay. I have been sick.

Don't worry. Health first always.

**Pull request merged**
