### PR TITLE
feat: add task manager widget

### LINKED ISSUE #1411: UI: Implement task manager bar
The design ticket for this is here:
https://github.com/containers/podman-desktop/issues/1254

The final mockups are here:
https://github.com/containers/podman-desktop/issues/1254#issuecomment-1423334229

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Adds a task manager widget displaying some tasks

### Screenshot/screencast of this PR

https://user-images.githubusercontent.com/436777/225672401-af12a567-2b94-478b-adce-9a26b373d04b.mp4

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/1411

### How to test this PR?

Tweak packages/renderer/src/stores/tasks.ts and add some tasks like

```typescript
const task1: Task = {
  id: '1',
  name: 'Task 1',
  started: new Date().getTime(),
  state: 'running',
  status: 'in-progress',
  progress: 50,
};

const task2: Task = {
  id: '2',
  name: 'Task 2',
  started: new Date().getTime(),
  state: 'completed',
  status: 'success',
};
setInterval(() => {
  task1.progress = task1.progress + 5;
  if (task1.progress > 100) {
    task1.progress = 0;
  }
}, 1000);

/**
 * Defines the store used to define the tasks.
 */
export const tasksInfo: Writable<Task[]> = writable([task1, task2]);
```

Change-Id: Ifa90b6c9ee40d3a239f509dd8b4148bf33f084aa

### CODE REVIEW

**Comment by mairin** [comment]
@benoitf This looks *fantastic*! I played through the video demo a couple of times; I tried it locally too but am not sure how to trigger a task in it. But the empty window anyway feels snappy and clean. I noticed the bell icon to toggle notifications on/off doesn't seem to do anything - I think it should probably work even in the state where the pop up is empty, what do you think? How does it feel on your end working with it using (sample?) data?

**Comment by benoitf** [comment]
I don't have implemented the toggle on/toggle off for notifications as I'm not sure what it should do 

Should we for example display the task manager when a task is added to it ?  ( And not show it if toggle is off) Or is it something else

**Comment by mairin** [comment]
> I don't have implemented the toggle on/toggle off for notifications as I'm not sure what it should do
> 
> Should we for example display the task manager when a task is added to it ? ( And not show it if toggle is off) Or is it something else

Oh good point. I was thinking if the bell is turned on, then any time there's a new task added to notifications, a purple dot / emblem gets added to the bell icon (if there isn't already one) + we animate the bell, smtg like this (But not in a loop! Maybe 5x and then no more movement):

https://codepen.io/mairindubh/pen/abjRGmG

And if notification is turned off.... no purple dot, and no bell animation. If you click the bell, you get the notifications, but we won't try to get your attention.

Does that make sense you think?

**Comment by benoitf** [comment]
@mairin if I compare with other tools, usually I got the notification/task being displayed when they're triggered/added or when they're completed and 'do not disturb' mode is not displaying the tasks/notification but the widget/icon looks almost the same

but here it looks do not disturb mode would be just for the icon ?

**Comment by mairin** [comment]
@benoitf well, having it just be for the icon (and the little purple dot) is a really low-key, conservative way to go. I worry that popping up a notice with the message might be too disturbing. (The first thing I do when I install a fresh GNOME desktop is mute the notifications, for instance - the popups cover the screen.) I guess in this case the pop up would be in the lower right of the app window so maybe a little less risk to blocking important info? I was thinking about pop ups in the mockups, something like:

Screenshot from 2023-03-16 16-44-05

That's why I left those bits in the design file. 

This is how vscode seems to handle it too, I was just in it and got the updates available notice

Screenshot from 2023-03-16 16-41-42

If you don't think that would be too disturbing it would be worth trying. So basically... just to be clear:

### DND Mode // Bell off
- Notification event happens (let's say, pulling a large image progress is happening)
- The purple dot shows up, the bell animates a few times (~5x)
- No pop up / toast notification at all

### Alert mode // Bell on
- Notification event happens
- The pop up card shows up in the lower right corner and auto disappears (after say 7s?)
- The purple dot shows up, the bell animates a few times (~5x)
- If the user hovered over / mouse entered the pop up card while it was up, it won't fade away after  7s, it can stay up until they dismiss it, and the bell icon animation / purple dot wouldn't be triggered since it's been "seen"

does that make sense? otherwise the more conservative approach would be [as described above](https://github.com/containers/podman-desktop/pull/1724#issuecomment-1472549375) (just turning on or turning off the pressure/tension of the purple light / bell animation.)

I've seen it done both ways in interfaces, I think either approach might work depending on how often notifications are popping up, wondering what you think.

**Comment by benoitf** [comment]
I think it would be more convenient to see messages for a while yes (from your latest proposal) and if it's too verbose user can opt-it for DND

But from what I read, you still want to have `The purple dot shows up, the bell animates a few times (~5x)`
and not only a 'purple dot'. I would expect in DND mode that it does not animate as the animation will disturb me

**Comment by benoitf** [comment]
also maybe I need to cut the PR in two:
- keep current state and remove the DND icon (so we can merge soon a basic task manager and grab feedback, etc)
- later PR that brings 'notifications/DND' improvements

**Comment by mairin** [comment]
> But from what I read, you still want to have `The purple dot shows up, the bell animates a few times (~5x)` and not only a 'purple dot'. I would expect in DND mode that it does not animate as the animation will disturb me

If you think the animation is too much lets just drop it. I think actually its not necessary w the pop up bc the pop up provides the motion to grab attention 👍

**Comment by benoitf** [comment]
I've removed DND icon as for now it was not doing stuff
I'll provide follow-up PR

**Review by jeffmaury — APPROVED** [review]
LGTM.

General remarks:

- for the Svelte components that have SVG for maintenance purposes it would be good to document from where this SVG content is from. I usually have a readme file in the same folder with content file url
- the bell icon seems to me associated with notifications rather that tasks but I maybe be biaised
- regarding the refresh can't we have a listener on task properties rather than refreshing at a constant schedule ?

**Review by cdrage — APPROVED** [review]
Code LGTM. I have no issues with the UI or code. Most of this is svelte boiler plate code, so LGTM.

* Stores code looks good
* Was able to press ESC and close it
* Use example code / messed around with a few settings and it worked appropriately.
* No issues with grammar / english / UI.

**Comment by cdrage** [comment]
https://user-images.githubusercontent.com/6422176/225930897-93ed383f-8876-42ff-ae14-ffa0afa0aca0.mov

Worked great 🎉

**Comment by benoitf** [comment]
> for the Svelte components that have SVG for maintenance purposes it would be good to document from where this SVG >content is from. I usually have a readme file in the same folder with content file url

it's coming from @mairin 

> the bell icon seems to me associated with notifications rather that tasks but I maybe be biaised

cc @mairin 

>regarding the refresh can't we have a listener on task properties rather than refreshing at a constant schedule ?

It's to update the '1 second ago', '2 seconds ago', etc.

**Comment by mairin** [comment]
> > for the Svelte components that have SVG for maintenance purposes it would be good to document from where this SVG >content is from. I usually have a readme file in the same folder with content file url
> 
> it's coming from @mairin

I pulled all of these from Font Awesome, I may have made some modifications. But for license purposes it might be good to mention Font Awesome if we don't already (but I would assume we do.) 

> > the bell icon seems to me associated with notifications rather that tasks but I maybe be biaised
> 
> cc @mairin

I mocked it up a few ways and I think the tasks icon nobody really recognized, and I think the bell works well enough, and maybe at some stage we can put notifications in there too. I was looking at bit at the GNOME shell notification area as a model and they use the bell too (they have mixed tasks / notifications)

But if you feel strongly about it I can take another pass and come up with something else.

**Pull request merged**
