### PR TITLE
nit: only install docker compose if user selected a version

### LINKED ISSUE #2126: Compose dialogue indicates installation completed when escaped/canceled.
### Bug description

The compose modal prompting for a version to be installed still indicates that compose was installed successfully when escaped/canceled. 

### Operating system

RHEL 8.7

### Version

0.14.1

### Steps to reproduce

- Click "Compose" in the bottom left-hand corner. Observe the version prompt pop-up asking which version should be installed
- Hit escape to leave the prompt
- Observe "Compose Version <version> has been installed" (Expected nothing to happen because I hit escape).

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
nit: only install docker compose if user selected a version

### What does this PR do?

Simple fix, it will only install docker compose if the user successfully
picks a version from showQuickPick.

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/2126

### How to test this PR?

1. Click on Compose
2. Press ESC
3. It should not install

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by benoitf** [comment]
I think unit tests should be adapted

**Comment by cdrage** [comment]
> I think unit tests should be adapted

Forgot to add them, added now!

**Review by benoitf — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
