### PR TITLE
docs: blog post about devies award

### PR DESCRIPTION
**Pull request by cedricclyburn**
### What does this PR do?

- Adds a blog post on the recent [DEVIES](https://www.developerweek.com/awards/) award won by Podman Desktop!
- Nice quote from @slemeur and sick graphic from @mairin, thanks team! 🥳 

### Screenshot / video of UI

- N/A

### What issues does this PR fix or reference?

- N/A

### How to test this PR?

- N/A

### CODE REVIEW

**Comment by cedricclyburn** [comment]
Let's wait until Monday Feb 19th to post/merge this please :)

**Comment by axel7083** [comment]
Hey! Very nice! Some commits are incorrectly signed off, to be able to merge this need to be fixed. See https://github.com/containers/podman-desktop/pull/6061/checks?check_run_id=21709165597 for details :) !

**Comment by jeffmaury** [comment]
@cedricclyburn can you add DCO and run yarn format:fix and push new commit ?

**Comment by cedricclyburn** [comment]
Okay thanks @axel7083 @jeffmaury, let me actually close this PR and create a fresh one #6078

**Pull request closed without merging**
