### PR TITLE
fix(docs): homepage screenshot update

### PR DESCRIPTION
**Pull request by myfear**
### What does this PR do?

Update homepage screenshot with latest 1.11.1 screenshots

### Screenshot / video of UI

n/a

### What issues does this PR fix or reference?

https://github.com/containers/podman-desktop-internal/issues/261

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by slemeur** [comment]
Are the white shadows expected? 

Screenshot 2024-07-01 at 09 12 36


Screenshot 2024-07-01 at 09 13 30

**Comment by myfear** [comment]
I was thinking, this gives it more of a "windows/dialog" feel.

**Comment by deboer-tim** [comment]
IMHO it's a little odd in dark mode, like the shadows should be dark instead of light. That could be done using separate images and styles, but would take more time/not sure it's worth it.

**Comment by myfear** [comment]
@slemeur @deboer-tim I've removed the shadows.

**Review by deboer-tim — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Pull request merged**
