### PR TITLE
chore(test): some e2e test fixes

### LINKED ISSUE #9574: k8s related e2e tests are failing on main branch
### Bug description

Currently there are several k8s related e2e tests that are failing on main branch on windows that need to be fixed.

### Operating system

Windows 11

### Installation Method

None

### Version

1.13.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cbr7**
### What does this PR do?
Fixes some broken k8s e2e tests

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop/issues/9574

### CODE REVIEW

**Comment by odockal** [comment]
@amisskii @cbr7 Something changed between merging/running: https://github.com/containers/podman-desktop/pull/9323 and now?

**Review by odockal — APPROVED** [review]

**Comment by cbr7** [comment]
@odockal it's hard for me to say since I don't know how it was when the previous PR was made, but I suspect a change in the dropdown component, I suspect that previously when selecting the k8s namespaces the options were of some kind of list, currently the options are actually individual buttons that get created when the dropdown is activated.

EDIT: I've started a test run on this branch here: https://github.com/containers/podman-desktop-e2e/actions/runs/11495007347

**Comment by odockal** [comment]
@cbr7 Well, let's see how workflow ends up. good catch.

**Review by amisskii — DISMISSED** [review]
https://github.com/containers/podman-desktop/blob/main/tests/playwright/src/model/pages/create-kind-cluster-page.ts#L77 there is also the createClusterParametrized method we should change as well.

**Review by amisskii — APPROVED** [review]

**Pull request merged**
