### PR TITLE
feat: Upgrade podman installers to v4.4.1

### LINKED ISSUE #1433: Update Podman to v4.4 (4.4.1)
### Is your feature request related to a problem? Please describe

There was a new 4.4 release

4.4.0 had issues but 4.4.1 fixed the problems so we should be able to upgrade to this version

### Describe the solution you'd like

Bump from v4.3 to v4.4

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Upgrade podman installers to v4.4.1

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/1433

### How to test this PR?

Run the files from the pull request artifacts on macOS/Windows

Change-Id: I662d0f69a431bcb719ed99d211efa3008a7670d1
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by benoitf** [comment]
I've rebased to include https://github.com/containers/podman-desktop/pull/1462

**Comment by lstocchi** [comment]
I already tried to upgrade podman with #1462 included. It works fine on windows

**Comment by benoitf** [comment]
we also need https://github.com/containers/podman-desktop/pull/1464 especially if users don't have brew being installed on the system. Else the pre-flight command is failing while checking if podman has been installed or not using brew

**Comment by jeffmaury** [comment]
I had the notification that it was installed but the button Update to is not removed:

image

**Comment by benoitf** [comment]
rebasing to include https://github.com/containers/podman-desktop/pull/1464

**Review by cdrage — APPROVED** [review]

**Comment by benoitf** [comment]
@jeffmaury you may file a new issue, it's not related directly to this PR

**Pull request merged**
