### PR TITLE
refactor(podman-extension): uses api env.isWindows

### LINKED ISSUE #9617: replace isMac,IsWindows,isLinux utility functions by the one provided by the extension API in podman extension
### Is your enhancement related to a problem? Please describe

the podman extension has an utility methods duplicating the extension API, we should remove the one from the utility file

### Describe the solution you'd like

remove is* methods

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Replace the `utils#isWindows` with the api `env.isWindows`.

### What issues does this PR fix or reference?

Part 1/3 of https://github.com/podman-desktop/podman-desktop/issues/9617

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
I would expect to have
```ts
vi.mocked(extensionApi.env).isWindows = true;
```

rather than

```ts
   (extensionApi.env.isWindows as boolean) = true;
```

**Comment by axel7083** [comment]
This is very weird, on windows `src/plugin/filesystem-monitoring.spec.ts:81:28` is failing 🤔 (not on my local machine only CI)

**Review by benoitf — APPROVED** [review]
thx for the changes

off topic, looks like during this run, we faced the bug https://github.com/podman-desktop/podman-desktop/issues/10043

**Comment by benoitf** [comment]
@axel7083 yes the test is flaky (since some days I saw it on Windows only)

**Comment by gastoner** [comment]
@axel7083 yes the test is flaky. For one of my PR it also failed, but re-triggering solved it :D

**Review by gastoner — APPROVED** [review]
LGTM

**Comment by axel7083** [comment]
That's the 4th time I'm re-triggering it :(

**Pull request merged**
