### PR TITLE
feat: register compose cli updater and update compose cli version

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

It adds the updater for the compose cli. 

### Screenshot/screencast of this PR

update_composa

### What issues does this PR fix or reference?

N/A

### How to test this PR?

1. remove compose from your machine
2. go through the onboarding and install an older version
3. go to the cli tools page
4. update compose

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
The update available link does not disappear once the update is performed and version is updated

**Comment by lstocchi** [comment]
> The update available link does not disappear once the update is performed and version is updated

Please check again with the last commit -> https://github.com/containers/podman-desktop/pull/5111/commits/bcf86f2c891924e0a9e2bad14da4d66de0cc02f0

**Review by jeffmaury — APPROVED** [review]
LGTM. Wondering if the composeCliToolUpdaterDisposable should not be added to the list of extension subscriptions

**Comment by lstocchi** [comment]
> LGTM. Wondering if the composeCliToolUpdaterDisposable should not be added to the list of extension subscriptions

It is not strictly necessary as when the cliTool is disposed, it also disposes its updater

**Comment by jeffmaury** [comment]
I noticed that if you install the latest version during onboading (the defaul) then CLI tools shows update available

**Review by jeffmaury — APPROVED** [review]
Tested both onboarding and update and both worked

**Review by deboer-tim — APPROVED** [review]
I'm not as familiar with the cli tools code, but LGTM and worked successfully to update to latest version and confirm that there are no more updates.

**Pull request merged**
