### PR TITLE
Fix partial reads in event processing

### PR DESCRIPTION
**Pull request by n1hility**
The current implementation expects that the json payload will not be split across reads. However,  read() can return arbitrary size chunks per call based on a number of factors (OS stack, transport, network, etc) irrespective of http values. Additionally, since socket streams are not framed, and the payload size is variable: a read may return multiple records, including partial segments at the end and beginning. 

The approach in this PR uses a streaming JSON parser library, which can tolerate semantic separation (e.g. it understands concatenated JSON payloads with no need for record delimiters or whitespace separation). 

An alternative approach would be to pipe the stream into a line scanner pipeline such as split2, and then use standard JSON parsing on each record from this pipeline. Such an approach would be limited to LF separated JSON streaming only.

TESTING NOTES: Forced partial reads can be simulated with socat, like so (in this case 10 bytes)

```
mv .local/share/containers/podman/machine/podman-machine-default/podman.sock  \  
   .local/share/containers/podman/machine/podman-machine-default/podman-orig.sock

socat -v -b10  UNIX-LISTEN:.local/share/containers/podman/machine/podman-machine-default/podman.sock,sndbuf=10,rcvbuf=10,fork \ 
               UNIX-CONNECT:.local/share/coniners/podman/machine/podman-machine-default/podman-orig.sock
```

### CODE REVIEW

**Comment by benoitf** [comment]
@n1hility I think it's already working no ?
AFAIK we don't need this PR

**Comment by benoitf** [comment]
it should already handle successive reads

**Comment by n1hility** [comment]
@benoitf this is one approach to fix the issue you are seeing in containers/podman#15037 . The existing code does have some partial holdover, but it does expect there to be at least one record

(EDIT forgot that it did have some support of partial reading
AHA probably because it was updated since i pulled)

```
The code handles:
--callback 1--
one
two
thr
--callback2--
ee
```

But what it might get is
```
--callback1--
on
--callback2--
e
two
th
--callback3--
ree
```

**Comment by n1hility** [comment]
If you run the testing scenario above to generate partial read scenarios with the current main (including support for some partial reading) you get a failure and event processing breaks:

image

With this PR everything works as expected. The existing line buffering approach is workable but it would need to scan copy vs the split approach (since a full event may not be present)

**Review by benoitf — APPROVED** [review]
> AHA probably because it was updated since i pulled

let's use your approach as you took time to provide a PR and it's always great to have contributions.

**Pull request merged**
