### PR TITLE
feat: add help page

### LINKED ISSUE #163: Add feedback mechanism
## Description

As a user, I should be able to quickly know how and where I can share a feedback about the tool. 
We would like to add in the UI of Podman Desktop different options to engage on the repository.

### System Tray
We would like to add one "Give Feedback" submenu item in the system-tray. When clicking on this item in the menu, it will redirect to https://github.com/containers/podman-desktop/issues/new/choose 

### Left Sidebar
We would like to add one item at the bottom of the left sidebar, which would provide the ability to the user to get Help.
We add "Help" tab, which will provide guidance to the user on the following areas:
- Access to Documentation
- Report a bug
- Share a Feedback
- Discuss with us (link to discord)

### PR DESCRIPTION
**Pull request by vzhukovs**
Current changes proposal adds a Help page with the list of useful resources related to Podman Desktop.

Снимок экрана 2022-06-30 в 11 21 19

fixes https://github.com/containers/podman-desktop/issues/163

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
hello, we may need to place the help items in the status bar

**Comment by slemeur** [comment]
Thanks @vzhukovs ! 
Could we envision a page with more "tiles" style? something around those lines? 
Frame 9

**Comment by slemeur** [comment]
I believe it's important we have a link to podman's docs too

**Comment by benoitf** [comment]
> I believe it's important we have a link to podman's docs too

we have links to podman docs in welcome page.
image



Also note that the 'podman docs' should be brought by 'Podman plug-in', not hardcoded in the Desktop App.

**Comment by vzhukovs** [comment]
>hello, we may need to place the help items in the status bar

As far as we need to implement status bar first, it would be nice to implement on next iteration. As a temporary solution, I've moved menu item to the title bar, as it has been implemented in various clients:

Снимок экрана 2022-06-30 в 20 32 41
Снимок экрана 2022-06-30 в 20 32 49

**Review by benoitf — APPROVED** [review]
Ok for me

Tiles, status bar etc can come in next itérations


You need to fix linter issues

**Pull request merged**
