### PR TITLE
nit: make warnings more subtle

### PR DESCRIPTION
**Pull request by cdrage**
nit: make warnings more subtle

### What does this PR do?

Temporary measure until we implement a better dashboard UI, but reduce
the "boldness" of the warnings and make it more subtle as to not
distract from other parts of Podman Desktop.

### Screenshot/screencast of this PR

Screenshot 2023-04-05 at 12 38 51 PM

### How to test this PR?

`yarn watch`

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by deboer-tim** [comment]
nit: 'less subtle' means 'more bold', I think you mean the opposite. ;-)

**Comment by cdrage** [comment]
> nit: 'less subtle' means 'more bold', I think you mean the opposite. ;-)

Not enough coffee today ☕ 

Updated it haha

**Review by benoitf — APPROVED** [review]

**Comment by jeffmaury** [comment]
The icon and the first part of the text are less visible now, is it on purpose ?

**Comment by cdrage** [comment]
> 

Yes, makes it less bold / annoying for users who do not have it enabled. Unfortunately it's a bit of an eye sore.

**Pull request merged**
