### PR TITLE
chore: check we don't have modified files

### LINKED ISSUE #2787: PR check should fail if package.json introduce a change but yarn.lock is not accurate
### Bug description

yarn.lock needs to reflect package.json changes so if we miss yarn.lock change, PR should fail

### Operating system

all

### Version

1.1.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
We're already checking that yarn.lock is correct, check that we don't have extra modified files

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/2787

### CODE REVIEW

**Review by cdrage — APPROVED** [review]

**Review by jeffmaury — COMMENTED** [review]
I don't get why it is located here as it's just executed after checkout and dependencies resolution  but before any check. Should'nt better execute the check after build ?

**Comment by benoitf** [comment]
@jeffmaury when you do yarn, there are post-install steps being executed, etc

the checks like the linter and prettier are in --check mode so they don't change the files as well

I can move it later but it won't change if it's before or after

**Comment by benoitf** [comment]
moved it later

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
