### PR TITLE
fix: Removed fullstop from summary

### LINKED ISSUE #3077: Summary shouldn't end with fullstop
### Is your enhancement related to a problem? Please describe

Summaries shouldn't end with fullstops

### Describe the solution you'd like

Remove the fullstop from https://github.com/containers/podman-desktop/blob/ab31a708ff5af373a22a9e5127668bafb58bcc67/.flatpak-appdata.xml#L7

### Describe alternatives you've considered

Not caring? :)

### Additional context

Stuff should be nice :sparkle:

### PR DESCRIPTION
**Pull request by harsh-solanki21**
### What does this PR do?
This PR removes the fullstop from the summary.

### Screenshot/screencast of this PR
fix

### What issues does this PR fix or reference?
fixes #3077

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
Thanks @harsh-solanki21

**Comment by benoitf** [comment]
FYI you'll need to do SignedOff of your commit else we can't merge the pull request ( check the PR check which should be green and not red)

**Comment by benoitf** [comment]
@harsh-solanki21 https://github.com/containers/podman-desktop/blob/main/CONTRIBUTING.md#sign-your-prs

**Comment by harsh-solanki21** [comment]
@benoitf Fixed the SignedOff of in my commit. Appreciate the support. Thanks :)

**Comment by benoitf** [comment]
@harsh-solanki21 thanks for your first contribution

**Pull request merged**
