### PR TITLE
style: do not hide terminal when there are errors

### LINKED ISSUE #5688: improve kind feedback when falling to create a cluster
### Is your enhancement related to a problem? Please describe

When something went wrong while creating a kind cluster, logs disappear, and leave the user frustrated with the only logs "exit with code 1".

### Describe the solution you'd like

https://github.com/containers/podman-desktop/assets/42176370/be435192-41e7-451c-97bf-637e8471b471

- Keeping the logs
- full logs

### Describe alternatives you've considered

Running the command manually (annoying)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by trmendes**
### What does this PR do?

Keep the terminal component when errors occur

### Screenshot / video of UI

Screenshot 2024-01-26 at 15 22 51

### What issues does this PR fix or reference?

Fixes #5688 

### How to test this PR?

1) Go to settings
2) Go to Resources
3) Find "Kind" and click on "Create new ..." button
4) Find the field "Node’s container image" and type anything there
5) Click Create

### CODE REVIEW

**Comment by benoitf** [comment]
hi @trmendes , to ensure it won't come back soon, could you add a component test ensuring that the error page stays in case of an error ?

**Comment by trmendes** [comment]
Consider it done 👍🏿  🗡️

**Comment by trmendes** [comment]
@benoitf Maybe you can help with the CSS here? I can let it go that way, but I'm not yet very happy with the result.

The error message has a different format from the Warning and Information message. Also, they are not very well aligned.

**Comment by benoitf** [comment]
cc @mairin

**Comment by trmendes** [comment]
@benoitf I'm having a similar issue with the test. There is a need of two ```await tick()``` to get ```errorMessage``` string updated after the exception. 

Any suggestions?

**Review by benoitf — APPROVED** [review]

**Review by deboer-tim — APPROVED** [review]

**Pull request merged**
