### PR TITLE
fix: fix lint errors

### PR DESCRIPTION
**Pull request by jeffmaury**
### What does this PR do?

Fix lint errors found in svelte update

### Screenshot / video of UI

NA

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Check workflows or run `pnpm lint:check`

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by feloy** [comment]
I'm getting this error when runing `pnpm watch`:

```
[plugin:vite-plugin-svelte] packages/renderer/src/lib/image/FilesystemLayerView.svelte:5:0 A component can have a single top-level `<script>` element and/or a single top-level `<script context="module">` element
packages/renderer/src/lib/image/FilesystemLayerView.svelte:5:0
3 |  </script>
 4 |  
 5 |  <script lang="ts">
      ^
 6 |  import type { ImageFile, ImageFileSymlink } from '@podman-desktop/api';
 7 |
```

I understand that this is a change in svelte 5, I ran `pnpm i`, but I still get the error

**Comment by jeffmaury** [comment]
> I'm getting this error when runing `pnpm watch`:
> 
> ```
> [plugin:vite-plugin-svelte] packages/renderer/src/lib/image/FilesystemLayerView.svelte:5:0 A component can have a single top-level `<script>` element and/or a single top-level `<script context="module">` element
> packages/renderer/src/lib/image/FilesystemLayerView.svelte:5:0
> 3 |  </script>
>  4 |  
>  5 |  <script lang="ts">
>       ^
>  6 |  import type { ImageFile, ImageFileSymlink } from '@podman-desktop/api';
>  7 |
> ```
> 
> I understand that this is a change in svelte 5, I ran `pnpm i`, but I still get the error

Should be fixed now

**Comment by benoitf** [comment]
just curious why we need these modules anyway ?

**Comment by feloy** [comment]
> just curious why we need these modules anyway ?

On `FilesystemLayerView`, `<script context="module"` is used to have a common `expansionState` variable across all instances of this component. But I realize that this introduces a problem, because, as it records only the last part of the path expanded, if the user expands`/usr/bin`, then `/usr/local/bin` and all other `bin` directories are expanded.

If I replace with `<script module`, the variable is not common anymore, so this notation does not seem equivalent.

Finally, @jeffmaury, you can completely remove `context="module"` for this component and keep only `<script lang="ts">`

**Review by feloy — APPROVED** [review]

**Pull request closed without merging**
