### PR TITLE
API to support non silent authentication session requests

### LINKED ISSUE #2224: Authentication provider support for silent authentication session requests
### Is your enhancement related to a problem? Please describe

When authentication provider installed and client extensions want to expose login commands on Settings/Authentication page authentication module should support creating so called silent authentication request. 

### Describe the solution you'd like

When authentication session requested form provider and marked as silent it should not trigger authentication workflow but just create record for request. Records can be requested by UI to build drop down menu based on Authentication provider requested and client extension name

For instance if OpenShift Local Extension during activation creates silent request for Red Hat SSO authentication session. A menu item or other UI element capable of executing command should be called 'Login to Red Hat SSO to use OpenShift Local'. Command behind menu should just trigger creating authentications session with provider  ID, client extension ID and scopes provided by client extension.

After menu item 'Login with Red Hat SSO to use OpehShif Local' is executed and session is created user can switch to OpenShift Local UI and start using it without further authentication required.

### Describe alternatives you've considered

_No response_

### Additional context

Related to https://github.com/containers/podman-desktop/issues/2140.

VSCode similar functionality in anuthentication service:
https://github.com/microsoft/vscode/blob/2c51b3de329d48f45eabe80316f099f46fd3a5cc/src/vs/workbench/services/authentication/browser/authenticationService.ts#L650
https://github.com/microsoft/vscode/blob/2c51b3de329d48f45eabe80316f099f46fd3a5cc/src/vs/workbench/api/browser/mainThreadAuthentication.ts#L275

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

Adds API to allow extensions to add requests for authentication sessions

### Screenshot/screencast of this PR

https://user-images.githubusercontent.com/620330/237025865-90538ed6-72b5-417e-ab39-978fed904ba7.mov

### What issues does this PR fix or reference?

Fixes #2224.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
FYI sonar cloud is reporting 
image

**Comment by jeffmaury** [comment]
I can't see the command to log in. I tried using the latest version of both extensions. Am I missing something ?

**Comment by jeffmaury** [comment]
I can't see the command to log in. I tried using the latest version of both extensions. Am I missing something ?

**Comment by dgolovin** [comment]
@benoitf that is exactly what I need. I want them to be sorted alphabetically.  it there a way to suppress that error?

**Comment by benoitf** [comment]
@dgolovin I've flagged in sonarcloud as 'won't fix'
there is still an issue in the formatter

**Comment by dgolovin** [comment]
@jeffmaury you do not see commands because no extension is using it yet. It should be authentication.getSession('provider.id', {silent: false}) call from extension. 

@benoitf there is another problem. It is related to extension activation order. When I a add call mentioned above to crc-extension activation and it activates before redahat.authentication-provider, the call fails with error, because there is not auth provider installed yet. I can fix it by removing check and let it fail later when authentication request it executed by selecting context menu on authentication page.

**Comment by benoitf** [comment]
> @benoitf there is another problem. It is related to extension activation order. When I a add call mentioned above to crc-extension activation and it activates before redahat.authentication-provider, the call fails with error, because there is not auth provider installed yet. I can fix it by removing check and let it fail later when authentication request it executed by selecting context menu on authentication page.


@dgolovin this should be sorted out by adding `dependencies` metadata in extensions. But in the meantime yes probably do a lazy call is probably better

**Pull request merged**
