### PR TITLE
chore: include a color registry

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
This is the place where to define colors for light/dark theme
register color definition of color names provided by UX team

### What issues does this PR fix or reference?

related to https://github.com/containers/podman-desktop/issues/5914

### How to test this PR?

unit tests provided

### CODE REVIEW

**Comment by benoitf** [comment]
@cdrage so there is always a light and dark color, but you can add custom theme and the theme has a parent (either dark or light) so if you don't provide a value for a color, it will default to the dark/light color

**Comment by deboer-tim** [comment]
When I saw #5931 and then RawThemeContribution here I thought themes were going to be delivered through separate json files or contributions, but both light/dark are declared in color-registry.ts.

I know the following example is likely too simplistic, but it seems like it would be easier to manage the themes if they were defined in files like 'dark.json'/'light.json' or contributions?
```
{ "GlobalNav": {
  "Bg":"charcoal-800",
  "Icon": "gray-600",
  ...
```

**Comment by benoitf** [comment]
I choose typescript registration over configuration files as we might use some variables to define colors and because I have type safety

This is the definition of the colors so no separate files as for example you may miss colors ( like you add only in light.json or only in dark.json or you do typos and then the color is missing)

But for sure an extension will be able to contribute a set of colors that will either define or inherits from it's parent theme in case it is missing

So definition is in the code, contribution is with .json files

**Comment by benoitf** [comment]
I've added the other PRs depending on this PR so you can see how it works

at the end we have colors registered as CSS variables for Podman Desktop and for the webviews (so they'll be able to reuse the same colors)

**Review by deboer-tim — APPROVED** [review]

**Review by lstocchi — APPROVED** [review]
LGTM

**Review by cdrage — APPROVED** [review]

**Comment by benoitf** [comment]
updated to use kebab-case color identifier (before registering `TitlebarBg` and now registering `titlebar-bg`) (still using camelCase for JSON contribution)

when listing colors, we specify the name of the CSS variable as well so no need to compute it on client side

css variable name is using the pattern `--pd-<name-of-the-color>` for example `--pd-titlebar-bg`

**Comment by benoitf** [comment]
FYI @deboer-tim @cdrage and @lstocchi as you reviewed/approved before this change

**Comment by deboer-tim** [comment]
Approval still ✅ after changes.

**Review by cdrage — APPROVED** [review]

**Pull request merged**
