### PR TITLE
feat: update forms look & feel

### LINKED ISSUE #2156: Look & feel update for forms
There are some forms such as the create pod form and deploy to k8s form that are out of sync with the current look & feel; need a quick/simple mockup to update these to look less out-of-place.

### PR DESCRIPTION
**Pull request by mairin**
### What does this PR do?

Updates the palette + minor layout details across the following forms to be more consistent with the rest of the UI in accordance with the updated palette from https://github.com/containers/podman-desktop/pull/2223 :

- deploy to k8s
- play kube
- pull image
- build image

#### deploy to k8s
<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>

Screenshot from 2023-05-01 16-33-20

</td><td>

Screenshot from 2023-05-01 16-02-58

</td>
</tr>
</table>

#### play kube

<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>

Screenshot from 2023-05-01 16-32-34

</td><td>

Screenshot from 2023-05-01 15-56-22

</td>
</tr>
</table>

#### pull image

<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>

Screenshot from 2023-05-01 16-32-42

</td><td>

Screenshot from 2023-05-01 15-48-44

</td>
</tr>
</table>

#### build image

<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>

Screenshot from 2023-05-01 16-32-47

</td><td>

Screenshot from 2023-05-01 15-44-50

</td>
</tr>
</table>

### What issues does this PR fix or reference?

https://github.com/containers/podman-desktop/issues/2156

### How to test this PR?

Run through each action in the UI (deploy to k8s, play kube, pull image, build image) and make sure the forms look ok. No global stylesheet changes / overrides were made so it shouldn't affect anything outside of the named forms.

### CODE REVIEW

**Comment by mairin** [comment]
ugh i have to rebase this, not ready for review

**Comment by mairin** [comment]
[I dropped the extra commits with a rebase, should be good to go now]

**Comment by benoitf** [comment]
FYI @mairin there is conflicting file: packages/renderer/src/lib/pod/DeployPodToKube.svelte

**Comment by benoitf** [comment]
@mairin looks like there is a formatting issue

**Comment by mairin** [comment]
@benoitf I think i got the formatting fixed now.

**Comment by benoitf** [comment]
@mairin is it expected these changes https://github.com/containers/podman-desktop/pull/2285/files#diff-e8366cdd7002a420e8272fb4522f06900b3ab945fdfc3ded058a5da48448ad03 ?

**Comment by benoitf** [comment]
@mairin it looks like we drop isOpenShiftURL, added some container statuses, etc

**Comment by mairin** [comment]
@benoitf hmm. Would it be better to drop the kube deploy form from this PR and do a different one for it? I think I kept rebasing against main which pulled in @cdrage 's changes to the screen... I didn't mean to drop anything that got dropped here.

**Review by benoitf — APPROVED** [review]

**Review by cdrage — APPROVED** [review]

**Pull request merged**
