### PR TITLE
feat: add lima kubernetes provider type

### LINKED ISSUE #3258: Add provider type Kubernetes to the Lima extension
### Is your feature request related to a problem? Please describe

Currently you can select type between "podman" and "docker", and it will return a container provider

podman-desktop-preferences-lima

### Describe the solution you'd like

There should be a third type called "kubernetes", that would instead return a kubernetes provider

The endpoint will be available under https://127.0.0.1:6443 since it is automatically being tunneled

```console
$ kubectl.lima get no
NAME       STATUS   ROLES           AGE   VERSION
lima-k8s   Ready    control-plane   48d   v1.28.0-alpha.0
$ kubectl.lima cluster-info
Kubernetes control plane is running at https://127.0.0.1:6443
CoreDNS is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Documentation**

* Kubernetes
  * ...
  * Working with Kind >
  * Working with Lima >
  * Working with Minikube >
  * Working with OpenShift >
  
### Describe alternatives you've considered

Currently you have to add the kubeconfig file manually, as documented under Lima instances:

https://podman-desktop.io/docs/Installation/creating-a-lima-instance-with-podman-desktop#kubernetes

The user would need to choose the template, between **k3s** (as in rancher) and **k8s** (as in kubeadm)

It does not need any other provider (such as podman or docker), like kind and minikube currently do.

### Additional context

Registering a proper provider, would also make it possible to add a "Push to Lima" menu item.

* https://github.com/containers/podman-desktop/issues/2623

But that would probably need to happen after Podman Desktop learns how to use `limactl`.

* https://github.com/containers/podman-desktop/issues/3069

### PR DESCRIPTION
**Pull request by afbjorklund**
### What does this PR do?

Adds a "kubernetes" type, to the Lima provider

### Screenshot/screencast of this PR

podman-desktop-lima-kubernetes

### What issues does this PR fix or reference?

Closes #3258

* #3258

### How to test this PR?

`brew install lima`

`limactl start template://k8s`

copy-paste the kubeconfig path, from the `limactl` output to the Lima preferences

<details>
copy-paste the kubeconfig path, from Resources > Lima to Preferences > kubeconfig

podman-desktop-lima-kubeconfig

podman-desktop-preferences-kubeconfig
</details>

Hopefully this step can be automated in the future, when multiple config is supported.

----

Haven't found where to set the kubeconfig yet, seems to be mostly about kubecontext ?

Workaround is to manually set in preferences, to replace the default `~/.kube/config`

It would be nice if Podman Desktop could support having multiple files in KUBECONFIG:

https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

### CODE REVIEW

**Comment by afbjorklund** [comment]
The "running" is currently a lie, the extension does not yet know how to check the instance status...

Since the kubernetes configuration was created with the cluster, it could have been stopped since.
But if you try to connect to the endpoint, you will eventually get some nice timeout error or similar:

`The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?`

**Comment by afbjorklund** [comment]
Avoiding HEAD, since it is broken (just showing a black window)

**Comment by afbjorklund** [comment]
It is possible to run other templates, such as k3s or perhaps even a custom template with cri-o instead:

`limactl start template://k3s`

merge k8s.yaml + https://cri-o.io = alternative: [k8s-alt.yaml](https://raw.githubusercontent.com/afbjorklund/lima/k8s-centos/examples/k8s-alt.yaml) (with CentOS Stream instead of Ubuntu LTS)

```
NAME           STATUS   ROLES           AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION          CONTAINER-RUNTIME
lima-k8s-alt   Ready    control-plane   94s   v1.27.4   192.168.5.15   <none>        CentOS Stream 9   5.14.0-316.el9.x86_64   cri-o://1.27.1
```

For context (i.e. translation to Red Hat), if "k8s" is similar to OpenShift then "k3s" is similar to MicroShift.

**Review by cdrage — CHANGES_REQUESTED** [review]
I was able to test this out and it works great! Thanks for the improved support to Lima.

The code LGTM. However, tests are failing.

Is there any way you can also update the documentation too? If not, we can always just open up another issue and track it there instead. We've been steadily improving out k8s docs anyways.

**Comment by afbjorklund** [comment]
I think that the master branch was in shambles at the time, but can rebase...

What documentation was needed? Currently it just links to the kubeconfig docs:

https://podman-desktop.io/docs/Installation/creating-a-lima-instance-with-podman-desktop#kubernetes

**Comment by afbjorklund** [comment]
Documenting how to create a cluster in Lima, probably will come after creating a virtual machine in Lima:

* https://github.com/containers/podman-desktop/issues/3069

**Review by cdrage — APPROVED** [review]

**Review by benoitf — CHANGES_REQUESTED** [review]
I think we need first to use the kubeConfig fragment and be able to use it before exposing it to APIs

Here extensions could feed that the field and here and can be exposed but it won't do anything so probably need to cut in two

1. expose what we have for now
2. implement fragments and see how it can be done, etc.
3. expose the kubeConfig fragment in the API

In a general manner, enhancements to the API is done in a separate PR than where extension use it

Also there are no unit tests for this new code ?

**Comment by afbjorklund** [comment]
The kubeconfig information is just for showing, so it can be removed and done separately.

The user would look at the output of the `limactl` command, and copy the path from that:

```
To run `kubectl` on the host (assumes kubectl is installed), run the following commands:
------
export KUBECONFIG="~/.lima/k8s/copied-from-guest/kubeconfig.yaml"
kubectl ...
------
```

~~Don't want to hardcode the current templates in external programs, as they are subject to change.~~

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
thanks @afbjorklund

**Comment by afbjorklund** [comment]
> The "running" is currently a lie, the extension does not yet know how to check the instance status...
> 
> 
> 
> Since the kubernetes configuration was created with the cluster, it could have been stopped since.

Lima will now remove the configuration again, when the instance is stopped.

**Pull request merged**
