### PR TITLE
feat: blank kubeconfig path will be set to default one

### LINKED ISSUE #9101: Empty kubeconfig path make podman hangs
### Bug description

If you set the kubeconfig path to an empty string in the settings, podman desktop stop responding. In the logs you could see that it loops over the refresh function in the kubernetes client

```
12:03:43 [main] (node:34688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 985)
12:03:43 [main] (node:34688) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open ''
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async KubernetesClient.refresh (C:\Users\luca\Work\github.com\containers\podman-desktop\packages\main\dist\index.cjs:103274:25)
    at async C:\Users\luca\Work\github.com\containers\podman-desktop\packages\main\dist\index.cjs:103118:7
```

maybe similar to https://github.com/containers/podman-desktop/issues/8486 , even though in that case there is the kubeconfig 🤔 

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Go to the preferences/settings and remove the content in the kubeconfig path setting

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
Checks if the kubeconfig path is empty string/ just whitespace, if yes sets the kubeconfig path to default one

### Screenshot / video of UI

https://github.com/user-attachments/assets/350fbb30-52c1-4400-a4fa-d3a0effcea1f

### What issues does this PR fix or reference?
Closes #9101 

### How to test this PR?
Try to set kubeconfig path to empty string 
- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
todo: provides a unit test covering the issue

**Review by jeffmaury — COMMENTED** [review]
Does it handle Podman Desktop start ie configuration has a blank value ?

**Comment by gastoner** [comment]
> Does it handle Podman Desktop start ie configuration has a blank value ?

From my testing yes

**Review by axel7083 — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
