### PR TITLE
Refactor containers list component

### PR DESCRIPTION
**Pull request by feloy**
### What does this PR do?

Refactor the Containers List component, so we can later insert Tabs inside it, to show running/stopped containers

### What issues does this PR fix or reference?

Related to https://github.com/containers/podman-desktop/issues/707

### CODE REVIEW

**Comment by deboer-tim** [comment]
I am worried that this will make the Containers page more complex, when we will almost certainly be asked to do similar things to other pages (e.g. running/stopped pods, or used vs unused images or volumes). I think we need to figure out how to extract some of the commonality and implement once vs doing it in each page. I don't know if it's possible yet, but see issue #4365 for some of my thoughts.

**Comment by feloy** [comment]
> I am worried that this will make the Containers page more complex, when we will almost certainly be asked to do similar things to other pages (e.g. running/stopped pods, or used vs unused images or volumes). I think we need to figure out how to extract some of the commonality and implement once vs doing it in each page. I don't know if it's possible yet, but see issue #4365 for some of my thoughts.

Can it help if I refactor the other List components (Pods, Images, ...) the same way, so it will be easier to detect common patterns between them?

**Review by benoitf — COMMENTED** [review]
from my understanding it will help if when splitting into components, if it also becomes less "container" centric so component could be used elsewhere

**Comment by deboer-tim** [comment]
Ditto. Separating each of the existing components into 4 just gives us 4x the number of files ;-) unless we see a common part we could extract & share to reduce the complexity.

**Comment by feloy** [comment]
By splitting into 4 components each List, I expect the related sub-components will be easier to merge together, for example the ContainerListContent and ImageListContent, as @deboer-tim describes in #4365.

**Comment by feloy** [comment]
To be sure we are talking about the same thing, I have pushed a commit adding the Tabs (it can be removed and cherry-picked to another PR when we agree, to have separate PRs for fixes / features). 

This commit shows IMO the necessity to move the ContainerListContent to a separate component, to be able to include it in different tabs, with differents containersLists as parameter.

The first 2 refactorings (TopActions and BottomActions) are not necessary, I could remove them if you think it is not worth it doing them.

**Comment by deboer-tim** [comment]
After a very rough look through the changes:
- The top vs bottom actions I don't think is really saving us much, to me we're losing more through the amount of code duplication.
- Personally, I'm not convinced tabs are the right approach here. First, because we don't use tabs for filtering elsewhere (ie I think we should use a different UI control), and second b/c we're essentially creating three separate container lists instead of having one container list with a filter.
- To me this is deferring the issue in #4365... it doesn't make it better or worse, we're just doing one more thing for containers that would have to be refactored out or done twice when we get the next request.

**Comment by benoitf** [comment]
@deboer-tim  tabs is what has been designed: https://github.com/containers/podman-desktop/issues/707#issuecomment-1773952917

**Comment by feloy** [comment]
Closing in favor of https://github.com/containers/podman-desktop/pull/4483

I think I have a better way to use the Tabs: in #4483, the tabs are ONLY used as a selector to select the running/stopped filter. This way, we can change easily from using tab to using another kind of selector (radio button, ...).

**Pull request closed without merging**
