### PR TITLE
chore: use input for proxy settings

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Use the Input component when configuring a proxy. This is the first control to require disabled inputs, so that support is added here - from the design it is the same as readonly except user text is the same color as placeholder text.

### Screenshot / video of UI

Screenshot 2024-02-11 at 12 08 19 AM
Screenshot 2024-02-11 at 12 08 29 AM

### What issues does this PR fix or reference?

Fixes another minor part of #3234.

### How to test this PR?

Configure a proxy, disable/enable the slider.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
FYI there is formatting issue

**Comment by benoitf** [comment]
FYI @deboer-tim I rebased the PR to solve conflicts on Input (overflow-hidden)
if you can take a look

**Review by jeffmaury — CHANGES_REQUESTED** [review]
As soon as I navigate to the Proxy page I can't navigate elsewhere

input

**Comment by deboer-tim** [comment]
Rebase had a couple odd artifacts, fixed now. Please try again @jeffmaury.

**Comment by benoitf** [comment]
probably my fault there

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
