### PR TITLE
feat: update background of buttons and change icons

### PR DESCRIPTION
**Pull request by cdrage**
feat: change background of buttons to circles

### What does this PR do?

This PR introduces changing the buttons to have no background, but circles on hover.

### Screenshot/screencast of this PR

205737122-d6840833-a92f-40c6-bac6-76c3482975e6
205737121-0d183af6-6598-41c3-9065-f61dab82ae31

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by benoitf** [comment]
adding @mairin and @gbengaoti as it's pure UI

**Comment by cdrage** [comment]
Updated PR to add border :)

See updated screenshots!

**Comment by benoitf** [comment]
I think it doesn't work due to some icons being rounded

**Comment by cdrage** [comment]
Updated and changed icon's that were previously rounded to their non-rounded versions. See screenshot below:

Screenshot 2022-11-29 at 9 41 11 AM

**Comment by cdrage** [comment]
Another update, pushed a commit and made the background more subtle by adding an opacity to the `text-gray-300`.

Screenshot 2022-11-29 at 9 52 09 AM

**Comment by gbengaoti** [comment]
We have similar icons to these in the resources area, the icon borders are #ffffff and the icons are the same colour. when the icons are disabled they are #767676. And the background is transparent so it fits into the existing background of where the icon is being placed.

To maintain visual consistency, it might be best to use the same colours for similar icons so it's not confusing to users.

**Comment by cdrage** [comment]
> We have similar icons to these in the resources area, the icon borders are #ffffff and the icons are the same colour. when the icons are disabled they are #767676. And the background is transparent so it fits into the existing background of where the icon is being placed.
> 
> To maintain visual consistency, it might be best to use the same colours for similar icons so it's not confusing to users.

The icons follow the same colours as the other text in the row in order to make it more subtle. I believe that these should stay as `text-gray-300` to maintain consistency with the design patterns of container list / pod list / etc.

Preferences is okay for it to be #ffffff and 767676 in preference. But we seem to use a lot of `text-gray-300` and `text-violet` within container list.

**Comment by gbengaoti** [comment]
I don't have the icons for the container list yet, if that's the case then it makes sense. Would there be a need to disable them at any point?

**Comment by cdrage** [comment]
> I don't have the icons for the container list yet, if that's the case then it makes sense. Would there be a need to disable them at any point?

In terms of disabling? I don't think so

**Comment by cdrage** [comment]
@mairin @gbengaoti 

I've changed it to remove the border. It looks really clashing vs the rest of the UI. Let me know your thoughts?

Before:

Screenshot 2022-12-01 at 3 06 09 PM

After:

Screenshot 2022-12-01 at 3 06 43 PM

I believe the ones without the white border and instead just have the rounded background looks better.

**Comment by mairin** [comment]
Hey @cdrage - how does it look with just the border, no background on the circle? It looks like the fill on the circle is different than the fill on the row background. It should be transparent.

**Comment by cdrage** [comment]
As per the discussion on slack, I've updated this PR so that circles only appear on hover.

Right now, the "details" page, the circle does not appear as it's the same colour as the background. But this can be updated in a later PR when design is finalized (there was discussion on adding a "square" background that goes around all the actions).

See below screenshots:
Screenshot 2022-12-05 at 3 28 52 PM
Screenshot 2022-12-05 at 3 29 09 PM

**Comment by mairin** [comment]
> Right now, the "details" page, the circle does not appear as it's the same colour as the background. But this can be updated in a later PR when design is finalized (there was discussion on adding a "square" background that goes around all the actions).


The square background is only meant for the settings panel area and not lists :)

**Comment by benoitf** [comment]
you may provide in the PR description a screenshot (rather than in comments) with the current state of what it looks in list and in the details view

**Comment by benoitf** [comment]
FYI I don't have circles on hover

https://user-images.githubusercontent.com/436777/205936055-c35128cf-a808-4939-a843-725e93358a39.mp4

**Pull request closed without merging**
