### PR TITLE
feat: add option to minimize on startup

### LINKED ISSUE #868: Minimize to tray on start / start minimized
### Discussed in https://github.com/containers/podman-desktop/discussions/867

<div type='discussions-op-text'>

<sup>Originally posted by **patstha** November 20, 2022</sup>
On Microsoft Windows, it would be nice to have an option to minimize podman desktop on start so it doesn't open a new window every time I reboot the computer. 

image

Microsoft Teams calls it "open application in background"

image

A user question and answer that explains this flow: https://techcommunity.microsoft.com/t5/microsoft-teams/allow-teams-application-start-minimized/m-p/1124951 
</div>

### PR DESCRIPTION
**Pull request by cdrage**
feat: add option to minimize on startup

### What does this PR do?

* Adds the option and ability to configure if Podman Desktop should
  start minimized

Tested on dev / prod mode on macOS & dedicated Windows machine

### Screenshot/screencast of this PR

Screenshot 2023-02-01 at 2 45 40 PM

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/868

### How to test this PR?

1. yarn watch
2. Go into preferences and enable "minimize on startup"
3. Restart Podman Desktop

### CODE REVIEW

**Comment by jeffmaury** [comment]
Does not work for me with `yarn:watch` but binary is fine

**Comment by benoitf** [comment]
Hello, I think it may not fix the primary use-case on restart.

Let me explain. Almost everytime that I launch the tool on my own, I expect to see the dashboard. But when computer restart, I expect to have only the tray icon.

so I like the option to opt-it/opt-out when I start the tool on my own.

But I would expect that the scripts that we're using to start Podman Desktop on Windows and Linux would have the `--minimize` flag so it'll always restart minimized (without having the user to change something in its preferences)

**Comment by cdrage** [comment]
> Hello, I think it may not fix the primary use-case on restart.
> 
> Let me explain. Almost everytime that I launch the tool on my own, I expect to see the dashboard. But when computer restart, I expect to have only the tray icon.
> 
> so I like the option to opt-it/opt-out when I start the tool on my own.
> 
> But I would expect that the scripts that we're using to start Podman Desktop on Windows and Linux would have the `--minimize` flag so it'll always restart minimized (without having the user to change something in its preferences)

I misinterpreted the issue as being part of opening as well when I read the "minimize on Linux" comment.

I'll update this PR.

**Comment by cdrage** [comment]
Updated!

To test:

1. Compile the binary (not yarn watch)
2. Click "minimize on startup" in settings
3. Logout / Login your machine
4. Podman Desktop will start minimized

**Comment by benoitf** [comment]
hi, I still don't see the scripts to launch Podman Desktop on macOs and windows providing the minimized flag ?

**Comment by cdrage** [comment]
> hi, I still don't see the scripts to launch Podman Desktop on macOs and windows providing the minimized flag ?

I'll convert this to draft. Still WIP.

**Comment by cdrage** [comment]
@benoitf I don't believe it's possible with just plist / property settings for mac os. It is possible with Windows (adding --minimize to the exe). 

 I've tried https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement as well as other property strings, but it doesnt work. 

I've added this as a 2nd commit / WIP to this PR as an example why it doesn't work. 

Documentation / examples online for electron point to just using .show() as I've done in the previous commit which works perfectly on mac os / windows at the moment.

**Comment by cdrage** [comment]
@benoitf So I've tried a few ways of implementing this via modifying the plist options as well as the exe and unfortunately it does not work well.

I've implemented this in my "wip" second commit that overrides the settings that I used before (.show())). This involved adding the https://github.com/electron-userland/electron-builder/issues/1456#issuecomment-293518692 element to it. I also tried with "--minimize" and that doesn't work either.

There's been a change in the way that macOS "hides" applications on startup. Testing it on Ventura / 13 doesn't work. 

My first commit works well in macOS as well as Windows with starting the application / on restart and uses https://github.com/electron/electron/issues/6893 (although an older issue, if you look at the PR's it links, there are implementations that work similarly there). This coincides with the electron documentation on how we should show / hide on startup.

Windows however works fine adding the --minimize to the exe (modifying it directly).

Thought to give an update on the compatibility with Mac. I'll continue working on this 👍

**Comment by cdrage** [comment]
Scratching my head all day trying to figure this out and I've come to the conclusion is that cannot do this on macOS with **just** the startup script.

If you see my latest commit, I used the key: LSUIElement in plist in order to get it to (in theory) work and reverted my `show()` changes back to main.

See both https://support.mozilla.org/gl/questions/1331130 and

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-108256 

Unfortunately, it doesn't work with Electron. Electron will always call .show() on first load when first starting and ignore what was set within `.plist`.

So we'll have to implement it both ways for macOS. Have it within plist (which makes sense) as well as making sure that if minimized setting is set and the application is first starting, show() isn't called on first run.

@benoitf I don't believe adding this to the startup scripts is a good idea and it should be implemented like my first commit.

**Comment by cdrage** [comment]
Windows appears to be doing the same despite adding `/min` to the script.

```
  WshShell.Run chr(34) & "${this.podmanDesktopBinaryPath}" & Chr(34) & " /min", 0
``` 

Electron does show(), ignores the /min parameter, and starts up anyways.

So looks like we can't do it 100% through the startup script. 

I'll have to modify this so it does _both_ on the startup script and in `main.ts`.

**Comment by cdrage** [comment]
Setup 3 different commits for review and to have a look over:

1. First commit is show() only approach
2. Second commit is startup only (which doesn't work, because electron ignores minimize on macOS on Ventura)
3. Third commit implements minimize on application start as well as startup, similar in-line with other electron applications (example: rocket chat: https://github.com/RocketChat/Rocket.Chat.Electron/issues/654).

In order words, startup minimize on Electron is buggy.

I'm going to tackle this epic instead: https://github.com/containers/podman-desktop/issues/395 and get back to this PR in the future. But feel free to review @benoitf / give any suggestions.

**Comment by benoitf** [comment]
@cdrage I'm not sure to understand why plist would not work

instead of:
```
    <key>ProgramArguments</key>
    <array>
        <string>/Applications/Podman Desktop.app/Contents/MacOS/Podman Desktop</string>
    </array>
```

we do
```
    <key>ProgramArguments</key>
    <array>
        <string>/Applications/Podman Desktop.app/Contents/MacOS/Podman Desktop</string>
        <string>--minimize</string>
    </array>
```

then in Podman Desktop we see if we have the flag `--minimize` and then we start minimized

**Comment by cdrage** [comment]
I'll push out a different PR as this one has gotten a bit too big. I'll keep all this information here for history. I'll modify the application startup and check for --minimize on windows and mac (wont work for linux).

**Comment by simonrey1** [comment]
Sorry for the wrong mention, I was confused with the sub-issues numbering

**Pull request closed without merging**
