### PR TITLE
fix: update to icon artwork

### PR DESCRIPTION
**Pull request by mairin**
So far I've pixel-snapped them, but there's still issues. very much a work in progress.

Signed-off-by: Máirín Duffy <duffy@redhat.com>

### Screenshot/screencast of this PR

TBD

### What issues does this PR fix or reference?

https://github.com/containers/podman-desktop/issues/2900

### How to test this PR?

Run and behold icons in the system tray!

### CODE REVIEW

**Comment by deboer-tim** [comment]
On MacOS the changes make the icon much more bold and noticeable:
https://github.com/containers/podman-desktop/assets/19958075/40314844-05cd-496c-b342-5f51c40cf34f

I know you weren't trying to change it here, but I find the animation far too subtle. Yes, I run my my monitors with some scaling, but I happened to catch the google drive doing a sync in the video above. You can see how much more visible it is (a periodic background task) vs PD (which I may have triggered and be waiting for).

**Comment by mairin** [comment]
@deboer-tim is bold and noticeable a good thing or a bad thing? :-) 

I agree the animation might be too subtle so I'll brainstorm a few ideas on that.

I'm struggling with the icons in GNOME... they show up glitchy when I have dark icons available at 2x and 3x. I know GNOME's tray is based on 48x48px... but look at how it looks

@3x
Screenshot from 2023-06-24 19-55-02

@2x
Screenshot from 2023-06-24 20-03-36

I even tried a GNOME icon to see if it was something about the format of my file - the GNOME icon also gets glitched...
Screenshot from 2023-06-24 20-06-02

I'm struggling a bit with this but it does look clean in the macOS video so that's good :)

**Comment by mairin** [comment]
Actually now that I look at it - it looks like it's overlaying multiple icons on top of each other with the leaf icon... 🤔

**Comment by mairin** [comment]
Been playing with this more and started a discussion here:
https://github.com/containers/podman-desktop/discussions/3154

Next step is to procure a windows system 😄

**Comment by benoitf** [comment]
@mairin on Windows, icon can also be animated

https://github.com/containers/podman-desktop/assets/436777/87c8970f-1160-45ee-bd11-adc4c0ddc5d9


if you want to always have something running the animation you can tweak the animate file

```diff
diff --git a/packages/main/src/tray-animate-icon.ts b/packages/main/src/tray-animate-icon.ts
index 7c56966f..2d16d1ce 100644
--- a/packages/main/src/tray-animate-icon.ts
+++ b/packages/main/src/tray-animate-icon.ts
@@ -31,7 +31,7 @@ export class AnimatedTray {
   static readonly MAIN_ASSETS_FOLDER = 'packages/main/src/assets';

   constructor() {
-    this.status = 'initialized';
+    this.status = 'updating';
     this.updateIcon();

     // refresh icon when theme is being updated (especially for Windows as for macOS we always use template icon and on linux the menu bar is not related to the theme)
@@ -147,7 +147,7 @@ export class AnimatedTray {
   }

   setStatus(status: TrayIconStatus) {
-    this.status = status;
+    console.log('ignoring the status being set to', status, 'keep the status', this.status);
     this.updateIcon();
   }
 }
```

**Comment by benoitf** [comment]
closing as this PR is stale since 5months old

**Pull request closed without merging**
