### PR TITLE
refactor: cleanup unused kubernetes client code

### PR DESCRIPTION
**Pull request by feloy**
### What does this PR do?

Cleanup unused kubernetes client code

### Screenshot / video of UI

No changes on UI

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Kubernetes features should work as before

- [x] Tests are covering the bug fix or the new feature (N/A)

### CODE REVIEW

**Comment by benoitf** [comment]
it looks like the body is not matching the Pull Request template

**Comment by feloy** [comment]
> it looks like the body is not matching the Pull Request template

Updated

**Review by jeffmaury — COMMENTED** [review]
Jut wondering why we are listing routes and not Ingresses anymore ?

Also I remember the createResource methods were used by deploy to kubernetes

**Comment by feloy** [comment]
> Jut wondering why we are listing routes and not Ingresses anymore ?
> 

Listing routes is used at https://github.com/podman-desktop/podman-desktop/blob/main/packages/renderer/src/lib/pod/PodActions.svelte#L69 to display links exposed by routes. It is not implemented for ingresses.

> Also I remember the createResource methods were used by deploy to kubernetes

As I understand, it has been replaced by another implementation in https://github.com/podman-desktop/podman-desktop/pull/5849

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by axel7083 — APPROVED** [review]

**Pull request merged**
