### PR TITLE
Add an ADOPTERS.md file to the project

### PR DESCRIPTION
**Pull request by slemeur**
### What does this PR do?

As we are getting more and more users, it would be nice if they could report their experience and show they are using the project. 

Add initial adopters.md file to the root directory of the repo

### CODE REVIEW

**Review by jeffmaury — DISMISSED** [review]
We should have a link to that file from the README.md

**Comment by cdrage** [comment]
I believe @mairin has some user feedback from companies that we could add to the ADOPTERS.md file.

Also we'll have to remove the "ACME" lines. I'm assuming this PR is a draft / WIP?

**Comment by afbjorklund** [comment]
> remove the "ACME" lines.

Must be a Bugs 🤭

**Comment by mairin** [comment]
> I believe @mairin has some user feedback from companies that we could add to the ADOPTERS.md file.
> 
> Also we'll have to remove the "ACME" lines. I'm assuming this PR is a draft / WIP?

I have a list of companies that agreed to be listed as users on podman.io:

https://podman.io/community

(See bottom under "special thanks")

I see at least one who is a Podman Desktop user and Valentin got the OK from them to be listed. Not 100% sure about the others (they all use at least Podman but we want Podman Desktop usage here.)

There's also tweets from the user testimony section but we would probably need to ask permission to list here. Here is that file from the website repo (older versions have more / different quotes - I update these manually every now and then.)

https://github.com/containers/podman.io/blob/main/static/data/testimonials.ts

**Comment by slemeur** [comment]
The "acme" is just an example added so people know the information expected if they submit a PR. (and can use that as inspiration)

**Review by cdrage — APPROVED** [review]

**Pull request merged**
