### PR TITLE
chore: add `joinPath` + `with` methods on Uri extension point

### LINKED ISSUE #5359: handling Uri path manipulation
### Is your enhancement related to a problem? Please describe

sometimes we need to merge path using Uri

Uri extension point should offer a way to join path with another one

it's a sub-issue of webviews

example: 

```ts
const uri = Uri.parse('file:///hello');
const newUri =Uri.joinPath(uri, '/my/subpath');
```

it should return `file:///hello/my/subpath`

### Describe the solution you'd like

implement Uri.joinPath

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### What does this PR do?
add/expose static `joinPath` and `with` methods

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/5359

### How to test this PR?

unit tests provided

### CODE REVIEW

**Comment by benoitf** [comment]
restarted macOS job

**Review by jeffmaury — COMMENTED** [review]
I don't see the with method be part of the extension API is it on purpose ?

**Comment by benoitf** [comment]
@jeffmaury yes it's an internal method (used by joinPath)

**Comment by benoitf** [comment]
I will add exposure

**Comment by benoitf** [comment]
@jeffmaury done

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
