### PR TITLE
Light mode for NavPage & FormPage

### LINKED ISSUE #6889: Light mode for NavPage & FormPage
### Is your enhancement related to a problem? Please describe

We need to support light mode on these two pages, since they're used extensively.

### Describe the solution you'd like

Define missing bg/tile/divider colors in the light mode palette and use them in these pages (bg color likely one page up).

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
### What does this PR do?

Adds support to light mode on NavPage & FormPage components

#### NavPage

light-navpage

#### FormPage

light-formpage

### What issues does this PR fix or reference?

Fixes #6889

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
Nice!

**Review by ekidneyrh — APPROVED** [review]
Nice! I'm still working on what colours to work for the missing components on here, but I'll update asap on the tracking ticket :)

**Comment by deboer-tim** [comment]
In the current design, forms have an intentional color change between the header area and the content. These color values remove that. @ekidneyrh is this an intentional design change? If so, do we need to keep a separate -bg color? The area between the title and start of form also looks big (since it's effectively double-padded), should we reduce this?

Screenshot 2024-05-10 at 8 05 35 AM

**Comment by ekidneyrh** [comment]
Nav Page:
[Nav Page.pdf](https://github.com/containers/podman-desktop/files/15307995/Nav.Page.pdf)
NavPage

Form Page:
Form Page
[Content Theming.pdf](https://github.com/containers/podman-desktop/files/15308032/Content.Theming.pdf)


Yah I'm in favour of getting rid of of the extra padding and use the same background for the header and the rest of the form. I don't think there's a reason to have two different colours.

Is there any values im missing? I know there is some overlap with the image and volumes pages. I dont think there's a need to have a bg colour for the table-body-label-text on the nav pages.

**Comment by feloy** [comment]
> Yah I'm in favour of getting rid of of the extra padding and use the same background for the header and the rest of the form. I don't think there's a reason to have two different colours.
> 

I have added a commit to remove the top padding of the forms using the FormPage component

**Comment by feloy** [comment]
> Nav Page: [Nav Page.pdf](https://github.com/containers/podman-desktop/files/15307995/Nav.Page.pdf) NavPage
> 

The `table-body-label-text` defined in https://github.com/containers/podman-desktop/pull/7151 was intended for the text `Kubernetes`/`Podman` in the `Environment` column (inside a label). You are reusing this name for the text of the header (which was defined by `table-header-text` in #7151).  I'm ok to use `table-body-label-text` for the header text, but in this case it will be missing the color for the text in the Environment column.

**Review by deboer-tim — APPROVED** [review]

**Pull request merged**
