### PR TITLE
chore: fix some linting rules

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
fix linting rules

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by feloy — APPROVED** [review]
LGTM

**Review by axel7083 — APPROVED** [review]
LGTM

> There are some conflicts

**Comment by benoitf** [comment]
I'm gonna look at the conflicting file

**Comment by benoitf** [comment]
rebased

**Pull request merged**
