### PR TITLE
fix: Nav tooltip

### LINKED ISSUE #2229: add immediate popup for icons of the navbar
### Is your enhancement related to a problem? Please describe

Following https://github.com/containers/podman-desktop/pull/2173, user has no immediate clue to know what icons are now

Creating an issue from my comment there: https://github.com/containers/podman-desktop/pull/2173#issuecomment-1519636789

So basically, now a user need to hover on an icon and wait for a while to have description.
We should have immediate popup being displayed hovering the navbar icon that describe the name of the icon

### Describe the solution you'd like

Immediate popup with the name of the icon

### Describe alternatives you've considered

open to other ideas

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Changes the tooltips on the main navigation from Electron's default to our own tooltip component. This looks prettier and appears instantaneously.

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/19958075/53f6bf03-fa66-46d9-a95d-88eb856d1be0

### What issues does this PR fix or reference?

Fixes #2229.

### How to test this PR?

Hover over the items in the main nav. Go to a few of the pages and open Settings while doing it.

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM but what about having SVG images defined in their own separate files for better future maintenance

**Comment by deboer-tim** [comment]
I moved all of the icons that are also used elsewhere to their own files a couple months ago. I can do the remaining two here (dashboard & settings) via another PR.

**Comment by deboer-tim** [comment]
I moved all of the icons that are also used elsewhere to their own files a couple months ago. I can do the remaining two here (dashboard & settings) via another PR.

**Comment by benoitf** [comment]
It is causing a regression (select a navbar item while clicking a container item)

https://github.com/containers/podman-desktop/assets/436777/2c6611d5-47f3-4156-8fce-799049e18f1f

**Pull request merged**
