### PR TITLE
feat: allow to add port mappings when image has no exported port (#1046)

### LINKED ISSUE #1046: Port Mapping Fields are not shown in the create container from image panel
### Bug description

If i pull an image without Port Mapping with explicit Expose Port number like rancher/hello-world. It is an standard image with port number 80.

I cann't create a container with a mapping port number like 8080 because the fields are not shown in the panel.

### Operating system

Windows 10 21h2 19044 Intel 64

### Version

0.10.0

### Steps to reproduce

1. podman pull rancher/hello-world in console or with podman desktop
2. try to create a container from this image
3. In the Basic Menu from Create container from Image Panel ist not show the Port mapping Labels und Field and Port Forward ist not possible.

### Relevant log output

```shell
All Logs are good
```

### Additional context

Same Image when it is with the podman CLI und with parameter -p 8080:80 could be with localhost:8080 in a browser called und show the info from the Hello World Image from Rancher

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

Allow to add port mappings when starting an image that has no exported ports.

### Screenshot/screencast of this PR

If there is no exported port, the user is free to add multiple local:remote port mappings
new_port_mapping_5

### What issues does this PR fix or reference?

fixes #1046 

### How to test this PR?

1. Pull rancher/hello-world
2. Start it

### CODE REVIEW

**Comment by slemeur** [comment]
Nice job @lstocchi ! 

If we want to be consistent in term of UI/UX with the other options, shouldn't we have the same type of layout with two columns and the '+' button?
Left column would be `host port` and right column `container port`? WDYT

**Comment by lstocchi** [comment]
> If we want to be consistent in term of UI/UX with the other options, shouldn't we have the same type of layout with two columns and the '+' button? Left column would be `host port` and right column `container port`? WDYT

Sure, now that you make me think about it, yes 😓 . I didn't notice it's the same exact case of adding new envs, for example.

**Comment by slemeur** [comment]
Also, if in the container definition there are already exposed port, we are showing it like this:
Capture d’écran 2023-01-26 à 12 04 57

Maybe, we should make that consistent - and allow the user to add additional port mapping even if the image has some pre-defined exposed port?

**Comment by lstocchi** [comment]
> Maybe, we should make that consistent - and allow the user to add additional port mapping even if the image has some pre-defined exposed port?

@slemeur It's certainly a use-case that could happen, do we want to always show those fields or I add a button that creates new fields when requested?

This is static, always visible. Maybe we should add a sentence to explain it
immagine

By adding new fields dynamically
new_port_mapping

WDYT? Do you have other ideas?

**Comment by slemeur** [comment]
I really like the dynamic approach you choose. Works well IMO.
Let's maybe clarify the tooltip on the "+" action?

**Comment by benoitf** [comment]
do we need to add a small text/subsection before the ports exposed from the EXPOSE instructions in the Dockerfile
And then add 'additional exposure/ports' where we can add new ports ?

**Comment by deboer-tim** [comment]
To me it isn't obvious looking at the UI that clicking on the [+] would create another port vs doing something on the existing port 80/9000, so I wouldn't have even looked at the hover help. If there are two existing ports it would probably be more confusing, so I would +1 Florent's comments to separating it and making it more obvious in the UI (but keeping it simple/compact is good).

I'm the kind of person that notices the volume, port, and environment variables all have two text fields and the middles are at three different y positions. :) The local 80/9000 port essentially creates a fourth. Would appreciate it if you could fix at least some of this, and line up the new port columns with something existing.

**Comment by lstocchi** [comment]
New day, new proposals

Based on your feedbacks I see this in two ways.

The first is just a static section which is always visible. Maybe we can indent the title and inputs a bit to the right to show they are children of the parent port mapping section.

additional_port

the second is an evolution of the dynamic button.
Added a text so everyone notices it. When clicked extra inputs are shown. If clicked again all inputs and their value are removed. It's like a reset.

new_port_mapping_2

WDYT? @slemeur @benoitf @deboer-tim

**Comment by benoitf** [comment]
I like option 2 but maybe the add remove custom ports button should be on the left ( Or maybe it's a bad idea as well)

**Comment by lstocchi** [comment]
> I like option 2 but maybe the add remove custom ports button should be on the left ( Or maybe it's a bad idea as well)

This is when displayed on the left
new_port_mapping_4

**Comment by benoitf** [comment]
yes it may be better like that especially when we don't have any EXPOSE instruction

**Comment by benoitf** [comment]
It looks like the codebase is still for the yesterday behaviour

**Comment by lstocchi** [comment]
> It looks like the codebase is still for the yesterday behaviour

I was waiting for an OK about the new design. Code pushed 👍

**Review by benoitf — APPROVED** [review]
image

tested and works fine for me 🎉

**Comment by deboer-tim** [comment]
Much better, but for me it's a bit odd that you add the first one from a button on the left and then add more on the right (which 'moves' each time you add one), plus the fact that the initial button changes from 'add one' to 'remove all'. I'd suggest always keeping the "Add custom port mapping" button as-is, and each row just has a delete button on the right. Florent has already approved, so I'd be fine doing this as an additional PR.

**Comment by benoitf** [comment]
I'm fine to have follow up PRs or amend this one

**Comment by lstocchi** [comment]
> Much better, but for me it's a bit odd that you add the first one from a button on the left and then add more on the right (which 'moves' each time you add one), plus the fact that the initial button changes from 'add one' to 'remove all'. I'd suggest always keeping the "Add custom port mapping" button as-is, and each row just has a delete button on the right. Florent has already approved, so I'd be fine doing this as an additional PR.

I see your point.

The initial idea was to have something similar to an `Advanced settings` button that makes visible a tab/panel with all extra settings. And then when clicking on it again the tab/panel gets closed. This is why the 'add one' and 'remove all'. For me it was more 'open the custom port mappings view', 'close it'.

I'm going to update this PR 👍

**Comment by lstocchi** [comment]
@deboer-tim something like this?

new_port_mapping_5

**Comment by benoitf** [comment]
@lstocchi would be nice to update the description body to be accurate ( the image)

**Comment by deboer-tim** [comment]
In case my thumbs-up isn't visible enough: yes! Thank you, looks great.

**Comment by lstocchi** [comment]
> @lstocchi would be nice to update the description body to be accurate ( the image)

@benoitf You mean the image in the first message right?

**Review by cdrage — APPROVED** [review]

**Comment by cdrage** [comment]
Tested and works well! Grats on the first ever svelte / UX/UI change merged PR! 🎉

**Pull request merged**
