### PR TITLE
fix: header line height issue

### LINKED ISSUE #4485: Give proper spacing in header to avoid overlapping
### Is your enhancement related to a problem? Please describe

When I selected the heading both the lines overlapped each other which is a bit unprofessional looking.

### Describe the solution you'd like

I'll introduce proper spacing to prevent the overlapping of the both lines

### Describe alternatives you've considered

image

### Additional context

Kindly assign me this issue.

### PR DESCRIPTION
**Pull request by singodiyashubham87**
### What does this PR do?

I have fixed the spacing issue in the header.

### Screenshot/screencast of this PR

# Old
image

# New 
image

### What issues does this PR fix or reference?

Fix #4485 

### How to test this PR?

Check the rendered website

### CODE REVIEW

**Comment by benoitf** [comment]
@singodiyashubham87 FYI you'll need to add a SignedOff to your commit (so PR check DCO will be ✅ )

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/blob/main/CONTRIBUTING.md#sign-your-prs

**Comment by singodiyashubham87** [comment]
@benoitf I've already made the commit, how can I edit the commit message now to add my SignedOff?

**Comment by benoitf** [comment]
You can amend your commit and force push it to your branch

**Comment by singodiyashubham87** [comment]
@benoitf Okay, I'll do this now.

**Comment by singodiyashubham87** [comment]
@benoitf I have added my signature still the check is failing, why?

**Comment by benoitf** [comment]
@singodiyashubham87 it requires a blank line before SignedOff

In your commit you used a very long line

**Comment by singodiyashubham87** [comment]
@benoitf The commit is proper now, I have added an empty line before Signature, but the test is still failing.
image

**Comment by lstocchi** [comment]
@singodiyashubham87 you can find more info here https://github.com/containers/podman-desktop/pull/4494/checks?check_run_id=18026745941 

The proper format should be 
`Signed-off-by: Shubham Sindodiya <sindodiyashubham87@gmail.com>`

**Comment by singodiyashubham87** [comment]
@lstocchi I have modified the commit again.

**Comment by lstocchi** [comment]
> @lstocchi I have modified the commit again.

Sorry i just gave a quick look and i thought the problem was only the missing `<>`

As said above the page https://github.com/containers/podman-desktop/pull/4494/checks?check_run_id=18026745941 gives you more details

```
Expected "singodiyashubham87 [singodiyashubham87@gmail.com](mailto:singodiyashubham87@gmail.com)", 
but got "Shubham Singodiya [singodiyashubham87@gmail.com](mailto:singodiyashubham87@gmail.com)".
```

**Comment by singodiyashubham87** [comment]
@benoitf @lstocchi Done!

**Review by lstocchi — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Pull request merged**
