### PR TITLE
Kubernetes Services Page

### LINKED ISSUE #4368: Kubernetes Services page
### Is your feature request related to a problem? Please describe

The podify flow creates Kubernetes services, but there is no way to view them or clean them up from within Podman Desktop, and hence rerunning the flow doesn't work.

### Describe the solution you'd like

Add a new main nav item for Kubernetes Services, a list page, and details page - similar to what we have for Containers or Pods. Users should be able to delete services.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Adds a UI for Kubernetes Services, similar to the Deployments page. All
design elements are included, columns are sortable, and there is a
delete action.

Depends on service store (PR #5295), so ignore everything except the
last commit (i.e. only review /service folder and App/AppNavigation).
Do not merge before #5295.

### Screenshot / video of UI

Screenshot 2023-12-21 at 5 00 23 PM

### What issues does this PR fix or reference?

Fixes #4368.

### How to test this PR?

Like the Deployments page, the Services page will appear whenever you have a kube context.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
I was wondering if we should have named services objects KubernetesServices to make it less confusing ( in the code)

not a required change

**Comment by slemeur** [comment]
pretty cool ! Nice work @deboer-tim  
cc @axel7083 ;)

**Comment by axel7083** [comment]
This is amazing job !

**Comment by feloy** [comment]
It seems to me there are missing some important information: the workloads served by these services. The 2 information important to me would be:
- the selector (what the user has defined)
- the list of endpoints, or at least the number of endpoints (what is the current state)

**Comment by deboer-tim** [comment]
> It seems to me there are missing some important information: the workloads served by these services. The 2 information important to me would be:
> 
> * the selector (what the user has defined)
> * the list of endpoints, or at least the number of endpoints (what is the current state)

@feloy the design discussion was in #4576 and this matches that. I'm fine changing, but there are already a lot of columns so I think we're at the point where every suggested addition should say which column it would replace - i.e. we only get to show <= 6 key things on the summary list, everything else would go in details like it does for pods or containers.

**Comment by feloy** [comment]
> > It seems to me there are missing some important information: the workloads served by these services. The 2 information important to me would be:
> > 
> > * the selector (what the user has defined)
> > * the list of endpoints, or at least the number of endpoints (what is the current state)
> 
> @feloy the design discussion was in #4576 and this matches that. I'm fine changing, but there are already a lot of columns so I think we're at the point where every suggested addition should say which column it would replace - i.e. we only get to show <= 6 key things on the summary list, everything else would go in details like it does for pods or containers.

That's ok for me. Just a note for future discussions

**Comment by slemeur** [comment]
It's actually a good idea, let's follow up on https://github.com/containers/podman-desktop/issues/5367

**Pull request merged**
