### PR TITLE
chore: exclude some jobs in draft mode unless a label is set

### LINKED ISSUE #9111: disable actions when pull request is in draft mode (unless a label is applied)
### Is your feature request related to a problem? Please describe

when a pull request is in draft mode, PR checks are run on top of it. But usually if the PR is not ready the checks can be ignored.

It is to limit the jobs on the available runners that we have in the current containers organization

### Describe the solution you'd like

- disable all PR checks jobs (linting, unit tests, formatting, e2e tests, etc) (the whole pr-check.yaml file)
- if a label is set (for example CI or another label that is meaningful) it will trigger the checks

we might add a comment to the PR in that case to explain that all checks are not triggered and it can be triggered using a label.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
exclude some jobs in draft mode unless a label is set

### What issues does this PR fix or reference?

fixes https://github.com/podman-desktop/podman-desktop/issues/9111

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by axel7083** [comment]
All the tests in this PR marked as `Skipped` are not reassuring me

**Comment by benoitf** [comment]
@axel7083 you should not be so scared. I added a new event `ready_for_review` so going from draft to review is triggering the checks

**Review by feloy — APPROVED** [review]
I think I'll need displayed somewhere which label needs to be added, or I'll always forget it (and it will be quite mysterious for new committers), but it can come later.

Thanks for this enhancement

**Comment by benoitf** [comment]
@feloy provided https://github.com/podman-desktop/podman-desktop/pull/9965

**Review by axel7083 — APPROVED** [review]

**Pull request merged**
