### PR TITLE
chore: solid icons

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

There are several places where we use solid (filled) versions of our icons. This adds a new property to each icon component so that you can use solid={true} to get a solid version.

### Screenshot/screencast of this PR

Screenshot 2023-01-27 at 9 46 49 AM

### CODE REVIEW

**Comment by benoitf** [comment]
hello, where do we use solid icons ? and why use solid versions ?

**Comment by deboer-tim** [comment]
Sorry, I should have explained better: all of the list views (containers, pods, images, volumes) currently use solid versions:
- Volumes uses FA-equivalent solid volume.
- Images uses solid FA layers.
- Pods uses FA-equivalent solid container.
- Containers uses a variety, e.g. pods are outlines when stopped but solid when running.

IMHO we should replace FA-equivalents with our own SVGs, use our image SVG in Images, etc. These will require the solid versions.

**Comment by benoitf** [comment]
I agree that we need to replace the fontAwesome by our SVGs but then do we also need the solid versions ?
For example in Volume lists, do we need a solid icon or we just use the wire icon as well ? AFAIK in the first implementation it was using solid icons but I think in the last iteration steps we replaced a lot of solid icons by wire icons.

**Comment by benoitf** [comment]
@mairin could you tell if we will need solid icons or not ?

**Review by benoitf — APPROVED** [review]
the code is perfectly fine so I'm approving but I still don't know if we have a need for the solid icons in the latest mockups

**Comment by mairin** [comment]
@benoitf 👋 Yeh, I think this is a nice feature. @deboer-tim talked with me about this early in the week. In some cases the outline icons are a little better / in some cases solid can be better. For example, maybe solid looks better in the leftnav in light mode but outline is better in dark mode (ex. better contrast.) Generally, assuming dark mode, by default I prefer outline for the small versions - left nav + in list, but sometimes solid is needed (eg for color coding) and solid is also nicer for large scale icons in empty list messaging. So having it as an option on the icons is 👍

**Comment by benoitf** [comment]
ok then let's merge

**Comment by mairin** [comment]
Just a few examples - and it seems I need to make an updated clean container list mockup so I'll add that to my backlog:

Icon in the dashboard notices: solid here and colorized, since there's fewer of them and we want them to be noticed more:
Screenshot from 2023-01-27 12-18-57

Icons in a design we probably won't end up using, but is a good example - we don't want to draw too much attention to these, just use them to ease the skimmability of a long list of similar looking items. They're outline icons, and not colored especially / same as text color, so they draw less attention:
Screenshot from 2023-01-27 12-20-12

This is out of date (the icon should be square, and the red is now grey to draw less attention, and the icon for started instead of a seedling is the same as off with a star emblem in the corner) - but you see how we use solid icon with green to draw attention to what's running, vs outlined icon with a grey color to draw less attention:
Screenshot from 2023-01-27 12-21-22

For the left nav in dark mode - outlined icons are just a quick guide to make it easier/faster to skim the otherwise similar looking text blocks in the nav... they don't need to draw too much attention, just enough to contrast with the other items. So they're outlined here in a grey.
Screenshot from 2023-01-27 12-19-07

Hope this helps - it's all about figuring out where each one should  land on the scale of attention to the user, we don't want to be loud with them everywhere, but it helps to have the option to go solid when needed to do a more effective color fill to draw attention when needed!

**Pull request merged**
