### PR TITLE
chore: patch kubernetes-client with health class

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Patch the `@kubernetesclient-node` import with the PR https://github.com/kubernetes-client/javascript/pull/2035

### What issues does this PR fix or reference?

Part of #9938

### CODE REVIEW

**Comment by benoitf** [comment]
I'm fine to merge any patch but it needs to be merged upstream first

**Comment by feloy** [comment]
draft waiting for PR https://github.com/kubernetes-client/javascript/pull/2035 to be merged

**Comment by benoitf** [comment]
it's in a good shape to be merged but better to wait it's merged.

if you're blocked, in the meantime you can issues PR using this patch

**Comment by feloy** [comment]
Setting as ready for review, the original PR being merged in 1.x branch

**Review by benoitf — APPROVED** [review]

**Pull request merged**
