### PR TITLE
fix: minor palette and padding adjustments for fit & finish

### PR DESCRIPTION
**Pull request by mairin**
### What does this PR do?
- Adjusts padding between the left hand nav and the right hand main content / screen area to be consistent across the main tabs of the application and the tabs of the settings area.
- Adjusts the color palette on the dashboard to match the color palette of the other main screens.

#### Dashboard Before & After
Screenshot from 2023-04-10 09-28-59
Screenshot from 2023-04-10 09-10-04

#### Resources before & after
Screenshot from 2023-04-10 09-29-05

Screenshot from 2023-04-10 09-10-13

#### Proxy before & after
Screenshot from 2023-04-10 09-29-20

Screenshot from 2023-04-10 09-10-23

### What issues does this PR fix or reference?

No related issues, just my nitpickiness

### How to test this PR?

Check the padding between the right hand side and the left nav and make sure it's generous, check color scheme on dashboard

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by lstocchi — COMMENTED** [review]
The background gets broken when the content is larger than the window height.
You can see it if you reduce the windows and scroll down.

Main branch
result-main

This PR
result-now

**Comment by mairin** [comment]
@lstocchi Ah good catch! I'll poke at it!

**Comment by deboer-tim** [comment]
FWIW, this issue existed weeks ago so I doubt it is related to this change. I can't reproduce locally atm, not sure if this has somehow brought it back or completely unrelated.

**Comment by mairin** [comment]
I figured out a good fix but need some help with the logic!

**Comment by mairin** [comment]
OK, @deboer-tim helped me with the logic needed to fix the issue you pointed out @lstocchi so this fixes that as well.

**Review by lstocchi — APPROVED** [review]
LGTM. Thanks @mairin 🚀

**Comment by benoitf** [comment]
DCO is failing and the formatter/linter is reporting some errors
`yarn format:fix && yarn lint:fix` to launch

@mairin let us know if you want to fix that or if I do the changes

**Pull request merged**
