### PR TITLE
feat(main): handle EnvFiles parameter when creating a container

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
when receiving an EnvFile parameter when creating a container, read the file and add the properties to Env object

### What issues does this PR fix or reference?

related to https://github.com/containers/podman-desktop/issues/3281

### How to test this PR?

unit tests added

use the PR https://github.com/containers/podman-desktop/pull/4026

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
Everything looks good. Just wonder why don't you just skip the comment lines if any? Because right now the user sees an error if he tries to import a file with comments. 

I think that one could use a file created by someone else which contains some comments in it and it could be annoying to clean it everytime.

**Comment by benoitf** [comment]
@lstocchi do you have an example of file that you used ?

**Comment by benoitf** [comment]
b/c yes it should filtered commented lines 👍 I may have skipped this simple case 🤦

**Comment by lstocchi** [comment]
> @lstocchi do you have an example of file that you used ?

Just add a comment with the #, something  like 

```
# used for this feature
feature=blabla
# needed for another
second=ok
```

**Comment by benoitf** [comment]
ok I think I forgot 👍

**Comment by benoitf** [comment]
@lstocchi I've pushed a fixup

**Review by lstocchi — APPROVED** [review]
LGTM!! Very useful feature 🚀

**Pull request merged**
