### PR TITLE
feat: allow to abort build image (#1655)

### LINKED ISSUE #1655: Allow to abort a build of an image
### Is your enhancement related to a problem? Please describe

Building an image may consume time.
We may notice at some point that we need to cancel the action (for any reason) but it is not currently possible.
We need to wait the end of the task

### Describe the solution you'd like

Allow to abort/cancel a current build of image

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?
This is built on https://github.com/containers/podman-desktop/pull/4364

It allows user to abort the build of an image

### Screenshot/screencast of this PR

abort_build

### What issues does this PR fix or reference?

it closes #1655 

### How to test this PR?

1. build an image
2. abort

### CODE REVIEW

**Comment by deboer-tim** [comment]
Nit: even though the underlying action is an abort, I think we generally use Cancel for buttons.

**Comment by lstocchi** [comment]
> Nit: even though the underlying action is an abort, I think we generally use Cancel for buttons.

Updated

**Comment by benoitf** [comment]
it looks like the PR check "linter, formatter, unit tests" is not passing

**Comment by lstocchi** [comment]
> it looks like the PR check "linter, formatter, unit tests" is not passing

we need to merge https://github.com/containers/podman-desktop/pull/4364 and rebase this one

**Comment by benoitf** [comment]
ok, I just tried this one and it was not working, cancel button was doing nothing :-)

**Comment by axel7083** [comment]
Nice @lstocchi !!

**Comment by benoitf** [comment]
I clicked on 'rebase the branch' button as dependent PR has been merged

**Review by benoitf — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by jannikbertram** [comment]
hey @lstocchi just wanted to let you know that the test `Expect Abort button to being visible when image build is in progress` adds a dependency to run tests in the right order. As soon as you swap the last two tests, there is a test failure. 

It's probably caused by this
```
  buildImagesInfo.set({
    buildImageKey: Symbol(),
    buildRunning: true,
  });
```

Maybe it should set the parameters back to the default after running the test?

**Comment by lstocchi** [comment]
Thanks @jannikbertram !!

**Pull request merged**
