### PR TITLE
chore: take screenshots of the website

### LINKED ISSUE #2402: Automated website usability testing
### Is your feature request related to a problem? Please describe

We have lots of automated testing in the project, but none that verify that the website is actually usable. Besides changes directly to the website, there are cases where changes to common things (e.g. tailwind config) can inadvertently break the site.

### Describe the solution you'd like

We should have more automated testing of the website, e.g. basic a11y or link checking to confirm that there are no major regressions.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Take screenshots of the website and upload them to argos-ci
it allows to check if there are changes/regressions with PR
so we should be able to see on PR check if we're introducing changes with PR

I took the example from https://docusaurus.io/blog/upgrading-frontend-dependencies-with-confidence-using-visual-regression-testing

From this example, I removed all the /tags/ URL (as it was too many links)

If it works, maybe we could have the same stuff for Podman Desktop screenshots (and compare the app and not only the website)

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/2402

### CODE REVIEW

**Comment by benoitf** [comment]
I think tests are failing as quay.io is down

**Review by jeffmaury — COMMENTED** [review]
LGTM. What is the rationale for the Playwright version downgrade ?

**Comment by benoitf** [comment]
@jeffmaury there was something not consistent

https://github.com/containers/podman-desktop/blob/9ca58e4d46875b2a2b07e97ce4d0f10171e59144/package.json#L99 is using 1.39.0

but https://github.com/containers/podman-desktop/blob/9ca58e4d46875b2a2b07e97ce4d0f10171e59144/package.json#L133 is using 1.37.1

while the two need to have the same version

without that, if I install the chromium, it will download for example version v189 (due to 1.39) but will execute v108 (due to v137.1)

I made the two using the same version (and the lower as https://github.com/containers/podman-desktop/pull/4305 is failing)

**Comment by jeffmaury** [comment]
> @jeffmaury there was something not consistent
> 
> https://github.com/containers/podman-desktop/blob/9ca58e4d46875b2a2b07e97ce4d0f10171e59144/package.json#L99
> is using 1.39.0
> 
> but
> 
> https://github.com/containers/podman-desktop/blob/9ca58e4d46875b2a2b07e97ce4d0f10171e59144/package.json#L133
> is using 1.37.1
> 
> while the two need to have the same version
> 
> without that, if I install the chromium, it will download for example version v189 (due to 1.39) but will execute v108 (due to v137.1)
> 
> I made the two using the same version (and the lower as #4305 is failing)

Do we need both as @playwright/test has a dependency on playwright

**Comment by benoitf** [comment]
@jeffmaury I can look at it but in a separate PR

**Comment by jeffmaury** [comment]
> @jeffmaury I can look at it but in a separate PR

LGTM

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by cdrage — APPROVED** [review]

**Pull request merged**
