### PR TITLE
chore(deps-dev): bump vitest to v2.1.5

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
update to v2.1.5

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]

**Comment by axel7083** [comment]
Hello dependabo... euhh Florent !

**Review by gastoner — APPROVED** [review]

**Comment by benoitf** [comment]
I don't know why dependabot doesn't want to update this dependency, maybe it's not working well...

**Comment by benoitf** [comment]
so, the root cause is that afterAll is not found in a setupFiles

trying 2.2.0-beta2 it works, so I would assume it's a bug only in 2.1.5, closing

**Review by cbr7 — APPROVED** [review]

**Comment by benoitf** [comment]
ok so fixing transitive dependencies, it should work now

**Pull request merged**
