### PR TITLE
docs(fix): correct syntax of kind doc

### PR DESCRIPTION
**Pull request by pwright**

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
hi @pwright FYI you need to sign off the commit (so DCO check can pass)

**Comment by pwright** [comment]
@benoitf I've got the DCO check now, is that all I need to do?

**Comment by benoitf** [comment]
all checks need to be ✅

**Comment by benoitf** [comment]
FYI DCO check is ❌

**Comment by pwright** [comment]
@benoitf yeah, for some reason, rebasing using the github ui removed the signature from my commit, corrected now to keep vale happy ( I could have left 'You should see a similar output:', but went ahead and tried to improve it.
image

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
thanks @pwright

**Pull request merged**
