### PR TITLE
fix: skip filesystem flaky test

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Skip the the flaky test

### What issues does this PR fix or reference?

See https://github.com/podman-desktop/podman-desktop/issues/10043 (not fixed, this PR just skip it)

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
needs to be skipped only on Windows (it's not flaky on Linux)

**Comment by axel7083** [comment]
> needs to be skipped only on Windows (it's not flaky on Linux)

Yes! Done (prettier got crazy)

**Review by benoitf — APPROVED** [review]
I was expecting https://vitest.dev/api/#test-skipif but it also works

**Comment by axel7083** [comment]
> I was expecting https://vitest.dev/api/#test-skipif but it also works

Oh, I was looking at what is the recommended practice in our repo,

**Pull request merged**
