### PR TITLE
feat: Update icons / SVG cleanup

### PR DESCRIPTION
**Pull request by mairin**
This PR is a WIP, here is the yet todo list:

- [x] Update container status icons in the container list
- [x] Update pod status icons in the container list
- [x] ~~Update the podman and docker icons (if currently used in app)~~
- [x] Check / adjust formatting with a linter / etc
- [x] Add padding between STATUS and NAME headers in container cols (narrower icons mean this is needed)
- [x] Indent extension sub items to account for realignment of parent title due to icon addition
- [x] Fix icon minimize bug introduces (extensions area now bleeds out when minimized)

### What does this PR do?

- Updates the design of many of the icons for the application (dashboard, containers, pods)
- Cleans up / optimizes SVGs for icons
- Provides consistent 24x24 base for icons with icons positioned centered on base
- Addition of a new icon for Extensions
- Adjustments to vertical centering/alignment of text labels and count emblems for nav items

### Screenshot/screencast of this PR

Screenshot from 2022-10-17 18-26-28

### What issues does this PR fix or reference?

https://gitlab.com/fedora/design/community-design-team/issues/-/issues/50

### How to test this PR?

Pull code and rebuild UI according to instructions in contributor's guide for the project.

### CODE REVIEW

**Comment by benoitf** [comment]
hello, FYI 
1. you should run `yarn format:fix` and `yarn lint:fix` to fix formatting issues
1. You could use draft mode if it's only a work in progress PR
( We could add also the wip action to make sure we can't merge PR with title wip )

**Comment by benoitf** [comment]
and last, you need to use Signed-off on your commits ( to make dco check ✅)

**Comment by slemeur** [comment]
Super slick! 
Nice work @mairin !! 👍

**Comment by mairin** [comment]
@benoitf Thank you, I will be sure to do both - and I converted to draft mode, I didn't even know that was a thing 🤦🏻‍♀️

**Comment by benoitf** [comment]
@mairin it seems SVG icons are using hardcoded `#FFF` color. I think it might be an issue when we'll enable light/dark mode.
Probably at some point we should use `currentColor` instead

**Review by benoitf — APPROVED** [review]
Nice improvement

image

also on container list, exited/created status icons are rendering better (less disruptive)

**Comment by mairin** [comment]
> @mairin it seems SVG icons are using hardcoded `#FFF` color. I think it might be an issue when we'll enable light/dark mode. Probably at some point we should use `currentColor` instead

I made an issue for this here:
https://gitlab.com/fedora/design/team/requests/-/issues/10

And will work on it.

**Review by cdrage — APPROVED** [review]

**Comment by cdrage** [comment]
Really nice! Thank you @mairin 🎉

**Comment by cdrage** [comment]
Really nice! Thank you @mairin 🎉  really liking the new icons for containers + pods and all.

**Pull request merged**
