### PR TITLE
website: landing page update

### LINKED ISSUE #738: Website: Update to site with regards to container clusters
### Is your enhancement related to a problem? Please describe

Too much focus on OpenShift support, need to focus on Kubernetes and listing alternative container clusters such as k3s, rancher, kubernetes, etc.

### Describe the solution you'd like

Proposing changes to the site:

- [x] Update main README with screenshot similar to the first image on the "Features" tab. However, have list of plugins in the screenshot too. 
- [x] Move mentions of OpenShift to alternative tab (Extend maybe?)
- [x] Increase mention of Kubernetes 
- [ ] Add list of plugins that work (Trivy, OpenShift, etc.)
- [ ] Add list of container clusters / container engines we support (list openshift, k8s maybe k3s if we support it, kind, etc. as well as podman, lima, etc).

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deekay2310**
### Screenshot/screencast of this PR
Screen Shot 2022-11-03 at 10 36 19 AM
Screen Shot 2022-11-03 at 10 36 26 AM

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
I think the size of the new image is too big (it's twice the width/height than the previous one)

**Comment by deekay2310** [comment]
@benoitf reduced the size to the previous image's dimensions

**Comment by slemeur** [comment]
It is still too big. On my laptop I can't even see the entire image's height :)

**Comment by benoitf** [comment]
The image is still using twice the size of the previous image ?

**Comment by slemeur** [comment]
The image is also looking blurry compared to other ones.
See on the left the image you are proposing and on the right one already on the website: 
Capture d’écran 2022-11-03 à 18 17 15

**Comment by slemeur** [comment]
The image size might be fine now, but it looks not sharp.
Also I believe we should also try to improve how that image is getting rendered in the layout, and looking at reducing the space it takes.

**Comment by deekay2310** [comment]
@slemeur please check the new changes

**Comment by slemeur** [comment]
the new image is still very big:
- 2MB
- W: 4790px | H: 3969px instead of W: 1640px | H: 1327px

**Comment by deekay2310** [comment]
@slemeur reduced the size by 50%. Further reduction will diminish image quality.

**Comment by slemeur** [comment]
This is still not working @deekay2310. 
See the comments in the following image.
homepage

**Review by slemeur — APPROVED** [review]
LGTM

**Pull request merged**
