### PR TITLE
chore: added details to the mgmt tray features section

### PR DESCRIPTION
**Pull request by deekay2310**
Signed-off-by: Dev Kumar <devskumar99@gmail.com>

### CODE REVIEW

**Comment by deekay2310** [comment]
Screen Shot 2022-06-29 at 11 43 42 AM
Screen Shot 2022-06-29 at 11 43 47 AM

**Comment by benoitf** [comment]
hello, it's feeling odd to me to have to click to expand something on a scrolling page and how it's rendered

Also I would expect if there is no other approach taken that the chevron icon is rotating when we click on it

**Comment by deekay2310** [comment]
reason behind adding that expansion was that the information deviates from the theme. I will make the icon rotate.

**Comment by benoitf** [comment]
> reason behind adding that expansion was that the information deviates from the theme. I will make the icon rotate.

but we can't make the information fitting the theme ?

**Comment by deekay2310** [comment]
> > reason behind adding that expansion was that the information deviates from the theme. I will make the icon rotate.
> 
> but we can't make the information fitting the theme ?

i tried, but couldn't find an optimum way. It would pour too much information in one div block.

**Comment by slemeur** [comment]
Hi @deekay2310 ! I think some of the information added in the "more details" section are repeating what's already said above. I actually don't think we need to go into that level of details on the feature page of the website - but would be nice to get that covered in documentation in the future.

Also agreeing that the layout does not fit really well into the "style" of the feature page. 

So I'd prefer we move that content into the documentation and we include a button in the feature page of the website that redirects to the docs page.

**Comment by deekay2310** [comment]
Noted, @slemeur
Also how would you want it structured in the documentation?

**Comment by benoitf** [comment]
> 1month old, closing

**Pull request closed without merging**
