### PR TITLE
chore: improved solid volume icon

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Updated solid volume icon. IMHO this version stands out (pops) better and is a little clearer on the solid background, plus it will match with the PVC icon (PR #7710) that really requires the full outline.

### Screenshot / video of UI

Before:

Screenshot 2024-06-18 at 7 59 15 AM

After:

Screenshot 2024-06-18 at 7 58 35 AM

### What issues does this PR fix or reference?

Raised as part of #7641, matches PVC icon in #7710.

### How to test this PR?

Open volumes page.

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
Should we also change the one in the nav bar ? Otherwise look good 

image

**Comment by deboer-tim** [comment]
> Should we also change the one in the nav bar ? Otherwise look good

The outline (non-solid) version of the new PVC icon is just a dashed version of the volume icon, so they're still consistent. IMHO adding a second outline would look odd compared to everything else, but that's up to @ekidneyrh.

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by deboer-tim** [comment]
Rebased to avoid build issues.

**Pull request merged**
