### PR TITLE
website: Add info about package managers for Windows

### LINKED ISSUE #733: Enhance download page with info about package managers for Windows
### Is your enhancement related to a problem? Please describe

https://podman-desktop.io/downloads provides hints about package managers for Linux and macOS

Such info is not available in the section for Windows.

https://podman-desktop.io/docs/Installation/windows-install covers choco, winget, and scoop. 

### Describe the solution you'd like

https://podman-desktop.io/downloads could link https://podman-desktop.io/docs/Installation/windows-install

Something like
```
    Using package managers?
Check the Windows Install guide.
```

Screenshot 2022-10-28 at 21 11 38

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rsvoboda**
Info about package managers for Windows

Fixes https://github.com/containers/podman-desktop/issues/733

CC @benoitf

Screenshot 2022-10-29 at 21 56 36

### CODE REVIEW

**Comment by benoitf** [comment]
awesome. Thanks for the PR

**Comment by rsvoboda** [comment]
I will amend my commit message to reflect https://github.com/containers/podman-desktop/blob/main/CONTRIBUTING.md#use-the-correct-commit-message-semantics

Should I use `style:` or something else (e.g. `website:`)?

**Comment by benoitf** [comment]
it's ok. Only PR title needs conventional commits

**Comment by benoitf** [comment]
website: prefix is used for the website. I should amend the readme file

**Comment by rsvoboda** [comment]
ok, I won't touch the commit message. I did update them for https://github.com/containers/podman-desktop/pull/737 though :)

**Review by benoitf — APPROVED** [review]
thanks @rsvoboda for your contribution 🎉 

image

image

image

**Pull request merged**
