### PR TITLE
fix: cache eslint based on content

### LINKED ISSUE #9168: Switch eslint to work on content mode
### Is your enhancement related to a problem? Please describe

eslint is now very slow in cases you want to submit a PR but you previously check several PRs because a lot of files are detected as changed

### Describe the solution you'd like

Switch eslint to content mode

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #9168

### What does this PR do?

Change eslint cache policy to content

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#9168 

### How to test this PR?

pnpm lint:check

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
Is it solving your problem ? When switching from branches ?

**Comment by jeffmaury** [comment]
> Is it solving your problem ? When switching from branches ?

Hard to say because switching to another PR will revert back to metadata mode

**Comment by deboer-tim** [comment]
I just switched branches (minimal file change) and `lint:fix` has been running for >10 min. I've dropped this change in and will see if I notice any improvement over the next day or two.

**Comment by deboer-tim** [comment]
Today's experience: initial run still took 5-10min, but subsequent runs when I changed branches or modified files 'only' took 10-25s depending on the number of files changed. I haven't had it revert to >5min run with any change like it did before, so far this is looking like a solid improvement to me. 👍🏼

**Comment by benoitf** [comment]
nice

**Comment by benoitf** [comment]
@deboer-tim maybe you can approve then 🎉

**Review by deboer-tim — APPROVED** [review]

**Comment by deboer-tim** [comment]
Just following up: this works much better... most of the time. Some dependency changes still trigger the full rescan.

I know we've talked about options but I couldn't find any existing issues so I opened #9449.

**Pull request merged**
