### PR TITLE
feat: implement update for kubectl

### LINKED ISSUE #5035: Implement update for kubectl CLI
### Is your enhancement related to a problem? Please describe

the kubectl-cli does not support update

### Describe the solution you'd like

When #4689 is implemented, we should implement the update in the extension

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #5035

### What does this PR do?

Add update support for kubectl

### What issues does this PR fix or reference?

Fixes #5035 

### How to test this PR?

1. Onboard kubectl with previous version (not the latest one)
2. Go to Settings -> CLI tools
3. Update should be displayed
4. Click Update
5. Version should be updated and Update should disappear

### CODE REVIEW

**Comment by benoitf** [comment]
it may not be directly related but when I remove the binary from /usr/local/bin

I still see the cli being listed 
image


as it's finding it from the extension local folder

but should we really display it as being there as I can't use it

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/assets/436777/6ba23247-b8b5-4c3f-b1db-f07b49f8d0c7


it works but I would expect that clicking on 'update available' button it prompts me to which version it will update and I can confirm before it does the update ? or that it displays the version to which it'll update in the field (Update to v1.28.4 available)

**Review by benoitf — APPROVED** [review]
I have comments but it's more on the core thing, not from the extension part

**Comment by lstocchi** [comment]
> it works but I would expect that clicking on 'update available' button it prompts me to which version it will update and I can confirm before it does the update ? or that it displays the version to which it'll update in the field (Update to v1.28.4 available)

Just checked bc i was sure i added it and i thought there was a regression. There is a tooltip that tells the version you're going to update. Maybe it's a bug on mac. This is what i see on Windows
label_link

**Review by lstocchi — APPROVED** [review]
LGTM

**Pull request merged**
