### PR TITLE
fix: add back 'Done' text on the button

### LINKED ISSUE #3485: Missing done button text
### Bug description

After playing Pod/Container from a Kubernetes YAML file, selecting runtime and clicking play, the Done button has no inscription inside it.

Screenshot_20230810_155238-1

### Operating system

Fedora 38

### Installation Method

Flathub (Linux)

### Version

Next

### Steps to reproduce

Have a container or pod and corresponding YAML file ready. 
Click Play Kubernets YAML.
Select YAML file and runtime.
Click the Play button.
The done button has no text inside it.

### Relevant log output

```shell
N/A
```

### Additional context

N/A

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
add back 'Done' text on the button

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/3485

### How to test this PR?

unit test or try the usecase of the issue

### CODE REVIEW

**Review by deboer-tim — APPROVED** [review]
FWIW you can remove `type="primary"` too.

**Comment by benoitf** [comment]
@deboer-tim yes good catch, amended

**Comment by benoitf** [comment]
There is something wrong, I pushed the commit but PR is not updated/new change is not there

**Comment by benoitf** [comment]
ok looks like it was lagging on github side...

**Comment by benoitf** [comment]
removed the `title` and `type` attributes

**Comment by deboer-tim** [comment]
> ok looks like it was lagging on github side...

Yes, it has been very laggy today when I pushed too.

**Pull request merged**
