### PR TITLE
feat: add initialFocus to Input

### LINKED ISSUE #8798: Initial focus on Input component
### Is your enhancement related to a problem? Please describe

I would like to be able to set the focus on the `Input` when loading a page.

### Describe the solution you'd like

Add an optional `initialFocus` to the `Input` component
 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

add initialFocus to Input

### What issues does this PR fix or reference?

Fixes #8798 

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by benoitf** [comment]
I'm wondering if it's up to the component to provide that as we could have multiple components on a page and it's not possible that they have all this option

**Comment by feloy** [comment]
> I'm wondering if it's up to the component to provide that as we could have multiple components on a page and it's not possible that they have all this option

I expect that it would be the responsability of the caller to set this option on only one component.

I can see on Podman Desktop sources that we are using a native `input` and not an `Input` everywhere we need to set focus (either at creation time or during the lifecycle). Working on #8786, I wonder if I should use a native `input` or an `Input`. In the first case, I will need to duplicate the `Input` style and behaviour, in the second case, I am missing the focus feature.

**Review by gastoner — APPROVED** [review]
LGTM

**Comment by feloy** [comment]
> > I'm wondering if it's up to the component to provide that as we could have multiple components on a page and it's not possible that they have all this option
> 
> I expect that it would be the responsability of the caller to set this option on only one component.
> 
> I can see on Podman Desktop sources that we are using a native `input` and not an `Input` everywhere we need to set focus (either at creation time or during the lifecycle). Working on #8786, I wonder if I should use a native `input` or an `Input`. In the first case, I will need to duplicate the `Input` style and behaviour, in the second case, I am missing the focus feature.

Well, finally I can see there are many other events I would like to handle in the input, which are not handled by `Input`. I'll go with a native `input` for now

**Pull request closed without merging**
