### PR TITLE
feat: upgraded flatpak to org.freedesktop.Platform version 23.08

### LINKED ISSUE #3966: Upgrade flatpak to org.freedesktop.Platform version 23.08
### Is your enhancement related to a problem? Please describe

[org.freedesktop.Platform version 23.08 is available](https://discourse.flathub.org/t/freedesktop-sdk-23-08-0-released/5089), but Podman Desktop flatpak is still built with version 22.08.

### Describe the solution you'd like

Build flatpak with org.freedesktop.Platform version 23.08.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by themr0c**
### What does this PR do?

feat: upgraded flatpak to org.freedesktop.Platform version 23.08

### What issues does this PR fix or reference?

fixes #3966

### How to test this PR?

1. Build the flatpak package:

   ```
   MODE=production npm run build && ./node_modules/.bin/electron-builder build --config .electron-builder.config.cjs --linux flatpak
   ```
1. Install the flatpak package:

   ```
   flatpak install -u dist/podman-desktop-1.5.0-next.flatpak 
   ```

### CODE REVIEW

**Comment by themr0c** [comment]
Tested successfully on Fedora 38.

**Comment by benoitf** [comment]
it needs to be synched with https://github.com/flathub/io.podman_desktop.PodmanDesktop/blob/master/io.podman_desktop.PodmanDesktop.yml

**Comment by themr0c** [comment]
@benoitf https://github.com/flathub/io.podman_desktop.PodmanDesktop/pull/31

**Comment by benoitf** [comment]
I think it requires https://github.com/flathub/org.electronjs.Electron2.BaseApp/issues/43 first

**Comment by themr0c** [comment]
You are entirely right @benoitf. Converted to draft, as long as BaseApp 23.08 is not out.

**Comment by mairin** [comment]
@themr0c just tested - seems fine! in GNOME it shows up under Development in the menu but not under Utilities.

**Comment by themr0c** [comment]
https://github.com/flathub/org.electronjs.Electron2.BaseApp/issues/43 has been done.

**Comment by benoitf** [comment]
FYI you had a comment there https://github.com/flathub/io.podman_desktop.PodmanDesktop/pull/31#issuecomment-1733687717

**Comment by themr0c** [comment]
> 23.08 baseapp is out now.
>
> Can you check if desktop notifications work without --talk-name=org.freedesktop.Notifications?
>
> The 23.08 baseapp includes libnotify 0.8.2 which should not require that hole.

quoting https://github.com/flathub/io.podman_desktop.PodmanDesktop/pull/31#issuecomment-1733687717

**Comment by themr0c** [comment]
@benoitf https://github.com/flathub/io.podman_desktop.PodmanDesktop/pull/31 is rebuilding. I am not sure how the merges should be synchronized (which one first? both simultaneously?)

**Comment by benoitf** [comment]
@themr0c I think here it's better b/c it's not rolled out to all people using flatpak

on flathub, once merged all people get it in 3-4hours

so better to check manual .flatpak here for a while before merging on flathub

WDYT ?

**Comment by benoitf** [comment]
https://github.com/flathub/io.podman_desktop.PodmanDesktop/pull/31 has been merged, merging there

**Review by benoitf — APPROVED** [review]

**Pull request merged**
