### PR TITLE
feat: extend withProgress API to use task manager widget

### LINKED ISSUE #2019: Expose tasks to extension API
### Is your enhancement related to a problem? Please describe

New task UI is very good, so I want to use it for long running tasks in openshift-local extension.

### Describe the solution you'd like

Extension could add/update/delete task with extension API.
This could be done with extending existing `window.withProgress` function or with complete replacement.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2019

### What does this PR do?

Extend the withProgress API to report progress in the task API

### Screenshot/screencast of this PR

progress

### What issues does this PR fix or reference?

Fixes #2019

### How to test this PR?

Re install Kind and Kind download should be reported in the task manager

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM

**Review by cdrage — APPROVED** [review]
LGTM! Don't see any issues with the code and was able to test it fine. 

Feel free to merge whenever.

**Review by benoitf — COMMENTED** [review]
I'm wondering if we should not remove ProgressLocation for APP_ICON but that's a different story.

It's not related to the withProgress API implementation using tasks but it seems the message that we display for kind is not accurate
We display in one side that we've downloaded kind but task is at 80% waiting that we install or not the binary in the PATH but the title is 'Downloading kind' so this task is over and it should be 100%
Or task should be 'Installing Kind' or two tasks I don't know but here it feels inconsistent.

https://user-images.githubusercontent.com/436777/234505157-4081c577-7c88-4759-a0df-147e8a92ee7b.mp4

**Comment by jeffmaury** [comment]
> I'm wondering if we should not remove ProgressLocation for APP_ICON but that's a different story.
> 
> It's not related to the withProgress API implementation using tasks but it seems the message that we display for kind is not accurate We display in one side that we've downloaded kind but task is at 80% waiting that we install or not the binary in the PATH but the title is 'Downloading kind' so this task is over and it should be 100% Or task should be 'Installing Kind' or two tasks I don't know but here it feels inconsistent.
> 7VRu3RXaZY.mp4

I discussed with @evidolob and we choose to keep APP_ICON for a while. Maybe we should mark it deprecated and remove it after 0.15.0 ?

Will update the implementation so that a completed task is always 100%

**Comment by evidolob** [comment]
I'm +1 to keep `APP_ICON` for now, mark it deprecated and delete on next release

**Review by benoitf — APPROVED** [review]

**Review by evidolob — APPROVED** [review]
LGTM

**Pull request merged**
