### PR TITLE
feat: Deploy a podman pod to a kubernetes cluster

### LINKED ISSUE #523: Run a defined/existing Pod on a Kubernetes environnement
## Description

As a developer, I'd like the ability to run my pod on a Kubernetes environment.

- From the list of Pods, I should have an action that enables to deploy (or apply) onto the default Kubernetes environment
- The user should have the ability to choose on which namespace to deploy (or apply)
- Later, we could add an option to choose on which environment

In a future time, when we will have more details on a Pod, I should also be able to run this action from #518

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Deploy a 'generate kube' from a container or a 'generate kube' from a podman pod to a Kubernetes pod.

### Screenshot/screencast of this PR

https://user-images.githubusercontent.com/436777/196199394-287338c2-dcc3-43fb-92b1-a9d46fe962f0.mp4

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/523

### How to test this PR?

Create a container and deploy it to k8s from container list or container detail
```
podman run registry.access.redhat.com/ubi8/httpd-24:latest
```

Create a pod, add a container and deploy from there
```
$ podman pod create httpd
$ podman run --pod:httpd registry.access.redhat.com/ubi8/httpd-24:latest
```

from pods list of from a pod detail

Change-Id: I61bf2e5bf738e8dcc771f21736b240909731eaf9
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by cdrage** [comment]
For my machine, I manually set my Kubernetes context using `export KUBECONFIG=$SPATH/etc/keys/k8s/home.conf` or using the `kubectl --kubeconfig` when running commands.

By default, my `loaded-context` is not set to my default cluster for security reasons (and also so I don't accidentally delete my namespace on my prod cluster while I'm messing around with `kind` or `k3s`).

The problem is that I'm unable to use the k8s feature in this PR unless I manually create a `.kube/config` and copy over my `home.conf` file over and then restart Podman Desktop.

I request that we add something in the Podman Desktop settings where we can manually set our default k8s configuration file, or request that we can set it in this section:

Screen Shot 2022-10-17 at 11 44 03 AM

**Comment by cdrage** [comment]
A lot of empty spacing after the logs and buttons, any way to make it by default to take as much as possible / show all the generated k8s yaml / have the buttons on the bottom?

Screen Shot 2022-10-17 at 11 47 46 AM

**Comment by benoitf** [comment]
> For my machine, I manually set my Kubernetes context using export KUBECONFIG=$SPATH/etc/keys/k8s/home.conf or using the kubectl --kubeconfig when running commands.

I assume the library is handling KUBECONFIG environment variable as well ?
Allowing to configure it though the UI is a nice improvement but it looks like a new enhancement.

**Comment by benoitf** [comment]
> A lot of empty spacing after the logs and buttons, any way to make it by default to take as much as possible / show all the generated k8s yaml / have the buttons on the bottom?

When you click on deploy, it will add content on the 'empty' space. If we show/consume all the spaces, it means, the page will shift when we'll click on the deploy button to display the result. Is it what is expected ?

**Comment by cdrage** [comment]
> 

You're right, it'd be an enhancement that we can perhaps work on after the PR is merged. 



> > A lot of empty spacing after the logs and buttons, any way to make it by default to take as much as possible / show all the generated k8s yaml / have the buttons on the bottom?
> 
> When you click on deploy, it will add content on the 'empty' space. If we show/consume all the spaces, it means, the page will shift when we'll click on the deploy button to display the result. Is it what is expected ?

Ah, that makes sense. The problem is when viewing it with Podman Desktop with lots of height, the full log doesn't show / you have to scroll through it. Is there an option in tailwindcss to have it auto height?

**Comment by benoitf** [comment]
> Ah, that makes sense. The problem is when viewing it with Podman Desktop with lots of height, the full log doesn't show / you have to scroll through it. Is there an option in tailwindcss to have it auto height?

for now I think it's using 1/3 like 33% of the height

**Comment by benoitf** [comment]
we have some settings to adjust size of elements but most them are based on the width, not the height

**Review by vzhukovs — APPROVED** [review]

**Review by cdrage — APPROVED** [review]

**Comment by cdrage** [comment]
Two approvals (myself + vlad). Improvements for UI + custom kubeconfig we can mark as enhancements.

**Pull request merged**
