### PR TITLE
fix: avoid "Create New VM" option for podman if podman is not installed

### LINKED ISSUE #2553: There should not be a "Create New ..." option for podman in Settings/Resources when podman is not installed
### Bug description

Create new podman machine is available even though podman is not yet installed. 

pd-createpodman-withoutpodman

### Operating system

Windows 10

### Version

1.0.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
### What does this PR do?

Prevent Create Podman machine to be displayed if Podman is not installed

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #2553

### How to test this PR?

1. Uninstall Podman
2. Launch Podman Desktop
3. Go to the resource pages --> No more Create Podman machine

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
it looks like you're changing stuff in activate method and in install part. But what happens if you install Podman externally without restarting Podman Desktop ? (looks like you assume people will install using Podman Desktop)

or that you uninstall podman while Podman Desktop is running ?

**Comment by benoitf** [comment]
Hello, it looks like that if I install podman externally I can then see the 'create button'
but then if I uninstall podman I still see 'create new' button

https://github.com/containers/podman-desktop/assets/436777/62fff7ef-24a9-4c08-94e9-e653d0394d1f

**Comment by lstocchi** [comment]
This PR looks superfluous to me. Aren't we going to fix the same issue here? https://github.com/containers/podman-desktop/issues/2706 
I was waiting to see the proposal by Mo. Maybe you are disabling it here and then i have to re-enable to show a different message/page

**Comment by benoitf** [comment]
@lstocchi it's to be able to cut the release tomorrow

**Comment by benoitf** [comment]
maybe it overlaps with https://github.com/containers/podman-desktop/pull/2817 now ?

**Comment by jeffmaury** [comment]
Obsoleted by #2817

**Pull request closed without merging**
